export const LANG_AR_TRANS = {
    accept: `قبول`,
    accepted: `الموافقة`,
    acceptedInvitation: `لقد قبلت هذه الدعوة.`,
    actions: `أفعال`,
    addHcp: `إضافة متخصص رعاية صحية جديد إلى المنصة`,
    addHCPTag: `إضافة متخصص رعاية صحية جديد إلى المنصة`,
    addHcpToPlatform: `إضافة متخصص رعاية صحية جديد إلى المنصة`,
    addNewHCP: `إضافة متخصص رعاية صحية جديد إلى المنصة`,
    addNewPatient: `إضافة مريض جديد`,
    addPatient: `إضافة مريض`,
    addPatientConsent: `أؤكد أنني تلقيت الموافقة من المريض لإدخال بياناته`,
    addPatientToPlatform: `يرجى الإضافة إلى منصة المريض`,
    administration: `الادارة`,
    agreed: `متفق عليه`,
    allHcps: `جميع متخصصو الرعاية الصحية`,
    allowNotifications: `قمت بتمكين الإشعارات، ممتاز!`,
    allPatients: `جميع المرضى`,
    almostHalfway: `أنت في منتصف الطريق تقريبا!`,
    almostThere: `أنت في نهاية المطاف تقريبا!`,
    am: `صباحاَ`,
    andMore: (params: string[]) => `و ${params[0]} اكثر`,
    apiErrorGetConsentDocument: `فشل تحميل وثيقة الموافقة إضغط هنا للمحاولة مرة أخرى`,
    appointment: `الموعد`,
    appointmentAcceptedByPatient: `قبول المريض`,
    appointmentAwaitingPatientResponse: `في إنتظار رد من المريض`,
    appointmentDeclinedByPatient: `رفض من قبل المريض`,
    appointmentName: `إسم الموعد`,
    appointmentNotification: `إشعار المواعيد`,
    appointments: `المواعيد`,
    appointmentsForPatient: (params: string[]) => `المواعيد ل ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `يمكن تحديد موعد بين ${params[0]} و${params[1]}`,
    appUnavailable: `عفوا هذا التطبيق غير متاح حاليا يرجى المحاولة لاحقا`,
    april: `أبريل`,
    ar: `العربية`,
    areYouSureDeclineMessage: `الفريق الطبي يحتاج إليك لمساعدتك في الإعداد ومراقبة التقدم المحرز بك.  \n\n  الرجاء الإتصال بطبيب الإحالة الخاص بك إذا كنت لا ترغب في الانضمام إلى المنصة`,
    areYouSureDeclineTitle: `هل أنت متأكد أنك لا ترغب في الانضمام إلى منصة Care4Today؟`,
    areYouSureDeleteNote: `هل أنت متأكد أنك تريد حذف هذه المذكرة؟`,
    article: `المقالة`,
    assignToMDT: `تعيين إلى الفريق متعدد التخصصات`,
    audio: `السمع`,
    august: `أغسطس`,
    back: `الرجوع`,
    backToAppointments: `العودة إلى مواعيدك`,
    backToDetails: (params: string[]) => `العودة الى تفاصيل ${params[0]}`,
    backToLogin: `العودة إلى تسجيل الدخول`,
    backToPatientProfile: `العودة الى ملف المريض`,
    badPassword: `لقد قمت بإدخال كلمة سر غير صحيحة`,
    bariatrics: `جراحة السمنة`,
    blockedUser: `تم حظر إسم المستخدم الخاص بك بسبب تسجيل دخول متعدد. يرجى المحاولة مرة أخرى بعد نصف ساعة.`,
    bmi: `مؤشر كتلة الجسم`,
    bookedSuccess: `لقد حجزت موعدك بنجاح`,
    cancel: `إلغاء`,
    cancelAlert: `إلغاء`,
    cantParseError: `غير قادر على تحليل الإجابة.`,
    cantSaveImage: `غير قادر على حفظ الصورة.`,
    care4Today: `Care4Today`,
    careModules: `وحدات الرعاية`,
    changePassword: `تغيير كلمة السر`,
    changePasswordSubtitle: `إختر كلمة السر الخاصة بك.`,
    changePasswordTitle: `يرجى تغيير كلمة السر`,
    choosePicture: `يرجى إختيار صورتك الشخصية`,
    chooseProfilePicture: `تغيير صورة الملف الشخصي`,
    cm: `سنتيمتر`,
    completed: `منجز`,
    conditionalGoal: `الأهداف المشروطة`,
    confirmAppointmentDelete: `هل أنت متأكد من أنك تريد حذف هذا الموعد؟`,
    confirmed: `تم التأكيد`,
    confirmNewPasswordPlaceholder: `تأكيد كلمة السر الجديدة`,
    consent: `الموافقة`,
    consentDontAgree: `أنا لا أوافق ولن استخدم منصة Care4Today`,
    consentedOn: (params: string[]) => `تم الحصول على الموافقة ب ${params[0]}`,
    contact: `البيانات`,
    contactDetails: `البيانات`,
    contactInfo: `معلومات الاتصال`,
    contentDescApptIcon: `أيقونة المواعيد`,
    contentDescAttachImage: `إرفاق الصورة`,
    contentDescAttachment: `المرفقات`,
    contentDescAttachmentImg: `صورة الشاشة كاملة`,
    contentDescBackground: `الخلفية`,
    contentDescChangePwdIcon: `تغيير كلمة السر`,
    contentDescClose: `إغلاق الشاشة`,
    contentDescDeleteAttachment: `حذف الصورة المرفقة`,
    contentDescDevicesIcon: `أيقونة الأجهزة المتصلة`,
    contentDescEduContentExpandBtn: `الرجاء فتح مرفقات المحتوى التعليمي`,
    contentDescEduContentThumb: `مرفقات المحتوى التعليمي`,
    contentDescEduItemCompleted: `تم إكمال المحتوى التعليمي`,
    contentDescEduItemIncomplete: `لم يتم إكمال المحتوى التعليمي`,
    contentDescGoalIcon: `أيقونة الهدف الشخصي`,
    contentDescHelpIcon: `أيقونة المساعدة`,
    contentDescKillswitchIcon: `الموقع محظور`,
    contentDescLegalIcon: `أيقونة المستندات القانونية`,
    contentDescLogo: `إشعار التطبيق`,
    contentDescLogoutIcon: `أيقونة الخروج`,
    contentDescMdtPic: `صورة الممارس الصحي`,
    contentDescMessageIcon: `أيقونة الرسائل`,
    contentDescNoGoalIcon: `لا يوجد أيقونة الهدف`,
    contentDescPathwayCurrent: `أيقونة المرحلة الحالية`,
    contentDescPathwayIcon: `أيقونة المسار`,
    contentDescPathwayOtherPhase: `أيقونة المرحلة الأخرى`,
    contentDescProfilePic: `صورة الملف الشخصي`,
    contentDescSend: `إرسال`,
    create: `إنشاء`,
    createAMedicalTeam: `إنشاء الفريق الطبي`,
    createAppointment: `تحديد الموعد`,
    createAppointmentButton: `تحديد الموعد وإرسال الدعوة`,
    createAppointmentSuccess: `تم تحديد الموعد بنجاح`,
    createAppt: `تحديد الموعد`,
    createMDT: `إنشاء فريق متعدد التخصصات`,
    currentBmi: `مؤشر كتلة الجسم الحالية`,
    currentPhase: `المرحلة الحالية`,
    currentWeight: `الوزن الحالي`,
    dashboard: `لوحة القيادة`,
    date: `التاريخ`,
    dateOfBirth: `تاريخ الولادة`,
    dateOfConsent: `تاريخ الموافقة`,
    dateOfConsentAsc: `تاريخ الموافقة تصاعدي`,
    dateOfConsentDesc: `تاريخ الموافقة تنازلي`,
    dateOfSurgery: `تاريخ العملية *`,
    december: `ديسمبر`,
    decline: `الرفض`,
    declined: `لقد تم الرفض`,
    declinedInvitation: `لقد تم رفض هذه الدعوة.`,
    declinedNotifications: `لم تسمح بالإشعارات، هل أنت متأكد؟ يمكنك تغيير ذلك في قائمة الإعدادات.`,
    declinedSuccess: `لقد رفضت موعدك`,
    defaultError: `هناك خطأ ما`,
    delete: `الحذف`,
    deleteAppointmentSuccess: `حذف الموعد بنجاح`,
    deleteNote: `حذف مذكرة`,
    deleting: `حذف ...`,
    description: `الوصف`,
    details: `التفاصيل`,
    devices: `الأجهزة المتصلة`,
    disagreeConsentError: `حدث خطـأ أثناء عدم موافقتك يرجى المحاولة مرة أخرى`,
    discardChanges: `تجاهل التغييرات؟`,
    document: `الوثيقة`,
    done: `منجز`,
    draftWontBeSaved: `لم يتم حفظ التعديل الخاص بك . هل ترغب في الإلغاء على أية حال؟`,
    duplicateMDT: `تم تحديد متخصصو الرعاية الصحية مسبقا`,
    edit: `التعديل`,
    editHcpsProfile: `تعديل الملف الشخصي لي متخصص الرعاية الصحية`,
    editMessageDetails: `تعديل تفاصيل المحادثة`,
    editMTDTeam: (params: string[]) => `تعديل فريق ل ${params[0]}`,
    editPassword: `تعديل كلمة السر`,
    editPatient: `تعديل بيانات المريض`,
    editPatientError: `حدث خطـأ في تحديث تفاصيل المريض`,
    editPatientSuccess: `تم التحديث بنجاح تفاصيل المريض`,
    editProfile: `تعديل الملف الشخصي`,
    editProfilePicture: `تعديل الصورة الشخصية`,
    editSubject: `ضبط الموضوع`,
    editTeamMembers: `تعديل أعضاء الفريق`,
    editYourPersonalGoal: `تعديل الهدف الشخصي`,
    eduContentHint: `يرجى الضغط على الأيقونة لفتح المرفقات`,
    email: `البريد الإلكتروني`,
    emailAddress: `البريد الإلكتروني`,
    emailConfirmation: (params: string[]) =>
        `لقد أرسلنا ر بريدا الالكترونيا إلى ${
            params[0]
        } مع رابط لإعادة تعيين كلمة السر الخاصة بك.`,
    emailExists: (params: string[]) =>
        `البريد الإلكتروني ${params[0]} مستخدم سابقا.`,
    emailSent: `تم إرسال البريد الإلكتروني`,
    en: `الإنجليزية`,
    enableNotifications: `تمكين الإشعارات`,
    enterANewHCP: `إدخال متخصص الرعاية الصحية الجديد`,
    enterSubjectHint: `أدخل الموضوع`,
    enterTheSubject: `أدخل موضوع لهذه المحادثة.`,
    errorEditingHcp: `حدث خطـأ في تعديل تفاصيل متخصص الرعاية الصحية`,
    errorFindingConsentDocument: `حدث خطأ العثورعلى وثيقة الموافقة.`,
    errorLoading: (params: string[]) => `خطأ في تحميل ${params[0]}`,
    errorSavingSettings: `حدث خطأ في حفظ الإعدادات`,
    errorUpdatingPassword: `لا يمكن تحديث كلمة السر`,
    excessWeightLost: `فقدان الوزن الزائد`,
    failEditHcp: `حدث خطأ أثناء تعديل ملفك الشخصي`,
    february: `فبراير`,
    female: `اُنثى`,
    filter: `تصفية`,
    firstName: `الإسم الكامل`,
    forgotPasswordInstruction: `الرجاء إدخال البريد الإلكتروني الذي قمت بتسجيله في المستشفى. سيتم إرسال بريد الإلكتروني ليتم إعادة تعيين كلمة السر الخاصة بك.`,
    forgotPasswordViewTitle: `هل نسيت كلمة السر`,
    forgotYourPassword: `هل نسيت كلمة السر؟`,
    formTimeRangeInPast: `الزمن لا يمكن أن يكون في الماضي`,
    formTimeRangeStartGreaterThanEnd: `النطاق الزمني غير صحيح`,
    forPatient: `لِ`,
    from: `من`,
    ft: `قدم`,
    fullName: `الإسم الكامل`,
    function: `الوظيفة`,
    gained: `اكتسبت`,
    gender: `الجنس`,
    goal: `الهدف`,
    goalSavedError: `لا يمكن حفظ الهدف`,
    goalSavedSuccess: `تم حفظ الهدف بنجاح`,
    goBack: `الرجوع`,
    hcps: `متخصصو الرعاية الصحية`,
    healthCareProfessionals: (params: string[]) =>
        `عدد متخصصو الرعاية الصحية: ${params[0]}`,
    height: `الطول`,
    help: `المساعدة`,
    heyChooseYourPicture: (params: string[]) =>
        `يرجى إختيار صورتك الشخصية , ${params[0]}`,
    iAgree: `أنا موافق`,
    iAgreeFormat: (params: string[]) => `أنا موافق (${params[0]}/${params[1]})`,
    iAmSure: `أنا متأكد`,
    idealBodyWeight: `الوزن المثالي`,
    iDoNotAgree: `أنا غير موافق`,
    iDontAgree: `أنا غير موافق ولن أستخدم منصة Care4Today`,
    imperial: `القياس الامبراطوري`,
    in: `في`,
    includeLinkToLocation: `إضافة رابط إلى الموقع`,
    initialWeight: `الوزن الاساسي`,
    installUpdate: `تنزيل التحديث`,
    invalidEmailError: `لبريد الإلكتروني غير صحيح`,
    invalidNumber: `يرجى إدخال رقم صحيح`,
    invalidTokenError: `غير قادر على التوثيق يرجى محاولة التسجيل مرة أخرى`,
    it: `إيطالي`,
    iWantToFitAgain: `على سبيل المثال: ”أريد أن يصبح حجم سروالي أصغر“`,
    january: `يناير`,
    july: `يوليو`,
    june: `يونيو`,
    keepGoing: `إستمر امضي قدما!`,
    keepMomentum: `الحفاظ على النشاط!`,
    kg: `كيلوغرام`,
    kilogrammes: `كيلوغرام`,
    language: `اللغة`,
    languageRequired: `اللغة`,
    lastName: `اللقب`,
    lb: `رطل إنجليزي`,
    learningMaterials: `المواد التعليمية`,
    legalDocuments: `الوثائق القانونية`,
    loading: `جاري التحميل`,
    loadingPatients: `جاري تحميل المريض، يُرجى الانتظار`,
    location: `موقعك`,
    locationUrl: `URL الموقع`,
    lockScreenHint: `تحتاج إلى قفل الشاشة لتأكد من الإستخدام الآمن للتطبيق`,
    login: `تسجيل الدخول`,
    loginIncorrect: `البريد الإلكتروني أو كلمة السر التي أدخلتها غير صحيحة`,
    logout: `الخروج`,
    logoutAreYouSure: `هل أنت متأكد من أنك تريد الخروج؟`,
    loseBefore: (params: string[]) => `خسارة ${params[0]}`,
    loseFormat: (params: string[]) => `خسارة ${params[0]} ${params[1]}`,
    lost: `ضائع`,
    male: `ذكر`,
    manageHCPs: `إدارة متخصصو الرعاية الصحية`,
    managePatients: `إدارة المرضى`,
    march: `مارس`,
    may: `مايو`,
    mdtTeam: `فريق متعدد التخصصات`,
    mdtTeamNotAddedYet: `لم يتم تعيين فريق متعدد التخصصات حتى الان.`,
    mdtTeamUC: `فريق متعدد التخصصات`,
    medicalTeam: `الفريق الطبي`,
    meetingInvite: `يوجد لديك موعد`,
    meetingInviteWith: (params: string[]) => `موعد مع ${params[0]}`,
    messageCreated: `بدأت محادثة بنجاح.`,
    messageNotCreated: `لقد فشلت في بدء محادثة.`,
    messageNotification: `إشعار الرسائل`,
    messageNotSent: `لم يتم إرسال الرسالة`,
    messages: `الرسائل`,
    metric: `القياس المتري`,
    movePhaseConfirmation: (params: string[]) =>
        `هل أنت متأكد أنك تريد نقل ${params[0]} للمرحلة ${params[1]}`,
    moveToNextPhase: `الإنتقال إلى المرحلة التالية`,
    multiDisTeam: `فريق متعدد التخصصات`,
    myMessages: `رسائلي`,
    myMotivation: `حافزي:`,
    myPersonalGoal: `هدفي الشخصي`,
    myProfile: `ملفي`,
    myTeam: `الفريق الطبي الخاص بي`,
    name: `الإسم`,
    nameOfMDT: `إسم فريق متعدد التخصصات`,
    needsConsent: `يجب على المريض إعطاء موافقته أولا.`,
    networkError: `حدث خطأ في الشبكة`,
    newAppointment: `تحديد موعد جديد`,
    newChat: `المحادثة الجديدة`,
    newInvitation: `دعوة جديدة`,
    newMessageNotificationMore: (params: string[]) =>
        `لديك ${params[0]} رسائل جديدة. أفتح التطبيق لمعرفة الجديد`,
    newMessageNotificationOne: `لديك رسالة جديدة. أفتح التطبيق لمعرفة الجديد`,
    newNote: `مذكرة جديدة`,
    newPasswordPlaceholder: `كلمة السر الجديدة`,
    newPatientSuccess: (params: string[]) =>
        `لقد قمت بإضافة ${params[0]} إلى المنصة بنجاح.`,
    newTeamFail: `لم يتم تعيين فريق متعدد التخصصات`,
    newTeamSuccess: `تم تعيين فريق متعدد التخصصات`,
    newVersionApp: `يجب عليك تحديث التطبيق الى آخر إصدار في App store`,
    nextAppointment: `الموعد التالي`,
    nextSelectCareModule: `التالي:اختر وحدات العناية`,
    nextSurgeryInformation: `التالي: معلومات الجراحة`,
    niceToSeeYouAgain: `سعيدون أن نراك مرة أخرى`,
    nickname: `اللقب`,
    nicknameError: `اللقب غير صالح. يمنع إستعمال الرموز.`,
    nl: `هولندي`,
    no: `لا`,
    noAppointments: `لا يوجد أي مواعيد`,
    noCurrentGoalForPatient: `لا يوجد هدف حالي لهذا المريض`,
    noDate: `لا يوجد تاريخ محدد`,
    noFutureAppointments: `لا يوجد موعد جديد`,
    noGoalSet: `لا توجد أهداف وضعت من قبل متخصصي الرعاية الصحية`,
    noMatchingConsentDocumentsFound: `لا توجد وثائق موافقة مطابقة`,
    noMessages: `لاتوجد رسائل مُتَوَفِّرة`,
    noNetworkConnection: `لايوجد إتصال بالشبكة . الرجاء إعادة المحاولة`,
    noNotesMessage: `لا توجد مذكرات مُتَوَفِّرة.\n اضغط على ”إنشاء“ لإضافة مذكرة جديدة`,
    noPersonalGoalSet: `لا يوجد أي هدف شخصي محدد`,
    noPersonalGoalSetDashboard: `لا يوجد أي هدف شخصي محدد. انتقل إلى صفحة الإعدادات لتحديثه.`,
    noPlannedAppointments: `لا يوجد أي مَوعد`,
    noPreview: `لا يوجد معاينة`,
    noProgressRecorded: `لا يوجد أي تقدم`,
    noResponseError: `لم تتلق أي إجابة.`,
    notAgreed: `لا اوافق`,
    noteDeletedError: `لا يمكن حذف الملاحظة`,
    noteDeletedSuccessfully: `تم حذف الملاحظة بنجاح`,
    notes: `المذكرات`,
    noteSaved: `المذكرات حفظت`,
    noteSavedError: `لم يَتم حفظ المذكرة!`,
    noteSavedSuccess: `تم حفظ المذكرة بنجاح!`,
    noteSaveError: `خطأ، غير قادر على حفظ المذكرة. حاول ثانية؟`,
    notifications: `الإشعارات`,
    notNow: `ليس الان`,
    notSet: `غير مضبوط`,
    notYetSubmitted: `لم تقدم بعد`,
    noUnreadMessages: `لا توجد رسائل غير مقروئة`,
    noUserFound: `خطأ العثور على المستخدم مع الأوراق المعتمدة.`,
    november: `نوفمبر`,
    noWeightDifference: `لا فرق في الوزن`,
    october: `اكتوبر`,
    ok: `حسنا`,
    onboardingNotificationsTitle: `نحن نريد أن نبقيكم على الاطلاع بأحدث المعلومات في كل مرة`,
    onboardingNotifictionsInfo: `سوف يتم إشعارك ب: \n\n • المواعيد \n • رسائل جديدة من الفريق الطبي الخاص`,
    onVar: (params: string[]) => `على ${params[0]}`,
    openCare: `الرجاء فتح care4today ومعرفة ما اذا كان لديك إخطارات جديدة!`,
    optOutSubtitle: `يرجى الاتصال بطبيب الإحالة الخاص بك إذا كنت لا ترغب في الانضمام إلى المنصة.`,
    optOutTitle: `هل أنت متأكد أنك لا ترغب في الانضمام إلى منصة Care4Today؟`,
    organisation: `منظمة`,
    orthopedics: `طب العظام`,
    other: `آخر`,
    outdatedVersion: `إنك تستخدم الآن نسخة غير حديثة من التطبيق`,
    overview: `النظرة عامة`,
    participant: `المشارك`,
    password: `كلمه السر`,
    passwordComplexityError: `يجب أن تكون كلمة السر 8 أحرف على الأقل طويلة ويكون 2 على الأقل من الأنواع التالية من : الأرقام والرموز.`,
    passwordMismatchError: `كلمة السر غير مطابقة`,
    passwordUpdated: `تم تحديث كلمة السر`,
    pastAppointments: `المواعيد الماضية`,
    pathwayScheduleFail: `حدث خطـأ . لا يمكن تحديث جدول المسار .`,
    patient: `المريض`,
    patientAge: (params: string[]) => `${params[0]} سنوات`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} سنة`,
    patientConsent: `موافقة المريض`,
    patientNameAsc: `إسم المريض تصاعدي`,
    patientNameDesc: `إسم المريض تنازلي`,
    patientRegistration: `تسجيل المريض`,
    patients: `لائحة المرضى`,
    patientsCount: (params: string[]) => `عدد المرضى : ${params[0]}`,
    patientsOverview: `النظرة العامة للمرضى`,
    pending: `في إنتظار الموافقة`,
    percent: `٪`,
    personalGoal: `هدفي الشخصي`,
    personalGoalEdit: `هدفي الشخصي`,
    personalPassword: `كلمة السر الشخصية`,
    personalPasswordHelper: `الرجاء اختيار كلمة السر الخاصة بك. يمكنك دائما تغيير كلمة السر الخاصة بك مرة أخرى في قائمة الإعدادات.`,
    phoneError: `رقم الهاتف غير صحيح. يرجى استخدام أرقام فقط (بدون قوس، الواصلات، +)`,
    phoneNumber: `رقم الهاتف`,
    picture: `الصورة`,
    pictureInstructions: `يرجى اختيار صورة ملفك الشخصي. وسيتم إستخدام هذه الصورة لحسابك الخاص.`,
    pleaseConnect: `يجب عليك ربط الانترنت والتأكد من التحديث الى آخر إصدار`,
    pleaseContactYourHospital: `يرجى الاتصال بالمستشفى مباشرة في حالة الطوارئ.`,
    pleaseProvidePassword: `يرجى إدخال كلمة السر لتأكيد هذه الخطوة :`,
    pm: `مساء`,
    pounds: `رطل إنجليزي`,
    preparation: `الإعداد`,
    preSurgeryPrep: `التحضيرات قبل الجراحة`,
    previous: `الخطوة السابقة`,
    privacyPolicy: `السياسة الخصوصية`,
    profileLabel: `سوف يتم إستخدام هذا الأسم لمخاطبتكم عبر رسائل البريد الإلكتروني، الرسائل النصية، وهذا التطبيق. وسيتم إرسال هذه المعلومات إلى فريقك الطبي`,
    profilePicture: `الصوره الشخصية`,
    profileTitle: `سوف نستخدم هذا أثناء مخاطبتكم في رسائل البريد الإلكتروني والرسائل النصية، وهذا التطبيق. ونحن سوف نرسل هذه المعلومات لفريق الطبي الخاص بك.`,
    progress: `التقدم`,
    progressMsgForgotPwd: `التحقق`,
    progressMsgLoading: `التحميل`,
    progressMsgLoadingContent: `تحميل المحتوى`,
    progressMsgLogin: `جاري تحميل المسار، قد يستغرق هذا مدة تصل إلى دقيقة واحدة`,
    progressMsgMdtLoading: `تحميل فريق متعدد التخصصات`,
    progressMsgNotesLoading: `تحميل الملاحظات`,
    progressMsgProfileEdit: `حفظ الملف الشخصي`,
    progressMsgProfilePhoto: `حفظ الصورة`,
    progressMsgResetPwd: `حفظ كلمة السر`,
    provideTheEmail: `يرجى توفير البريد الإلكتروني الذي سجل في المستشفى.`,
    pwdValidationDoesNotMatch: `كلمة السر غير متوافقة`,
    pwdValidationIllegal: `يوجد رموز غير مسموح بها`,
    pwdValidationNotComplex: `كملة السر ضعيفة`,
    pwdValidationTooShort: `كلمة السر قصيرة`,
    quickFilter: `تصفية سريعة`,
    remindmeLater: `ذكرني لاحقا`,
    requiredFields: `الخانات الاجبارية`,
    requiredHCPs: `متخصصو الرعاية الصحية *`,
    resetPassword: `إعادة تعيين كلمة السر`,
    respond: `الرد`,
    retry: `الإعادة`,
    save: `الحفظ`,
    saveAndContinue: `الحفظ والمتابعة`,
    saveChanges: `حفظ التغييرات`,
    scheduleNewAppointment: `تحديد موعد جديد`,
    searchInConversation: `بحث في المحادثات ...`,
    secureRealmError: `فشل في التشغيل - يلزم تمكين شاشة القفل`,
    selectDifferentImage: `تحديد صورة مختلفة`,
    selectFile: `إختر الملف`,
    selectFunction: `حدد الوظيفة`,
    selectLanguage: `إختيار اللغة`,
    selectOneOrMoreHCPs: `إختر واحد أو أكثر من متخصصو الرعاية الصحية`,
    selectPictureSource: `إختر مصدر الصورة`,
    selectProfilePicture: `تحديد صورة الملف الشخصي`,
    selectSurgeon: `إختر الجراح`,
    send: `إرسال`,
    sendMessage: `إرسال رسالة`,
    sendNewMessage: `إرسال رسالة جديدة`,
    september: `سبتمبر`,
    setPassword: `ضبط كلمة السر`,
    setPasswordReminder: `إبدأ الإعداد الخاص بك`,
    settings: `الإعدادات`,
    setup: `الإعداد`,
    setYourPersonalGoal: `تعيين هدفك الشخصي`,
    someonesPathway: (params: string[]) => `مسار ${params[0]}`,
    sortBy: `ترتيب حسب`,
    splashSubtitle: `عملية انقاص الوزن`,
    start: `البداية`,
    startANewConversation: `بدء محادثة جديدة`,
    startConversation: `بدء المحادثة`,
    startingPoint: `نقطة البداية`,
    startNewConversation: `بدء محادثة جديدة`,
    startPreparation: `إبدأ التحضيرات الخاصة بك`,
    status: `الحالة`,
    subject: `الموضوع`,
    subjectChangedSuccess: `تم تغيير موضوع المحادثة بنجاح`,
    subjectChangeFail: `لم يتغير موضوع المحادثة`,
    submit: `التقديم`,
    subPhase: `المرحلة الفرعية`,
    successEditHcp: `تم تعديل ملفك الشخصي بنجاح`,
    surgeon: `الجراح`,
    surgeryInformation: `معلومات العملية الجراحية`,
    tasks: `المهام`,
    tasksCompleted: `المهام المنجزة`,
    team: `الفريق`,
    thisMonth: `هذا الشهر`,
    time: `الوقت والمكان`,
    timeAndLocation: `الوقت والمكان`,
    timeOfSurgery: `وقت العملية *`,
    to: `إلى`,
    today: `اليوم`,
    toDo: `الأفعال`,
    undo: `إعادة تصحيح`,
    unitRequired: `الوحدة`,
    units: `الوحدات`,
    unknown: `أفضل عدم القول`,
    unknownError: `حدث خطأ غير معروف.`,
    unknownGender: `أنا أفضل عدم الإجابة`,
    unknownUser: `غير معروف`,
    unreadMessage: `رسالة غير مقروءة`,
    unreadMessages: `رسائل غير مقروءة`,
    untitled: `بدون عنوان ...`,
    update: `تحديث`,
    updateAppointment: `تغيير الموعد`,
    updateAppointmentButton: `حفظ التغييرات وإرسال التحديثات`,
    updateAppointmentSuccess: `تم تحديث الموعد بنجاح`,
    updateMessage: `للإستمرار يجب عليك تحديث التطبيق الى آخر إصدار في App store`,
    updateProfilePicture: `تحديث الملف الشخصي`,
    updateProgress: `تحديث التقدم`,
    useCamera: `إستخدام الكاميرا`,
    username: `إسم المستخدم`,
    video: `فيديو`,
    viewAllMessages: `مشاهدة كل الرسائل`,
    viewAndEditPathway: `الإطلاع وتغيير مواعيد المسار`,
    viewDocument: `الإطلاع على الوثيقة`,
    weight: `الوزن`,
    weightLoss: `فقدان الوزن`,
    weightUpdatedSuccess: `تم تحديث الوزن الحالي بنجاح`,
    welcomeHeader: `أهلا بك`,
    welcomeMessage: (params: string[]) => `مرحبا ${params[0]}!`,
    wellDoneNextStep: `أحسنت! أنت على استعداد للإنتقال إلى الخطوة التالية!`,
    withdrawConfirm: `حسنا، أترك التطبيق`,
    withdrawConsent: `سحب الموافقة`,
    withdrawConsentBody: `من خلال سحب الموافقة للمعلومات الشخصية الخاصة بك، سيتم حذف بياناتك المحلية كالمذكرات والأهداف الشخصية، وبعد 30 يوما من الإنتظار ، فإنك لن تكون قادرا على الدخول إلى التطبيق.`,
    withdrawConsentTitle: `هل أنت متأكد أنك تريد الإنسحاب من منصة Care4Today ؟`,
    writeAMessage: `أكتب رسالة...`,
    writeSomething: `أكتب شيئا...`,
    wrongUserName: `إسم المستخدم الذي أدخلته غير صحيح`,
    xUnread: (params: string[]) => `غير مقروء ${params[0]}`,
    yes: `نعم`,
    yesDelete: `نعم، حذف`,
    yesDiscard: `نعم، تجاهل`,
    youAreOffline: `أنت غير متصل`,
    youCanSetASentence: `يمكنك كتابة جملة لتحفيز نفسك للوصول إلى هدفك الشخصي.`,
    youGained: (params: string[]) => `لقد اكتسبت ${params[0]}`,
    youGainedFormat: (params: string[]) =>
        `زيادة الوزن ${params[0]} ${params[1]}`,
    youHaveANewMessageFrom: (params: string[]) =>
        `لديك رسالة جديدة من ${params[0]}.`,
    youHaveNewAppointment: `لديك موعد جديد. أفتح التطبيق لمعرفة ما هو جديد.`,
    youHaveNewAppointments: (params: string[]) =>
        `لديك ${params[0]} مواعيد جديدة.إفتح التطبيق لمعرفة ما هو جديد.`,
    youHaveNewMessage: `لديك رسالة جديدة.إفتح التطبيق لمعرفة ما هو جديد.`,
    youHaveNewMessages: (params: string[]) =>
        `لديك ${params[0]} رسائل جديدة.إفتح التطبيق لمعرفة ما هو جديد.`,
    youHaveUndone: `لقد تم التراجع الى الخيار السابق`,
    youLost: (params: string[]) => `لقد فقدت ${params[0]}`,
    youLostFormat: (params: string[]) =>
        `خسارة الوزن ${params[0]} ${params[1]}`,
    yourAppointments: `مواعيدك الخاصة`,
    yourGoals: `الأهداف الخاصة بك`,
    yourNote: `الملاحظات الخاصة بك`,
    yourPassword: `كلمة السر الخاصة بك`,
    yourPasswordHasBeenReset: `تم إعادة تعيين كلمة السر الخاصة بك`,
    yourProfile: `ملفك الشخصي`,
    export: `تصدير`,
    exportData: `تصدير البيانات الشخصية`,
    exportDataFail: `حدث خطأ. تعذر تصدير البيانات`,
    exportMyData: `تصدير بياناتي الشخصية`,
    goalStepCount: `الهدف (خطوات في اليوم)`,
    loadingPathway: `جارٍ تحميل المسار، قد يستغرق هذا مدة تصل إلى دقيقة واحدة`,
    loadingPatient: `جارٍ تحميل المريض، يُرجى الانتظار`,
    pleaseEnterTotalSteps: `يُرجى إدخال إجمالي عدد الخطوات في نهاية كل يوم`,
    stepCount: `عدد الخطوات`,
    stepsPerDay: `خطوات في اليوم`,
    walkStepsPerDay: (params: string[]) => `خطوات في اليوم ${params[0]} مشي`,
    steps: `الخطوات`,
    avgWeeklySteps: `معدل الخطوات هذا الأسبوع`,
    rightToBeForgotten: `حذف بياناتي الشخصية`,
    totalStepsDuringDay: `إجمالي الخطوات التي تمت خلال يوم واحد`,
    youAlreadyWalked: (params: string[]) =>
        `لقد مشيت ${params[0]} خطوات اليوم.`,
    rightToBeForgottenTitle: `هل أنت متأكد من رغبتك في بدء حذف بياناتك الشخصية؟`,
    rightToBeForgottenInfo: `ببدء هذا الطلب، ستُحذف بياناتك الشخصية ولن يصبح بإمكانك الوصول إلى هذا التطبيق. يُرجى العلم أن بعض المعلومات الشخصية المحدودة مثل اسمك المُرسل من نظام معلومات المستشفى قد تستمر في الظهور في المواعيد.    لطرح أي أسئلة أخرى، يُرجى التواصل عبر support@care4todaypatient.com.    يُرجى إدخال كلمة مرورك لتأكيد هذا الإجراء:`,
    passwordHint: `كلمة السر الخاصة بك`,
    rightToBeForgottenSuccess: `Care4Today تم إرسال طلب حذف البيانات الشخصية إلى صندوق بريد دعم`,
    incorrectPassword: `تم إدخال كلمة سر غير صحيحة`,
    errorInitiatingRightToBeForgotten: `خطأ في إرسال الطلب، يُرجى التواصل مع فريق الدعم مباشرةً`,
    updateStepCount: `تحديث عدد الخطوات`,
    mon: `الإثنين`,
    tue: `الثلاثاء`,
    wed: `الأربعاء`,
    thu: `الخميس`,
    fri: `الجمعة`,
    sat: `السبت`,
    sun: `الأحد`,
    stepsAmount: (params: string[]) => `خطوات ${params[0]}`,
    stepsGoalUpdateSuccess: `تمت إضافة قيمة الخطوات بنجاح`,
    search: `...بحث`,
    successEditMDT: `تم تحديث تفاصيل فريق متعدد التخصصات بنجاح`,
    failEditMDT: `حدث خطأ في تحديث تفاصيل فريق متعدد التخصصات`,
    userCreationError: `حدث خطأ في إنشاء المستخدم`,
    userUpdateSuccess: `تم تحديث تفاصيل المستخدم بنجاح`,
    legal: `وثائق قانونية`,
    termsOfUse: `شروط الأستخدام`,
    disclaimer: `إخلاء مسؤولية`,
    exportDataSuccessV1: `تم إرسال طلب تصدير البيانات الشخصية إلى فريق دعم Care4Today`,
    exportDataSuccess: `تم إرسال طلب تصدير البيانات الشخصية إلى فريق دعم Care4Today`,
    dataFormatV1: `سيتم تصدير بياناتك الشخصية في ملف بتنسيق CSV. سيتم إرسال الملف إلى عنوان بريدك الإلكتروني المسجل`,
    dataFormat: `سيتم تصدير بياناتك الشخصية في ملف بتنسيق JSON. سيتم إرسال الملف إلى عنوان بريدك الإلكتروني المسجل`,
    viewAllMaterials: `عرض كل المواد`,
    viewAllAppointments: `عرض كل المواعيد`,
    enjoyYourDay: `استمتع بيوم إجازتك!`,
    motivateAlmost: `كِدتَ أن تصل!`,
    startConversationHcp: `ابدأ محادثة مع اختصاصي رعاية صحية (HCP)`,
    andYou: `، أنت`,
    viewAllNotifications: `عرض كل الإشعارات`,
    noInvitations: `لا توجد دعوات`,
    yourTimeline: `جدولك الزمني`,
    currentSubphase: `المرحلة الفرعية الحالية`,
    updateWeight: `تحديث الوزن الحالي`,
    teamLoading: `جارٍ تحميل الفريق`,
    noMdt: `لم يتم تعيين فريق متعدد التخصصات.`,
    teamDetails: `عرض تفاصيل الفريق`,
    showResolved: `عرض المشكلات التي تم حلها`,
    readDoc: `قراءة الوثيقة`,
    consultationNotes: `ملاحظات الاستشارة`,
    viewAllConsultationNotes: `عرض كل ملاحظات الاستشارة`,
    createNewNote: `+ إنشاء ملاحظة جديدة`,
    dismiss: `تجاهل`,
    pictureError: `خطأ في تحميل الصورة`,
    wrongFormat: `تنسيق الصورة خاطئ`,
    backToDashboard: `عودة إلى لوحة البيانات`,
    noMessage: `لا توجد رسائل`,
    noSpecialCharacters: `غير مسموح باستخدام أحرف خاصة`,
    noNotesAvailable: `لا تتوفر ملاحظات`,
    hcpPortal: `بوابة المستشفى`,
    patientPortal: `بوابة المريض`,
    consultationNote: `ملاحظة الاستشارة`,
    noteTitle: `عنوان الملاحظة`,
    noteContents: `محتويات الملاحظة`,
    writeConsultationNotes: `اكتب ملاحظات الاستشارة هنا`,
    createHcpNote: `إنشاء ملاحظة`,
    consultationNoteCreatedBy: (params: string[]) =>
        `تم الإنشاء: ${params[0]} بواسطة ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) => `آخر تحرير: ${params[0]}`,
    loadingConsultaionNotes: `جار تحميل ملاحظات الاستشارة`,
    consultationNotesFor: (params: string[]) =>
        `ملاحظات الاستشارة لـ ${params[0]}`,
    editHcpNote: `تحرير ملاحظة`,
    reason: `السبب`,
    writeReasonForEditing: `اكتب سبب التحرير...`,
    confirmCancelCreateNote: `هل أنت متأكد من أنك تريد الخروج بدون إنشاء الملاحظة؟`,
    confirmCancelEditNote: `هل أنت متأكد من أنك تريد الخروج بدون تحرير الملاحظة؟`,
    rotateYourDevice: `تدوير جهازك`,
    patientId: `معرف المريض`,
    oldPassword: `كلمة السر القديمة`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `الوثائق`,
    hcpId: `معرف اختصاصي الرعاية الصحية`,
    userInactivity: `تم تسجيل الخروج بسبب عدم النشاط`,
    duplicateMrn: `معرف اختصاصي الرعاية الصحية موجود بالفعل في Care4Today`,
    confirm: `تأكيد`,
    viewDetails: `عرض التفاصيل`,
    upperCaseLetters: `أحرف كبيرة`,
    lowerCaseLetters: `أحرف صغيرة`,
    numbers: `أرقام`,
    specialCharacters: `أحرف خاصة (علامات الترقيم، الرموز)`,
    passwordRequirements: `يجب أن تتكون كلمة السر من 8 أحرف على الأقل وتفي باثنين من معايير التعقيد:`,
    incorrectOldPassword: `كلمة السر القديمة غير صحيحة. سيتم قفل حسابك بعد 5 محاولات فاشلة`,
    newPasswordsNotSame: `كلمتا السر الجديدتان اللتان أدخلتهما غير متماثلتين`,
    passwordSuccesfullyChanged: `تم تغيير كلمة السر بنجاح`,
    accountBlockedFifteenMinutes: `تم قفل حسابك. يرجى المحاولة مرة أخرى بعد 15 دقيقة`,
    loadingLegalDocuments: `جارٍ تحميل الوثائق القانونية...`,
    fr: `الفرنسية`,
    errorFetchingLegalDocuments: `خطأ في تحميل الوثائق القانونية`,
    nameAndMrnNotFound: `لم يتم العثور على مجموعة معرف المريض واسم العائلة`,
    duplicateNameAndMrn: `معرف المريض موجود بالفعل في Care4Today`,
    NSCameraUsageDescription: `يتطلب هذا التطبيق الوصول إلى الكاميرا لإضافة / تحديث صورة الملف الشخصي وإضافة مرفقات إلى الملاحظات`,
    NSPhotoLibraryUsageDescription: `يتطلب هذا التطبيق الوصول إلى مكتبة الصور لإضافة مرفقات إلى الملاحظات`,
    initiate: `بدء`,
    lastNameAsc: `اسم العائلة تصاعدي`,
    lastNameDesc: `اسم العائلة تنازلي`,
    firstNameAsc: `الاسم الأول تصاعدي`,
    firstNameDesc: `الاسم الأول تنازلي`,
    messageParticipantIsInactive: `لم يعد نشطًا`,
    participantNoLonger: `لم يعد المشارك مستخدمًا للمنصة`,
    requestDeletionInProgress: `طلب حذف البيانات الشخصية قيد التقدم بالفعل. سيُطلعك فريق الدعم على آخر المستجدات بمجرد الانتهاء من ذلك`,
    contactNotAvailableOnDeactivated: `تفاصيل الاتصال غير متاحة لاختصاصي الرعاية الصحية المعطل`,
    deactivated: `معطل`,
    noPermissionToSendMessage: `ليس لديك إذن بإرسال رسالة إلى هذا الشخص`,
    refrainSendingMedData: `يُرجى الامتناع عن إرسال الرسائل التي تحتوي على بيانات/معلومات طبية خاصة بالمريض`,
    refrainEnteringMedData: `يُرجى الامتناع عن إدخال البيانات/المعلومات الطبية الخاصة بالمريض في الحقل أعلاه`,
    contactHospitalAppointment: `يُرجى الاتصال بالمستشفى في حال رغبتك في تحديث الموعد أو إلغائه!`,
    noInfoDescriptionAppointment: `لا يوجـد مزيد من المعلومات. يُرجى الاتصال بالمستشفى في حالة الشك أو عندما يكون لديك أي أسئلة حول هذا الموعد.`,
    noInfoDescriptionAndDateAppointment: `سيصدر قريبًا تحديث سيقدم مزيدًا من المعلومات حول الموعد. يُرجى الاتصال بالمستشفى في حالة الشك أو عندما يكون لديك أي أسئلة حول هذا الموعد.`,
    participants: `المشاركون`,
    noMdtAssigned: `لم يتم تخصيص فريق متعدد الاختصاصات للمريض. يُرجى تخصيص فريق للمريض أولاً.`,
    scheduled: `مجدول`,
    updated: `مُحدث`,
    proposed: `مُقترح`,
    he: `اللغة العبرية`,
    restrictProcessingPersonal: `تقييد معالجة بياناتي الشخصية`,
    restrictProcessingArticle: `استنادًا إلى المادة 18 من النظام الأوروبي العام لحماية البيانات (GDPR)، أي مما يلي ينطبق على حالتك؟`,
    dataAccuracy: `دقة البيانات`,
    unlawfulProcessing: `المعالجة غير القانونية`,
    legalClaim: `المطالبة القانونية`,
    provideExplanation: `يُرجى تقديم توضيح:`,
    provideExplanationDescription: `يُرجى تقديم نص توضيحي لوصف المشكلة والمساعدة في تقييم طلبك`,
    restrictProcessing: `تقييد المعالجة`,
    sureProcessing: `هل أنت متأكد من رغبتك في تقييد معالجة بياناتك الشخصية؟`,
    processingPasswordConfirmation: `بقيامك ببدء هذا الطلب، سيتم تعطيل بياناتك بشكل مؤقت، وما لم نُعلمك بخلاف ذلك، فإننا لن نقوم إلا بتخزين البيانات، ولن نجري عليها أي معالجة إلا إذا حصلنا على موافقتك. لطرح أية أسئلة أخرى أو لتقديم طلب التقييد، يُرجى التواصل عبر support@care4todaypatient.com. يُرجى إدخال كلمة المرور الخاصة بك لتأكيد هذا الإجراء:`,
    processingSent: `تم إرسال طلب تقييد معالجة البيانات الشخصية إلى صندوق البريد الخاص بدعم Care4Today`,
    versionNumber: (params: string[]) => `الإصدار ${params[0]}`,
    pleaseSelect: `يرجى التحديد:`,
    restrictedLogout: `لقد خضع حسابك إلى تسجيل الخروج لأن طلبك لتقييد معالجة البيانات الشخصية قد تم التعامل معه وتم تطبيق قيود على حساب Care4Today الخاص بك. إذا كانت لديك أية أسئلة، يُرجى التواصل عبر support@care4todaypatient.com`,
    restrictProcessingAlreadyRequested: `جاري التعامل بالفعل على طلب تقييد معالجة البيانات الشخصية الذي قدمته. سيُطلعك فريق الدعم على آخر المستجدات بمجرد الانتهاء من ذلك.`,
    rightToRestrictQuestion: `استنادًا إلى المادة 18 من النظام الأوروبي العام لحماية البيانات (GDPR)، أي مما يلي ينطبق على حالتك؟`,
    rightToRestrictExplanation: `يُرجى تقديم توضيح:`,
    rightToRestrictTitle: `تقييد معالجة بياناتي الشخصية`,
    rightToRestrictExplanationPlaceholder: `يُرجى تقديم نص توضيحي لوصف المشكلة والمساعدة في تقييم طلبك.`,
    rightToRestrictConfirmationTitle: `هل أنت متأكد من رغبتك في تقييد معالجة بياناتك الشخصية؟`,
    rightToRestrictConfirmationDescription: `سيُرسل طلبك إلى فريق الدعم. سيتم تعطيل حسابك وبياناتك بشكل مؤقت، وما لم نُعلمك بخلاف ذلك، فإننا لن نقوم إلا بتخزين البيانات، ولن نجري معالجة لها إلا إذا حصلنا على موافقتك. لطرح أي أسئلة أخرى أو لتقديم طلب التقييد، يُرجى التواصل عبر support@care4todaypatient.com`,
    assignedRole: (params: string[]) => `المعين ${params[0]} (غير نشط)`,
    requestRestrictionSubmitted: `تم إرسال طلب تقييد معالجة البيانات الشخصية إلى صندوق بريد دعم Care4Today`,
    temporarelyUnavailableHCPAlertMessage: `اختصاصي الرعاية الصحية (HCP) غير متاح مؤقتًا على المنصة. إذا كانت لديك أي أسئلة، يُرجى التواصل مع فريق الدعم.`,
    temporarelyUnavailableHCPSubtitle: `اختصاصي الرعاية الصحية (HCP) غير متاح مؤقتًا`,
    assignedHCP: (params: string[]) => `المعين ${params[0]}`,
    inactive: `غير نشط`,
    appointmentInvite: `لديك موعد`,
    disabledAppointmentActionMessage: `يُرجى استخدام نظام حجز المواعيد الخاص بالمستشفى مباشرة لجدولة موعد أو تحديثه أو إلغائه.`,
    noFurtherInformation: `لا يوجـد مزيد من المعلومات`,
    cancelled: `مُلغى`,
    cancelledNotificationPrefix: `مُلغى:`,
    updatedNotificationPrefix: `مُحدث:`,
    allDay: `طوال اليوم`,
    editCareModule: `تعديل وحدة الرعاية`,
    nextSurgeryProcedureInformation: `التالي: تفاصيل الجراحة/ الإجراء`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `لم يعد جزءًا من فريق متعدد الاختصاصات المخصص لك ${params[0]}`,
    editCareModuleWarning: `يرجى ملاحظة أنه بمجرد تغيير وحدة الرعاية، فإن كل تاريخ الأهداف ومواد التعليم الخاصة بالإجراء السابق لن تصبح متاحة للمريض`,
    editSurgeryWarning: `يُرجى تعديل بيانات الجراحة إذا لزم الأمر.`,
    nextUpdateMDT: `التالي: تحديث الفريق الطبي`,
    updateCareModule: `تحديث وحدة الرعاية`,
    editMdtTeamWarning: `يُرجى مراجعة الفريق المتعدد الاختصاصات للتحقق إن كان هناك تحديثات مطلوبة.`,
    participantNotInMDT: `لم تعد جزءًا من الفريق متعدد الاختصاصات لهذا المريض`,
    createMedicalTeam: `تشكيل فريق طبي`,
    editMedicalTeam: `تعديل الفريق الطبي`,
    mdtName: `اسم الفريق المتعدد الاختصاصات`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `هل أنت متأكد من رغبتك في تغيير وحدة رعاية هذا المريض من '${
            params[0]
        }' إلى '${params[1]}'؟`,
    changePathwayConfirmationSubTitle: `يرجى ملاحظة أنه بمجرد تغيير وحدة الرعاية، فإن كل تاريخ الأهداف ومواد التعليم الخاصة بالإجراء السابق لن تصبح متاحة للمريض`,
    changePathwaySuccessMessage: (params: string[]) =>
        `لقد نجحت بتغيير وحدة رعاية المريض ${params[2]} من '${
            params[0]
        }' إلى '${params[1]}'`,
    mdtChanged: `لقد تم تغير فريقك الطبي`,
    tapForDetails: `اضغط هنا لمعرفة التفاصيل.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} لم يعد جزءًا من\nفريق متعدد الاختصاصات المخصص لك`,
    addPatientReceivedConsent: `يُعد تقديمي للمعلومات أدناه إقرارًا مني بأني قد حصلت على موافقة من المريض على معالجة بياناته.`,
    attended: `تم الحضور`,
    entityCreationError: (params: string[]) =>
        `حدثت مشكلة أثناء إنشاء ${params[0]}`,
    updateAppointmentError: `حدثت مشكلة عند محاولة تحديث الموعد`,
    updateConsultationNoteError: `حدثت مشكلة عند محاولة تحديث ملاحظات الاستشارة`,
    createConsultationNoteError: `حدثت مشكلة عند محاولة إنشاء ملاحظات الاستشارة`,
    missed: `لم يحضر`,
    contentDescCloseNotification: `إغلاق الإخطار`,
    pathwayChanged: `لقد تغيرت وحدة الرعاية الخاصة بك`,
    pathwayChangedDetails: (params: string[]) =>
        `من ${params[0]} إلى ${
            params[1]
        }. يرجى الاتصال بمنسق الرعاية/ اختصاصي الرعاية الصحية المتابع بك للمزيد من المعلومات.`,
    de: `ألمانية`,
    doYouWantToDeletePatient: (params: string[]) =>
        `هل أنت متأكد من رغبتك في حذف المريض ${params[0]}؟`,
    personWillBeRemovedFromRecords: `لن يستطيع هذا الشخص بعد هذا تسجيل الدخول إلى تطبيق C4T وسيُحذف من السجلات الرقمية.`,
    provideDeletionReason: `يُرجى توضيح سبب الحذف:`,
    deletionSuccess: (params: string[]) =>
        `لقد أتممت حذف ${params[0]} بنجاح من المنصة`,
    consentNotProvided: `لم يتم تقديم الموافقة`,
    entryError: `مشكلة في الإدخال`,
    duplicatePatient: `مريض مكرر`,
    addExtraSecurity: `أضِف المزيد من الحماية لحسابك عن طريق التحقق من خطوتين`,
    mfaDescription: `في كل مرة تسجل فيها الدخول إلى حسابك من جهاز جديد، سيُطلب منك إدخال رمز أمان.سيُرسل إليك رمز الامان هذا بالبريد الإلكتروني أو على الهاتف.`,
    activateMfa: `تفعيل التحقق من خطوتين`,
    userAccountNotActive: `حساب المستخدم الخاص بك غير مفعّل`,
    useHCPPortal: `يُرجى استخدام بوابة متخصصي الرعاية الصحية على الإنترنت إن كنت قد نسيت كلمة المرور الخاصة بك`,
    noPatientsAssigned: `لا يوجد مريض معين لك`,
    currentAppointments: `المواعيد الحالية`,
    noCurrentAppointments: `لا توجد مواعيد مستقبلية متاحة`,
    phase: `المرحلة`,
    noPhaseInformation: `لا توجد أي معلومات عن المرحلة`,
    noSubphaseInformation: `لا توجد أي معلومات عن المرحلة الفرعية`,
    you: (params: string[]) => `${params[0]} (أنت)`,
    hcpsMedicalStaff: `متخصصو الرعاية الصحية`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `في ${params[0]} (${params[1]})`,
    newMessage: `رسالة جديدة`,
    addParticipant: `إضافة مشارك`,
    editParticipant: `تعديل مشارك`,
    messagesFor: (params: string[]) => `إرسال رسالة إلى ${params[0]}`,
    noParticipants: `لا يوجد مشاركون متاحون`,
    whichMfaMethod: `ما الطريقة التي تود من خلالها استلام رمز الأمان؟`,
    mfaMethodExplanation: `رمز الأمان هذا مطلوب للوصول إلى حسابك. يمكنك الحصول على رمز تسجيل الدخول عن طريق استخدام هاتفك المحمول أو البريد الإلكتروني. اختر الطريقة التي تناسبك.`,
    textMe: `إرسال رمز تسجيل الدخول عبر رسالة نصية`,
    emailMe: `إرسال رمز تسجيل الدخول عبر البريد الإلكتروني`,
    textMeSubtitle: `سوف نطلب رقم هاتفك`,
    emailMeSubtitle: `يُرجى تأكيد عنوان بريدك الإلكتروني`,
    backToMethod: `رجوع لاختيار الطريقة`,
    addPhone: `إضافة رقم هاتف`,
    whichPhone: `ما رقم الهاتف الذي ترغب في استلام رمز الأمان عليه؟`,
    phoneDisclaimer: `لن يُستخدم رقم الهاتف هذا إلا لأمان الحساب. قد تُفرض رسوم على إرسال الرسائل النصية واستخدام البيانات.`,
    sendCode: `إرسال رمز الأمان`,
    confirmEmail: `تأكيد بريدك الإلكتروني`,
    whichEmail: `ما عنوان البريد الإلكتروني الذي ترغب في استلام رمز الأمان عليه؟`,
    emailDisclaimer: `لن يُستخدم عنوان البريد الإلكتروني هذا إلا لأمان الحساب.`,
    insertCode: `يُرجى إدخال رمز الأمان.`,
    mayTakeTwoMinutes: `قد يستغرق استلام الرمز ما يصل إلى دقيقتين.`,
    sentCodeByText: (params: string[]) =>
        `لقد أرسلنا للتوّ رمز الأمان عبر رسالة نصية إلى ${params[0]}`,
    sentCodeByEmail: (params: string[]) =>
        `لقد أرسلنا للتوّ رمز الأمان عبر البريد الإلكتروني إلى ${params[0]}`,
    didntGetCode: `لم تتلق الرمز؟`,
    resendCode: `إعادة إرسال رمز الأمان`,
    authenticate: `المصادقة`,
    verifyingCode: `التحقق من رمز الأمان`,
    mfaSuccess: `تم بنجاح! تم تمكين المصادقة على خطوتين!`,
    mfaCodeRequired: `رمز تسجيل الدخول مطلوب لكي تستطيع الوصول إلى حسابك.`,
    mfaMethodExplanationLogin: `رمز الأمان هذا مطلوب للوصول إلى حسابك. يمكنك الحصول على رمز تسجيل الدخول عن طريق استخدام هاتفك المحمول أو البريد الإلكتروني.`,
    contentDescMfaIcon: `أيقونة المصادقة على خطوتين`,
    mfaSendCodeTo: (params: string[]) => `سنرسل الرمز إلى ${params[0]}`,
    continueLabel: `متابعة`,
    authenticating: `المصادقة`,
    mfaInvalidCode: `الرمز الذي أدخلته غير صالح. يُرجى المحاولة مرة أخرى.`,
    mfaUnableToVerifyPhoneNumber: `لا يمكننا التحقق من رقم الهاتف هذا. يُرجى تجربة رقم آخر.`,
    mfaUnableToVerifyEmail: `لا يمكننا التحقق من عنوان البريد الإلكتروني هذا. يُرجى تجربة عنوان آخر.`,
    sessionExpired: `انتهت صلاحية جلستك. يرجي تسجيل الدخول مرة أخرى.`,
    passwordExpired: `انتهت صلاحية كلمة مرورك. يُرجى تغيير كلمة مرورك.`,
    rightToBeForgottenInfoNonIntegrated: `ببدء هذا الطلب، سيتم حذف بياناتك الشخصية ولن يصبح بإمكانك الوصول إلى هذا التطبيق. لطرح أي أسئلة أخرى، يُرجى التواصل عبر support@care4todaypatient.com. يُرجى ادخال كلمة السر الخاصة بك لتأكيد هذا الإجراء:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `سيُرسل طلبك إلى فريق الدعم. سيتم تعطيل حسابك وبياناتك بشكل مؤقت، وما لم نُعلمك بخلاف ذلك، فإننا لن نقوم إلا بتخزين البيانات، ولن نجري معالجة لها إلا إذا حصلنا على موافقتك. لطرح أي أسئلة أخرى أو لتقديم طلب التقييد، يُرجى التواصل عبر support@care4todaypatient.com`,
    password_expired_message: `انتهت صلاحية كلمة المرور ويجب تغييرها للوصول إلى C4T`,
    firstdayOftheWeek: `اليوم الأول من الأسبوع`,
    dateformat: `تنسيق التاريخ`,
    selectDateFormat: `اختيار تنسيق التاريخ`,
    selectDay: `حدد يومًا`,
    monday: `الإثنين`,
    tuesday: `الثلاثاء`,
    wednesday: `الأربعاء`,
    thursday: `الخميس`,
    friday: `الجمعة`,
    saturday: `السبت`,
    sunday: `الأحد`,
    manageTheAppointmentTemplates: `إدارة قالب الموعد`,
    prefillTemplatesFor: `التعبئة المسبقة للقوالب الخاصة بـ`,
    appointmentTemplates: `قوالب المواعيد`,
    backToTemplateTypes: `الرجوع إلى أنواع القوالب`,
    addNewAppointmentTemplate: `إضافة قالب موعد جديد`,
    caremoduleName: `اسم وحدة الرعاية`,
    selectPathway: `اختيار مسار`,
    notShowInDropdownAfterDelete: `إذا تم حذف هذا القالب، فلن يظهر بعد ذلك في القائمة المنسدلة`,
    messagesTemplates: `قوالب الرسائل`,
    addNewMessageTemplate: `إضافة قالب رسالة جديد`,
    pathway: `المسار`,
    template: `القوالب`,
    typesTwo: `نوعان`,
    scheduledAppointmentInDropdown: `إذا تم حذف هذا القالب، فلن يظهر بعد ذلك في حقول القائمة المنسدلة عند تحديد موعد.`,
    manageTemplate: `إدارة القالب`,
    manageTheMessageTemplates: `إدارة قالب الرسالة`,
    addMdt: `+ إضافة MDT (فريق متعدد التخصصات) جديد إلى المنصة`,
    mdts: `MDTs (فرق متعددة التخصصات)`,
    NameAsc: `الاسم ”تصاعدي“`,
    NameDesc: `الاسم ”تنازلي“`,
    Teams: `الفرق`,
    MdtsName: `اسم MDTs (الفرق متعددة التخصصات)`,
    managemdts: `إدارة MDTs (الفرق متعددة التخصصات)`,
    members: `الأعضاء`,
    editTeam: `تحرير الفريق`,
    addANewMDTToThePlatform: `إضافة MDT (فريق متعدد التخصصات) جديد إلى المنصة`,
    week: `الأسبوع`,
    month: `الشهر`,
    year: `السنة`,
    total: `الإجمالي`,
    dailyaverage: `المتوسط اليومي`,
    nochartdata: `لا توجد بيانات مخطط متاحة`,
    youCanOnlyAssignOneMDTAtATime: `يمكنك تعيين MDT (فريق متعدد التخصصات) واحد فقط في وقت محدد`,
    noMoreOptionsAvailable: `لا تتوفر المزيد من الخيارات`,
    mdt: `MDT (فريق متعدد التخصصات)`,
    relatingPatient: `ربط مريض`,
    nonrelatingPatient: `عدم ربط مريض`,
    sendMsgPatient: `إرسال رسالة جديدة إلى المريض`,
    expectedResponseTime: `وقت الاستجابة المتوقع بين 3 إلى 4 ساعات`,
    walkedText: `تم المشي`,
    walk: `مشي`,
    mymedicalteam: `فريقي الطبي`,
    yesterday: `الأمس`,
    close: `إغلاق`,
    passwordUsedBefore: `لقد استُخدمت كلمة المرور الجديدة في السابق ولا يمكن إعادة استخدامها. يُرجى إدخال كلمة مرور أخرى.`,
    sendMessageTo: `إرسال رسالة إلى`,
    message: `الرسالة`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} أضاف ${params[1]} إلى المحادثة`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} أزال ${params[1]} من المحادثة`,
    removedParticipant: `تمت إزالة المشارك`,
    noMessagesSelected: `ليس لديك رسالة محددة`,
    noMessagesSelectedDesc: `حدد رسالة على الجانب الأيسر من الشاشة أو ابدأ محادثة جديدة`,
    mfaMethodExplanationRegistration: `رمز الأمان هذا مطلوب للوصول إلى حسابك. يمكنك الحصول على رمز تسجيل الدخول باستخدام هاتفك المحمول أو بريدك الإلكتروني. يُرجى اختيار الطريقة الأنسب لك.\n\nيُرجى العلم أنه يمكنك اختيار طريقة تحقق واحدة فقط في هذا الوقت. بمجرد اختيارك، سيتم حفظ تفضيلاتك ولا يمكن تغييرها دون الاتصال بمكتب المساعدة.`,
    signinCodeRequired: `طلب رمز الأمان`,
    securityCodeRequired: `رمز الأمان هذا مطلوب للوصول إلى حسابك. يمكنك الحصول على رمز تسجيل الدخول باستخدام الطريقة التي اخترتها أثناء التسجيل الأول.`,
    newMfaUserDesc1: `رمز الأمان هذا مطلوب للوصول إلى حسابك. يمكنك الحصول على رمز تسجيل الدخول باستخدام هاتفك المحمول أو بريدك الإلكتروني. يُرجى اختيار الطريقة الأنسب لك.`,
    newMfaUserDesc2: `يُرجى العلم أنه يمكنك اختيار طريقة تحقق واحدة فقط في هذا الوقت. بمجرد اختيارك، سيتم حفظ تفضيلاتك ولا يمكن تغييرها دون الاتصال بمكتب المساعدة.`,
    feelFreeToMessageTeam: `لا تتردد في بدء محادثة مع شخص من فريقك.`,
    noFutureMessages: `ليس لديك أي رسائل بعد`,
    chatSelfRemove: `لقد أزلت نفسك من المحادثة بنجاح`,
    noResultFound: `لم يتم العثور على نتائج`,
    chatUpdated: `تم تحديث المحادثة بنجاح`,
    chatNotUpdated: `لم يتم تحديث المحادثة`,
    searchPlaceholder: `بحث عن قالب...`,
    editPrefillTemplate: `تحرير قالب مسبق الملء`,
    forAppointments: `للمواعيد`,
    addTemplateToList: `إضافة قالب إلى قائمة`,
    addNewPrefillTemplate: `إضافة قالب مسبق الملء جديد`,
    forMessages: `للرسائل`,
    editNewPrefillTemplate: `تحرير قالب مسبق الملء جديد`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
