export const LANG_EN_TRANS = {
    accept: `Accept`,
    accepted: `Accepted`,
    acceptedInvitation: `You have accepted this invitation.`,
    actions: `Actions`,
    addHcp: `Add HCP to platform`,
    addHCPTag: `+ HCP`,
    addHcpToPlatform: `Add an HCP to the platform`,
    addNewHCP: `+ Add new HCP to the platform`,
    addNewPatient: `+ Add a new patient to the platform`,
    addPatient: `Add patient`,
    addPatientConsent: `Hereby I confirm that I received the consent from the patient to enter the patient data.`,
    addPatientToPlatform: `Add patient to platform`,
    administration: `Administration`,
    agreed: `Agreed`,
    allHcps: `All HCPs`,
    allowNotifications: `You enabled notifications, super!`,
    allPatients: `All Patients`,
    almostHalfway: `You're almost halfway!`,
    almostThere: `You're almost there!`,
    am: `AM`,
    andMore: (params: string[]) => `and ${params[0]} more`,
    apiErrorGetConsentDocument: `Failed to load consent document Tap here to try again`,
    appointment: `Appointment`,
    appointmentAcceptedByPatient: `Accepted by patient`,
    appointmentAwaitingPatientResponse: `Awaiting response from patient`,
    appointmentDeclinedByPatient: `Declined by patient`,
    appointmentName: `Appointment name`,
    appointmentNotification: `Appointment notification`,
    appointments: `Appointments`,
    appointmentsForPatient: (params: string[]) =>
        `Appointments for ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `An appointment can be scheduled between ${params[0]} and ${params[1]}`,
    appUnavailable: `We're sorry, the app is currently unavailable. Please try again later or check for updates.`,
    april: `April`,
    ar: `Arabic`,
    areYouSureDeclineMessage: `Clinical team needs you onboard to help you in the preparation and monitoring your progress.\n\nPlease contact your referral doctor if you don't want to join the platform`,
    areYouSureDeclineTitle: `Are you sure you don't want to join Care4Today platform?`,
    areYouSureDeleteNote: `Are you sure you want to delete this note?`,
    article: `Article`,
    assignToMDT: `Assign to MDT`,
    audio: `Audio`,
    august: `August`,
    back: `Back`,
    backToAppointments: `Back to your appointments`,
    backToDetails: (params: string[]) => `Back to ${params[0]}'s details`,
    backToLogin: `Back to Login`,
    backToPatientProfile: `Back to patient profile`,
    badPassword: `You have entered an invalid password.`,
    bariatrics: `Bariatrics`,
    blockedUser: `Your user has been blocked. Please try again in half an hour.`,
    bmi: `BMI`,
    bookedSuccess: `You have successfully booked your appointment`,
    cancel: `Cancel`,
    cancelAlert: `Cancel`,
    cantParseError: `Unable to parse response.`,
    cantSaveImage: `Unable to save image.`,
    care4Today: `Care4Today`,
    careModules: `Care modules`,
    changePassword: `Change password`,
    changePasswordSubtitle: `Choose your own, personal password.`,
    changePasswordTitle: `Please personalize your password`,
    choosePicture: `Choose picture`,
    chooseProfilePicture: `Change picture`,
    cm: `cm`,
    completed: `Completed`,
    conditionalGoal: `Conditional goal`,
    confirmAppointmentDelete: `Are you sure you want to delete this appointment?`,
    confirmed: `Confirmed`,
    confirmNewPasswordPlaceholder: `Confirm new password`,
    consent: `Consent`,
    consentDontAgree: `I don't agree and won't use the Care4Today platform`,
    consentedOn: (params: string[]) => `You gave consent on ${params[0]}`,
    contact: `Contact`,
    contactDetails: `Contact Details`,
    contactInfo: `CONTACT INFO`,
    contentDescApptIcon: `Appointment icon`,
    contentDescAttachImage: `Attach image`,
    contentDescAttachment: `Attachment`,
    contentDescAttachmentImg: `Full screen image`,
    contentDescBackground: `Background`,
    contentDescChangePwdIcon: `Change password icon`,
    contentDescClose: `Close full screen`,
    contentDescDeleteAttachment: `Delete image attachment`,
    contentDescDevicesIcon: `Connected devices icon`,
    contentDescEduContentExpandBtn: `Open educational content attachment`,
    contentDescEduContentThumb: `Educational content attachment`,
    contentDescEduItemCompleted: `Educational item is completed`,
    contentDescEduItemIncomplete: `Educational item is not completed`,
    contentDescGoalIcon: `Personal goal icon`,
    contentDescHelpIcon: `Help icon`,
    contentDescKillswitchIcon: `Killswitch icon`,
    contentDescLegalIcon: `Legal documents icon`,
    contentDescLogo: `Application logo`,
    contentDescLogoutIcon: `Logout icon`,
    contentDescMdtPic: `Health-care professional's picture`,
    contentDescMessageIcon: `Message icon`,
    contentDescNoGoalIcon: `No goal icon`,
    contentDescPathwayCurrent: `Current phase icon`,
    contentDescPathwayIcon: `Pathway icon`,
    contentDescPathwayOtherPhase: `Another phase icon`,
    contentDescProfilePic: `Profile picture`,
    contentDescSend: `Send`,
    create: `Create`,
    createAMedicalTeam: `Create a medical team`,
    createAppointment: `Create Appointment`,
    createAppointmentButton: `Create appointment and send invitation`,
    createAppointmentSuccess: `Appointment successfully created`,
    createAppt: `Create appt`,
    createMDT: `Create MDT`,
    currentBmi: `Current BMI`,
    currentPhase: `Current phase`,
    currentWeight: `Current weight`,
    dashboard: `Dashboard`,
    date: `Date`,
    dateOfBirth: `Date of birth`,
    dateOfConsent: `Date of Consent`,
    dateOfConsentAsc: `Date of Consent Asc`,
    dateOfConsentDesc: `Date of Consent Desc`,
    dateOfSurgery: `Date of surgery *`,
    december: `December`,
    decline: `Decline`,
    declined: `Declined`,
    declinedInvitation: `You have declined this invitation.`,
    declinedNotifications: `You didn't allow notifications, are you sure? You can change this in the settings menu.`,
    declinedSuccess: `You declined your appointment`,
    defaultError: `Something went wrong`,
    delete: `Delete`,
    deleteAppointmentSuccess: `Appointment successfully deleted`,
    deleteNote: `Delete note`,
    deleting: `Deleting...`,
    description: `Description`,
    details: `Details`,
    devices: `Connected devices`,
    disagreeConsentError: `An error occurred while you disagreed the consent. Please try again`,
    discardChanges: `Discard Changes?`,
    document: `Document`,
    done: `Done`,
    draftWontBeSaved: `Your draft wont be saved. Do you want to cancel anyway?`,
    duplicateMDT: `HCP already selected`,
    edit: `Edit`,
    editHcpsProfile: `Edit HCP profile`,
    editMessageDetails: `Edit conversation details`,
    editMTDTeam: (params: string[]) => `Edit team for ${params[0]}`,
    editPassword: `Edit password`,
    editPatient: `Edit patient`,
    editPatientError: `There was an issue updating the patient details`,
    editPatientSuccess: `Patient details successfully updated.`,
    editProfile: `Edit Profile`,
    editProfilePicture: `Edit profile picture`,
    editSubject: `Edit subject`,
    editTeamMembers: `Edit team members`,
    editYourPersonalGoal: `Edit your personal goal`,
    eduContentHint: `Please tap on the expand button to open the attached content.`,
    email: `Email`,
    emailAddress: `Email address`,
    emailConfirmation: (params: string[]) =>
        `We've sent an email to ${
            params[0]
        } with a link to reset your password.`,
    emailExists: (params: string[]) =>
        `A user with the email ${params[0]} already exists.`,
    emailSent: `Email Sent`,
    en: `English`,
    enableNotifications: `Enable notifications`,
    enterANewHCP: `Enter a new HCP`,
    enterSubjectHint: `Enter subject`,
    enterTheSubject: `Enter the subject for this conversation.`,
    errorEditingHcp: `An error has occurred editing the HCP`,
    errorFindingConsentDocument: `Error finding consent document.`,
    errorLoading: (params: string[]) => `Error loading ${params[0]}`,
    errorSavingSettings: `Error saving settings`,
    errorUpdatingPassword: `Could not update password`,
    excessWeightLost: `Excess weight lost`,
    failEditHcp: `There was an error editing your profile`,
    february: `February`,
    female: `Female`,
    filter: `Filter`,
    firstName: `First name`,
    forgotPasswordInstruction: `Provide the email address you're registered with at your hospital. We'll send you and email with a link to reset your password.`,
    forgotPasswordViewTitle: `Forgot Password`,
    forgotYourPassword: `Forgot your password?`,
    formTimeRangeInPast: `The time range cannot be in the past`,
    formTimeRangeStartGreaterThanEnd: `The time range is invalid`,
    forPatient: `For`,
    from: `From`,
    ft: `ft`,
    fullName: `Full name`,
    function: `Function`,
    gained: `gained`,
    gender: `Gender`,
    goal: `Goal`,
    goalSavedError: `The goal could not be saved!`,
    goalSavedSuccess: `Goal saved successfully!`,
    goBack: `Go back`,
    hcps: `HCPs`,
    healthCareProfessionals: (params: string[]) =>
        `${params[0]} healthcare professionals`,
    height: `Height`,
    help: `Help`,
    heyChooseYourPicture: (params: string[]) =>
        `Hey ${params[0]}, choose your profile picture`,
    iAgree: `I agree`,
    iAgreeFormat: (params: string[]) => `I agree (${params[0]}/${params[1]})`,
    iAmSure: `I am sure`,
    idealBodyWeight: `Ideal body weight`,
    iDoNotAgree: `I do not agree`,
    iDontAgree: `I don't agree and won't use the Care4Today platform`,
    imperial: `Imperial`,
    in: `in`,
    includeLinkToLocation: `Include link to location`,
    initialWeight: `Initial weight`,
    installUpdate: `Install Update`,
    invalidEmailError: `Not a valid email`,
    invalidNumber: `Please enter a valid number`,
    invalidTokenError: `Unable to authenticate, please try logging in again.`,
    it: `Italiano`,
    iWantToFitAgain: `Example: “I want to fit again in a size L”`,
    january: `January`,
    july: `July`,
    june: `June`,
    keepGoing: `Keep going!`,
    keepMomentum: `Keep up the momentum!`,
    kg: `kg`,
    kilogrammes: `kilogrammes`,
    language: `Language`,
    languageRequired: `Language *`,
    lastName: `Last name`,
    lb: `lb`,
    learningMaterials: `Learning Materials`,
    legalDocuments: `Legal documents`,
    loading: `Loading`,
    loadingPatients: `Loading Patients, please wait`,
    location: `Location`,
    locationUrl: `Location URL`,
    lockScreenHint: `You need to setup a device lock-screen, to enable secure usage of the app.`,
    login: `Log in`,
    loginIncorrect: `Email or Password you have entered is incorrect`,
    logout: `Logout`,
    logoutAreYouSure: `Are you sure you want to logout?`,
    loseBefore: (params: string[]) => `Lose ${params[0]}`,
    loseFormat: (params: string[]) => `Lose ${params[0]} ${params[1]}`,
    lost: `lost`,
    male: `Male`,
    manageHCPs: `Manage HCPs`,
    managePatients: `Manage patients`,
    march: `March`,
    may: `May`,
    mdtTeam: `MDT Team`,
    mdtTeamNotAddedYet: `MDT not assigned yet.`,
    mdtTeamUC: `MDT TEAM`,
    medicalTeam: `Medical team`,
    meetingInvite: `You have a meeting`,
    meetingInviteWith: (params: string[]) => `Meeting with ${params[0]}`,
    messageCreated: `You successfully started a conversation.`,
    messageNotCreated: `You have failed to start a conversation.`,
    messageNotification: `Message notification`,
    messageNotSent: `Message not sent`,
    messages: `Messages`,
    metric: `Metric`,
    movePhaseConfirmation: (params: string[]) =>
        `Are you sure you want to move ${params[0]} to phase ${params[1]}`,
    moveToNextPhase: `Move to next phase`,
    multiDisTeam: `Multidisciplinary Team`,
    myMessages: `My messages`,
    myMotivation: `My motivation:`,
    myPersonalGoal: `My personal goal`,
    myProfile: `My Profile`,
    myTeam: `My team`,
    name: `Name`,
    nameOfMDT: `Name of MDT *`,
    needsConsent: `Patient should first accept the consent.`,
    networkError: `A network error occurred`,
    newAppointment: `New appointment`,
    newChat: `New chat`,
    newInvitation: `New invitation`,
    newMessageNotificationMore: (params: string[]) =>
        `You have ${params[0]} new messages. Open the app to see what's new.`,
    newMessageNotificationOne: `You have one new message. Open the app to see what's new.`,
    newNote: `New note`,
    newPasswordPlaceholder: `New password`,
    newPatientSuccess: (params: string[]) =>
        `You successfully added ${params[0]} to the platform.`,
    newTeamFail: `MDT team not assigned`,
    newTeamSuccess: `MDT Team assigned`,
    newVersionApp: `Please update this app with the latest version that's available on the app store.`,
    nextAppointment: `Next appointment`,
    nextSelectCareModule: `Next: Select Care Modules`,
    nextSurgeryInformation: `Next: Surgery Information`,
    niceToSeeYouAgain: `Nice to see you again!`,
    nickname: `Nickname`,
    nicknameError: `Invalid nickname. Special characters are not allowed.`,
    nl: `Nederlandse`,
    no: `No`,
    noAppointments: `There are no appointments available`,
    noCurrentGoalForPatient: `There is no current goal associated with this patient`,
    noDate: `no date set`,
    noFutureAppointments: `No upcoming appointments`,
    noGoalSet: `No goal set by your HCP`,
    noMatchingConsentDocumentsFound: `No Matching consent documents found`,
    noMessages: `There are no messages available`,
    noNetworkConnection: `No network connectivity available. Please check…`,
    noNotesMessage: `There are no notes available.\n Tap on “Create” to add new notes`,
    noPersonalGoalSet: `No personal goal set.`,
    noPersonalGoalSetDashboard: `No personal goal set. Go to the settings page to update it.`,
    noPlannedAppointments: `No planned appointments`,
    noPreview: `No preview available`,
    noProgressRecorded: `No progress recorded`,
    noResponseError: `No response received.`,
    notAgreed: `Not agreed`,
    noteDeletedError: `The note could not be deleted!`,
    noteDeletedSuccessfully: `Note deleted successfully!`,
    notes: `Notes`,
    noteSaved: `Note saved`,
    noteSavedError: `The note could not be saved!`,
    noteSavedSuccess: `Note saved successfully!`,
    noteSaveError: `Error, unable to save note. Try again?`,
    notifications: `Notifications`,
    notNow: `Not now`,
    notSet: `Not set`,
    notYetSubmitted: `Not yet submitted`,
    noUnreadMessages: `No unread messages`,
    noUserFound: `Error finding the user with the supplied credentials.`,
    november: `November`,
    noWeightDifference: `No weight difference`,
    october: `October`,
    ok: `OK`,
    onboardingNotificationsTitle: `We want to keep you up-to-date every time`,
    onboardingNotifictionsInfo: `You'll get notified about:\n\n• Your appointments\n• New messages from your medical team`,
    onVar: (params: string[]) => `on ${params[0]}`,
    openCare: `Please open care4today and check if you have new notifications!`,
    optOutSubtitle: `Please contact your referral doctor is you don't want to join the platform.`,
    optOutTitle: `Are you sure you don't want to join the Care4Today platform?`,
    organisation: `Organisation`,
    orthopedics: `Orthopedics`,
    other: `Other`,
    outdatedVersion: `You are currently using an outdated version of the app.`,
    overview: `Overview`,
    participant: `Participant`,
    password: `Password`,
    passwordComplexityError: `Password should be at least 8 characters long and have at least 2 of following types of characters: Upper case letters, lower case letters, numbers or symbols.`,
    passwordMismatchError: `Passwords do not match`,
    passwordUpdated: `Password Updated`,
    pastAppointments: `Past appointments`,
    pathwayScheduleFail: `An error occurred. Pathway schedule could not be updated`,
    patient: `Patient`,
    patientAge: (params: string[]) => `${params[0]} years`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} years`,
    patientConsent: `Patient Consent`,
    patientNameAsc: `Patient Name Asc`,
    patientNameDesc: `Patient Name Desc`,
    patientRegistration: `Patient Registration`,
    patients: `Patients`,
    patientsCount: (params: string[]) => `${params[0]} Patients`,
    patientsOverview: `Patients overview`,
    pending: `Pending`,
    percent: `%`,
    personalGoal: `Personal goal`,
    personalGoalEdit: `Personal goal`,
    personalPassword: `Personal Password`,
    personalPasswordHelper: `Please choose your own, personal password. You can always change your password again in the settings menu.`,
    phoneError: `Invalid phone number. Please only use numbers (no parenthesis, hyphens, +)`,
    phoneNumber: `Phone number`,
    picture: `Picture`,
    pictureInstructions: `Please choose your personal profile picture. This picture will be used for your own account.`,
    pleaseConnect: `Please connect to the Internet to ensure you are using the latest version of the app.`,
    pleaseContactYourHospital: `Please contact your hospital directly in case of an emergency.`,
    pleaseProvidePassword: `Please provide your password to confirm this action:`,
    pm: `PM`,
    pounds: `pounds`,
    preparation: `Preparation`,
    preSurgeryPrep: `Pre Surgery Preparation`,
    previous: `Previous`,
    privacyPolicy: `Privacy Policy`,
    profileLabel: `We will use this to address you in emails, text messages, and this app. We will also pass on this information to your medical team.`,
    profilePicture: `Profile Picture`,
    profileTitle: `We will use this to address you in emails, text messages, and this app. We will also pass on this information to your medical team.`,
    progress: `Progress`,
    progressMsgForgotPwd: `Validating…`,
    progressMsgLoading: `Loading…`,
    progressMsgLoadingContent: `Loading content…`,
    progressMsgLogin: `Loading Pathway, \nThis may take up to 1 minute…`,
    progressMsgMdtLoading: `Loading MDT…`,
    progressMsgNotesLoading: `Loading notes…`,
    progressMsgProfileEdit: `Saving Profile…`,
    progressMsgProfilePhoto: `Saving photo…`,
    progressMsgResetPwd: `Saving password…`,
    provideTheEmail: `Provide the email address you're registered with at the hospital.`,
    pwdValidationDoesNotMatch: `Your passwords do not match`,
    pwdValidationIllegal: `Contains not allowed characters`,
    pwdValidationNotComplex: `Password complexity has not been met`,
    pwdValidationTooShort: `Your password is too short`,
    quickFilter: `Quick filter`,
    remindmeLater: `Remind Me Later`,
    requiredFields: `Required fields`,
    requiredHCPs: `HCPs *`,
    resetPassword: `Reset password`,
    respond: `Respond`,
    retry: `Retry`,
    save: `Save`,
    saveAndContinue: `Save and continue`,
    saveChanges: `Save Changes`,
    scheduleNewAppointment: `Schedule new appointment`,
    searchInConversation: `Search in conversations...`,
    secureRealmError: `Failed to launch - need lock-screen enabled`,
    selectDifferentImage: `Select a different image`,
    selectFile: `Select file`,
    selectFunction: `Select Function`,
    selectLanguage: `Select Language`,
    selectOneOrMoreHCPs: `Select one or more HCPs`,
    selectPictureSource: `Select picture from`,
    selectProfilePicture: `Select a profile picture`,
    selectSurgeon: `Select Surgeon`,
    send: `Send`,
    sendMessage: `Send Message`,
    sendNewMessage: `Send a new message`,
    september: `September`,
    setPassword: `Set password`,
    setPasswordReminder: `You can always change your password again in the settings menu.`,
    settings: `Settings`,
    setup: `SETUP`,
    setYourPersonalGoal: `Set your personal goal`,
    someonesPathway: (params: string[]) => `${params[0]}'s pathway`,
    sortBy: `Sort by`,
    splashSubtitle: `Weight Loss Surgery`,
    start: `Start`,
    startANewConversation: `Start a new conversation`,
    startConversation: `Start Conversation`,
    startingPoint: `Starting point`,
    startNewConversation: `+ Start new Conversation`,
    startPreparation: `Start with your preparation`,
    status: `Status`,
    subject: `Subject`,
    subjectChangedSuccess: `Conversation subject edited successfully`,
    subjectChangeFail: `Conversation subject not changed`,
    submit: `Submit`,
    subPhase: `SubPhase`,
    successEditHcp: `You successfully edited your profile`,
    surgeon: `Surgeon`,
    surgeryInformation: `Surgery Information`,
    tasks: `tasks`,
    tasksCompleted: `Tasks completed`,
    team: `Team`,
    thisMonth: `This month`,
    time: `Time`,
    timeAndLocation: `Time & Location`,
    timeOfSurgery: `Surgery Time *`,
    to: `To`,
    today: `today`,
    toDo: `To do`,
    undo: `Undo`,
    unitRequired: `Unit *`,
    units: `Units`,
    unknown: `Prefer not to say`,
    unknownError: `An error occurred while processing. Please try again…`,
    unknownGender: `I prefer not to answer`,
    unknownUser: `Unknown`,
    unreadMessage: `Unread Message`,
    unreadMessages: `Unread Messages`,
    untitled: `Untitled...`,
    update: `Update`,
    updateAppointment: `Edit appointment`,
    updateAppointmentButton: `Save changes and send updates`,
    updateAppointmentSuccess: `Appointment successfully updated`,
    updateMessage: `You need to update this app from the app store to the most recent version in order to continue using the app`,
    updateProfilePicture: `Update profile picture`,
    updateProgress: `Update progress`,
    useCamera: `Use camera`,
    username: `Username`,
    video: `Video`,
    viewAllMessages: `View all messages`,
    viewAndEditPathway: `View and edit pathway dates`,
    viewDocument: `View document`,
    weight: `Weight`,
    weightLoss: `Weight loss`,
    weightUpdatedSuccess: `Current Weight is updated successfully`,
    welcomeHeader: `Welcome`,
    welcomeMessage: (params: string[]) => `Hi ${params[0]}!`,
    wellDoneNextStep: `Well done! You are prepared to move to the next step!`,
    withdrawConfirm: `OK, leave app`,
    withdrawConsent: `Withdraw consent`,
    withdrawConsentBody: `By withdrawing consent for processing your personal information, your local data such as notes and personal goals will be deleted and after a 30 days waiting-period, you will no longer be able to access the application.`,
    withdrawConsentTitle: `Are you sure you want to opt out from the Care4Today-platform?`,
    writeAMessage: `Write a message...`,
    writeSomething: `Write something…`,
    wrongUserName: `The username you have entered is incorrect`,
    xUnread: (params: string[]) => `${params[0]} unread`,
    yes: `Yes`,
    yesDelete: `Yes, delete`,
    yesDiscard: `Yes, discard`,
    youAreOffline: `You are offline`,
    youCanSetASentence: `You can set a sentence to motivate yourself to reach your personal goal.`,
    youGained: (params: string[]) => `You've gained ${params[0]}`,
    youGainedFormat: (params: string[]) =>
        `You've gained ${params[0]} ${params[1]}`,
    youHaveANewMessageFrom: (params: string[]) =>
        `You have a new message from ${params[0]}.`,
    youHaveNewAppointment: `You have a new appointment. Open the app to see what's new.`,
    youHaveNewAppointments: (params: string[]) =>
        `You have ${
            params[0]
        } new appointments. Open the app to see what's new.`,
    youHaveNewMessage: `You have one new message. Open the app to see what's new.`,
    youHaveNewMessages: (params: string[]) =>
        `You have ${params[0]} new messages. Open the app to see what's new.`,
    youHaveUndone: `You have undone your previous chosen option`,
    youLost: (params: string[]) => `You've lost ${params[0]}`,
    youLostFormat: (params: string[]) =>
        `You've lost ${params[0]} ${params[1]}`,
    yourAppointments: `Your Appointments`,
    yourGoals: `Your goals`,
    yourNote: `Your note`,
    yourPassword: `Your password`,
    yourPasswordHasBeenReset: `Your password has been reset`,
    yourProfile: `Your profile`,
    export: `Export`,
    exportData: `Export personal data`,
    exportDataFail: `An error occurred. Could not export data`,
    exportMyData: `Export my personal data`,
    goalStepCount: `Goal (steps/day)`,
    loadingPathway: `Loading pathway, this may take up to 1 minute`,
    loadingPatient: `Loading patient, please wait`,
    pleaseEnterTotalSteps: `Please enter total number of steps at the end of each day`,
    stepCount: `Step Count`,
    stepsPerDay: `steps/day`,
    walkStepsPerDay: (params: string[]) => `Walk ${params[0]} steps/day`,
    steps: `steps`,
    avgWeeklySteps: `Avg. steps this week`,
    rightToBeForgotten: `Delete my personal data`,
    totalStepsDuringDay: `Total steps taken during a day`,
    youAlreadyWalked: (params: string[]) =>
        `You have walked ${params[0]} steps today`,
    rightToBeForgottenTitle: `Are you sure you want to initiate deletion of your personal data?`,
    rightToBeForgottenInfo: `By initiating this request your personal information will be deleted and you will no longer be able to access the application. Please note that some limited personal information such as your name sent from the Hospital Information System may continue to appear in the appointments.  For any further questions please contact support@care4todaypatient.com.  Please provide your password to confirm this action:`,
    passwordHint: `Your password`,
    rightToBeForgottenSuccess: `Delete personal data request has been sent to Care4Today support mailbox`,
    incorrectPassword: `Incorrect password entered`,
    errorInitiatingRightToBeForgotten: `Error submitting request, please contact support directly`,
    updateStepCount: `Update step count`,
    mon: `Mon`,
    tue: `Tue`,
    wed: `Wed`,
    thu: `Thu`,
    fri: `Fri`,
    sat: `Sat`,
    sun: `Sun`,
    stepsAmount: (params: string[]) => `${params[0]} steps`,
    stepsGoalUpdateSuccess: `Steps value was added successfully`,
    search: `Search...`,
    successEditMDT: `MDT successfully updated`,
    failEditMDT: `An error occurred updating the MDT`,
    userCreationError: `An error occurred creating the user`,
    userUpdateSuccess: `User was successfully updated`,
    legal: `Legal`,
    termsOfUse: `Terms of Use`,
    disclaimer: `Disclaimer`,
    exportDataSuccessV1: `Personal data export request has been sent to Care4Today support team`,
    exportDataSuccess: `Personal data export initiated`,
    dataFormatV1: `Your personal data will be exported in CSV file format. File will be sent to your registered email address.`,
    dataFormat: `Your personal data will be exported in JSON file format. File will be sent to your registered email address.`,
    viewAllMaterials: `View all materials`,
    viewAllAppointments: `View all appointments`,
    enjoyYourDay: `Enjoy your free day!`,
    motivateAlmost: `You’re almost there!`,
    startConversationHcp: `Start a conversation with an HCP`,
    andYou: `, you`,
    viewAllNotifications: `View all notifications`,
    noInvitations: `No Invitations`,
    yourTimeline: `Your timeline`,
    currentSubphase: `Current Subphase`,
    updateWeight: `Update current weight`,
    teamLoading: `Team is loading`,
    noMdt: `No MDT assigned.`,
    teamDetails: `View team details`,
    showResolved: `Show resolved`,
    readDoc: `Read document`,
    consultationNotes: `Consultation Notes`,
    viewAllConsultationNotes: `View all consultation notes`,
    createNewNote: `+ Create new note`,
    dismiss: `Dismiss`,
    pictureError: `Picture load error`,
    wrongFormat: `Wrong image format`,
    backToDashboard: `Back to dashboard`,
    noMessage: `No messages`,
    noSpecialCharacters: `Special characters are not allowed.`,
    noNotesAvailable: `No notes available`,
    hcpPortal: `HCP Portal`,
    patientPortal: `Patient Portal`,
    consultationNote: `consultation note`,
    noteTitle: `Note title`,
    noteContents: `Note contents`,
    writeConsultationNotes: `Write consultation notes here`,
    createHcpNote: `Create Note`,
    consultationNoteCreatedBy: (params: string[]) =>
        `Created: ${params[0]} by ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `Last edited: ${params[0]}`,
    loadingConsultaionNotes: `Loading consultation notes`,
    consultationNotesFor: (params: string[]) =>
        `Consultation notes for ${params[0]}`,
    editHcpNote: `Edit note`,
    reason: `Reason`,
    writeReasonForEditing: `Write reason for editing...`,
    confirmCancelCreateNote: `Are you sure you want to exit without creating the note?`,
    confirmCancelEditNote: `Are you sure you want to exit without editing the note?`,
    rotateYourDevice: `Rotate your device`,
    patientId: `Patient ID`,
    oldPassword: `Old password`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `Documents`,
    hcpId: `HCP ID`,
    userInactivity: `You have been logged out due to inactivity.`,
    duplicateMrn: `This HCP ID already exists in Care4Today`,
    confirm: `Confirm`,
    viewDetails: `View details`,
    upperCaseLetters: `Upper case letters`,
    lowerCaseLetters: `Lower case letters`,
    numbers: `Numbers`,
    specialCharacters: `Special characters (punctuation, symbols)`,
    passwordRequirements: `The password must be at least 8 characters and meet two complexity criteria:`,
    incorrectOldPassword: `Old password is incorrect. Your account will be locked after 5 failed attempts`,
    newPasswordsNotSame: `The new passwords you entered are not the same`,
    passwordSuccesfullyChanged: `Password is successfully changed`,
    accountBlockedFifteenMinutes: `Your account is locked. Please try again after 15 minutes`,
    loadingLegalDocuments: `Loading legal documents...`,
    fr: `French`,
    errorFetchingLegalDocuments: `Error loading legal documents`,
    nameAndMrnNotFound: `The Patient ID & Last Name combination could not be found`,
    duplicateNameAndMrn: `The Patient ID already exists in Care4Today`,
    NSCameraUsageDescription: `This App requires access to the camera to add / update the profile picture and add attachments into the notes`,
    NSPhotoLibraryUsageDescription: `This App requires access to the photo library to add attachments to notes`,
    initiate: `Initiate`,
    lastNameAsc: `Last Name Asc`,
    lastNameDesc: `Last Name Desc`,
    firstNameAsc: `First Name Asc`,
    firstNameDesc: `First Name Desc`,
    messageParticipantIsInactive: `is no longer active`,
    participantNoLonger: `The participant is no longer a user of the platform`,
    requestDeletionInProgress: `Your request for deletion of personal data is already in progress. Support team will update you as soon as this is done`,
    contactNotAvailableOnDeactivated: `Contact details not available for deactivated HCP`,
    deactivated: `Deactivated`,
    noPermissionToSendMessage: `You do not have permission to message this person`,
    refrainSendingMedData: `Please refrain from sending messages that contain medical data/information of the patient`,
    refrainEnteringMedData: `Please refrain from entering medical data/information of the Patient in the above field`,
    contactHospitalAppointment: `Please contact the hospital directly if you need to rearrange or cancel your appointment.`,
    noInfoDescriptionAppointment: `No further information is available. Please contact the hospital directly if you have any questions about your appointment.`,
    noInfoDescriptionAndDateAppointment: `An update will follow shortly providing more information about your appointment. Please contact the hospital directly if you have any questions about your appointment.`,
    participants: `Participants`,
    noMdtAssigned: `No multidisciplinary team assigned to the patient. Please assign a team to the patient first.`,
    scheduled: `Scheduled`,
    updated: `Updated`,
    proposed: `Proposed`,
    he: `Hebrew`,
    restrictProcessingPersonal: `Restrict processing of my personal data`,
    restrictProcessingArticle: `Based on article 18 of the GDPR, which of the following applies to your situation?`,
    dataAccuracy: `Data Accuracy`,
    unlawfulProcessing: `Unlawful Processing`,
    legalClaim: `Legal Claim`,
    provideExplanation: `Please provide an explanation:`,
    provideExplanationDescription: `Please provide an explanatory text to describe the issue and help the assessment of your request`,
    restrictProcessing: `Restrict processing`,
    sureProcessing: `Are you sure you want to restrict processing of your personal data?`,
    processingPasswordConfirmation: `By initiating this request your data will be temporarily disabled and, unless we let you know otherwise, we will only store the data, and we will only process it further if we obtain your consent. For any further questions or to lift the restriction please contact support@care4todaypatient.com. Please provide your password to confirm this action:`,
    processingSent: `Request to restrict processing of your personal data has been sent to Care4Today support mailbox`,
    versionNumber: (params: string[]) => `Version ${params[0]}`,
    pleaseSelect: `Please select:`,
    restrictedLogout: `You have been logged out because your request to restrict processing of personal data has been handled and restriction applied to your Care4Today account. If you have any questions please reach out to support@care4todaypatient.com`,
    restrictProcessingAlreadyRequested: `Your request for restrict processing of personal data is already in progress. Support team will update you as soon as this is done.`,
    rightToRestrictQuestion: `Based on article 18 of the GDPR, which of the following applies to your situation?`,
    rightToRestrictExplanation: `Please provide an explanation:`,
    rightToRestrictTitle: `Restrict processing of my personal data`,
    rightToRestrictExplanationPlaceholder: `Please provide an explanatory text to describe the issue and help the assessment of your request.`,
    rightToRestrictConfirmationTitle: `Are you sure you want to restrict processing of your personal data?`,
    rightToRestrictConfirmationDescription: `Your request will be sent to the support team. Your account and data will be temporarily disabled and, unless we let you know otherwise, we will only store the data, and we will only process it further if we obtain your consent. Please note that some limited personal information such as your name sent from the Hospital Information System may continue to appear in the appointments.  For any further questions or to lift the restriction please contact support@care4todaypatient.com.  Please provide your password to confirm this action:`,
    assignedRole: (params: string[]) => `Assigned ${params[0]} (inactive)`,
    requestRestrictionSubmitted: `Request to restrict processing of your personal data has been sent to Care4Today support mailbox`,
    temporarelyUnavailableHCPAlertMessage: `The HCP is temporarily unavailable in the platform. In case of any questions, please contact the support team.`,
    temporarelyUnavailableHCPSubtitle: `The HCP is temporarily unavailable`,
    assignedHCP: (params: string[]) => `Assigned ${params[0]}`,
    inactive: `Inactive`,
    appointmentInvite: `You have an appointment`,
    disabledAppointmentActionMessage: `Please use the hospital appointment booking system directly to schedule, update or cancel an appointment.`,
    noFurtherInformation: `No further information available`,
    cancelled: `Cancelled`,
    cancelledNotificationPrefix: `Cancelled:`,
    updatedNotificationPrefix: `Updated:`,
    allDay: `All day`,
    editCareModule: `Edit Care Module`,
    nextSurgeryProcedureInformation: `Next: Surgery / Procedure Detail`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} is no longer part of\nyour Multidisciplinary Team`,
    editCareModuleWarning: `Please note that upon changing the Care Module, all history of goals and learning materials from the previous procedure will no long be available for the patient.`,
    editSurgeryWarning: `Please adjust the surgery information if required.`,
    nextUpdateMDT: `Next: Update Medical Team`,
    updateCareModule: `Update Care Module`,
    editMdtTeamWarning: `Please check the multidisciplinary team to see if any updates are required.`,
    participantNotInMDT: `You are no longer part of the MDT team for this patient`,
    createMedicalTeam: `Create medical team`,
    editMedicalTeam: `Edit medical team`,
    mdtName: `Name of MDT`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `Are you sure you want to change this patient's care module from '${
            params[0]
        }' to '${params[1]}'?`,
    changePathwayConfirmationSubTitle: `Please note that upon changing the Care Module, all history of goals and learning materials from the previous procedure will no longer be available for the patient`,
    changePathwaySuccessMessage: (params: string[]) =>
        `You successfully changed Patient ${params[2]} Care Module from '${
            params[0]
        }' to '${params[1]}'`,
    mdtChanged: `Your medical team has changed`,
    tapForDetails: `Tap here to find more details.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `Assigned ${
            params[0]
        } is no longer part of\nyour Multidisciplinary Team`,
    addPatientReceivedConsent: `By providing the information below, I declare that I have received consent from the patient to process patient data.`,
    attended: `Attended`,
    entityCreationError: (params: string[]) =>
        `There was an error creating the ${params[0]}`,
    updateAppointmentError: `There was an error updating the appointment`,
    updateConsultationNoteError: `There was an error updating the consultation note`,
    createConsultationNoteError: `There was an error creating the consultation note`,
    missed: `Missed`,
    contentDescCloseNotification: `Close notification`,
    pathwayChanged: `Your care module has changed`,
    pathwayChangedDetails: (params: string[]) =>
        `from ${params[0]} to ${
            params[1]
        }. Please contact your care coordinator / HCP for more information.`,
    de: `German`,
    doYouWantToDeletePatient: (params: string[]) =>
        `Are you sure you want to delete patient ${params[0]}?`,
    personWillBeRemovedFromRecords: `This person will not be able to log in to the C4T app and will be removed from digital records.`,
    provideDeletionReason: `Please provide a reason for deletion:`,
    deletionSuccess: (params: string[]) =>
        `You successfully deleted ${params[0]} from the platform`,
    consentNotProvided: `Consent was not provided`,
    entryError: `Entry error`,
    duplicatePatient: `Duplicate patient`,
    addExtraSecurity: `Add extra security to your account with 2-step verification`,
    mfaDescription: `Every time you log into your account, you will be asked to enter a security code. This security code will be sent by email or phone.`,
    activateMfa: `Activate 2-step verification`,
    userAccountNotActive: `Your user account is not active`,
    useHCPPortal: `Please use the online HCP Portal in case you forgot your password`,
    noPatientsAssigned: `There is no patient assigned to you.`,
    currentAppointments: `Current appointments`,
    noCurrentAppointments: `There are no future appointments available`,
    phase: `Phase`,
    noPhaseInformation: `No phase information`,
    noSubphaseInformation: `No sub-phase information`,
    you: (params: string[]) => `${params[0]} (you)`,
    hcpsMedicalStaff: `HCPs`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `in ${params[0]} (${params[1]})`,
    newMessage: `New Message`,
    addParticipant: `Add Participant`,
    editParticipant: `Edit Participant`,
    messagesFor: (params: string[]) => `Messages ${params[0]}`,
    noParticipants: `No participants available`,
    whichMfaMethod: `How would you like to receive the security code?`,
    mfaMethodExplanation: `This security code is required to access your account. You can get the sign-in code using your mobile phone or email. Choose the method that works best for you.`,
    textMe: `Text me a sign-in code`,
    emailMe: `Email me a sign-in code`,
    textMeSubtitle: `We will ask for your phone number`,
    emailMeSubtitle: `Please confirm your email address`,
    backToMethod: `Back to method choice`,
    addPhone: `Add a phone number`,
    whichPhone: `Which phone number would you like to receive the security code?`,
    phoneDisclaimer: `This phone number will only be used for account security. Costs for texting and data usage may be charged.`,
    sendCode: `Send security code`,
    confirmEmail: `Confirm your email`,
    whichEmail: `Which email address would you like to receive the security code?`,
    emailDisclaimer: `This email address will only be used for account security.`,
    insertCode: `Please insert your security code`,
    mayTakeTwoMinutes: `It may take up to two minutes to receive your code.`,
    sentCodeByText: (params: string[]) =>
        `We just sent the security code via text to ${params[0]}`,
    sentCodeByEmail: (params: string[]) =>
        `We just sent the security code via email to ${params[0]}`,
    didntGetCode: `Didn't receive a code?`,
    resendCode: `Resend security code`,
    authenticate: `Authenticate`,
    verifyingCode: `Verifying security code`,
    mfaSuccess: `Success! 2-step authentication is enabled!`,
    mfaCodeRequired: `A sign-in code is required to access your account.`,
    mfaMethodExplanationLogin: `This security code is required to access your account. You can get the sign-in code using your mobile phone or email.`,
    contentDescMfaIcon: `2-step authentication icon`,
    mfaSendCodeTo: (params: string[]) =>
        `We will send the code to ${params[0]}`,
    continueLabel: `Continue`,
    authenticating: `Authenticating`,
    mfaInvalidCode: `The code you entered is invalid. Please try again.`,
    mfaUnableToVerifyPhoneNumber: `We are unable to verify this phone number. Please try another one.`,
    mfaUnableToVerifyEmail: `We are unable to verify this email address. Please try another one.`,
    sessionExpired: `Your session has expired. Please login again.`,
    passwordExpired: `Your password has expired. Please change your password.`,
    rightToBeForgottenInfoNonIntegrated: `By initiating this request your personal information will be deleted and you will no longer be able to access the application. For any further questions please contact support@care4todaypatient.com. Please provide your password to confirm this action:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `Your request will be sent to the support team. Your account and data will be temporarily disabled and, unless we let you know otherwise, we will only store the data, and we will only process it further if we obtain your consent. For any further questions or to lift the restriction please contact support@care4todaypatient.com`,
    password_expired_message: `Password has expired and must be changed to access C4T`,
    firstdayOftheWeek: `First day of the week`,
    dateformat: `Date format`,
    selectDateFormat: `Select Date Format`,
    selectDay: `Select Day`,
    monday: `Monday`,
    tuesday: `Tuesday`,
    wednesday: `Wednesday`,
    thursday: `Thursday`,
    friday: `Friday`,
    saturday: `Saturday`,
    sunday: `Sunday`,
    manageTheAppointmentTemplates: `Manage the appointment templates`,
    prefillTemplatesFor: `Prefill templates for`,
    appointmentTemplates: `Appointment Templates`,
    backToTemplateTypes: `Back to template types`,
    addNewAppointmentTemplate: `Add new appointment template`,
    caremoduleName: `Caremodule Name`,
    selectPathway: `Select a pathaway`,
    notShowInDropdownAfterDelete: `By deleting this template it will no longer be shown in the dropdown`,
    messagesTemplates: `Message Templates`,
    addNewMessageTemplate: `Add new message template`,
    pathway: `Pathway`,
    template: `Templates`,
    typesTwo: `2 types`,
    scheduledAppointmentInDropdown: `By deleting this template it will no longer be shown in the dropdown fields when scheduling an appoinment.`,
    manageTemplate: `Manage templates`,
    manageTheMessageTemplates: `Manage the message templates`,
    addMdt: `+ Add a new MDT to platform`,
    mdts: `MDTs`,
    NameAsc: `Name Asc`,
    NameDesc: `Name Desc`,
    Teams: `Teams`,
    MdtsName: `MDTs Name`,
    managemdts: `Manage MDTs `,
    members: `Members`,
    editTeam: `Edit team`,
    addANewMDTToThePlatform: `Add a new MDT to the platform`,
    week: `Week`,
    month: `Month`,
    year: `Year`,
    total: `Total`,
    dailyaverage: `Daily average`,
    nochartdata: `No chart data available`,
    youCanOnlyAssignOneMDTAtATime: `You can only assign one MDT at a time`,
    noMoreOptionsAvailable: `No more options available`,
    mdt: `MDT `,
    relatingPatient: `Relating a patient`,
    nonrelatingPatient: `Not relating a patient `,
    sendMsgPatient: `Send new message to patient`,
    expectedResponseTime: `Expected response time between 3 to 4 hours`,
    walkedText: `walked`,
    walk: `walk`,
    mymedicalteam: `My Medical Team`,
    yesterday: `Yesterday`,
    close: `Close`,
    passwordUsedBefore: `New password has been used previously and cannot be reused. Please enter another password.`,
    sendMessageTo: `Send message to`,
    message: `Message`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} added ${params[1]} to the conversation`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} removed ${params[1]} from the conversation`,
    removedParticipant: `Removed Participant`,
    noMessagesSelected: `You don't have a message selected`,
    noMessagesSelectedDesc: `Select a message on the left side of the screen, or start a new conversation`,
    mfaMethodExplanationRegistration: `This security code is required to access your account. You can get the sign-in code using your mobile phone or email. Please choose the method that works best for you.\n\nPlease note, you may only choose one verification method at this time. Once you have made your choice, your preference will be saved and cannot be changed without contacting the help desk.`,
    signinCodeRequired: `Request security code`,
    securityCodeRequired: `This security code is required to access your account. You can get the sign-in code using the method you chose during your first registration.`,
    newMfaUserDesc1: `This security code is required to access your account. You can get the sign-in code using your mobile phone or email. Please choose the method that works best for you.`,
    newMfaUserDesc2: `Please note, you may only choose one verification method at this time. Once you have made your choice, your preference will be saved and cannot be changed without contacting the help desk.`,
    feelFreeToMessageTeam: `Feel free to start a conversation with someone from your team.`,
    noFutureMessages: `You don't have any messages yet`,
    chatSelfRemove: `You have successfully removed yourself from the conversation`,
    noResultFound: `No result found`,
    chatUpdated: `Chat has been updated successfully`,
    chatNotUpdated: `Chat has not updated`,
    searchPlaceholder: `Search for a template...`,
    editPrefillTemplate: `Edit prefill template`,
    forAppointments: `For Appointments`,
    addTemplateToList: `Add template to list`,
    addNewPrefillTemplate: `Add new prefill template`,
    forMessages: `For Messages`,
    editNewPrefillTemplate: `Edit new prefill template`,
    generateNewCode: `Generate a new onboarding code`,
    manageRegistration: `Manage onboarding requests`,
    generateOnboardingCode: `Generate an onboarding code`,
    generateCode: `Generate timed code`,
    onboardingRequests: `Onboarding requests`,
    approveSelected: `Approve selected`,
    requestDate: `Request date`,
    phone: `Phone`,
    searchPatient: `Search for a patient...`,
    pathwayCode: `Pathway code`,
    timedCode: `Timed code`,
    areYouSureDeleteTemplate: `Are you sure you want to delete this template?`,
    validUntil: `valid until`,
    selectPathwayText: `Select a pathway`,
};
