export const LANG_ES_TRANS = {
    accept: `Aceptar`,
    accepted: `Aceptado`,
    acceptedInvitation: `Ha aceptado esta invitación.`,
    actions: `Acciones`,
    addHcp: `Añadir profesional sanitario (PS) a la plataforma`,
    addHCPTag: `+ PS`,
    addHcpToPlatform: `Añadir un profesional sanitario (PS) a la plataforma`,
    addNewHCP: `+ Añadir un nuevo PS a la plataforma`,
    addNewPatient: `+ Añadir un nuevo paciente a la plataforma`,
    addPatient: `Añadir paciente`,
    addPatientConsent: `Por la presente confirmo que he recibido el consentimiento del paciente para introducir sus datos.`,
    addPatientToPlatform: `Añadir paciente a la plataforma`,
    administration: `Administración`,
    agreed: `Acordado`,
    allHcps: `Todos los profesionales sanitarios (PS)`,
    allowNotifications: `Ha activado las notificaciones, ¡genial!`,
    allPatients: `Todos los pacientes`,
    almostHalfway: `¡Está casi a la mitad!`,
    almostThere: `¡Ya casi ha llegado!`,
    am: `a. m.`,
    andMore: (params: string[]) => `y ${params[0]} más`,
    apiErrorGetConsentDocument: `No se pudo cargar el documento de consentimiento. Pulse aquí para intentarlo de nuevo`,
    appointment: `Cita`,
    appointmentAcceptedByPatient: `Aceptada por el paciente`,
    appointmentAwaitingPatientResponse: `En espera de respuesta del paciente`,
    appointmentDeclinedByPatient: `Rechazada por el paciente`,
    appointmentName: `Nombre de la cita`,
    appointmentNotification: `Notificación de la cita`,
    appointments: `Citas`,
    appointmentsForPatient: (params: string[]) => `Citas para ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `Una cita se puede programar entre ${params[0]} y ${params[1]}`,
    appUnavailable: `Lo sentimos, la aplicación no está disponible en este momento.Inténtelo de nuevo más tarde o compruebe si hay actualizaciones.`,
    april: `Abril`,
    ar: `Árabe`,
    areYouSureDeclineMessage: `El equipo clínico necesita su colaboración para ayudarle en la preparación y monitorización de su progreso.\n\nPóngase en contacto con su médico si no desea unirse a la plataforma`,
    areYouSureDeclineTitle: `¿Está seguro/a de que no quiere unirse a la plataforma Care4Today?`,
    areYouSureDeleteNote: `¿Está seguro/a de que desea eliminar esta nota?`,
    article: `Artículo`,
    assignToMDT: `Asignar a Equipo multidisciplinar (EMD)`,
    audio: `Audio`,
    august: `Agosto`,
    back: `Volver`,
    backToAppointments: `Volver a sus citas`,
    backToDetails: (params: string[]) =>
        `Volver a los detalles de ${params[0]}`,
    backToLogin: `Volver a Iniciar sesión`,
    backToPatientProfile: `Volver al perfil del paciente`,
    badPassword: `Ha introducido una contraseña no válida.`,
    bariatrics: `Bariátrica`,
    blockedUser: `Su usuario ha sido bloqueado.Inténtelo dentro de media hora.`,
    bmi: `IMC`,
    bookedSuccess: `Ha concertado su cita correctamente`,
    cancel: `Cancelar`,
    cancelAlert: `Cancelar`,
    cantParseError: `No se ha podido analizar la respuesta.`,
    cantSaveImage: `No se ha podido guardar la imagen.`,
    care4Today: `Care4Today`,
    careModules: `Módulos de atención`,
    changePassword: `Cambiar contraseña`,
    changePasswordSubtitle: `Elija su propia contraseña personal.`,
    changePasswordTitle: `Personalice su contraseña`,
    choosePicture: `Elija una foto`,
    chooseProfilePicture: `Cambie la foto`,
    cm: `cm`,
    completed: `Completado`,
    conditionalGoal: `Objetivo condicional`,
    confirmAppointmentDelete: `¿Está seguro/a de que desea eliminar esta cita?`,
    confirmed: `Confirmado`,
    confirmNewPasswordPlaceholder: `Confirmar nueva contraseña`,
    consent: `Consentimiento`,
    consentDontAgree: `No estoy de acuerdo y no usaré la plataforma Care4Today`,
    consentedOn: (params: string[]) =>
        `Usted dio su consentimiento el ${params[0]}`,
    contact: `Contacto`,
    contactDetails: `Datos de contacto`,
    contactInfo: `INFORMACIÓN DE CONTACTO`,
    contentDescApptIcon: `Icono de la cita`,
    contentDescAttachImage: `Adjuntar imagen`,
    contentDescAttachment: `Adjunto`,
    contentDescAttachmentImg: `Imagen a pantalla completa`,
    contentDescBackground: `Antecedentes`,
    contentDescChangePwdIcon: `Cambiar icono de contraseña`,
    contentDescClose: `Cerrar pantalla completa`,
    contentDescDeleteAttachment: `Eliminar la imagen adjunta`,
    contentDescDevicesIcon: `Icono de dispositivos conectados`,
    contentDescEduContentExpandBtn: `Abrir adjunto de material educativo`,
    contentDescEduContentThumb: `Adjunto de material educativo`,
    contentDescEduItemCompleted: `El módulo educativo ha finalizado`,
    contentDescEduItemIncomplete: `El módulo educativo no ha finalizado`,
    contentDescGoalIcon: `Icono de objetivo personal`,
    contentDescHelpIcon: `Icono de ayuda`,
    contentDescKillswitchIcon: `Icono de interruptor de apagado`,
    contentDescLegalIcon: `Icono de documentos legales`,
    contentDescLogo: `Logotipo de la aplicación`,
    contentDescLogoutIcon: `Icono de cerrar sesión`,
    contentDescMdtPic: `Foto del profesional sanitario`,
    contentDescMessageIcon: `Icono de mensaje`,
    contentDescNoGoalIcon: `Icono de ningún objetivo`,
    contentDescPathwayCurrent: `Icono de fase actual`,
    contentDescPathwayIcon: `Icono de procesos asistenciales`,
    contentDescPathwayOtherPhase: `Icono de otra fase`,
    contentDescProfilePic: `Foto de perfil`,
    contentDescSend: `Enviar`,
    create: `Crear`,
    createAMedicalTeam: `Crear un equipo médico`,
    createAppointment: `Crear cita`,
    createAppointmentButton: `Crear cita y enviar invitación`,
    createAppointmentSuccess: `Cita creada correctamente`,
    createAppt: `Crear cita`,
    createMDT: `Crear EMD`,
    currentBmi: `IMC actual`,
    currentPhase: `Fase actual`,
    currentWeight: `Peso actual`,
    dashboard: `Panel`,
    date: `Fecha`,
    dateOfBirth: `Fecha de nacimiento`,
    dateOfConsent: `Fecha de consentimiento`,
    dateOfConsentAsc: `Fecha de consentimiento, orden asc.`,
    dateOfConsentDesc: `Fecha de consentimiento, orden desc.`,
    dateOfSurgery: `Fecha de la cirugía *`,
    december: `Diciembre`,
    decline: `Rechazar`,
    declined: `Rechazada`,
    declinedInvitation: `Ha rechazado esta invitación.`,
    declinedNotifications: `No ha permitido activar las notificaciones, ¿está seguro/a?Puede cambiar esta opción en el menú de configuración.`,
    declinedSuccess: `Ha rechazado su cita`,
    defaultError: `Ha habido un problema`,
    delete: `Eliminar`,
    deleteAppointmentSuccess: `Cita eliminada correctamente`,
    deleteNote: `Eliminar nota`,
    deleting: `Eliminando...`,
    description: `Descripción`,
    details: `Detalles`,
    devices: `Dispositivos conectados`,
    disagreeConsentError: `Se ha producido un error mientras mostraba su desacuerdo con el consentimiento.Inténtelo de nuevo`,
    discardChanges: `¿Desea descartar los cambios?`,
    document: `Documento`,
    done: `Listo`,
    draftWontBeSaved: `Su borrador no se guardará.¿Desea cancelarlo de todos modos?`,
    duplicateMDT: `Profesional sanitario (PS) ya seleccionado`,
    edit: `Editar`,
    editHcpsProfile: `Editar perfil del PS`,
    editMessageDetails: `Editar detalles de la conversación`,
    editMTDTeam: (params: string[]) => `Editar equipo para ${params[0]}`,
    editPassword: `Editar contraseña`,
    editPatient: `Editar paciente`,
    editPatientError: `Ha habido un problema al actualizar los datos del paciente`,
    editPatientSuccess: `Datos del paciente actualizados correctamente.`,
    editProfile: `Editar perfil`,
    editProfilePicture: `Editar foto de perfil`,
    editSubject: `Editar asunto`,
    editTeamMembers: `Editar miembros del equipo`,
    editYourPersonalGoal: `Editar su objetivo personal`,
    eduContentHint: `Pulse en el botón expandir para abrir el contenido adjunto.`,
    email: `Correo electrónico`,
    emailAddress: `Dirección de correo electrónico`,
    emailConfirmation: (params: string[]) =>
        `Hemos enviado un correo electrónico a ${
            params[0]
        } con un enlace para restablecer su contraseña.`,
    emailExists: (params: string[]) =>
        `Ya existe un usuario con el correo electrónico ${params[0]}.`,
    emailSent: `Correo electrónico enviado`,
    en: `Inglés`,
    enableNotifications: `Permitir notificaciones`,
    enterANewHCP: `Introducir un nuevo profesional sanitario (PS)`,
    enterSubjectHint: `Introducir asunto`,
    enterTheSubject: `Introduzca el asunto de esta conversación.`,
    errorEditingHcp: `Ha ocurrido un error al editar el profesional sanitario (PS)`,
    errorFindingConsentDocument: `Error al intentar encontrar el documento de consentimiento.`,
    errorLoading: (params: string[]) => `Error al cargar ${params[0]}`,
    errorSavingSettings: `Error al guardar la configuración`,
    errorUpdatingPassword: `No se pudo actualizar la contraseña`,
    excessWeightLost: `Exceso de peso perdido`,
    failEditHcp: `Ha habido un error al editar su perfil`,
    february: `Febrero`,
    female: `Mujer`,
    filter: `Filtro`,
    firstName: `Nombre`,
    forgotPasswordInstruction: `Proporcione la dirección de correo electrónico con la que está registrado en su hospital.Le enviaremos un correo electrónico con un enlace para restablecer su contraseña.`,
    forgotPasswordViewTitle: `Contraseña olvidada`,
    forgotYourPassword: `¿Ha olvidado su contraseña?`,
    formTimeRangeInPast: `El intervalo de tiempo no puede estar en el pasado`,
    formTimeRangeStartGreaterThanEnd: `El intervalo de tiempo no es válido`,
    forPatient: `Para`,
    from: `De`,
    ft: `pies`,
    fullName: `Nombre completo`,
    function: `Función`,
    gained: `ganado`,
    gender: `Sexo`,
    goal: `Objetivo`,
    goalSavedError: `¡El objetivo no ha podido guardarse!`,
    goalSavedSuccess: `¡Objetivo guardado correctamente!`,
    goBack: `Retroceder`,
    hcps: `Profesionales sanitarios (PS)`,
    healthCareProfessionals: (params: string[]) =>
        `${params[0]} profesionales sanitarios`,
    height: `Altura`,
    help: `Ayuda`,
    heyChooseYourPicture: (params: string[]) =>
        `Hola, ${params[0]}, elija su foto de perfil`,
    iAgree: `Estoy de acuerdo`,
    iAgreeFormat: (params: string[]) =>
        `Estoy de acuerdo (${params[0]}/${params[1]})`,
    iAmSure: `Estoy seguro/a`,
    idealBodyWeight: `Peso corporal ideal`,
    iDoNotAgree: `No estoy de acuerdo`,
    iDontAgree: `No estoy de acuerdo y no usaré la plataforma Care4Today`,
    imperial: `Imperial`,
    in: `pulg.`,
    includeLinkToLocation: `Incluir enlace a la ubicación`,
    initialWeight: `Peso inicial`,
    installUpdate: `Instalar actualización`,
    invalidEmailError: `El correo electrónico no es válido`,
    invalidNumber: `Introduzca un número válido`,
    invalidTokenError: `No se pudo autenticar. Intente iniciar sesión de nuevo.`,
    it: `Italiano`,
    iWantToFitAgain: `Ejemplo:“Quiero volver a entrar en una talla L”`,
    january: `Enero`,
    july: `Julio`,
    june: `Junio`,
    keepGoing: `¡Siga así!`,
    keepMomentum: `¡Mantenga el impulso!`,
    kg: `kg`,
    kilogrammes: `kilogramos`,
    language: `Idioma`,
    languageRequired: `Idioma *`,
    lastName: `Apellido`,
    lb: `lb`,
    learningMaterials: `Materiales de formación`,
    legalDocuments: `Documentos legales`,
    loading: `Cargando`,
    loadingPatients: `Cargando pacientes; por favor, espere`,
    location: `Ubicación`,
    locationUrl: `URL de la ubicación`,
    lockScreenHint: `Necesita establecer una pantalla de bloqueo del dispositivo para permitir el uso seguro de la aplicación.`,
    login: `Inicio de sesión`,
    loginIncorrect: `El correo electrónico o contraseña introducidos son incorrectos`,
    logout: `Cerrar sesión`,
    logoutAreYouSure: `¿Está seguro/a de que quiere cerrar sesión?`,
    loseBefore: (params: string[]) => `Perder ${params[0]}`,
    loseFormat: (params: string[]) => `Perder ${params[0]} ${params[1]}`,
    lost: `perdido(s)`,
    male: `Hombre`,
    manageHCPs: `Gestionar PS`,
    managePatients: `Gestionar pacientes`,
    march: `Marzo`,
    may: `Mayo`,
    mdtTeam: `Equipo EMD`,
    mdtTeamNotAddedYet: `EMD no asignado todavía.`,
    mdtTeamUC: `EQUIPO EMD`,
    medicalTeam: `Equipo médico`,
    meetingInvite: `Tiene una reunión`,
    meetingInviteWith: (params: string[]) => `Reunión con ${params[0]}`,
    messageCreated: `Ha iniciado una conversación correctamente.`,
    messageNotCreated: `No ha podido iniciar una conversación.`,
    messageNotification: `Notificación de mensaje`,
    messageNotSent: `Mensaje no enviado`,
    messages: `Mensajes`,
    metric: `Métrico`,
    movePhaseConfirmation: (params: string[]) =>
        `¿Está seguro/a de que quiere trasladar ${params[0]} a la fase ${
            params[1]
        }?`,
    moveToNextPhase: `Pasar a la siguiente fase`,
    multiDisTeam: `Equipo multidisciplinar`,
    myMessages: `Mis mensajes`,
    myMotivation: `Mi motivación:`,
    myPersonalGoal: `Mi objetivo personal`,
    myProfile: `Mi perfil`,
    myTeam: `Mi equipo`,
    name: `Nombre`,
    nameOfMDT: `Nombre del EMD *`,
    needsConsent: `El paciente debe aceptar primero el consentimiento.`,
    networkError: `Ha habido un error de red`,
    newAppointment: `Nueva cita`,
    newChat: `Nuevo chat`,
    newInvitation: `Nueva invitación`,
    newMessageNotificationMore: (params: string[]) =>
        `Tiene ${
            params[0]
        } mensajes nuevos.Abra la aplicación para ver las novedades.`,
    newMessageNotificationOne: `Tiene un nuevo mensaje.Abra la aplicación para ver las novedades.`,
    newNote: `Nueva nota`,
    newPasswordPlaceholder: `Nueva contraseña`,
    newPatientSuccess: (params: string[]) =>
        `Ha añadido ${params[0]} a la plataforma correctamente.`,
    newTeamFail: `Equipo EMD no asignado`,
    newTeamSuccess: `Equipo EMD asignado`,
    newVersionApp: `Actualice esta aplicación con la última versión disponible en la tienda de aplicaciones.`,
    nextAppointment: `Siguiente cita`,
    nextSelectCareModule: `Siguiente:Seleccionar módulos de atención`,
    nextSurgeryInformation: `Siguiente:Información sobre la cirugía`,
    niceToSeeYouAgain: `¡Nos alegramos de volver a verle!`,
    nickname: `Nombre de usuario`,
    nicknameError: `Nombre de usuario no válido.No están permitidos los caracteres especiales.`,
    nl: `Neerlandés`,
    no: `No`,
    noAppointments: `No hay citas disponibles`,
    noCurrentGoalForPatient: `No hay un objetivo actual asociado a este paciente`,
    noDate: `no se ha fijado una fecha`,
    noFutureAppointments: `No hay citas futuras`,
    noGoalSet: `Su PS no ha fijado un objetivo`,
    noMatchingConsentDocumentsFound: `No se han encontrado los documentos de consentimiento correspondientes`,
    noMessages: `No hay mensajes disponibles`,
    noNetworkConnection: `No hay conectividad de red disponible.Compruebe…`,
    noNotesMessage: `No hay notas disponibles.\n Pulse “Crear” para añadir nuevas notas`,
    noPersonalGoalSet: `No se ha fijado un objetivo personal.`,
    noPersonalGoalSetDashboard: `No se ha fijado un objetivo personal.Vaya a la página de configuración para actualizarlo.`,
    noPlannedAppointments: `No hay citas planificadas`,
    noPreview: `No hay una vista previa disponible`,
    noProgressRecorded: `No se ha registrado ningún progreso`,
    noResponseError: `No se ha recibido ninguna respuesta.`,
    notAgreed: `No acordado`,
    noteDeletedError: `¡No se ha podido eliminar la nota!`,
    noteDeletedSuccessfully: `¡Nota eliminada correctamente!`,
    notes: `Notas`,
    noteSaved: `Nota guardada`,
    noteSavedError: `¡La nota no ha podido guardarse!`,
    noteSavedSuccess: `¡Nota guardada correctamente!`,
    noteSaveError: `Error, no se pudo guardar la nota.Vuelva a intentarlo.`,
    notifications: `Notificaciones`,
    notNow: `Ahora no`,
    notSet: `No fijado/a`,
    notYetSubmitted: `No enviado/a aún`,
    noUnreadMessages: `No hay mensajes sin leer`,
    noUserFound: `Error, no se encuentra el usuario con las credenciales introducidas.`,
    november: `Noviembre`,
    noWeightDifference: `Sin diferencia de peso`,
    october: `Octubre`,
    ok: `Aceptar`,
    onboardingNotificationsTitle: `Queremos mantenerle al día en todo momento`,
    onboardingNotifictionsInfo: `Le notificaremos sobre:\n\n• Sus citas\n• Nuevos mensajes de su equipo médico`,
    onVar: (params: string[]) => `el ${params[0]}`,
    openCare: `Abra Care4Today y compruebe si tiene nuevas notificaciones.`,
    optOutSubtitle: `Póngase en contacto con su médico si no desea unirse a la plataforma.`,
    optOutTitle: `¿Está seguro/a de que no quiere unirse a la plataforma Care4Today?`,
    organisation: `Organización`,
    orthopedics: `Traumatología y Ortopedia`,
    other: `Otros`,
    outdatedVersion: `En este momento está usando una versión antigua de la aplicación.`,
    overview: `Descripción general`,
    participant: `Participante`,
    password: `Contraseña`,
    passwordComplexityError: `La contraseña debe tener como mínimo 8 caracteres y al menos 2 de los tipos de caracteres que siguen:mayúsculas, minúsculas, números o símbolos.`,
    passwordMismatchError: `Las contraseñas no coinciden`,
    passwordUpdated: `Contraseña actualizada`,
    pastAppointments: `Citas anteriores`,
    pathwayScheduleFail: `Se ha producido un error.El calendario del proceso asistencial no se ha podido actualizar`,
    patient: `Paciente`,
    patientAge: (params: string[]) => `${params[0]} años`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} años`,
    patientConsent: `Consentimiento del paciente`,
    patientNameAsc: `Nombre del paciente, orden asc.`,
    patientNameDesc: `Nombre del paciente, orden desc.`,
    patientRegistration: `Registro de paciente`,
    patients: `Pacientes`,
    patientsCount: (params: string[]) => `${params[0]} pacientes`,
    patientsOverview: `Descripción general de los pacientes`,
    pending: `Pendiente`,
    percent: `%`,
    personalGoal: `Objetivo personal`,
    personalGoalEdit: `Objetivo personal`,
    personalPassword: `Contraseña personal`,
    personalPasswordHelper: `Por favor, elija su propia contraseña personal.Puede cambiar su contraseña en el menú de configuración en cualquier momento.`,
    phoneError: `Número de teléfono no válido.Por favor, use solo números (no paréntesis, guiones, +)`,
    phoneNumber: `Número de teléfono`,
    picture: `Foto`,
    pictureInstructions: `Elija su foto de perfil personal.Esta foto se usará para su cuenta personal.`,
    pleaseConnect: `Conéctese a internet para asegurarse de que está usando la última versión de la aplicación.`,
    pleaseContactYourHospital: `Póngase en contacto directamente con su hospital en caso de urgencia.`,
    pleaseProvidePassword: `Proporcione su contraseña para confirmar esta acción:`,
    pm: `p. m.`,
    pounds: `libras`,
    preparation: `Preparación`,
    preSurgeryPrep: `Preparación prequirúrgica`,
    previous: `Anterior`,
    privacyPolicy: `Política de privacidad`,
    profileLabel: `Lo usaremos para dirigirnos a usted en correos electrónicos, mensajes de texto y esta aplicación.También pasaremos esta información a su equipo médico.`,
    profilePicture: `Foto de perfil`,
    profileTitle: `Lo usaremos para dirigirnos a usted en correos electrónicos, mensajes de texto y esta aplicación.También pasaremos esta información a su equipo médico.`,
    progress: `Progreso`,
    progressMsgForgotPwd: `Validando…`,
    progressMsgLoading: `Cargando...`,
    progressMsgLoadingContent: `Cargando contenido…`,
    progressMsgLogin: `Cargando proceso asistencial, \nEsto puede llevar hasta 1 minuto…`,
    progressMsgMdtLoading: `Cargando EMD…`,
    progressMsgNotesLoading: `Cargando notas…`,
    progressMsgProfileEdit: `Guardando perfil…`,
    progressMsgProfilePhoto: `Guardando foto…`,
    progressMsgResetPwd: `Guardando contraseña…`,
    provideTheEmail: `Proporcione la dirección de correo electrónico con la que está registrado en el hospital.`,
    pwdValidationDoesNotMatch: `Sus contraseñas no coinciden`,
    pwdValidationIllegal: `Contiene caracteres no permitidos`,
    pwdValidationNotComplex: `No se han cumplido los requisitos de complejidad de la contraseña`,
    pwdValidationTooShort: `Su contraseña es demasiado corta`,
    quickFilter: `Filtro rápido`,
    remindmeLater: `Recuérdemelo más tarde`,
    requiredFields: `Campos obligatorios`,
    requiredHCPs: `PS *`,
    resetPassword: `Restablecer contraseña`,
    respond: `Responder`,
    retry: `Intentar de nuevo`,
    save: `Guardar`,
    saveAndContinue: `Guardar y continuar`,
    saveChanges: `Guardar cambios`,
    scheduleNewAppointment: `Programar nueva cita`,
    searchInConversation: `Buscar en conversaciones...`,
    secureRealmError: `Lanzamiento fallido, es necesario activar una pantalla de bloqueo`,
    selectDifferentImage: `Seleccionar una imagen distinta`,
    selectFile: `Seleccionar archivo`,
    selectFunction: `Seleccionar función`,
    selectLanguage: `Seleccionar idioma`,
    selectOneOrMoreHCPs: `Seleccionar uno o más PS`,
    selectPictureSource: `Seleccionar foto de`,
    selectProfilePicture: `Seleccionar una foto de perfil`,
    selectSurgeon: `Seleccionar cirujano`,
    send: `Enviar`,
    sendMessage: `Enviar mensaje`,
    sendNewMessage: `Enviar un nuevo mensaje`,
    september: `Septiembre`,
    setPassword: `Establecer contraseña`,
    setPasswordReminder: `Puede cambiar su contraseña en el menú de configuración en cualquier momento.`,
    settings: `Configuración`,
    setup: `CONFIGURACIÓN`,
    setYourPersonalGoal: `Fijar su objetivo personal`,
    someonesPathway: (params: string[]) =>
        `Proceso asistencial de ${params[0]}`,
    sortBy: `Ordenar por`,
    splashSubtitle: `Cirugía para la pérdida de peso`,
    start: `Empezar`,
    startANewConversation: `Empezar una nueva conversación`,
    startConversation: `Empezar conversación`,
    startingPoint: `Punto de partida`,
    startNewConversation: `+ Empezar una nueva conversación`,
    startPreparation: `Empezar su preparación`,
    status: `Estado`,
    subject: `Asunto`,
    subjectChangedSuccess: `Asunto de la conversación editado correctamente`,
    subjectChangeFail: `No se ha cambiado el asunto de la conversación`,
    submit: `Enviar`,
    subPhase: `Subfase`,
    successEditHcp: `Ha editado su perfil correctamente`,
    surgeon: `Cirujano`,
    surgeryInformation: `Información sobre la cirugía`,
    tasks: `tareas`,
    tasksCompleted: `Tareas completadas`,
    team: `Equipo`,
    thisMonth: `Este mes`,
    time: `Hora`,
    timeAndLocation: `Hora y Ubicación`,
    timeOfSurgery: `Hora de la cirugía *`,
    to: `Para`,
    today: `Hoy`,
    toDo: `Hacer`,
    undo: `Deshacer`,
    unitRequired: `Unidad *`,
    units: `Unidades`,
    unknown: `Prefiero no decirlo`,
    unknownError: `Se ha producido un error en el proceso.Inténtelo de nuevo…`,
    unknownGender: `Prefiero no responder`,
    unknownUser: `Desconocido`,
    unreadMessage: `Mensaje no leído`,
    unreadMessages: `Mensajes no leídos`,
    untitled: `Sin título…`,
    update: `Actualizar`,
    updateAppointment: `Editar cita`,
    updateAppointmentButton: `Guardar cambios y enviar actualizaciones`,
    updateAppointmentSuccess: `Cita actualizada correctamente`,
    updateMessage: `Para continuar usando esta aplicación debe actualizarla a la versión más reciente en la tienda de aplicaciones`,
    updateProfilePicture: `Actualizar foto de perfil`,
    updateProgress: `Actualizar progreso`,
    useCamera: `Usar la cámara`,
    username: `Nombre de usuario`,
    video: `Vídeo`,
    viewAllMessages: `Ver todos los mensajes`,
    viewAndEditPathway: `Ver y editar fechas de procesos asistenciales`,
    viewDocument: `Ver documento`,
    weight: `Peso`,
    weightLoss: `Pérdida de peso`,
    weightUpdatedSuccess: `El peso actual se ha actualizado correctamente`,
    welcomeHeader: `Bienvenido/a`,
    welcomeMessage: (params: string[]) => `¡Hola, ${params[0]}!`,
    wellDoneNextStep: `¡Buen trabajo!¡Está listo/a para pasar al paso siguiente!`,
    withdrawConfirm: `De acuerdo, abandone la aplicación`,
    withdrawConsent: `Retirar consentimiento`,
    withdrawConsentBody: `Con la retirada del consentimiento para procesar su información personal, ciertos datos como sus notas y sus objetivos personales se eliminarán y, tras un periodo de espera de 30 días, ya no podrá acceder a la aplicación.`,
    withdrawConsentTitle: `¿Está seguro/a de que quiere salir de la plataforma Care4Today?`,
    writeAMessage: `Escriba un mensaje...`,
    writeSomething: `Escriba algo…`,
    wrongUserName: `El nombre de usuario que ha introducido es incorrecto`,
    xUnread: (params: string[]) => `${params[0]} no se ha leído`,
    yes: `Sí`,
    yesDelete: `Sí, eliminar`,
    yesDiscard: `Sí, desechar`,
    youAreOffline: `No está conectado/a`,
    youCanSetASentence: `Puede establecer una frase que le motive para lograr su objetivo personal.`,
    youGained: (params: string[]) => `Ha ganado ${params[0]}`,
    youGainedFormat: (params: string[]) =>
        `Ha ganado ${params[0]} ${params[1]}`,
    youHaveANewMessageFrom: (params: string[]) =>
        `Tiene un nuevo mensaje de ${params[0]}.`,
    youHaveNewAppointment: `Tiene una nueva cita.Abra la aplicación para ver las novedades.`,
    youHaveNewAppointments: (params: string[]) =>
        `Tiene ${
            params[0]
        } citas nuevas.Abra la aplicación para ver las novedades.`,
    youHaveNewMessage: `Tiene un nuevo mensaje.Abra la aplicación para ver las novedades.`,
    youHaveNewMessages: (params: string[]) =>
        `Tiene ${
            params[0]
        } mensajes nuevos.Abra la aplicación para ver las novedades.`,
    youHaveUndone: `Ha anulado la opción elegida anteriormente`,
    youLost: (params: string[]) => `Ha perdido ${params[0]}`,
    youLostFormat: (params: string[]) => `Ha perdido ${params[0]} ${params[1]}`,
    yourAppointments: `Sus citas`,
    yourGoals: `Sus objetivos`,
    yourNote: `Su nota`,
    yourPassword: `Su contraseña`,
    yourPasswordHasBeenReset: `Su contraseña se ha restablecido`,
    yourProfile: `Su perfil`,
    export: `Exportar`,
    exportData: `Exportar datos personales`,
    exportDataFail: `Se ha producido un error.No se han podido exportar los datos`,
    exportMyData: `Exportar mis datos personales`,
    goalStepCount: `Objetivo (pasos/día)`,
    loadingPathway: `Cargando proceso asistencial, esto puede llevar hasta 1 minuto`,
    loadingPatient: `Cargando paciente; por favor, espere`,
    pleaseEnterTotalSteps: `Introduzca el número total de pasos el final de cada día`,
    stepCount: `Recuento de pasos`,
    stepsPerDay: `pasos/día`,
    walkStepsPerDay: (params: string[]) => `Caminar ${params[0]} pasos/día`,
    steps: `Pasos`,
    avgWeeklySteps: `Promedio de pasos esta semana`,
    rightToBeForgotten: `Borrar mis datos personales`,
    totalStepsDuringDay: `Total de pasos durante el día`,
    youAlreadyWalked: (params: string[]) =>
        `Hoy ha caminado ${params[0]} pasos`,
    rightToBeForgottenTitle: `¿Está seguro/a de querer eliminar sus datos personales?`,
    rightToBeForgottenInfo: `Al iniciar esta solicitud, su información personal se eliminará y ya no podrá acceder a la aplicación. Tenga en cuenta que cierta información personal como su nombre, enviado desde el sistema de información del hospital, puede seguir apareciendo en las citas.    Si tiene más preguntas póngase en contacto con support@care4todaypatient.com.    Introduzca su contraseña para confirmar esta acción:`,
    passwordHint: `Su contraseña`,
    rightToBeForgottenSuccess: `La solicitud de eliminar datos personales se ha enviado al buzón de asistencia técnica de Care4Today`,
    incorrectPassword: `Ha introducido una contraseña incorrecta`,
    errorInitiatingRightToBeForgotten: `Error al enviar la solicitud; póngase en contacto directamente con la asistencia técnica`,
    updateStepCount: `Actualizar el recuento de pasos`,
    mon: `Lun.`,
    tue: `Mar.`,
    wed: `Mié.`,
    thu: `Jue.`,
    fri: `Vie.`,
    sat: `Sáb.`,
    sun: `Dom.`,
    stepsAmount: (params: string[]) => `${params[0]} pasos`,
    stepsGoalUpdateSuccess: `El valor de los pasos se ha añadido correctamente`,
    search: `Buscar...`,
    successEditMDT: `EMD actualizado correctamente`,
    failEditMDT: `Se ha producido un error en la actualización del EMD`,
    userCreationError: `Se ha producido un error en la creación del usuario`,
    userUpdateSuccess: `El usuario se ha actualizado correctamente`,
    legal: `Legal`,
    termsOfUse: `Condiciones de uso`,
    disclaimer: `Exención de responsabilidad`,
    exportDataSuccessV1: `La solicitud de exportar datos personales se ha enviado al equipo de asistencia técnica de Care4Today`,
    exportDataSuccess: `Se ha iniciado la exportación de datos personales`,
    dataFormatV1: `Sus datos personales se exportarán en formato de archivo CSV.El archivo se enviará a su dirección de correo electrónico registrada.`,
    dataFormat: `Sus datos personales se exportarán en formato de archivo JSON.El archivo se enviará a su dirección de correo electrónico registrada.`,
    viewAllMaterials: `Ver todos los materiales`,
    viewAllAppointments: `Ver todas las citas`,
    enjoyYourDay: `¡Disfrute de su día libre!`,
    motivateAlmost: `¡Ya casi ha llegado!`,
    startConversationHcp: `Inicie una conversación con un PS`,
    andYou: `, usted`,
    viewAllNotifications: `Ver todas las notificaciones`,
    noInvitations: `Ninguna invitación`,
    yourTimeline: `Su cronograma`,
    currentSubphase: `Subfase actual`,
    updateWeight: `Actualizar peso actual`,
    teamLoading: `Se está cargando el equipo`,
    noMdt: `Ningún equipo multidisciplinar asignado.`,
    teamDetails: `Ver detalles del equipo`,
    showResolved: `Mostrar resueltos`,
    readDoc: `Leer documento`,
    consultationNotes: `Notas de consulta`,
    viewAllConsultationNotes: `Ver todas las notas de consulta`,
    createNewNote: `+ Crear nota nueva`,
    dismiss: `Descartar`,
    pictureError: `Error al cargar foto`,
    wrongFormat: `Formato de imagen incorrecto`,
    backToDashboard: `Volver al panel`,
    noMessage: `Ningún mensaje`,
    noSpecialCharacters: `No están permitidos los caracteres especiales.`,
    noNotesAvailable: `No hay notas disponibles`,
    hcpPortal: `Portal del PS`,
    patientPortal: `Portal del paciente`,
    consultationNote: `nota de consulta`,
    noteTitle: `Título de la nota`,
    noteContents: `Contenido de la nota`,
    writeConsultationNotes: `Escriba aquí las notas de consulta`,
    createHcpNote: `Crear nota`,
    consultationNoteCreatedBy: (params: string[]) =>
        `Creada: ${params[0]} por ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `Editada por última vez: ${params[0]}`,
    loadingConsultaionNotes: `Cargando notas de consulta`,
    consultationNotesFor: (params: string[]) =>
        `Notas de consulta para ${params[0]}`,
    editHcpNote: `Editar nota`,
    reason: `Motivo`,
    writeReasonForEditing: `Escriba el motivo del cambio...`,
    confirmCancelCreateNote: `¿Está seguro/a de que quiere salir sin crear la nota?`,
    confirmCancelEditNote: `¿Está seguro/a de que quiere salir sin editar la nota?`,
    rotateYourDevice: `Gire su dispositivo`,
    patientId: `Identificador de paciente`,
    oldPassword: `Contraseña antigua`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `Documentos`,
    hcpId: `Identificador del profesional sanitario (PS)`,
    userInactivity: `La sesión ha caducado debido a la inactividad.`,
    duplicateMrn: `Este identificador de profesional sanitario (PS) ya existe en Care4Today`,
    confirm: `Confirmar`,
    viewDetails: `Ver detalles`,
    upperCaseLetters: `Mayúsculas`,
    lowerCaseLetters: `Minúsculas`,
    numbers: `Números`,
    specialCharacters: `Caracteres especiales (signos de puntuación, símbolos)`,
    passwordRequirements: `La contraseña debe tener como mínimo 8 caracteres y cumplir dos criterios de complejidad:`,
    incorrectOldPassword: `La contraseña antigua es incorrecta.Su cuenta se bloqueará después de 5 intentos fallidos`,
    newPasswordsNotSame: `La nueva contraseña que ha introducido no coincide`,
    passwordSuccesfullyChanged: `La contraseña se ha cambiado correctamente`,
    accountBlockedFifteenMinutes: `Su cuenta está bloqueada.Vuelva a intentarlo pasados 15 minutos`,
    loadingLegalDocuments: `Cargando documentos legales...`,
    fr: `Francés`,
    errorFetchingLegalDocuments: `Error en la carga de documentos legales`,
    nameAndMrnNotFound: `No se ha podido encontrar la combinación de identificador y apellido del paciente`,
    duplicateNameAndMrn: `El identificador del paciente ya existe en Care4Today`,
    NSCameraUsageDescription: `Esta aplicación necesita acceso a la cámara para añadir / actualizar la foto de perfil y añadir adjuntos a las notas`,
    NSPhotoLibraryUsageDescription: `Esta aplicación necesita acceso a la biblioteca de fotos para añadir adjuntos a las notas`,
    initiate: `Iniciar`,
    lastNameAsc: `Apellidos, orden asc.`,
    lastNameDesc: `Apellidos, orden desc.`,
    firstNameAsc: `Nombre, orden asc.`,
    firstNameDesc: `Nombre, orden desc.`,
    messageParticipantIsInactive: `ya no está activo`,
    participantNoLonger: `El participante ya no es usuario de la plataforma`,
    requestDeletionInProgress: `Estamos trabajando en su solicitud para eliminar sus datos personales.El equipo de asistencia técnica le informará tan pronto como se haya completado el proceso`,
    contactNotAvailableOnDeactivated: `Los datos de contacto de un PS desactivado no están disponibles`,
    deactivated: `Desactivado`,
    noPermissionToSendMessage: `No tiene permiso para enviar mensajes a esta persona`,
    refrainSendingMedData: `Absténgase de enviar mensajes que contengan datos o información médica del paciente`,
    refrainEnteringMedData: `Absténgase de introducir datos o información médica del paciente en el campo anterior`,
    contactHospitalAppointment: `Póngase en contacto con el hospital directamente si necesita reprogramar o cancelar su cita.`,
    noInfoDescriptionAppointment: `No hay más información disponible.Póngase en contacto con el hospital directamente si tiene alguna pregunta sobre su cita.`,
    noInfoDescriptionAndDateAppointment: `Próximamente le enviaremos más información sobre su cita.Póngase en contacto con el hospital directamente si tiene alguna pregunta sobre su cita.`,
    participants: `Participantes`,
    noMdtAssigned: `No hay ningún equipo multidisciplinar asignado al paciente.Asignar primero un equipo multidisciplinar al paciente.`,
    scheduled: `Programada`,
    updated: `Actualizada`,
    proposed: `Propuesta`,
    he: `Hebreo`,
    restrictProcessingPersonal: `Restricción del tratamiento de mis datos personales`,
    restrictProcessingArticle: `En función del artículo 18 del RGPD, ¿cuál de los siguientes puntos se aplica a su situación?`,
    dataAccuracy: `Precisión de los datos`,
    unlawfulProcessing: `Tratamiento ilícito`,
    legalClaim: `Reclamación judicial`,
    provideExplanation: `Proporcione una explicación:`,
    provideExplanationDescription: `Proporcione una explicación para describir el problema que ayude a valorar su solicitud`,
    restrictProcessing: `Restringir el tratamiento`,
    sureProcessing: `¿Está seguro/a de que quiere restringir el tratamiento de sus datos personales?`,
    processingPasswordConfirmation: `Al iniciar esta solicitud sus datos se desactivarán de forma temporal y, a menos que le informemos de lo contrario, solo almacenaremos los datos, y solo los seguiremos tratando si obtenemos su consentimiento.Si tiene más preguntas o si quiere cancelar la restricción póngase en contacto con support@care4todaypatient.com.Proporcione su contraseña para confirmar esta acción:`,
    processingSent: `La solicitud de restringir el tratamiento de sus datos personales se ha enviado al buzón de asistencia técnica de Care4Today`,
    versionNumber: (params: string[]) => `Versión ${params[0]}`,
    pleaseSelect: `Seleccione:`,
    restrictedLogout: `La sesión se ha cerrado porque su solicitud de restringir el tratamiento de sus datos personales se ha procesado y aplicado a su cuenta de Care4Today.Si tiene alguna pregunta, escríbanos a support@care4todaypatient.com.`,
    restrictProcessingAlreadyRequested: `Estamos trabajando en su solicitud de restringir el tratamiento de sus datos personales.El equipo de asistencia técnica le informará tan pronto como se haya completado el proceso.`,
    rightToRestrictQuestion: `En función del artículo 18 del RGPD, ¿cuál de los siguientes puntos se aplica a su situación?`,
    rightToRestrictExplanation: `Proporcione una explicación:`,
    rightToRestrictTitle: `Restricción del tratamiento de mis datos personales`,
    rightToRestrictExplanationPlaceholder: `Proporcione una explicación para describir el problema que ayude en la valoración de su solicitud.`,
    rightToRestrictConfirmationTitle: `¿Está seguro/a de que quiere restringir el tratamiento de sus datos personales?`,
    rightToRestrictConfirmationDescription: `Su solicitud se enviará al equipo de asistencia técnica.Su cuenta y sus datos se desactivarán de forma temporal y, a menos que le informemos de lo contrario, solo almacenaremos los datos, y solo los seguiremos tratando si obtenemos su consentimiento.Si tiene más preguntas o si quiere cancelar la restricción póngase en contacto con support@care4todaypatient.com`,
    assignedRole: (params: string[]) => `${params[0]} asignado (inactivo)`,
    requestRestrictionSubmitted: `La solicitud de restringir el tratamiento de sus datos personales se ha enviado al buzón de asistencia técnica de Care4Today`,
    temporarelyUnavailableHCPAlertMessage: `El PS no está disponible temporalmente en la plataforma.En caso de tener alguna pregunta, póngase en contacto con el equipo de asistencia técnica.`,
    temporarelyUnavailableHCPSubtitle: `El PS no está disponible temporalmente`,
    assignedHCP: (params: string[]) => `${params[0]} asignado`,
    inactive: `Inactivo`,
    appointmentInvite: `Tiene una cita`,
    disabledAppointmentActionMessage: `Use el sistema de reserva de citas del hospital directamente para programar, actualizar o cancelar una cita.`,
    noFurtherInformation: `No hay más información disponible`,
    cancelled: `Cancelada`,
    cancelledNotificationPrefix: `Cancelada:`,
    updatedNotificationPrefix: `Actualizada:`,
    allDay: `Todo el día`,
    editCareModule: `Editar módulo de atención`,
    nextSurgeryProcedureInformation: `Siguiente:Detalles de cirugía / procedimiento`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} ya no forma parte de\nsu Equipo multidisciplinar`,
    editCareModuleWarning: `Tenga en cuenta que al cambiar el Módulo de atención, todo el historial de objetivos y materiales de formación del procedimiento anterior dejarán de estar disponibles para el paciente.`,
    editSurgeryWarning: `Ajuste la información de la cirugía si es necesario.`,
    nextUpdateMDT: `Siguiente:Actualizar equipo médico`,
    updateCareModule: `Actualizar módulo de atención`,
    editMdtTeamWarning: `Compruebe el equipo multidisciplinar para ver si es necesaria alguna actualización.`,
    participantNotInMDT: `Ya no forma parte del equipo multidisciplinar (EMD) para este paciente`,
    createMedicalTeam: `Crear equipo médico`,
    editMedicalTeam: `Editar equipo médico`,
    mdtName: `Nombre del equipo multidisciplinar (EMD)`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `¿Está seguro/a de que quiere cambiar el módulo de atención de este paciente “${
            params[0]
        }” a “${params[1]}”?`,
    changePathwayConfirmationSubTitle: `Tenga en cuenta que al cambiar el Módulo de atención, todo el historial de objetivos y materiales de formación del procedimiento anterior dejarán de estar disponibles para el paciente`,
    changePathwaySuccessMessage: (params: string[]) =>
        `Ha cambiado correctamente el módulo de atención del paciente ${
            params[2]
        } de “${params[0]}” a “${params[1]}”`,
    mdtChanged: `Su equipo médico ha cambiado`,
    tapForDetails: `Pulse aquí para ver más detalles.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `El ${
            params[0]
        } asignado ya no forma parte de\nsu equipo multidisciplinar`,
    addPatientReceivedConsent: `Al proporcionar la siguiente información, declaro que he recibido el consentimiento del paciente para tratar sus datos personales.`,
    attended: `Asistió`,
    entityCreationError: (params: string[]) =>
        `Ha habido un error al crear el ${params[0]}`,
    updateAppointmentError: `Ha habido un error en la actualización de la cita`,
    updateConsultationNoteError: `Ha habido un error en la actualización de la nota de consulta`,
    createConsultationNoteError: `Ha habido un error en la creación de la nota de consulta`,
    missed: `Olvidada`,
    contentDescCloseNotification: `Cerrar notificación`,
    pathwayChanged: `Su módulo de atención ha cambiado`,
    pathwayChangedDetails: (params: string[]) =>
        `de ${params[0]} a ${
            params[1]
        }.Póngase en contacto con su coordinador de atención / PS para obtener más información.`,
    de: `Alemán`,
    doYouWantToDeletePatient: (params: string[]) =>
        `¿Está seguro/a de que desea eliminar a este paciente ${params[0]}?`,
    personWillBeRemovedFromRecords: `Esta persona no podrá iniciar sesión en la aplicación C4T y será eliminada de los registros digitales.`,
    provideDeletionReason: `Proporcione un motivo para la eliminación:`,
    deletionSuccess: (params: string[]) =>
        `Ha eliminado ${params[0]} de la plataforma correctamente`,
    consentNotProvided: `No se dispone de consentimiento`,
    entryError: `Error de introducción`,
    duplicatePatient: `Paciente duplicado`,
    addExtraSecurity: `Añada seguridad extra a su cuenta con el sistema de verificación de 2 pasos`,
    mfaDescription: `Cada que vez que inicie sesión en su cuenta desde un dispositivo nuevo se le pedirá que introduzca un código de seguridad.Este código de seguridad se le enviará por correo electrónico o por teléfono.`,
    activateMfa: `Activación de la verificación en 2 pasos`,
    userAccountNotActive: `Su cuenta de usuario no está activa`,
    useHCPPortal: `Utilice el portal PS en línea si ha olvidado su contraseña`,
    noPatientsAssigned: `No tiene ningún paciente asignado.`,
    currentAppointments: `Citas actuales`,
    noCurrentAppointments: `No hay citas futuras disponibles`,
    phase: `Fase`,
    noPhaseInformation: `No hay información de fase`,
    noSubphaseInformation: `No hay información de subfase`,
    you: (params: string[]) => `${params[0]} (usted)`,
    hcpsMedicalStaff: `Profesionales sanitarios (PS)`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `en ${params[0]} (${params[1]})`,
    newMessage: `Nuevo mensaje`,
    addParticipant: `Añadir participante`,
    editParticipant: `Editar participante`,
    messagesFor: (params: string[]) => `Mensajes ${params[0]}`,
    noParticipants: `No hay participantes disponibles`,
    whichMfaMethod: `¿Cómo le gustaría recibir el código de seguridad?`,
    mfaMethodExplanation: `Necesita este código de seguridad para acceder a su cuenta. Puede obtener el código de registro con su teléfono móvil o correo electrónico. Elija el método que prefiera.`,
    textMe: `Enviarme un código de registro por mensaje de texto`,
    emailMe: `Enviarme un código de registro por correo electrónico`,
    textMeSubtitle: `Le solicitaremos su número de teléfono`,
    emailMeSubtitle: `Confirme su dirección de correo electrónico`,
    backToMethod: `Volver a la elección de método`,
    addPhone: `Añadir un número de teléfono`,
    whichPhone: `¿En qué número de teléfono le gustaría recibir el código de seguridad?`,
    phoneDisclaimer: `Este número de teléfono solo se utilizará para la seguridad de la cuenta. Se podrán cargar costes por el uso de datos y mensaje de texto.`,
    sendCode: `Enviar código de seguridad`,
    confirmEmail: `Confirme su dirección de correo electrónico`,
    whichEmail: `¿En qué dirección de correo electrónico le gustaría recibir el código de seguridad?`,
    emailDisclaimer: `Esta dirección de correo electrónico solo se utilizará para la seguridad de la cuenta.`,
    insertCode: `Introduzca su código de seguridad`,
    mayTakeTwoMinutes: `Puede tardar hasta dos minutos en recibir su código.`,
    sentCodeByText: (params: string[]) =>
        `Acabamos de enviar el código de seguridad a través de mensaje de texto a ${
            params[0]
        }`,
    sentCodeByEmail: (params: string[]) =>
        `Acabamos de enviar el código de seguridad a través de correo electrónico a ${
            params[0]
        }`,
    didntGetCode: `¿No ha recibido ningún código?`,
    resendCode: `Volver a enviar código de seguridad`,
    authenticate: `Verificar`,
    verifyingCode: `Verificando el código de seguridad`,
    mfaSuccess: `La verificación en dos pasos se ha activado correctamente.`,
    mfaCodeRequired: `Se requiere un código de registro para acceder a su cuenta.`,
    mfaMethodExplanationLogin: `Necesita este código de seguridad para acceder a su cuenta. Puede obtener el código de registro con su teléfono móvil o correo electrónico.`,
    contentDescMfaIcon: `Icono de verificación en dos pasos`,
    mfaSendCodeTo: (params: string[]) => `Enviaremos el código a ${params[0]}`,
    continueLabel: `Continuar`,
    authenticating: `Verificando`,
    mfaInvalidCode: `El código introducido no es válido. Inténtelo de nuevo.`,
    mfaUnableToVerifyPhoneNumber: `No podemos verificar este número de teléfono. Inténtelo con otro.`,
    mfaUnableToVerifyEmail: `No podemos verificar esta dirección de correo electrónico. Inténtelo con otra.`,
    sessionExpired: `Su sesión ha finalizado. Iniciar sesión de nuevo.`,
    passwordExpired: `Su contraseña ha caducado. Cambie su contraseña.`,
    rightToBeForgottenInfoNonIntegrated: `Al iniciar esta solicitud, su información personal se eliminará y ya no podrá acceder a la aplicación.Si tiene más preguntas póngase en contacto con support@care4todaypatient.com.Proporcione su contraseña para confirmar esta acción:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `Su solicitud se enviará al equipo de asistencia técnica.Su cuenta y sus datos se desactivarán de forma temporal y, a menos que le informemos de lo contrario, solo almacenaremos los datos, y solo los seguiremos tratando si obtenemos su consentimiento.Si tiene más preguntas o si quiere cancelar la restricción póngase en contacto con support@care4todaypatient.com`,
    password_expired_message: `Su contraseña ha caducado y debe cambiarla para acceder a Care4Today`,
    firstdayOftheWeek: `Primer día de la semana`,
    dateformat: `Formato de fecha`,
    selectDateFormat: `Seleccione formato de fecha`,
    selectDay: `Seleccione el día`,
    monday: `Lunes`,
    tuesday: `Martes`,
    wednesday: `Miércoles`,
    thursday: `Jueves`,
    friday: `Viernes`,
    saturday: `Sábado`,
    sunday: `Domingo`,
    manageTheAppointmentTemplates: `Gestionar el formulario de citas`,
    prefillTemplatesFor: `Precumplimentar formularios para`,
    appointmentTemplates: `Formulario de citas`,
    backToTemplateTypes: `Volver a tipos de formularios`,
    addNewAppointmentTemplate: `Añadir formulario de nueva cita`,
    caremoduleName: `Nombre del módulo de cuidado asistencial`,
    selectPathway: `Seleccionar un proceso asistencial`,
    notShowInDropdownAfterDelete: `Si elimina este formulario dejará de aparecer en el menú desplegable`,
    messagesTemplates: `Formularios de mensajes`,
    addNewMessageTemplate: `Añadir formulario de nuevo mensaje`,
    pathway: `Proceso asistencial`,
    template: `Formularios`,
    typesTwo: `2 tipos`,
    scheduledAppointmentInDropdown: `Si elimina este formulario dejará de aparecer en los campos desplegables cuando programe una cita.`,
    manageTemplate: `Gestionar formulario`,
    manageTheMessageTemplates: `Gestionar el formulario de mensajes`,
    addMdt: `+ Añadir un nuevo equipo multidisciplinar a la plataforma`,
    mdts: `Equipos multidisciplinares`,
    NameAsc: `Nombre asc.`,
    NameDesc: `Nombre desc.`,
    Teams: `Equipos`,
    MdtsName: `Nombre del equipo multidisciplinar`,
    managemdts: `Gestionar equipo multidisciplinar`,
    members: `Miembros`,
    editTeam: `Editar equipo`,
    addANewMDTToThePlatform: `Añadir un nuevo equipo multidisciplinar a la plataforma`,
    week: `Semana`,
    month: `Mes`,
    year: `Año`,
    total: `Total`,
    dailyaverage: `Promedio diario`,
    nochartdata: `No hay gráfico de datos disponible`,
    youCanOnlyAssignOneMDTAtATime: `Solo puede asignar un equipo multidisciplinar a la vez`,
    noMoreOptionsAvailable: `No hay más opciones disponibles`,
    mdt: `Equipo multidisciplinar`,
    relatingPatient: `Referente a un paciente`,
    nonrelatingPatient: `No referente a un paciente`,
    sendMsgPatient: `Enviar mensaje nuevo al paciente`,
    expectedResponseTime: `Tiempo de respuesta previsto entre 3 y 4 horas`,
    walkedText: `caminados`,
    walk: `caminar`,
    mymedicalteam: `Mi equipo médico`,
    yesterday: `Ayer`,
    close: `Cerrar`,
    passwordUsedBefore: `La nueva contraseña ya se ha utilizado previamente y no puede volver a utilizarse. Introduzca otra contraseña.`,
    sendMessageTo: `Enviar mensaje a`,
    message: `Mensaje`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} añadió a ${params[1]} a la conversación`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} eliminó a ${params[1]} de la conversación`,
    removedParticipant: `Participante eliminado`,
    noMessagesSelected: `No tiene ningún mensaje seleccionado`,
    noMessagesSelectedDesc: `Seleccione un mensaje en el lado izquierdo de la pantalla o inicie una nueva conversación`,
    mfaMethodExplanationRegistration: `Necesita este código de seguridad para acceder a su cuenta. Puede obtener el código de registro con su teléfono móvil o correo electrónico. Elija el método que mejor le venga.\n\nTenga en cuenta que solo puede elegir un método de verificación en este momento. Una vez que haya realizado su elección, su preferencia se guardará y no podrá cambiarla sin ponerse en contacto con el servicio de asistencia.`,
    signinCodeRequired: `Solicitar código de seguridad`,
    securityCodeRequired: `Necesita este código de seguridad para acceder a su cuenta. Puede obtener el código de registro utilizando el método que eligió durante su primer registro.`,
    newMfaUserDesc1: `Necesita este código de seguridad para acceder a su cuenta. Puede obtener el código de registro con su teléfono móvil o correo electrónico. Elija el método que prefiera.`,
    newMfaUserDesc2: `Tenga en cuenta que solo puede elegir un método de verificación en este momento. Una vez que haya realizado su elección, su preferencia se guardará y no podrá cambiarla sin ponerse en contacto con el servicio de asistencia.`,
    feelFreeToMessageTeam: `Inicie una conversación con alguien de su equipo.`,
    noFutureMessages: `No tiene ningún mensaje`,
    chatSelfRemove: `Usted se ha eliminado correctamente de la conversación`,
    noResultFound: `No se encontraron resultados`,
    chatUpdated: `El chat se ha actualizado correctamente`,
    chatNotUpdated: `El chat no se ha actualizado`,
    searchPlaceholder: `Buscar una plantilla...`,
    editPrefillTemplate: `Editar plantilla precumplimentada`,
    forAppointments: `Para citas`,
    addTemplateToList: `Añadir plantilla a la lista`,
    addNewPrefillTemplate: `Añadir nueva plantilla precumplimentada`,
    forMessages: `Para mensajes`,
    editNewPrefillTemplate: `Editar nueva plantilla precumplimentada`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
