export const LANG_HE_TRANS = {
    accept: `אשר/י`,
    accepted: `אושר`,
    acceptedInvitation: `אישרת הזמנה זו.`,
    actions: `פעולות`,
    addHcp: `הוספת חבר צוות חדש לפלטפורמה`,
    addHCPTag: `+ צוות רפואי`,
    addHcpToPlatform: `הוספת חבר צוות לפלטפורמה`,
    addNewHCP: `+ הוספת חבר צוות חדש לפלטפורמה`,
    addNewPatient: `+ הוספת מטופל חדש לפלטפורמה`,
    addPatient: `הוספת מטופל/ת`,
    addPatientConsent: `מאושר על ידי בזאת כי קיבלתי את הסכמת המטופל להזין את נתוניו.`,
    addPatientToPlatform: `הוספת מטופל/ת לפלטפורמה`,
    administration: `ניהול`,
    agreed: `מוסכם`,
    allHcps: `כל אנשי הסגל הרפואי`,
    allowNotifications: `אפשרת הודעות, מעולה!`,
    allPatients: `כל המטופלים`,
    almostHalfway: `!כמעט הגעת לחצי הדרך`,
    almostThere: `כמעט הגעת ליעד!`,
    am: `בבוקר`,
    andMore: (params: string[]) => `ועוד ${params[0]}`,
    apiErrorGetConsentDocument: `הטענת מסמך ההסכמה נכשלה, יש להקיש כאן כדי לנסות שוב`,
    appointment: `פגישה`,
    appointmentAcceptedByPatient: `התקבל על ידי המטופל`,
    appointmentAwaitingPatientResponse: `ממתין לתגובה מהמטופל`,
    appointmentDeclinedByPatient: `נדחה על ידי המטופל`,
    appointmentName: `שם הפגישה`,
    appointmentNotification: `התראה על פגישה`,
    appointments: `פגישות`,
    appointmentsForPatient: (params: string[]) => `פגישות עבור ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `ניתן לקבוע פגישה בין ${params[0]} ל-${params[1]}`,
    appUnavailable: `סליחה, האפליקציה אינה זמינה כרגע. נא לבצע שוב ניסיון מאוחר יותר, או לבדוק האם קיימים עדכונים.`,
    april: `אפריל`,
    ar: `ערבית`,
    areYouSureDeclineMessage: `הצוות הקליני זקוק להצטרפותך כדי לעזור לך בהכנות ובניטור ההתקדמות שלך.\n\n נא ליצור קשר עם הרופא המפנה אם אינך רוצה להצטרף לפלטפורמה`,
    areYouSureDeclineTitle: `האם בודאות אינך רוצה להצטרף לפלטפורמת Care4Today?`,
    areYouSureDeleteNote: `האם בודאות ברצונך למחוק הערה זו?`,
    article: `מאמר`,
    assignToMDT: `הקצה לצוות`,
    audio: `שמע`,
    august: `אוגוסט`,
    back: `חזרה`,
    backToAppointments: `חזרה לפגישותיך`,
    backToDetails: (params: string[]) => `חזרה לפרטים של ${params[0]}`,
    backToLogin: `חזרה לדף הכניסה`,
    backToPatientProfile: `חזרה לפרופיל המטופל`,
    badPassword: `הזנת סיסמה לא תקינה.`,
    bariatrics: `בריאטריה`,
    blockedUser: `המשתמש שלך נחסם. נא לנסות שוב בעוד חצי שעה.`,
    bmi: `BMI`,
    bookedSuccess: `פגישתך נקבעה בהצלחה`,
    cancel: `ביטול`,
    cancelAlert: `ביטול`,
    cantParseError: `לא ניתן לנתח תגובה.`,
    cantSaveImage: `לא ניתן לשמור תמונה.`,
    care4Today: `Care4Today`,
    careModules: `מודולים של טיפול`,
    changePassword: `שינוי סיסמה`,
    changePasswordSubtitle: `נא לבחור סיסמה אישית משלך.`,
    changePasswordTitle: `נא לבצע התאמה אישית לסיסמתך`,
    choosePicture: `בחירת תמונה`,
    chooseProfilePicture: `שינוי תמונה`,
    cm: `ס"מ`,
    completed: `הושלם`,
    conditionalGoal: `יעד`,
    confirmAppointmentDelete: `האם בודאות ברצונך למחוק פגישה זו?`,
    confirmed: `מאושר`,
    confirmNewPasswordPlaceholder: `אישור סיסמה חדשה`,
    consent: `הסכמה`,
    consentDontAgree: `אין הסכמה על ידי, ולא אשתמש בפלטפורמת Care4Today`,
    consentedOn: (params: string[]) => `נתת הסכמתך בתאריך ${params[0]}`,
    contact: `צור קשר`,
    contactDetails: `פרטי יצירת קשר`,
    contactInfo: `פרטי יצירת קשר`,
    contentDescApptIcon: `אייקון פגישה`,
    contentDescAttachImage: `צירוף תמונה`,
    contentDescAttachment: `קובץ מצורף`,
    contentDescAttachmentImg: `תמונה על גבי מסך מלא`,
    contentDescBackground: `רקע`,
    contentDescChangePwdIcon: `אייקון שנה סיסמה`,
    contentDescClose: `סגירת מסך מלא`,
    contentDescDeleteAttachment: `מחיקת תמונה מצורפת`,
    contentDescDevicesIcon: `אייקון מכשירים מחוברים`,
    contentDescEduContentExpandBtn: `פתיחת קובץ תוכן לימודי מצורף`,
    contentDescEduContentThumb: `קובץ תוכן לימודי מצורף`,
    contentDescEduItemCompleted: `פריט לימודי הושלם`,
    contentDescEduItemIncomplete: `פריט לימודי לא הושלם`,
    contentDescGoalIcon: `אייקון יעד אישי`,
    contentDescHelpIcon: `אייקון עזרה`,
    contentDescKillswitchIcon: `אייקון מתג השבתה`,
    contentDescLegalIcon: `אייקון מסמכים משפטיים`,
    contentDescLogo: `לוגו אפליקציה`,
    contentDescLogoutIcon: `אייקון יציאה`,
    contentDescMdtPic: `תמונת איש סגל רפואי`,
    contentDescMessageIcon: `אייקון הודעה`,
    contentDescNoGoalIcon: `אייקון ללא יעד`,
    contentDescPathwayCurrent: `אייקון שלב נוכחי`,
    contentDescPathwayIcon: `אייקון מסלול הטיפול`,
    contentDescPathwayOtherPhase: `אייקון שלב אחר`,
    contentDescProfilePic: `תמונת פרופיל`,
    contentDescSend: `שליחה`,
    create: `יצירה`,
    createAMedicalTeam: `יצירת צוות רפואי`,
    createAppointment: `יצירת פגישה`,
    createAppointmentButton: `יצירת פגישה ושליחת הזמנה`,
    createAppointmentSuccess: `הפגישה נוצרה בהצלחה`,
    createAppt: `יצירת פגישה`,
    createMDT: `יצירת צוות טיפול`,
    currentBmi: `BMI נוכחי`,
    currentPhase: `שלב נוכחי`,
    currentWeight: `משקל נוכחי`,
    dashboard: `לוח מחוונים`,
    date: `תאריך`,
    dateOfBirth: `תאריך לידה`,
    dateOfConsent: `תאריך הסכמה`,
    dateOfConsentAsc: `תאריך הסכמה ממוין בסדר עולה`,
    dateOfConsentDesc: `תאריך הסכמה ממוין בסדר יורד`,
    dateOfSurgery: `תאריך הניתוח *`,
    december: `דצמבר`,
    decline: `סירוב`,
    declined: `נדחה`,
    declinedInvitation: `סירבת להזמנה זו`,
    declinedNotifications: `לא איפשרת קבלת הודעות, האם זה רצונך בוודאות? ניתן יהיה לשנות זאת בתפריט ההגדרות`,
    declinedSuccess: `דחית את פגישתך`,
    defaultError: `משהו השתבש`,
    delete: `מחיקה`,
    deleteAppointmentSuccess: `הפגישה נמחקה בהצלחה`,
    deleteNote: `מחיקת הערה`,
    deleting: `מתבצעת מחיקה...`,
    description: `תיאור`,
    details: `פרטים`,
    devices: `מכשירים מחוברים`,
    disagreeConsentError: `חלה שגיאה בעת סירובך להסכמה. נא לנסות שוב `,
    discardChanges: `לבטל שינויים?`,
    document: `מסמך`,
    done: `בוצע`,
    draftWontBeSaved: `הטיוטה שלך לא תישמר. האם ברצונך לבטל בכל זאת?`,
    duplicateMDT: `איש צוות כבר נבחר`,
    edit: `עריכה`,
    editHcpsProfile: `עריכת פרופיל חבר צוות`,
    editMessageDetails: `עריכת פרטי שיחה`,
    editMTDTeam: (params: string[]) => `עריכת צוות עבור ${params[0]}`,
    editPassword: `עריכת סיסמה`,
    editPatient: `עריכת מטופל`,
    editPatientError: `הייתה בעיה בעדכון פרטי המטופל`,
    editPatientSuccess: `פרטי המטופל עודכנו בהצלחה.`,
    editProfile: `עריכת פרופיל`,
    editProfilePicture: `עריכת תמונת פרופיל`,
    editSubject: `עריכת נושא`,
    editTeamMembers: `עריכת חברי צוות`,
    editYourPersonalGoal: `עריכת יעדיך האישיים`,
    eduContentHint: `יש להקיש על כפתור ההרחבה כדי לפתוח את התוכן המצורף.`,
    email: `דוא"ל`,
    emailAddress: `כתובת דוא"ל`,
    emailConfirmation: (params: string[]) =>
        `שלחנו לך דוא"ל ל-${params[0]} עם קישור לאיפוס סיסמתך.`,
    emailExists: (params: string[]) => `משתמש עם הדוא"ל ${params[0]} קיים כבר.`,
    emailSent: `הדוא"ל נשלח`,
    en: `אנגלית`,
    enableNotifications: `אפשרת הודעות`,
    enterANewHCP: `הזנת איש צוות רפואי חדש`,
    enterSubjectHint: `הזנת נושא`,
    enterTheSubject: `הזנת נושא לשיחה זו.`,
    errorEditingHcp: `חלה שגיאה בעת עריכת חבר הסגל הרפואי`,
    errorFindingConsentDocument: `שגיאה במציאת מסמך ההסכמה.`,
    errorLoading: (params: string[]) => `שגיאה בהטענת ${params[0]}`,
    errorSavingSettings: `שגיאה בשמירת ההגדרות`,
    errorUpdatingPassword: `לא ניתן לעדכן את הסיסמה`,
    excessWeightLost: `משקל עודף שירד`,
    failEditHcp: `חלה שגיאה בעריכת הפרופיל שלך`,
    february: `פברואר`,
    female: `נקבה`,
    filter: `פילטר`,
    firstName: `שם פרטי`,
    forgotPasswordInstruction: `נא לספק את כתובת הדוא"ל בה נרשמת בבית החולים שלך. אנו נשלח לך דוא"ל עם קישור לאיפוס סיסמתך.`,
    forgotPasswordViewTitle: `שכחתי סיסמה`,
    forgotYourPassword: `שכחת את סיסמתך?`,
    formTimeRangeInPast: `טווח הזמנים לא יכול להיות בעבר`,
    formTimeRangeStartGreaterThanEnd: `טווח הזמנים אינו תקין`,
    forPatient: `עבור`,
    from: `מ-`,
    ft: `רגל`,
    fullName: `שם מלא`,
    function: `תפקיד`,
    gained: `נוסף`,
    gender: `מין`,
    goal: `יעד`,
    goalSavedError: `לא ניתן לשמור את היעד!`,
    goalSavedSuccess: `היעד נשמר בהצלחה!`,
    goBack: `חזרה`,
    hcps: `סגל רפואי`,
    healthCareProfessionals: (params: string[]) =>
        `${params[0]} אנשי סגל רפואי`,
    height: `גובה`,
    help: `עזרה`,
    heyChooseYourPicture: (params: string[]) =>
        `שלום ${params[0]}, נא לבחור את תמונת הפרופיל שלך`,
    iAgree: `מוסכם על ידי`,
    iAgreeFormat: (params: string[]) =>
        `מוסכם על ידי (${params[0]}/${params[1]})`,
    iAmSure: `מאשר`,
    idealBodyWeight: `משקל גוף אידיאלי`,
    iDoNotAgree: `לא מוסכם מבחינתי`,
    iDontAgree: `לא מוסכם מבחינתי, ולא אשתמש בפלטפורמת Care4Today`,
    imperial: `יחידות אימפריאליות`,
    in: `אינץ'`,
    includeLinkToLocation: `כלול קישור למיקום`,
    initialWeight: `משקל התחלתי`,
    installUpdate: `התקן עדכון`,
    invalidEmailError: `דוא"ל לא תקין`,
    invalidNumber: `יש להזין מספר תקין`,
    invalidTokenError: `לא ניתן לאמת, נא לנסות להיכנס למערכת שוב.`,
    it: `איטלקית`,
    iWantToFitAgain: `דוגמה: "אני רוצה ללבוש שוב מידה L"`,
    january: `ינואר`,
    july: `יולי`,
    june: `יוני`,
    keepGoing: `המשך להתקדם!`,
    keepMomentum: `שמור על המומנטום!`,
    kg: `ק"ג`,
    kilogrammes: `קילוגרמים`,
    language: `שפה`,
    languageRequired: `שפה *`,
    lastName: `שם משפחה`,
    lb: `פאונד`,
    learningMaterials: `חומרי לימוד`,
    legalDocuments: `מסמכים משפטיים`,
    loading: `טוען`,
    loadingPatients: `טוען מטופלים, נא להמתין`,
    location: `מיקום`,
    locationUrl: `URL של מיקום`,
    lockScreenHint: `עליך להגדיר נעילת מסך למכשיר, כדי לאפשר שימוש מאובטח באפליקציה.`,
    login: `כניסה למערכת`,
    loginIncorrect: `הדוא"ל או הסיסמה שהזנת אינם נכונים`,
    logout: `התנתקות מהמערכת`,
    logoutAreYouSure: `האם בודאות ברצונך להתנתק מהמערכת?`,
    loseBefore: (params: string[]) => `להוריד ${params[0]}`,
    loseFormat: (params: string[]) => `להוריד ${params[0]} ${params[1]}`,
    lost: `ירדת`,
    male: `זכר`,
    manageHCPs: `ניהול הסגל הרפואי`,
    managePatients: `ניהול מטופלים`,
    march: `מרץ`,
    may: `מאי`,
    mdtTeam: `צוות רפואי`,
    mdtTeamNotAddedYet: `לא הוקצה צוות רפואי עדיין.`,
    mdtTeamUC: `צוות רפואי`,
    medicalTeam: `צוות רפואי`,
    meetingInvite: `יש לך פגישה`,
    meetingInviteWith: (params: string[]) => `פגישה עם ${params[0]}`,
    messageCreated: `שיחה התחילה בהצלחה.`,
    messageNotCreated: `התחלת שיחה נכשלה`,
    messageNotification: `דיווח על הודעה`,
    messageNotSent: `הודעה לא נשלחה`,
    messages: `הודעות`,
    metric: `שיטה מטרית`,
    movePhaseConfirmation: (params: string[]) =>
        `האם בודאות ברצונך להעביר את ${params[0]} לשלב ${params[1]}`,
    moveToNextPhase: `נא לעבור לשלב הבא`,
    multiDisTeam: `הצוות הרפואי שלך`,
    myMessages: `ההודעות שלי`,
    myMotivation: `המוטיבציה שלי:`,
    myPersonalGoal: `היעד האישי שלי`,
    myProfile: `הפרופיל שלי`,
    myTeam: `הצוות שלי`,
    name: `שם`,
    nameOfMDT: `שם איש הצוות *`,
    needsConsent: `ראשית המטופל צריך לקבל את ההסכמה.`,
    networkError: `חלה שגיאת רשת`,
    newAppointment: `פגישה חדשה`,
    newChat: `שיחה חדשה`,
    newInvitation: `הזמנה חדשה`,
    newMessageNotificationMore: (params: string[]) =>
        `יש לך ${params[0]} הודעות חדשות. פתיחת האפליקציה תציג מה חדש.`,
    newMessageNotificationOne: `יש לך הודעה חדשה אחת. פתיחת האפליקציה תציג מה חדש.`,
    newNote: `הערה חדשה`,
    newPasswordPlaceholder: `סיסמה חדשה`,
    newPatientSuccess: (params: string[]) =>
        `הוספת את ${params[0]} בהצלחה לפלטפורמה.`,
    newTeamFail: `לא הוקצה צוות`,
    newTeamSuccess: `צוות הוקצה`,
    newVersionApp: `יש לעדכן אפליקציה זו לגרסה העדכנית ביותר הזמינה בחנות האפליקציות.`,
    nextAppointment: `הפגישה הבאה`,
    nextSelectCareModule: `הבא: בחר מודולי טיפול`,
    nextSurgeryInformation: `הבא: פרטי הניתוח`,
    niceToSeeYouAgain: `טוב לראותך שוב!`,
    nickname: `כינוי`,
    nicknameError: `כינוי לא תקין. אסור להשתמש בתווים מיוחדים.`,
    nl: `הולנדית`,
    no: `לא`,
    noAppointments: `אין פגישות זמינות`,
    noCurrentGoalForPatient: `אין יעד נוכחי המקושר למטופל זה`,
    noDate: `לא הוגדר תאריך`,
    noFutureAppointments: `אין פגישות קרובות`,
    noGoalSet: `לא הוגדר יעד על ידי הצוות הרפואי שלך`,
    noMatchingConsentDocumentsFound: `לא נמצאו מסמכי הסכמה תואמים`,
    noMessages: `אין הודעות זמינות`,
    noNetworkConnection: `אין חיבור רשת זמין. נא לבדוק...`,
    noNotesMessage: `אין הערות זמינות.\n יש להקיש על "צור" להוספת הערות חדשות`,
    noPersonalGoalSet: `לא הוגדר יעד אישי.`,
    noPersonalGoalSetDashboard: `לא הוגדר יעד אישי. יש לעבור לעמוד ההגדרות כדי לעדכן זאת.`,
    noPlannedAppointments: `אין פגישות מתוכננות`,
    noPreview: `אין תצוגה מקדימה זמינה`,
    noProgressRecorded: `לא תועדה התקדמות`,
    noResponseError: `לא התקבלה תגובה.`,
    notAgreed: `לא מוסכם`,
    noteDeletedError: `לא ניתן היה למחוק את ההערה!`,
    noteDeletedSuccessfully: `ההערה נמחקה בהצלחה!`,
    notes: `הערות`,
    noteSaved: `ההערה נשמרה`,
    noteSavedError: `לא ניתן היה לשמור את ההערה!`,
    noteSavedSuccess: `ההערה נשמרה בהצלחה!`,
    noteSaveError: `שגיאה, לא ניתן לשמור את ההערה. האם לנסות שוב?`,
    notifications: `הודעות`,
    notNow: `לא כעת`,
    notSet: `לא הוגדר`,
    notYetSubmitted: `טרם נשלח`,
    noUnreadMessages: `אין הודעות שלא נקראו`,
    noUserFound: `שגיאה באיתור משתמש עם הרשאות המשתמש שסופקו.`,
    november: `נובמבר`,
    noWeightDifference: `אין הבדל במשקל`,
    october: `אוקטובר`,
    ok: `אישור`,
    onboardingNotificationsTitle: `אנו רוצים לעדכן אותך בכל עת`,
    onboardingNotifictionsInfo: `תשלח אליך הודעה בנוגע ל:\n\n• פגישותיך\n• הודעות חדשות מהצוות הרפואי שלך`,
    onVar: (params: string[]) => `ב-${params[0]}`,
    openCare: `נא לפתוח את care4today ולבדוק אם יש לך הודעות חדשות!`,
    optOutSubtitle: `נא ליצור קשר עם הרופא המפנה אם אינך רוצה להצטרף לפלטפורמה.`,
    optOutTitle: `האם בודאות אינך רוצה להצטרף לפלטפורמת Care4Today?`,
    organisation: `ארגון`,
    orthopedics: `אורתופדיה`,
    other: `אחר`,
    outdatedVersion: `מתבצע כעת שימוש בגרסה לא מעודכנת של האפליקציה.`,
    overview: `סקירה כללית`,
    participant: `משתתף`,
    password: `סיסמה`,
    passwordComplexityError: `הסיסמה צריכה להיות באורך של 8 תווים לפחות ולכלול לפחות 2 תווים מהסוגים הבאים: אותיות גדולות, אותיות קטנות, מספרים או סמלים.`,
    passwordMismatchError: `הסיסמאות אינן תואמות`,
    passwordUpdated: `הסיסמה עודכנה`,
    pastAppointments: `פגישות בעבר`,
    pathwayScheduleFail: `חלה שגיאה. לא ניתן היה לעדכן את לוח הזמנים למסלול הטיפול`,
    patient: `מטופל`,
    patientAge: (params: string[]) => `${params[0]} שנים`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} שנים`,
    patientConsent: `הסכמת מטופל`,
    patientNameAsc: `שמות המטופלים ממוינים בסדר עולה`,
    patientNameDesc: `שמות המטופלים ממוינים בסדר יורד`,
    patientRegistration: `רישום מטופל`,
    patients: `מטופלים`,
    patientsCount: (params: string[]) => `${params[0]} מטופלים`,
    patientsOverview: `סקירת מטופלים כללית`,
    pending: `ממתין`,
    percent: `%`,
    personalGoal: `יעד אישי`,
    personalGoalEdit: `יעד אישי`,
    personalPassword: `סיסמה אישית`,
    personalPasswordHelper: `נא לבחור סיסמה אישית עבורך. ניתן תמיד לשנות את סיסמתך שוב בתפריט ההגדרות.`,
    phoneError: `מספר טלפון לא תקין. נא להשתמש בספרות בלבד (ללא סוגריים, מקפים, +)`,
    phoneNumber: `מספר טלפון`,
    picture: `תמונה`,
    pictureInstructions: `נא לבחור את תמונת הפרופיל האישי שלך. בתמונה זו ייעשה שימוש עבור החשבון האישי שלך.`,
    pleaseConnect: `נא להתחבר לאינטרנט כדי לוודא שמבוצע שימוש בגרסה העדכנית של האפליקציה.`,
    pleaseContactYourHospital: `נא ליצור קשר ישירות עם בית החולים במקרה חירום.`,
    pleaseProvidePassword: `נא להזין את סיסמתך כדי לאשר פעולה זו:`,
    pm: `בערב`,
    pounds: `פאונדים`,
    preparation: `הכנות`,
    preSurgeryPrep: `הכנות לפני הניתוח`,
    previous: `הקודם`,
    privacyPolicy: `מדיניות הפרטיות`,
    profileLabel: `יבוצע שימוש בכך כדי לפנות אליך בדוא"ל, בהודעות טקסט, ובאפליקציה זו. כמו כן יועבר מידע זה לצוות הרפואי שלך.`,
    profilePicture: `תמונת פרופיל`,
    profileTitle: `יבוצע שימוש בכך כדי לפנות אליך בדוא"ל, בהודעות טקסט, ובאפליקציה זו. כמו כן יועבר מידע זה לצוות הרפואי שלך.`,
    progress: `התקדמות`,
    progressMsgForgotPwd: `מבצע אימות...`,
    progressMsgLoading: `טוען...`,
    progressMsgLoadingContent: `טוען תוכן...`,
    progressMsgLogin: `טוען מסלול טיפול,פעולה זו עשויה להימשך עד דקה אחת...`,
    progressMsgMdtLoading: `טוען צוות...`,
    progressMsgNotesLoading: `טוען הערות...`,
    progressMsgProfileEdit: `שומר פרופיל...`,
    progressMsgProfilePhoto: `שומר תמונה...`,
    progressMsgResetPwd: `שומר סיסמה...`,
    provideTheEmail: `נא לספק את כתובת הדוא"ל בה נרשמת בבית החולים.`,
    pwdValidationDoesNotMatch: `הסיסמאות שלך אינן תואמות`,
    pwdValidationIllegal: `מכילה תווים אסורים`,
    pwdValidationNotComplex: `לא עמדת בדרישות מורכבות הסיסמה`,
    pwdValidationTooShort: `הסיסמה שלך קצרה מדי`,
    quickFilter: `מסנן מהיר`,
    remindmeLater: `הזכר לי מאוחר יותר`,
    requiredFields: `שדות חובה`,
    requiredHCPs: `אנשי סגל רפואי *`,
    resetPassword: `אפס סיסמה`,
    respond: `כתיבת תגובה`,
    retry: `ביצוע ניסיון נוסף`,
    save: `שמירה`,
    saveAndContinue: `שמירה והמשך`,
    saveChanges: `שמירת שינויים`,
    scheduleNewAppointment: `קביעת מועד לפגישה חדשה`,
    searchInConversation: `חיפוש בשיחות...`,
    secureRealmError: `העלאה נכשלה - יש לאפשר נעילת מסך`,
    selectDifferentImage: `בחירת תמונה אחרת`,
    selectFile: `בחירת קובץ`,
    selectFunction: `בחירת פונקציה`,
    selectLanguage: `בחירת שפה`,
    selectOneOrMoreHCPs: `בחירת איש סגל רפואי אחד או יותר`,
    selectPictureSource: `בחירת תמונה מתוך`,
    selectProfilePicture: `בחירת תמונת פרופיל`,
    selectSurgeon: `בחירת מנתח`,
    send: `שליחה`,
    sendMessage: `שליחת הודעה`,
    sendNewMessage: `שליחת הודעה חדשה`,
    september: `ספטמבר`,
    setPassword: `הגדרת סיסמה`,
    setPasswordReminder: `ניתן תמיד לשנות את סיסמתך שוב בתפריט ההגדרות.`,
    settings: `הגדרות`,
    setup: `הגדרות`,
    setYourPersonalGoal: `הגדרת היעד האישי שלך`,
    someonesPathway: (params: string[]) => `מסלול הטיפול של ${params[0]}`,
    sortBy: `מיין על פי`,
    splashSubtitle: `ניתוח לירידה במשקל`,
    start: `התחל`,
    startANewConversation: `התחלת שיחה חדשה`,
    startConversation: `התחלת שיחה`,
    startingPoint: `נקודת התחלה`,
    startNewConversation: `+ התחלת שיחה חדשה`,
    startPreparation: `התחלת הכנותיך`,
    status: `סטטוס`,
    subject: `נושא`,
    subjectChangedSuccess: `נושא השיחה נערך בהצלחה`,
    subjectChangeFail: `נושא השיחה לא שונה`,
    submit: `שליחה`,
    subPhase: `תת-שלב`,
    successEditHcp: `ערכת בהצלחה את הפרופיל שלך`,
    surgeon: `מנתח`,
    surgeryInformation: `פרטי הניתוח`,
    tasks: `משימות`,
    tasksCompleted: `משימות שהושלמו`,
    team: `צוות`,
    thisMonth: `חודש זה`,
    time: `שעה`,
    timeAndLocation: `שעה ומיקום`,
    timeOfSurgery: `שעת הניתוח *`,
    to: `עד`,
    today: `היום`,
    toDo: `משימות`,
    undo: `בטל פעולה`,
    unitRequired: `יחידה *`,
    units: `יחידות מדידה`,
    unknown: `מעדיף לא להגיב`,
    unknownError: `חלה שגיאה בעת העיבוד. נא לנסות שוב...`,
    unknownGender: `מעדיף לא להגיב`,
    unknownUser: `לא ידוע`,
    unreadMessage: `הודעה שלא נקראה`,
    unreadMessages: `הודעות שלא נקראו`,
    untitled: `ללא כותרת...`,
    update: `ביצוע עידכון`,
    updateAppointment: `עריכת פגישה`,
    updateAppointmentButton: `שמירת שינויים ושליחת עדכונים`,
    updateAppointmentSuccess: `הפגישה עודכנה בהצלחה`,
    updateMessage: `עליך לעדכן אפליקציה זו לגרסה העדכנית ביותר בחנות האפליקציות על מנת להמשיך להשתמש בה`,
    updateProfilePicture: `יש לעדכן תמונת פרופיל`,
    updateProgress: `יש לעדכן התקדמות`,
    useCamera: `נא להשתמש במצלמה`,
    username: `שם משתמש`,
    video: `וידיאו`,
    viewAllMessages: `הצגת כל ההודעות`,
    viewAndEditPathway: `הצגת ועריכת תאריכי מסלול הטיפול`,
    viewDocument: `הצגת מסמך`,
    weight: `משקל`,
    weightLoss: `ירידה במשקל`,
    weightUpdatedSuccess: `המשקל הנוכחי עודכן בהצלחה`,
    welcomeHeader: `ברוך הבא`,
    welcomeMessage: (params: string[]) => `שלום ${params[0]}!`,
    wellDoneNextStep: `כל הכבוד! יש מוכנות שלך לעבור לשלב הבא!`,
    withdrawConfirm: `בסדר, צא מהאפליקציה`,
    withdrawConsent: `בטל הסכמה`,
    withdrawConsentBody: `באמצעות ביטול ההסכמה לעיבוד הנתונים האישיים שלך, הנתונים המקומיים שלך, כגון הערות ויעדים אישיים יימחקו, ולאחר תקופת המתנה של 30 ימים, לא יתאפשר עבורך עוד לגשת לאפליקציה.`,
    withdrawConsentTitle: `האם בודאות ברצונך לבטל את הצטרפותך לפלטפורמת Care4Today?`,
    writeAMessage: `נא לכתוב הודעה...`,
    writeSomething: `נא לכתוב מידע כלשהוא...`,
    wrongUserName: `שם המשתמש שהזנת אינו נכון`,
    xUnread: (params: string[]) => `${params[0]} לא נקרא`,
    yes: `כן`,
    yesDelete: `כן, ניתן למחוק`,
    yesDiscard: `כן, ניתן לבטל`,
    youAreOffline: `מצב לא מקוון`,
    youCanSetASentence: `אפשרי להגדיר משפט שידרבן אותך להגיע ליעדך האישי.`,
    youGained: (params: string[]) => `עלית ${params[0]}`,
    youGainedFormat: (params: string[]) => `עלית ${params[0]} ${params[1]}`,
    youHaveANewMessageFrom: (params: string[]) =>
        `יש לך הודעה חדשה מ-${params[0]}.`,
    youHaveNewAppointment: `יש לך פגישה חדשה. נא לפתוח את האפליקציה כדי לראות מה חדש.`,
    youHaveNewAppointments: (params: string[]) =>
        `יש לך ${
            params[0]
        } פגישות חדשות. נא לפתוח את האפליקציה כדי לראות מה חדש.`,
    youHaveNewMessage: `יש לך הודעה חדשה אחת. נא לפתוח את האפליקציה כדי לראות מה חדש.`,
    youHaveNewMessages: (params: string[]) =>
        `יש לך ${
            params[0]
        } הודעות חדשות. נא לפתוח את האפליקציה כדי לראות מה חדש.`,
    youHaveUndone: `ביטלת את האפשרות שבחרת קודם לכן`,
    youLost: (params: string[]) => `הורדת ${params[0]}`,
    youLostFormat: (params: string[]) => `הורדת ${params[0]} ${params[1]}`,
    yourAppointments: `הפגישות שלך`,
    yourGoals: `היעדים שלך`,
    yourNote: `ההערה שלך`,
    yourPassword: `הסיסמה שלך`,
    yourPasswordHasBeenReset: `סיסמתך אופסה`,
    yourProfile: `הפרופיל שלך`,
    export: `ייצוא`,
    exportData: `ייצוא נתונים אישיים`,
    exportDataFail: `חלה שגיאה. לא ניתן היה לייצא נתונים`,
    exportMyData: `ייצא את נתוניי האישיים`,
    goalStepCount: `יעד (צעדים/יום)`,
    loadingPathway: `טוען מסלול טיפול, פעולה זו עשויה להימשך עד דקה אחת...`,
    loadingPatient: `טוען מטופל, נא להמתין`,
    pleaseEnterTotalSteps: `נא להזין מספר צעדים כולל בסיומו של כל יום`,
    stepCount: `ספירת צעדים`,
    stepsPerDay: `צעדים/יום`,
    walkStepsPerDay: (params: string[]) => `יש ללכת ${params[0]} צעדים/יום`,
    steps: `צעדים`,
    avgWeeklySteps: `מספר צעדים ממוצע בשבוע זה`,
    rightToBeForgotten: `מחק את הנתונים האישיים שלי`,
    totalStepsDuringDay: `מספר הצעדים שנעשו במהלך יום`,
    youAlreadyWalked: (params: string[]) => `צעדת ${params[0]} צעדים היום`,
    rightToBeForgottenTitle: `האם בודאות ברצונך להתחיל במחיקת הנתונים האישיים שלך?`,
    rightToBeForgottenInfo: `בביצוע בקשה זו יימחקו הנתונים האישיים שלך ולא תהיה לך יותר אפשרות לגשת לאפליקציה. אנא שים לב כי חלק מהמידע האישי המוגבל, כגון שמך, שנשלח ממערכת המידע של בית החולים, עשוי להמשיך להופיע בפגישות.    לשאלות נוספות אנא צור קשר עם support@care4todaypatient.com.     אנא הזן את סיסמתך כדי לאשר פעולה זו:`,
    passwordHint: `הסיסמה שלך`,
    rightToBeForgottenSuccess: `בקשת מחיקת נתונים אישיים נשלחה אל תיבת דואר התמיכה של Care4Today`,
    incorrectPassword: `הוזנה סיסמה שגויה`,
    errorInitiatingRightToBeForgotten: `שגיאה בשליחת הבקשה, נא ליצור קשר ישירות עם התמיכה`,
    updateStepCount: `נא לעדכן ספירת צעדים`,
    mon: `שני`,
    tue: `שלישי`,
    wed: `רביעי`,
    thu: `חמישי`,
    fri: `שישי`,
    sat: `שבת`,
    sun: `ראשון`,
    stepsAmount: (params: string[]) => `${params[0]} צעדים`,
    stepsGoalUpdateSuccess: `ערך הצעדים נוסף בהצלחה`,
    search: `חפש...`,
    successEditMDT: `צוות עודכן בהצלחה`,
    failEditMDT: `חלה שגיאה בעת עדכון אנשי הצוות`,
    userCreationError: `חלה שגיאה בעת יצירת המשתמש`,
    userUpdateSuccess: `המשתמש עודכן בהצלחה`,
    legal: `משפטי`,
    termsOfUse: `תנאי שימוש`,
    disclaimer: `כתב ויתור`,
    exportDataSuccessV1: `בקשת ייצוא נתונים אישיים נשלחה אל צוות התמיכה של Care4Today`,
    exportDataSuccess: `ייצוא הנתונים האישיים החל`,
    dataFormatV1: `הנתונים האישיים שלך ייוצאו בפורמט קובץ CSV. הקובץ יישלח לכתובת הדוא"ל הרשומה שלך.`,
    dataFormat: `הנתונים האישיים שלך ייוצאו בפורמט קובץ JSON. הקובץ יישלח לכתובת הדוא"ל הרשומה שלך.`,
    viewAllMaterials: `הצגת כלל החומרים`,
    viewAllAppointments: `הצגת כלל הפגישות`,
    enjoyYourDay: `איחולי הנאה ליום החופשי שלך!`,
    motivateAlmost: `כמעט הגעת ליעד!`,
    startConversationHcp: `התחל שיחה עם חבר הצוות הרפואי`,
    andYou: `, אתה`,
    viewAllNotifications: `הצגת כלל ההתראות`,
    noInvitations: `אין הזמנות`,
    yourTimeline: `ציר הזמן שלך`,
    currentSubphase: `תת-שלב נוכחי`,
    updateWeight: `עידכון משקל נוכחי`,
    teamLoading: `הצוות נטען`,
    noMdt: `לא הוקצה צוות רפואי.`,
    teamDetails: `צפיה בפרטי הצוות`,
    showResolved: `הראה פתורים`,
    readDoc: `צפייה במסמך`,
    consultationNotes: `הערות ייעוץ`,
    viewAllConsultationNotes: `צפה בכלל הערות הייעוץ`,
    createNewNote: `+ יצירת הערה חדשה`,
    dismiss: `ביטול`,
    pictureError: `שגיאת טעינת תמונה`,
    wrongFormat: `פורמט תמונה שגוי`,
    backToDashboard: `חזרה ללוח מחוונים`,
    noMessage: `אין הודעות`,
    noSpecialCharacters: `אסור להשתמש בתווים מיוחדים.`,
    noNotesAvailable: `אין הערות זמינות`,
    hcpPortal: `פורטל הסגל הרפואי`,
    patientPortal: `פורטל מטופלים`,
    consultationNote: `הערת ייעוץ`,
    noteTitle: `כותרת ההערה`,
    noteContents: `תוכן ההערה`,
    writeConsultationNotes: `נא לכתוב הערות ייעוץ כאן`,
    createHcpNote: `יצירת הערה`,
    consultationNoteCreatedBy: (params: string[]) =>
        `נוצר: ${params[0]} על ידי ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `נערך לאחרונה: ${params[0]}`,
    loadingConsultaionNotes: `טוען הערות ייעוץ`,
    consultationNotesFor: (params: string[]) => `הערות ייעוץ עבור ${params[0]}`,
    editHcpNote: `עריכת הערה`,
    reason: `סיבה`,
    writeReasonForEditing: `נא לכתוב סיבה לעריכה...`,
    confirmCancelCreateNote: `האם בודאות ברצונך לצאת מבלי ליצור את ההערה?`,
    confirmCancelEditNote: `האם בודאות ברצונך לצאת מבלי לערוך את ההערה?`,
    rotateYourDevice: `נא לסובב את מכשירך`,
    patientId: `מספר זיהוי מטופל`,
    oldPassword: `סיסמה ישנה`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `מסמכים`,
    hcpId: `מספר זיהוי של חבר הצוות הרפואי`,
    userInactivity: `נותקת מהמערכת עקב חוסר פעילות.`,
    duplicateMrn: `מספר זיהוי איש סגל רפואי זה קיים כבר ב-Care4Today`,
    confirm: `אישור`,
    viewDetails: `הצגת פרטים`,
    upperCaseLetters: `אותיות גדולות`,
    lowerCaseLetters: `אותיות קטנות`,
    numbers: `מספרים`,
    specialCharacters: `תווים מיוחדים (סימני פיסוק, סמלים)`,
    passwordRequirements: `הסיסמה חייבת להכיל לפחות 8 תווים ולעמוד בשני קריטריוני מורכבות:`,
    incorrectOldPassword: `הסיסמה הישנה שגויה. חשבונך יינעל לאחר 5 ניסיונות כושלים`,
    newPasswordsNotSame: `הסיסמאות החדשות שהזנת אינן זהות`,
    passwordSuccesfullyChanged: `הסיסמה שונתה בהצלחה`,
    accountBlockedFifteenMinutes: `חשבונך ננעל. נא לנסות שוב בעוד 15 דקות`,
    loadingLegalDocuments: `טוען מסמכים משפטיים...`,
    fr: `צרפתית`,
    errorFetchingLegalDocuments: `שגיאה בטעינת מסמכים משפטיים...`,
    nameAndMrnNotFound: `לא ניתן למצוא את הצירוף של מספר זיהוי המטופל ושם המשפחה`,
    duplicateNameAndMrn: `מספר זיהוי המטופל כבר קיים ב-Care4Today`,
    NSCameraUsageDescription: `אפליקציה זו דורשת גישה למצלמה כדי להוסיף / לעדכן את תמונת הפרופיל וכדי לצרף קבצים לתוך ההערות`,
    NSPhotoLibraryUsageDescription: `אפליקציה זו דורשת גישה לספריית התמונות כדי לצרף קבצים להערות`,
    initiate: `התחל`,
    lastNameAsc: `שם משפחה ממוין בסדר עולה`,
    lastNameDesc: `שם משפחה ממוין בסדר יורד`,
    firstNameAsc: `שם פרטי ממוין בסדר עולה`,
    firstNameDesc: `שם פרטי ממוין בסדר יורד`,
    messageParticipantIsInactive: `אינו פעיל עוד`,
    participantNoLonger: `המשתתף אינו משתמש בפלטפורמה יותר`,
    requestDeletionInProgress: `בקשתך למחיקת הנתונים האישיים שלך מתבצעת כעת. צוות התמיכה יעדכן אותך בהקדם שתסתיים הפעולה`,
    contactNotAvailableOnDeactivated: `פרטי קשר אינם זמינים עבור חבר הצוות שאינו פעיל`,
    deactivated: `אינו פעיל`,
    noPermissionToSendMessage: `אין לך הרשאה לשלוח הודעות לאדם זה`,
    refrainSendingMedData: `נא להימנע ממשלוח הודעות המכילות נתונים רפואיים/מידע על המטופל`,
    refrainEnteringMedData: `נא להימנע מהזנת נתונים רפואיים/מידע על המטופל בשדה שלעיל`,
    contactHospitalAppointment: `נא ליצור קשר עם בית החולים אם ברצונך לעדכן או לבטל את הפגישה!`,
    noInfoDescriptionAppointment: `אין מידע זמין נוסף. נא ליצור קשר עם בית החולים במקרה של ספק, או אם יש לך שאלות כלשהן בנוגע לפגישה זו.`,
    noInfoDescriptionAndDateAppointment: `בקרוב יישלח עדכון המספק מידע נוסף על הפגישה. נא ליצור קשר עם בית החולים במקרה של ספק, או אם יש לך שאלות כלשהן בנוגע לפגישה זו.`,
    participants: `משתתפים`,
    noMdtAssigned: `לא הוקצה למטופל צוות רפואי. יש להקצות תחילה צוות למטופל.`,
    scheduled: `מתוכנן`,
    updated: `מעודכן`,
    proposed: `מוצע`,
    he: `עברית`,
    restrictProcessingPersonal: `הגבל עיבוד של הנתונים האישיים שלי`,
    restrictProcessingArticle: `בהתבסס על סעיף 18 של ה-GDPR (תקנות הפרטיות של האיחוד האירופאי), איזו מהסיבות הבאות רלוונטיות למצבכם?`,
    dataAccuracy: `מידע לא מדויק`,
    unlawfulProcessing: `עיבוד שלא כחוק`,
    legalClaim: `טענה משפטית`,
    provideExplanation: `אנא ספקו הסבר:`,
    provideExplanationDescription: `אנא ספקו הסבר כתוב המתאר את הבעיה שיסייע לנו בהערכת בקשתכם`,
    restrictProcessing: `הגבל עיבוד נתונים`,
    sureProcessing: `האם אתם בטוחים כי ברצונכם להגביל את עיבוד הנתונים האישיים שלכם?`,
    processingPasswordConfirmation: `בשליחת בקשה זו, המידע שלכם ייחסם באופן זמני, ואלא אם נודיע לכם אחרת, אנו נאחסן את הנתונים בלבד, ולא נמשיך לעבד אותם אלא אם נקבל את הסכמתכם. לשאלות נוספות אנא צרו קשר עם support@care4todaypatient.com. נא הזינו את סיסמתכם כדי לאשר פעולה זו`,
    processingSent: `בקשה להגבלת עיבוד נתוניכם האישיים נשלחה אל תיבת הדואר של התמיכה של Care4Today`,
    versionNumber: (params: string[]) => `גרסה ${params[0]}`,
    pleaseSelect: `אנא בחרו:`,
    restrictedLogout: `בשליחת בקשה זו, המידע שלכם ייחסם באופן זמני, אלא אם נודיע לכם אחרת, אנו נאחסן את הנתונים בלבד, ולא נמשיך לעבד אותם אלא אם נקבל את הסכמתכם. לשאלות נוספות אנא צרו קשר עם support@care4todaypatient.com. נא הזינו את סיסמתכם כדי לאשר פעולה זו`,
    restrictProcessingAlreadyRequested: `בקשתכם להגבלת עיבוד הנתונים האישיים שלכם מתבצעת כעת. צוות התמיכה יעדכן אתכם ברגע שתסתיים הפעולה.`,
    rightToRestrictQuestion: `בהתבסס על סעיף 18 של ה-GDPR (תקנות הפרטיות של האיחוד האירופאי), איזו מהסיבות הבאות רלוונטיות למצבכם?`,
    rightToRestrictExplanation: `אנא ספקו הסבר:`,
    rightToRestrictTitle: `הגבל עיבוד של הנתונים האישיים שלי`,
    rightToRestrictExplanationPlaceholder: `אנא ספקו הסבר כתוב המתאר את הבעיה שיסייע לנו בהערכת בקשתכם`,
    rightToRestrictConfirmationTitle: `האם אתם בטוחים כי ברצונכם להגביל את עיבוד הנתונים האישיים שלכם?`,
    rightToRestrictConfirmationDescription: `בקשתכם תישלח לצוות התמיכה. חשבונכם והנתונים שלכם ייחסמו באופן זמני, אלא אם נודיע לכם אחרת, נאחסן את הנתונים בלבד, ונמשיך לעבד אותם רק אם נקבל את הסכמתכם. לשאלות נוספות אנא צור קשר עם support@care4todaypatient.com`,
    assignedRole: (params: string[]) => `הועבר ל ${params[0]} - (לא פעיל)`,
    requestRestrictionSubmitted: `בקשה להגבלת עיבוד נתוניכם האישיים נשלחה אל תיבת הדואר של התמיכה של Care4Today`,
    temporarelyUnavailableHCPAlertMessage: `איש הצוות הרפואי אינו זמין כעת בפלטפורמה. במידה ויש שאלות, אנא צרו קשר עם צוות התמיכה.`,
    temporarelyUnavailableHCPSubtitle: `איש הצוות הרפואי אינו זמין כעת`,
    assignedHCP: (params: string[]) => `הועבר ל-${params[0]}`,
    inactive: `לא פעיל`,
    appointmentInvite: `יש לך תור חדש`,
    disabledAppointmentActionMessage: `אנא השתמש ישירות במערכת זימון התורים של בית החולים כדי לקבוע, לעדכן או לבטל תורים.`,
    noFurtherInformation: `אין מידע זמין נוסף`,
    cancelled: `בוטל`,
    cancelledNotificationPrefix: `הפגישה בוטלה:`,
    updatedNotificationPrefix: `הפגישה עודכנה:`,
    allDay: `כל היום`,
    editCareModule: `ערוך מודול טיפול`,
    nextSurgeryProcedureInformation: `הבא: פרטי ניתוח / הליך`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} כבר אינו חלק מהצוות הרפואי שלך`,
    editCareModuleWarning: `שים לב כי עם שינוי מודול הטיפול, כל היסטוריית המטרות וחומרי הלימוד מההליך הקודם לא תהיה זמינה יותר למטופל.`,
    editSurgeryWarning: `אנא עדכן את המידע על הניתוח במידה ויש צורך.`,
    nextUpdateMDT: `הבא: עדכן צוות רפואי`,
    updateCareModule: `עדכן מודול טיפול`,
    editMdtTeamWarning: `אנא בדוק את הצוות הרפואי כדי לראות אם נדרשים עדכונים.`,
    participantNotInMDT: `כבר אינך חלק מהצוות הרפואי של מטופל זה`,
    createMedicalTeam: `צור צוות רפואי`,
    editMedicalTeam: `ערוך צוות רפואי`,
    mdtName: `שם הצוות הרפואי`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `האם אתה בטוח שברצונך לשנות את מודול הטיפול של המטופל מ-'${
            params[0]
        }' ל-'${params[1]}'?`,
    changePathwayConfirmationSubTitle: `שים לב כי עם שינוי מודול הטיפול, כל היסטוריית המטרות וחומרי הלימוד מההליך הקודם כבר לא תהיה זמינה יותר למטופל`,
    changePathwaySuccessMessage: (params: string[]) =>
        `שינית בהצלחה את מודול הטיפול של המטופל y מ-'${params[0]}' ל-'${
            params[1]
        }'`,
    mdtChanged: `הצוות הרפואי שלך השתנה`,
    tapForDetails: `לחץ כאן לפרטים נוספים.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} שהוקצה כבר אינו חלק מהצוות הרפואי שלך`,
    addPatientReceivedConsent: `בכך שאני מוסר את הנתונים להלן, אני מצהיר כי קיבלתי את הסכמת המטופל לעבד את נתוני המטופל.`,
    attended: `הגיע לפגישה`,
    entityCreationError: (params: string[]) => `חלה שגיאה ביצירת ${params[0]}`,
    updateAppointmentError: `חלה שגיאה בעדכון הפגישה`,
    updateConsultationNoteError: `חלה שגיאה בעדכון הערת הייעוץ`,
    createConsultationNoteError: `חלה שגיאה ביצירת הערת הייעוץ`,
    missed: `לא הגיע`,
    contentDescCloseNotification: `סגור הודעה`,
    pathwayChanged: `מודול הטיפול שלך השתנה`,
    pathwayChangedDetails: (params: string[]) =>
        `מ-'${params[0]}' ל-'${
            params[1]
        }'. אנא צור קשר עם מתאם הטיפולים / איש הצוות הרפואי שלך למידע נוסף.`,
    de: `גרמנית`,
    doYouWantToDeletePatient: (params: string[]) =>
        `האם אתה בטוח שברצונך למחוק את מטופל ${params[0]}?`,
    personWillBeRemovedFromRecords: `אדם זה לא יוכל להתחבר לאפליקציית C4T ויוסר מהרשומות הדיגיטליות.`,
    provideDeletionReason: `אנא ספק סיבה למחיקה:`,
    deletionSuccess: (params: string[]) =>
        `מחקת בהצלחה את ${params[0]} מהפלטפורמה`,
    consentNotProvided: `טופס הסכמה לא אושר`,
    entryError: `שגיאת הזנת נתונים`,
    duplicatePatient: `כפל רשומות מטופל`,
    addExtraSecurity: `הגבר את רמת האבטחה של חשבונך ע"י אימות בשני שלבים`,
    mfaDescription: `בכל פעם שתתחבר לחשבונך ממכשיר חדש, תתבקש להזין קוד אבטחה. קוד אבטחה זה יישלח בדוא"ל או בטלפון.`,
    activateMfa: `הפעל אימות בשני שלבים`,
    userAccountNotActive: `חשבון המשתמש שלך אינו פעיל`,
    useHCPPortal: `אנא השתמש בפורטל המקוון לאנשי סגל רפואי במידה ושכחת את סיסמתך`,
    noPatientsAssigned: `לא הוקצו לך מטופלים.`,
    currentAppointments: `פגישות נוכחיות`,
    noCurrentAppointments: `לא קיימות פגישות עתידיות`,
    phase: `שלב`,
    noPhaseInformation: `לא קיים מידע על השלב`,
    noSubphaseInformation: `לא קיים מידע על שלב המשנה`,
    you: (params: string[]) => `${params[0]} (אתה)`,
    hcpsMedicalStaff: `צוות רפואי`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `ב-${params[0]} ‏(${params[1]})`,
    newMessage: `הודעה חדשה`,
    addParticipant: `הוסף משתתף`,
    editParticipant: `ערוך משתתף`,
    messagesFor: (params: string[]) => `הודעות ${params[0]}`,
    noParticipants: `לא קיימים משתתפים`,
    whichMfaMethod: `כיצד תרצה לקבל את קוד האבטחה?`,
    mfaMethodExplanation: `קוד אבטחה זה נדרש לקבלת גישה לחשבונך. תוכל לקבל את קוד ההתחברות לטלפון הנייד או לדוא"ל שלך. בחר בשיטה המתאימה לך ביותר.`,
    textMe: `שלחו לי קוד התחברות בהודעת טקסט`,
    emailMe: `שלחו לי קוד התחברות בדוא"ל`,
    textMeSubtitle: `תתבקש להזין את מספר הטלפון שלך`,
    emailMeSubtitle: `אנא אמת את כתובת הדוא"ל שלך`,
    backToMethod: `חזרה לבחירת שיטה`,
    addPhone: `הוסף מספר טלפון`,
    whichPhone: `לאיזה מספר טלפון תרצה לקבל את קוד האבטחה?`,
    phoneDisclaimer: `מספר טלפון זה ישמש רק לצורך אבטחת החשבון. ייתכנו חיובים בגין קבלת הודעות טקסט ושימוש בנתונים.`,
    sendCode: `שליחת קוד אבטחה`,
    confirmEmail: `אמת את כתובת הדוא"ל שלך`,
    whichEmail: `לאיזו כתובת דוא"ל תרצה לקבל את קוד האבטחה?`,
    emailDisclaimer: `כתובת דוא"ל זו תשמש רק לצורך אבטחת החשבון.`,
    insertCode: `אנא הזן את קוד האבטחה שלך`,
    mayTakeTwoMinutes: `שליחת הקוד עשויה להימשך עד שתי דקות.`,
    sentCodeByText: (params: string[]) =>
        `קוד האבטחה נשלח כעת בהודעת טקסט אל ${params[0]}`,
    sentCodeByEmail: (params: string[]) =>
        `קוד האבטחה נשלח כעת בדוא"ל אל ${params[0]}`,
    didntGetCode: `לא קיבלת קוד?`,
    resendCode: `קבלת קוד אבטחה חדש`,
    authenticate: `אימות`,
    verifyingCode: `מאמת קוד אבטחה`,
    mfaSuccess: `הצלחת! אימות בשני שלבים הופעל!`,
    mfaCodeRequired: `נדרש קוד התחברות לקבלת גישה לחשבונך.`,
    mfaMethodExplanationLogin: `קוד אבטחה זה נדרש לקבלת גישה לחשבונך. תוכל לקבל את קוד ההתחברות לטלפון הנייד או לדוא"ל שלך.`,
    contentDescMfaIcon: `סמל אימות בשני שלבים`,
    mfaSendCodeTo: (params: string[]) => `הקוד יישלח אל ${params[0]}`,
    continueLabel: `המשך`,
    authenticating: `מאמת`,
    mfaInvalidCode: `הקוד שהזנת אינו תקף. אנא נסה שוב.`,
    mfaUnableToVerifyPhoneNumber: `לא הצלחנו לאמת מספר טלפון זה. אנא נסה מספר טלפון אחר.`,
    mfaUnableToVerifyEmail: `לא הצלחנו לאמת כתובת דוא"ל זו. אנא נסה כתובת דוא"ל אחרת.`,
    sessionExpired: `פג תוקף החיבור שלך. אנא התחבר מחדש.`,
    passwordExpired: `פג תוקף סיסמתך. אנא שנה את סיסמתך.`,
    rightToBeForgottenInfoNonIntegrated: `בביצוע בקשה זו ימחקו הנתונים האישיים שלך ולא יתאפשר עוד עבורך לגשת לאפליקציה. לשאלות נוספות אנא צור קשר עם support@care4todaypatient.com. יש להזין את סיסמתך כדי לאשר פעולה זו:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `בקשתכם תישלח לצוות התמיכה. חשבונכם והנתונים שלכם ייחסמו באופן זמני, ואלא אם נודיע לכם אחרת, נאחסן את הנתונים בלבד, ונמשיך לעבד אותם רק אם נקבל את הסכמתכם. לשאלות נוספות אנא צור קשר עם support@care4todaypatient.com`,
    password_expired_message: `תוקף הסיסמה שלך פג ויש להחליפה כדי לגשת ל-C4T`,
    firstdayOftheWeek: `היום הראשון בשבוע`,
    dateformat: `תבנית תאריך`,
    selectDateFormat: `בחר תבנית תאריך`,
    selectDay: `בחר יום`,
    monday: `שני`,
    tuesday: `שלישי`,
    wednesday: `רביעי`,
    thursday: `חמישי`,
    friday: `שישי`,
    saturday: `שבת`,
    sunday: `ראשון`,
    manageTheAppointmentTemplates: `נהל את תבנית הפגישה`,
    prefillTemplatesFor: `תבניות מילוי מראש עבור`,
    appointmentTemplates: `תבניות פגישה`,
    backToTemplateTypes: `חזרה לסוגי תבניות`,
    addNewAppointmentTemplate: `הוספת תבנית פגישה חדשה`,
    caremoduleName: `שם מודול טיפול`,
    selectPathway: `בחר/י מסלול טיפול`,
    notShowInDropdownAfterDelete: `במידה ותבנית זו תימחק היא לא תופיע יותר בתפריט הנפתח`,
    messagesTemplates: `תבניות הודעות`,
    addNewMessageTemplate: `הוספת תבנית הודעה חדשה`,
    pathway: `מסלול טיפול`,
    template: `תבניות`,
    typesTwo: `2 סוגים`,
    scheduledAppointmentInDropdown: `במידה ותבנית זו תימחק היא לא תופיע עוד בשדות הנפתחים בזמן קביעת פגישה.`,
    manageTemplate: `נהל תבנית`,
    manageTheMessageTemplates: `נהל את תבנית ההודעה`,
    addMdt: `‎‏‎‏+ הוספת צוות רפואי חדש לפלטפורמה`,
    mdts: `צוותים רפואיים`,
    NameAsc: `שם בסדר עולה`,
    NameDesc: `שם בסדר יורד`,
    Teams: `צוותים`,
    MdtsName: `שם צוות רפואי`,
    managemdts: `נהל צוות רפואי`,
    members: `חברים`,
    editTeam: `ערוך צוות`,
    addANewMDTToThePlatform: `הוספת צוות רפואי חדש לפלטפורמה`,
    week: `שבוע`,
    month: `חודש`,
    year: `שנה`,
    total: `סך הכול`,
    dailyaverage: `ממוצע יומי`,
    nochartdata: `אין נתונים זמינים מהתרשים`,
    youCanOnlyAssignOneMDTAtATime: `ניתן להקצות צוות רפואי אחד בלבד בכל פעם`,
    noMoreOptionsAvailable: `אין אפשרויות זמינות נוספות`,
    mdt: `צוות רפואי`,
    relatingPatient: `צירוף מטופל`,
    nonrelatingPatient: `ללא צירוף מטופל`,
    sendMsgPatient: `שליחת הודעה חדשה למטופל`,
    expectedResponseTime: `זמן תגובה צפוי בין 3 ל-4 שעות`,
    walkedText: `הליכה`,
    walk: `הליכה`,
    mymedicalteam: `הצוות הרפואי שלי`,
    yesterday: `אתמול`,
    close: `סגור`,
    passwordUsedBefore: `נעשה שימוש בסיסמה החדשה בעבר ולא ניתן לעשות בה שימוש חוזר. אנא הזן/הזיני סיסמה אחרת.`,
    sendMessageTo: `שליחת הודעה אל`,
    message: `הודעה`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} הוסיף את ${params[1]} לשיחה`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} הסיר את ${params[1]} מהשיחה`,
    removedParticipant: `משתתף הוסר`,
    noMessagesSelected: `לא נבחרה הודעה`,
    noMessagesSelectedDesc: `בחר הודעה בצד שמאל של המסך, או התחל שיחה חדשה`,
    mfaMethodExplanationRegistration: `קוד אבטחה זה נדרש כדי להיכנס לחשבונך. תוכל לקבל את קוד הכניסה באמצעות הטלפון הנייד או הדוא"ל שלך. אנא בחר את שיטת האימות המתאימה ביותר עבורך.\n\nלתשומת לבך, תוכל לבחור רק שיטה אחת כעת. לאחר שבחרת, העדפותיך יישמרו ולא ניתן לשנות אותן מבלי ליצור קשר עם מוקד התמיכה.`,
    signinCodeRequired: `בקש קוד אבטחה`,
    securityCodeRequired: `קוד אבטחה זה נדרש כדי להיכנס לחשבונך. תוכל לקבל את קוד הכניסה באמצעות שיטת האימות שבחרת במהלך הרשמתך הראשונה.`,
    newMfaUserDesc1: `קוד אבטחה זה נדרש כדי להיכנס לחשבונך. תוכל לקבל את קוד הכניסה באמצעות הטלפון הנייד או הדוא"ל שלך. בחר את שיטת האימות המתאימה לך ביותר.`,
    newMfaUserDesc2: `שים לב, בשלב זה תוכל לבחור שיטת אימות אחת בלבד. לאחר שבחרת, העדפותיך יישמרו ולא ניתן לשנות אותן מבלי ליצור קשר עם מוקד התמיכה.`,
    feelFreeToMessageTeam: `באפשרותך להתחיל שיחה עם מישהו בצוותך כעת.`,
    noFutureMessages: `אין לך הודעות עדיין`,
    chatSelfRemove: `הסרת את עצמך מהשיחה בהצלחה`,
    noResultFound: `לא נמצאה כל תוצאה`,
    chatUpdated: `הצ'אט עודכן בהצלחה`,
    chatNotUpdated: `הצ'אט לא עודכן`,
    searchPlaceholder: `חיפוש תבנית...`,
    editPrefillTemplate: `עריכת תבנית מילוי מראש`,
    forAppointments: `עבור פגישות`,
    addTemplateToList: `הוספת תבנית לרשימה`,
    addNewPrefillTemplate: `הוספת תבנית מילוי מראש חדשה`,
    forMessages: `עבור הודעות`,
    editNewPrefillTemplate: `עריכת תבנית מילוי מראש חדשה`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
