export const LANG_DE_TRANS = {
    accept: `Zustimmen`,
    accepted: `Zugestimmt`,
    acceptedInvitation: `Sie haben diese Einladung angenommen.`,
    actions: `Aktionen`,
    addHcp: `Medizinisches Fachpersonal zur Plattform hinzufügen`,
    addHCPTag: `+ Medizinisches Fachpersonal`,
    addHcpToPlatform: `Der Plattform eine medizinische Fachkraft hinzufügen`,
    addNewHCP: `+ Der Plattform medizinisches Fachpersonal hinzufügen`,
    addNewPatient: `+ Der Plattform einen neuen Patienten hinzufügen`,
    addPatient: `Patienten hinzufügen`,
    addPatientConsent: `Hiermit bestätige ich, dass ich die Einwilligung des Patienten zur Eingabe der Patientendaten erhalten habe.`,
    addPatientToPlatform: `Patienten zur Plattform hinzufügen`,
    administration: `Verwaltung`,
    agreed: `Einverstanden`,
    allHcps: `Alle medizinischen Fachkräfte`,
    allowNotifications: `Sie haben Benachrichtigungen aktiviert, super!`,
    allPatients: `Alle Patienten`,
    almostHalfway: `Sie haben die Hälfte bereits geschafft!`,
    almostThere: `Sie sind fast da!`,
    am: `Uhr`,
    andMore: (params: string[]) => `und ${params[0]} mehr`,
    apiErrorGetConsentDocument: `Fehler beim Laden des Einwilligungsdokumentes. Tippen Sie hier, um es erneut zu versuchen`,
    appointment: `Termin`,
    appointmentAcceptedByPatient: `Vom Patienten akzeptiert`,
    appointmentAwaitingPatientResponse: `Warten auf Antwort vom Patienten`,
    appointmentDeclinedByPatient: `Vom Patienten abgelehnt`,
    appointmentName: `Termin Titel`,
    appointmentNotification: `Terminbenachrichtigung`,
    appointments: `Termine`,
    appointmentsForPatient: (params: string[]) => `Termine für ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `Ein Termin kann zwischen ${params[0]} und ${params[1]} geplant werden`,
    appUnavailable: `Es tut uns leid, die App ist derzeit nicht verfügbar. Bitte versuchen Sie es später erneut oder überprüfen Sie auf Updates.`,
    april: `April`,
    ar: `Arabisch`,
    areYouSureDeclineMessage: `Das klinische Team benötigt Ihre Teilnahme, um Sie bei der Vorbereitung und Überwachung Ihrer Fortschritte zu unterstützen. Bitte setzen Sie sich mit Ihrem Arzt in Verbindung, wenn Sie der Plattform nicht beitreten möchten`,
    areYouSureDeclineTitle: `Sind Sie sicher, dass Sie der Care4Today Plattform nicht beitreten möchten?`,
    areYouSureDeleteNote: `Möchten Sie diese Notiz wirklich löschen?`,
    article: `Artikel`,
    assignToMDT: `Zu MDT zuweisen`,
    audio: `Audio`,
    august: `August`,
    back: `Zurück`,
    backToAppointments: `Zurück zu Ihren Terminen`,
    backToDetails: (params: string[]) =>
        `Zurück zu den Details von ${params[0]}`,
    backToLogin: `Zurück zur Anmeldung`,
    backToPatientProfile: `Zurück zum Patientenprofil`,
    badPassword: `Sie haben ein ungültiges Kennwort eingegeben.`,
    bariatrics: `Bariatrie`,
    blockedUser: `Ihr Benutzer wurde gesperrt. Bitte versuchen Sie es in einer halben Stunde erneut.`,
    bmi: `BMI`,
    bookedSuccess: `Sie haben Ihren Termin erfolgreich gebucht`,
    cancel: `Abbrechen`,
    cancelAlert: `Abbrechen`,
    cantParseError: `Antwort kann nicht analysiert werden.`,
    cantSaveImage: `Bild konnte nicht gespeichert werden.`,
    care4Today: `Care4Today`,
    careModules: `Pflegemodule`,
    changePassword: `Passwort ändern`,
    changePasswordSubtitle: `Wählen Sie Ihr persönliches Kennwort.`,
    changePasswordTitle: `Bitte personalisieren Sie Ihr Kennwort`,
    choosePicture: `Bild auswählen`,
    chooseProfilePicture: `Bild ändern`,
    cm: `cm`,
    completed: `Abgeschlossen`,
    conditionalGoal: `Persönliches Ziel`,
    confirmAppointmentDelete: `Möchten Sie diesen Termin wirklich löschen?`,
    confirmed: `Bestätigt`,
    confirmNewPasswordPlaceholder: `Neues Kennwort bestätigen`,
    consent: `Zustimmung`,
    consentDontAgree: `Ich stimme nicht zu und werde die Care4Today-Plattform nicht verwenden`,
    consentedOn: (params: string[]) =>
        `Sie haben Ihre Zustimmung zu ${params[0]} gegeben`,
    contact: `Kontakt`,
    contactDetails: `Kontaktinformationen`,
    contactInfo: `KONTAKTINFORMATION`,
    contentDescApptIcon: `Termin-Symbol`,
    contentDescAttachImage: `Bild anhängen`,
    contentDescAttachment: `Anlagen`,
    contentDescAttachmentImg: `Vollbild`,
    contentDescBackground: `Hintergrund`,
    contentDescChangePwdIcon: `Kennwort-Symbol ändern`,
    contentDescClose: `Vollbild schließen`,
    contentDescDeleteAttachment: `Bildanhang löschen`,
    contentDescDevicesIcon: `Verbundene Geräte-Symbol`,
    contentDescEduContentExpandBtn: `Öffnen Sie den Anhang zum Schulungsinhalt`,
    contentDescEduContentThumb: `Anhang zum Schulungsinhalt`,
    contentDescEduItemCompleted: `Schulungselement ist abgeschlossen`,
    contentDescEduItemIncomplete: `Schulungselement ist nicht abgeschlossen`,
    contentDescGoalIcon: `Persönliches Ziel-Symbol`,
    contentDescHelpIcon: `Hilfe-Symbol`,
    contentDescKillswitchIcon: `Killswitch-Symbol`,
    contentDescLegalIcon: `Rechtliche Dokumente-Symbol`,
    contentDescLogo: `Anwendungslogo`,
    contentDescLogoutIcon: `Abmelden-Symbol`,
    contentDescMdtPic: `Bild der medizinischen Fachkraft`,
    contentDescMessageIcon: `Nachrichten-Symbol`,
    contentDescNoGoalIcon: `Kein Ziel-Symbol`,
    contentDescPathwayCurrent: `Aktuelle Phase-Symbol`,
    contentDescPathwayIcon: `Wege-Symbol`,
    contentDescPathwayOtherPhase: `Andere Phase-Symbol`,
    contentDescProfilePic: `Profilbild`,
    contentDescSend: `Senden`,
    create: `Erstellen`,
    createAMedicalTeam: `Ein Ärzteteam erstellen`,
    createAppointment: `Termin erstellen`,
    createAppointmentButton: `Termin erstellen und Einladung senden`,
    createAppointmentSuccess: `Termin erfolgreich angelegt`,
    createAppt: `Trmn erstellen`,
    createMDT: `MDT erstellen`,
    currentBmi: `Aktueller BMI`,
    currentPhase: `Aktuelle Phase`,
    currentWeight: `Aktuelles Gewicht`,
    dashboard: `Dashboard`,
    date: `Datum`,
    dateOfBirth: `Geburtsdatum`,
    dateOfConsent: `Datum der Zustimmung`,
    dateOfConsentAsc: `Datum der Zustimmung Aufst.`,
    dateOfConsentDesc: `Datum der Zustimmung Abst.`,
    dateOfSurgery: `Datum der Operation *`,
    december: `Dezember`,
    decline: `Ablehnen`,
    declined: `Abgelehnt`,
    declinedInvitation: `Sie haben diese Einladung abgelehnt.`,
    declinedNotifications: `Sie haben keine Benachrichtigungen zugelassen, sind Sie sicher? Sie können dies im Einstellungsmenü ändern.`,
    declinedSuccess: `Sie haben Ihren Termin abgelehnt`,
    defaultError: `Etwas ist schief gelaufen`,
    delete: `Löschen`,
    deleteAppointmentSuccess: `Termin erfolgreich gelöscht`,
    deleteNote: `Notiz löschen`,
    deleting: `Wird gelöscht ...`,
    description: `Beschreibung`,
    details: `Details`,
    devices: `Verbundene Geräte`,
    disagreeConsentError: `Es ist ein Fehler aufgetreten, während Sie die Einwilligung abgelehnt haben. Bitte versuchen Sie es erneut …`,
    discardChanges: `Änderungen verwerfen?`,
    document: `Dokument`,
    done: `Fertig`,
    draftWontBeSaved: `Ihr Entwurf wird nicht gespeichert. Möchten Sie trotzdem abbrechen?`,
    duplicateMDT: `Medizinische Fachkraft ist bereits ausgewählt`,
    edit: `Bearbeiten`,
    editHcpsProfile: `Medizinische Fachkraft-Profil bearbeiten`,
    editMessageDetails: `Gesprächsdetails bearbeiten`,
    editMTDTeam: (params: string[]) => `Team für ${params[0]} bearbeiten`,
    editPassword: `Kennwort bearbeiten`,
    editPatient: `Patienten bearbeiten`,
    editPatientError: `Es gab ein Problem bei der Aktualisierung der Patientendaten`,
    editPatientSuccess: `Patientendaten wurden erfolgreich aktualisiert.`,
    editProfile: `Profil bearbeiten`,
    editProfilePicture: `Profilbild bearbeiten`,
    editSubject: `Betreff bearbeiten`,
    editTeamMembers: `Teammitglieder bearbeiten`,
    editYourPersonalGoal: `Ihr persönliches Ziel festlegen`,
    eduContentHint: `Tippen Sie auf die Erweiterungsschaltfläche, um den angehängten Inhalt zu öffnen.`,
    email: `E-Mail-Adresse`,
    emailAddress: `E-Mail-Adresse`,
    emailConfirmation: (params: string[]) =>
        `Wir haben eine E-Mail mit einem Link zum Zurücksetzen Ihres Kennworts an ${
            params[0]
        } gesendet.`,
    emailExists: (params: string[]) =>
        `Ein Benutzer mit der E-Mail ${params[0]} ist bereits vorhanden.`,
    emailSent: `E-Mail gesendet`,
    en: `Englisch`,
    enableNotifications: `Benachrichtigungen aktivieren`,
    enterANewHCP: `Geben Sie eine neue Medizinische Fachkraft ein`,
    enterSubjectHint: `Betreff eingeben`,
    enterTheSubject: `Geben Sie den Betreff für dieses Gespräch ein.`,
    errorEditingHcp: `Beim Bearbeiten der Medizinischen Fachkraft ist ein Fehler aufgetreten`,
    errorFindingConsentDocument: `Fehler beim Finden des Einwilligungsdokumentes`,
    errorLoading: (params: string[]) => `Fehler beim Laden von ${params[0]}`,
    errorSavingSettings: `Fehler beim Speichern der Einstellungen`,
    errorUpdatingPassword: `Kennwort konnte nicht aktualisiert werden`,
    excessWeightLost: `Gewichtsabnahme`,
    failEditHcp: `Beim Bearbeiten Ihres Profils ist ein Fehler aufgetreten`,
    february: `Februar`,
    female: `Weiblich`,
    filter: `Filter`,
    firstName: `Vorname`,
    forgotPasswordInstruction: `Geben Sie die E-Mail-Adresse an, mit der Sie in Ihrem Krankenhaus registriert sind. Wir senden Ihnen eine E-Mail mit einem Link, um Ihr Kennwort zurückzusetzen.`,
    forgotPasswordViewTitle: `Kennwort vergessen`,
    forgotYourPassword: `Haben Sie Ihr Kennwort vergessen?`,
    formTimeRangeInPast: `Der Zeitbereich kann nicht in der Vergangenheit liegen`,
    formTimeRangeStartGreaterThanEnd: `Der Zeitbereich ist ungültig`,
    forPatient: `Für`,
    from: `Von`,
    ft: `Fuß`,
    fullName: `Vollständiger Name`,
    function: `Position`,
    gained: `zugenommen`,
    gender: `Geschlecht`,
    goal: `Ziel`,
    goalSavedError: `Das Ziel konnte nicht gespeichert werden!`,
    goalSavedSuccess: `Ziel erfolgreich gespeichert!`,
    goBack: `Gehe zurück`,
    hcps: `HCPs`,
    healthCareProfessionals: (params: string[]) =>
        `${params[0]} Medizinische Fachkräfte`,
    height: `Körpergröße`,
    help: `Hilfe`,
    heyChooseYourPicture: (params: string[]) =>
        `Hallo ${params[0]}, wählen Sie Ihr Profilbild`,
    iAgree: `Ich stimme zu`,
    iAgreeFormat: (params: string[]) =>
        `Ich stimme zu (${params[0]}/${params[1]})`,
    iAmSure: `Ich bin mir sicher`,
    idealBodyWeight: `Ideales Körpergewicht`,
    iDoNotAgree: `Ich stimme nicht zu`,
    iDontAgree: `Ich stimme nicht zu und werde die Care4Today-Plattform nicht verwenden`,
    imperial: `Imperial`,
    in: `Zoll`,
    includeLinkToLocation: `Link zum Standort einschließen`,
    initialWeight: `Ursprüngliches Gewicht`,
    installUpdate: `Update installieren`,
    invalidEmailError: `Keine gültige E-Mail`,
    invalidNumber: `Geben Sie bitte eine gültige Zahl ein`,
    invalidTokenError: `Authentifizierung nicht möglich. Bitte melden Sie sich erneut an.`,
    it: `Italienisch`,
    iWantToFitAgain: `Beispiel: „Ich will wieder in Größe L passen“`,
    january: `Januar`,
    july: `Juli`,
    june: `Juni`,
    keepGoing: `Weiter so!`,
    keepMomentum: `Weiter so!`,
    kg: `kg`,
    kilogrammes: `Kilogramm`,
    language: `Sprache`,
    languageRequired: `Sprache *`,
    lastName: `Nachname`,
    lb: `Pfund`,
    learningMaterials: `Lernmaterialien`,
    legalDocuments: `Rechtliche Dokumente`,
    loading: `Wird geladen …`,
    loadingPatients: `Patienten werden geladen, bitte warten Sie`,
    location: `Standort`,
    locationUrl: `Standort-URL`,
    lockScreenHint: `Sie müssen einen Gerätesperrbildschirm einrichten, um die sichere Verwendung der App zu ermöglichen.`,
    login: `Anmelden`,
    loginIncorrect: `E-Mail oder Kennwort sind falsch`,
    logout: `Abmelden`,
    logoutAreYouSure: `Möchten Sie sich wirklich abmelden?`,
    loseBefore: (params: string[]) => `${params[0]} abnehmen`,
    loseFormat: (params: string[]) => `${params[0]} ${params[1]} abnehmen`,
    lost: `abgenommen`,
    male: `Männlich`,
    manageHCPs: `Medizinische Fachkräfte verwalten`,
    managePatients: `Patienten verwalten`,
    march: `März`,
    may: `Mai`,
    mdtTeam: `MDT-Team`,
    mdtTeamNotAddedYet: `MDT noch nicht zugewiesen`,
    mdtTeamUC: `MDT-TEAM`,
    medicalTeam: `Ärzteteam`,
    meetingInvite: `Sie haben eine Besprechung`,
    meetingInviteWith: (params: string[]) => `Besprechung mit ${params[0]}`,
    messageCreated: `Sie haben erfolgreich ein Gespräch begonnen.`,
    messageNotCreated: `Sie haben kein Gespräch begonnen.`,
    messageNotification: `Benachrichtigung über Nachricht`,
    messageNotSent: `Nachricht nicht gesendet`,
    messages: `Nachrichten`,
    metric: `Metrisch`,
    movePhaseConfirmation: (params: string[]) =>
        `Sind Sie sicher, dass Sie ${params[0]} in die Phase ${
            params[1]
        } verschieben möchten`,
    moveToNextPhase: `Zur nächsten Phase verschieben`,
    multiDisTeam: `Multidisziplinäre Teams (MDT)`,
    myMessages: `Meine Nachrichten`,
    myMotivation: `Meine Motivation:`,
    myPersonalGoal: `Mein persönliches Ziel`,
    myProfile: `Mein Profil`,
    myTeam: `Mein Team`,
    name: `Name`,
    nameOfMDT: `Name des MDT *`,
    needsConsent: `Der Patient sollte zuerst die Einwilligungserklärung annehmen.`,
    networkError: `Ein Netzwerkfehler ist aufgetreten`,
    newAppointment: `Neuer Termin`,
    newChat: `Neuer Chat`,
    newInvitation: `Neue Einladung`,
    newMessageNotificationMore: (params: string[]) =>
        `Sie haben ${
            params[0]
        } neue Nachrichten. Öffnen Sie die App, um zu erfahren, was neu ist.`,
    newMessageNotificationOne: `Sie haben eine neue Nachricht. Öffnen Sie die App, um zu erfahren, was neu ist.`,
    newNote: `Neue Notiz`,
    newPasswordPlaceholder: `Neues Kennwort`,
    newPatientSuccess: (params: string[]) =>
        `Sie haben erfolgreich ${params[0]} zur Plattform hinzugefügt.`,
    newTeamFail: `MDT-Team nicht zugewiesen`,
    newTeamSuccess: `MDT-Team zugewiesen`,
    newVersionApp: `Aktualisieren Sie diese App mit der neuesten Version, die im App Store verfügbar ist.`,
    nextAppointment: `Nächster Termin`,
    nextSelectCareModule: `Weiter: Pflegemodule auswählen`,
    nextSurgeryInformation: `Weiter: OP-Informationen`,
    niceToSeeYouAgain: `Schön, dass Sie wieder da sind!`,
    nickname: `Spitzname`,
    nicknameError: `Ungültiger Spitzname Sonderzeichen sind nicht erlaubt.`,
    nl: `Niederländisch`,
    no: `Nein`,
    noAppointments: `Es sind keine Termine verfügbar`,
    noCurrentGoalForPatient: `Mit diesem Patienten ist kein aktuelles Ziel verbunden`,
    noDate: `Kein Datum eingestellt`,
    noFutureAppointments: `Anstehende Termine`,
    noGoalSet: `Kein Ziel von Ihrer Medizinischen Fachkraft festgelegt`,
    noMatchingConsentDocumentsFound: `Keine übereinstimmenden Einwilligungsdokumente gefunden`,
    noMessages: `Es sind keine Nachrichten verfügbar`,
    noNetworkConnection: `Keine Netzwerkverbindung verfügbar. Bitte prüfen …`,
    noNotesMessage: `Es sind keine Notizen verfügbar.\nTippen Sie auf 'Erstellen', um neue Notizen hinzuzufügen`,
    noPersonalGoalSet: `Kein persönliches Ziel gesetzt.`,
    noPersonalGoalSetDashboard: `Kein persönliches Ziel gesetzt. Gehen Sie zur Einstellungsseite, um es zu aktualisieren.`,
    noPlannedAppointments: `Keine geplanten Termine`,
    noPreview: `Keine Vorschau vorhanden`,
    noProgressRecorded: `Kein Fortschritt aufgezeichnet`,
    noResponseError: `Keine Antwort erhalten.`,
    notAgreed: `Nicht zugestimmt`,
    noteDeletedError: `Die Notiz konnte nicht gelöscht werden!`,
    noteDeletedSuccessfully: `Notiz erfolgreich gelöscht!`,
    notes: `Notizen`,
    noteSaved: `Notiz gespeichert`,
    noteSavedError: `Die Notiz konnte nicht gespeichert werden!`,
    noteSavedSuccess: `Notiz erfolgreich gespeichert!`,
    noteSaveError: `Fehler, Notiz kann nicht gespeichert werden. Erneut versuchen?`,
    notifications: `Benachrichtigungen`,
    notNow: `Nicht jetzt`,
    notSet: `Nicht eingestellt`,
    notYetSubmitted: `Noch nicht abgesendet`,
    noUnreadMessages: `Keine ungelesenen Nachrichten`,
    noUserFound: `Fehler beim Suchen des Benutzers mit den angegebenen Anmeldeinformationen.`,
    november: `November`,
    noWeightDifference: `Kein Gewichtsunterschied`,
    october: `Oktober`,
    ok: `OK`,
    onboardingNotificationsTitle: `Wir möchten Sie jedes Mal auf dem Laufenden halten`,
    onboardingNotifictionsInfo: `Sie werden informiert über:\n\n• Ihre Termine\n• Neue Nachrichten von Ihrem Ärzteteam`,
    onVar: (params: string[]) => `auf ${params[0]}`,
    openCare: `Bitte öffnen Sie care4today und prüfen Sie, ob Sie neue Benachrichtigungen haben!`,
    optOutSubtitle: `Bitte wenden Sie sich an Ihren überweisenden Arzt, wenn Sie der Plattform nicht beitreten möchten.`,
    optOutTitle: `Sind Sie sicher, dass Sie nicht an der Care4Today-Plattform teilnehmen möchten?`,
    organisation: `Organisation`,
    orthopedics: `Orthopädie`,
    other: `Sonstiges`,
    outdatedVersion: `Sie verwenden derzeit eine veraltete Version der App.`,
    overview: `Übersicht`,
    participant: `Teilnehmer`,
    password: `Kennwort`,
    passwordComplexityError: `Das Kennwort sollte mindestens 8 Zeichen lang sein und mindestens zwei der folgenden Arten von Zeichen enthalten: Großbuchstaben, Kleinbuchstaben, Zahlen oder Symbole.`,
    passwordMismatchError: `Kennwörter stimmen nicht überein`,
    passwordUpdated: `Kennwort aktualisiert`,
    pastAppointments: `Vergangene Termine`,
    pathwayScheduleFail: `Ein Fehler ist aufgetreten. Der Verlaufsplan konnte nicht aktualisiert werden`,
    patient: `Patient`,
    patientAge: (params: string[]) => `${params[0]} Jahre`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} Jahre`,
    patientConsent: `Einwilligung des Patienten`,
    patientNameAsc: `Patientenname Abst.`,
    patientNameDesc: `Patientenname Aufst.`,
    patientRegistration: `Patientenregistrierung`,
    patients: `Patienten`,
    patientsCount: (params: string[]) => `${params[0]} Patienten`,
    patientsOverview: `Patientenübersicht`,
    pending: `Ausstehend`,
    percent: `%`,
    personalGoal: `Persönliches Ziel`,
    personalGoalEdit: `Persönliches Ziel`,
    personalPassword: `Persönliches Kennwort`,
    personalPasswordHelper: `Bitte wählen Sie Ihr eigenes, persönliches Kennwort. Sie können Ihr Kennwort jederzeit im Einstellungsmenü ändern.`,
    phoneError: `Ungültige Telefonnummer. Bitte nur Zahlen verwenden (keine Klammern, Bindestriche, +)`,
    phoneNumber: `Telefonnummer`,
    picture: `Bild`,
    pictureInstructions: `Bitte wählen Sie Ihr persönliches Profilbild. Dieses Bild wird für Ihr eigenes Konto verwendet.`,
    pleaseConnect: `Stellen Sie eine Verbindung zum Internet her, um sicherzustellen, dass Sie die neueste Version der App verwenden.`,
    pleaseContactYourHospital: `Bitte wenden Sie sich im Notfall direkt an Ihr Krankenhaus.`,
    pleaseProvidePassword: `Bitte geben Sie Ihr Kennwort ein, um diese Aktion zu bestätigen:`,
    pm: `Uhr`,
    pounds: `Pfund`,
    preparation: `Vorbereitung`,
    preSurgeryPrep: `Vorbereitung vor der OP`,
    previous: `Zurück`,
    privacyPolicy: `Datenschutzrichtlinie`,
    profileLabel: `Wir werden dies verwenden, um Sie in E-Mails, SMS und dieser App anzusprechen. Diese Informationen geben wir auch an Ihr Ärzteteam weiter.`,
    profilePicture: `Profilbild`,
    profileTitle: `Wir werden dies verwenden, um Sie in E-Mails, SMS und dieser App anzusprechen. Diese Informationen geben wir auch an Ihr Ärzteteam weiter.`,
    progress: `Fortschritt`,
    progressMsgForgotPwd: `Validierung …`,
    progressMsgLoading: `Wird geladen …`,
    progressMsgLoadingContent: `Inhalt wird geladen …`,
    progressMsgLogin: `Pfad laden, \nDies kann bis zu 1 Minute dauern …`,
    progressMsgMdtLoading: `MDT laden …`,
    progressMsgNotesLoading: `Notizen werden geladen …`,
    progressMsgProfileEdit: `Profil speichern …`,
    progressMsgProfilePhoto: `Foto speichern …`,
    progressMsgResetPwd: `Kennwort speichern …`,
    provideTheEmail: `Geben Sie die E-Mail-Adresse an, mit der Sie im Krankenhaus registriert sind.`,
    pwdValidationDoesNotMatch: `Kennwörter stimmen nicht überein`,
    pwdValidationIllegal: `Enthält unzulässige Zeichen`,
    pwdValidationNotComplex: `Anforderung an Kennwortkomplexität wurde nicht erfüllt`,
    pwdValidationTooShort: `Ihr Kennwort ist zu kurz`,
    quickFilter: `Schnellfilter`,
    remindmeLater: `Später erinnern`,
    requiredFields: `Benötigte Felder`,
    requiredHCPs: `Medizinische Fachkräfte*`,
    resetPassword: `Kennwort zurücksetzen`,
    respond: `Antworten`,
    retry: `Wiederholen`,
    save: `Speichern`,
    saveAndContinue: `Speichern und fortfahren`,
    saveChanges: `Änderungen speichern`,
    scheduleNewAppointment: `Neuen Termin vereinbaren`,
    searchInConversation: `In Gesprächen suchen ...`,
    secureRealmError: `Starten fehlgeschlagen - Sperrbildschirm muss aktiviert sein`,
    selectDifferentImage: `Wählen Sie ein anderes Bild aus`,
    selectFile: `Datei aussuchen`,
    selectFunction: `Funktion auswählen`,
    selectLanguage: `Sprache auswählen`,
    selectOneOrMoreHCPs: `Wählen Sie eine oder mehrere Medizinische Fachkräfte aus`,
    selectPictureSource: `Bild auswählen aus`,
    selectProfilePicture: `Ein Profilbild auswählen`,
    selectSurgeon: `Chirurg auswählen`,
    send: `Senden`,
    sendMessage: `Nachricht senden`,
    sendNewMessage: `Eine neue Nachricht senden`,
    september: `September`,
    setPassword: `Kennwort einstellen`,
    setPasswordReminder: `Sie können Ihr Kennwort jederzeit im Einstellungsmenü ändern.`,
    settings: `Einstellungen`,
    setup: `KONFIGURATION`,
    setYourPersonalGoal: `Legen Sie Ihr persönliches Ziel fest`,
    someonesPathway: (params: string[]) => `Der Weg von ${params[0]}`,
    sortBy: `Sortieren nach`,
    splashSubtitle: `Adipositas-Chirurgie`,
    start: `Start`,
    startANewConversation: `Ein neues Gespräch beginnen`,
    startConversation: `Gespräch beginnen`,
    startingPoint: `Startgewicht`,
    startNewConversation: `+ Neues Gespräch beginnen.`,
    startPreparation: `Beginnen Sie mit Ihrer Vorbereitung`,
    status: `Status`,
    subject: `Betreff`,
    subjectChangedSuccess: `Betreff des Gesprächs erfolgreich bearbeitet`,
    subjectChangeFail: `Betreff des Gesprächs wurde nicht geändert`,
    submit: `Senden`,
    subPhase: `SubPhase`,
    successEditHcp: `Sie haben Ihr Profil erfolgreich bearbeitet`,
    surgeon: `Chirurg`,
    surgeryInformation: `OP-Informationen`,
    tasks: `Aufgaben`,
    tasksCompleted: `Aufgaben abgeschlossen`,
    team: `Team`,
    thisMonth: `Aktueller Monat`,
    time: `Uhrzeit`,
    timeAndLocation: `Zeit und Ort`,
    timeOfSurgery: `OP-Zeit *`,
    to: `Bis`,
    today: `Heute`,
    toDo: `Aufgaben`,
    undo: `Rückgängig machen`,
    unitRequired: `Einheit *`,
    units: `Einheiten`,
    unknown: `Möchte dazu nichts sagen`,
    unknownError: `Bei der Verarbeitung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut …`,
    unknownGender: `Ich möchte nicht antworten`,
    unknownUser: `Unbekannt`,
    unreadMessage: `Ungelesene Nachricht`,
    unreadMessages: `Ungelesene Nachrichten`,
    untitled: `Ohne Titel ...`,
    update: `Update`,
    updateAppointment: `Termin bearbeiten`,
    updateAppointmentButton: `Änderungen speichern und Aktualisierungen senden`,
    updateAppointmentSuccess: `Termin erfolgreich aktualisiert`,
    updateMessage: `Sie müssen diese App vom App Store auf die neueste Version aktualisieren, um die App weiterhin verwenden zu können`,
    updateProfilePicture: `Profilbild aktualisieren`,
    updateProgress: `Aktualisierungsfortschritt`,
    useCamera: `Kamera verwenden`,
    username: `Benutzername`,
    video: `Video`,
    viewAllMessages: `Alle Nachrichten anzeigen`,
    viewAndEditPathway: `Anzeigen und Bearbeiten von Pfaddaten`,
    viewDocument: `Dokument anzeigen`,
    weight: `Gewicht`,
    weightLoss: `Gewichtsverlust`,
    weightUpdatedSuccess: `Das aktuelle Gewicht wurde erfolgreich aktualisiert`,
    welcomeHeader: `Willkommen`,
    welcomeMessage: (params: string[]) => `Hallo ${params[0]}!`,
    wellDoneNextStep: `Gut gemacht! Sie sind bereit, zum nächsten Schritt überzugehen!`,
    withdrawConfirm: `OK, App verlassen`,
    withdrawConsent: `Einwilligung zurückziehen`,
    withdrawConsentBody: `Wenn Sie die Einwilligung zur Verarbeitung Ihrer personenbezogenen Daten widerrufen, werden Ihre lokalen Daten wie Notizen und persönliche Ziele gelöscht, und nach einer Frist von 30 Tagen können Sie nicht mehr auf die Anwendung zugreifen.`,
    withdrawConsentTitle: `Möchten Sie sich wirklich von der Care4Today-Plattform abmelden?`,
    writeAMessage: `Eine Nachricht schreiben ...`,
    writeSomething: `Schreiben Sie etwas …`,
    wrongUserName: `Der eingegebene Benutzername ist falsch`,
    xUnread: (params: string[]) => `${params[0]} ungelesen`,
    yes: `Ja`,
    yesDelete: `Ja, löschen`,
    yesDiscard: `Ja, verwerfen`,
    youAreOffline: `Sie sind offline`,
    youCanSetASentence: `Sie können einen Satz festlegen, um sich zu motivieren, Ihr persönliches Ziel zu erreichen.`,
    youGained: (params: string[]) => `Sie haben ${params[0]} zugenommen`,
    youGainedFormat: (params: string[]) =>
        `Sie haben ${params[0]} ${params[1]} zugenommen`,
    youHaveANewMessageFrom: (params: string[]) =>
        `Sie haben eine neue Nachricht von ${params[0]}.`,
    youHaveNewAppointment: `Sie haben einen neuen Termin. Öffnen Sie die App, um zu erfahren, was neu ist.`,
    youHaveNewAppointments: (params: string[]) =>
        `Sie haben ${
            params[0]
        } neue Termine. Öffnen Sie die App, um zu erfahren, was neu ist.`,
    youHaveNewMessage: `Sie haben eine neue Nachricht. Öffnen Sie die App, um zu erfahren, was neu ist.`,
    youHaveNewMessages: (params: string[]) =>
        `Sie haben ${
            params[0]
        } neue Nachrichten. Öffnen Sie die App, um zu erfahren, was neu ist.`,
    youHaveUndone: `Sie haben Ihre zuvor gewählte Option rückgängig gemacht`,
    youLost: (params: string[]) => `Sie haben ${params[0]} abgenommen`,
    youLostFormat: (params: string[]) =>
        `Sie haben ${params[0]} ${params[1]} abgenommen`,
    yourAppointments: `Ihre Termine`,
    yourGoals: `Ihre Ziele`,
    yourNote: `Ihre Notiz`,
    yourPassword: `Ihr Kennwort`,
    yourPasswordHasBeenReset: `Ihr Kennwort wurde zurückgesetzt`,
    yourProfile: `Ihr Profil`,
    export: `Exportieren`,
    exportData: `Persönliche Daten exportieren`,
    exportDataFail: `Ein Fehler ist aufgetreten. Daten konnten nicht exportiert werden`,
    exportMyData: `Meine persönlichen Daten exportieren`,
    goalStepCount: `Ziel (Schritte/Tag)`,
    loadingPathway: `Pfad wird geladen, dies kann bis zu 1 Minute dauern`,
    loadingPatient: `Patient wird geladen, bitte warten`,
    pleaseEnterTotalSteps: `Bitte geben Sie die Gesamtzahl der Schritte am Ende eines jeden Tages ein`,
    stepCount: `Schrittzahl`,
    stepsPerDay: `Schritte/Tag`,
    walkStepsPerDay: (params: string[]) =>
        `Gehen Sie ${params[0]} Schritte/Tag`,
    steps: `Schritte`,
    avgWeeklySteps: `Durchschn. Schritte diese Woche`,
    rightToBeForgotten: `Meine persönlichen Daten löschen`,
    totalStepsDuringDay: `Gesamtschritte während eines Tages`,
    youAlreadyWalked: (params: string[]) =>
        `Sie sind heute ${params[0]} Schritte gegangen`,
    rightToBeForgottenTitle: `Möchten Sie die Löschung Ihrer persönlichen Daten wirklich einleiten?`,
    rightToBeForgottenInfo: `Durch Einleitung dieser Anfrage werden Ihre persönlichen Daten gelöscht und Sie können nicht mehr auf die Anwendung zugreifen. Bitte beachten Sie, dass einige eingeschränkte persönliche Informationen, wie Ihr Name, die vom Krankenhausinformationssystem gesendet werden, möglicherweise weiterhin in den Terminen angezeigt werden.  Für weitere Fragen wenden Sie sich bitte an support@care4todaypatient.com.  Bitte geben Sie Ihr Kennwort ein, um diese Aktion zu bestätigen:`,
    passwordHint: `Ihr Kennwort`,
    rightToBeForgottenSuccess: `Die Anforderung zum Löschen persönlicher Daten wurde an die Support-E-Mail von Care4Today gesendet`,
    incorrectPassword: `Falsches Kennwort eingegeben`,
    errorInitiatingRightToBeForgotten: `Fehler beim Senden der Anfrage, wenden Sie sich direkt an den Support`,
    updateStepCount: `Schrittanzahl aktualisieren`,
    mon: `Mo`,
    tue: `Di`,
    wed: `Mi`,
    thu: `Do`,
    fri: `Fr`,
    sat: `Sa`,
    sun: `So`,
    stepsAmount: (params: string[]) => `${params[0]} Schritte`,
    stepsGoalUpdateSuccess: `Schrittwert wurde erfolgreich hinzugefügt`,
    search: `Suchen ...`,
    successEditMDT: `MDT wurde erfolgreich aktualisiert`,
    failEditMDT: `Beim Aktualisieren von MDT ist ein Fehler aufgetreten`,
    userCreationError: `Beim Erstellen des Benutzers ist ein Fehler aufgetreten`,
    userUpdateSuccess: `Benutzer wurde erfolgreich aktualisiert`,
    legal: `Rechtliches`,
    termsOfUse: `Nutzungsbedingungen`,
    disclaimer: `Haftungsausschluss`,
    exportDataSuccessV1: `Die Anfrage zum Export persönlicher Daten wurde an das Care4Today-Supportteam gesendet`,
    exportDataSuccess: `Der Export persönlicher Daten wurde eingeleitet`,
    dataFormatV1: `Ihre persönlichen Daten werden im CSV-Dateiformat exportiert. Die Datei wird an Ihre registrierte E-Mail-Adresse gesendet.`,
    dataFormat: `Ihre persönlichen Daten werden im JSON-Dateiformat exportiert. Die Datei wird an Ihre registrierte E-Mail-Adresse gesendet.`,
    viewAllMaterials: `Alle Materialien anzeigen`,
    viewAllAppointments: `Alle Termine anzeigen`,
    enjoyYourDay: `Genießen Sie Ihren freien Tag!`,
    motivateAlmost: `Sie sind fast da!`,
    startConversationHcp: `Starten Sie ein Gespräch mit einer Medizinischen Fachkraft`,
    andYou: `, Sie`,
    viewAllNotifications: `Alle Benachrichtigungen anzeigen`,
    noInvitations: `Keine Einladungen`,
    yourTimeline: `Ihre Zeitlinie`,
    currentSubphase: `Aktuelle Phase`,
    updateWeight: `Aktuelles Gewicht aktualisieren`,
    teamLoading: `Team wird geladen`,
    noMdt: `Kein MDT zugewiesen.`,
    teamDetails: `Teamdetails anzeigen`,
    showResolved: `Gelöste anzeigen`,
    readDoc: `Dokument lesen`,
    consultationNotes: `Konsultationshinweise`,
    viewAllConsultationNotes: `Alle Konsultationshinweise anzeigen`,
    createNewNote: `+ Neue Notiz erstellen`,
    dismiss: `Verlassen`,
    pictureError: `Fehler beim Laden des Bildes`,
    wrongFormat: `Falsches Bildformat`,
    backToDashboard: `Zurück zum Dashboard`,
    noMessage: `Keine Nachrichten`,
    noSpecialCharacters: `Sonderzeichen sind nicht erlaubt.`,
    noNotesAvailable: `Keine Notizen vorhanden`,
    hcpPortal: `Medizinische Fachkraft-Portal`,
    patientPortal: `Patienten-Portal`,
    consultationNote: `Konsultationshinweis`,
    noteTitle: `Notiz-Titel`,
    noteContents: `Notiz-Inhalt`,
    writeConsultationNotes: `Schreiben Sie hier Konsultationsnotizen`,
    createHcpNote: `Notiz erstellen`,
    consultationNoteCreatedBy: (params: string[]) =>
        `Erstellt: ${params[0]} durch ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `Zuletzt bearbeitet: ${params[0]}`,
    loadingConsultaionNotes: `Konsultationshinweise laden`,
    consultationNotesFor: (params: string[]) =>
        `Konsultationshinweise für ${params[0]}`,
    editHcpNote: `Notiz bearbeiten`,
    reason: `Grund`,
    writeReasonForEditing: `Grund für die Bearbeitung schreiben ...`,
    confirmCancelCreateNote: `Möchten Sie den Vorgang wirklich beenden, ohne die Notiz zu erstellen?`,
    confirmCancelEditNote: `Möchten Sie den Vorgang wirklich beenden, ohne die Notiz zu bearbeiten?`,
    rotateYourDevice: `Drehen Sie Ihr Gerät`,
    patientId: `Patienten-ID`,
    oldPassword: `Altes Kennwort`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `Dokumente`,
    hcpId: `Medizinische Fachkraft-ID`,
    userInactivity: `Sie wurden aufgrund von Inaktivität abgemeldet.`,
    duplicateMrn: `Diese Medizinische Fachkraft-ID existiert bereits in Care4Today`,
    confirm: `Bestätigen`,
    viewDetails: `Details anzeigen`,
    upperCaseLetters: `Großbuchstaben`,
    lowerCaseLetters: `Kleinbuchstaben`,
    numbers: `Zahlen`,
    specialCharacters: `Sonderzeichen (Satzzeichen, Symbole)`,
    passwordRequirements: `Das Kennwort muss mindestens 8 Zeichen lang sein und zwei Komplexitätskriterien erfüllen:`,
    incorrectOldPassword: `Das alte Kennwort ist falsch. Ihr Konto wird nach 5 fehlgeschlagenen Versuchen gesperrt`,
    newPasswordsNotSame: `Die neuen Kennwörter sind nicht identisch`,
    passwordSuccesfullyChanged: `Kennwort erfolgreich geändert`,
    accountBlockedFifteenMinutes: `Ihr Konto ist gesperrt. Bitte versuchen Sie es nach 15 Minuten erneut`,
    loadingLegalDocuments: `Legale Dokumente werden geladen ...`,
    fr: `Französisch`,
    errorFetchingLegalDocuments: `Fehler beim Laden der rechtlichen Dokumente`,
    nameAndMrnNotFound: `Die Kombination aus Patienten-ID und Nachnamen konnte nicht gefunden werden`,
    duplicateNameAndMrn: `Die Patienten-ID ist bereits in Care4Today vorhanden`,
    NSCameraUsageDescription: `Diese App erfordert Zugriff auf die Kamera, um das Profilbild hinzuzufügen/zu aktualisieren und Anhänge zu den Notizen hinzuzufügen`,
    NSPhotoLibraryUsageDescription: `Diese App erfordert Zugriff auf die Foto-Galerie, um Notizen Anhänge hinzuzufügen`,
    initiate: `Start`,
    lastNameAsc: `Nachname aufsteigend`,
    lastNameDesc: `Nachname absteigend`,
    firstNameAsc: `Vorname aufsteigend`,
    firstNameDesc: `Vorname absteigend`,
    messageParticipantIsInactive: `ist nicht mehr aktiv`,
    participantNoLonger: `Der Teilnehmer ist kein Benutzer der Plattform mehr.`,
    requestDeletionInProgress: `Ihre Anfrage auf Entfernung persönlicher Daten ist bereits in Bearbeitung. Das Support Team wird Sie informieren, sobald der Prozess beendet ist.`,
    contactNotAvailableOnDeactivated: `Kontaktdaten für deaktivierte HCP nicht verfügbar.`,
    deactivated: `Deaktiviert`,
    noPermissionToSendMessage: `Sie sind nicht berechtigt, dieser Person eine Nachricht zukommen zu lassen.`,
    refrainSendingMedData: `Bitte sehen Sie davon ab, Nachrichten zu senden, die medizinische Daten oder Patienteninformationen enthalten.`,
    refrainEnteringMedData: `Bitte sehen Sie davon ab, im obenstehenden Feld medizinische oder Patientendaten einzutragen.`,
    contactHospitalAppointment: `Bitte wenden Sie sich direkt an das Krankenhaus, wenn Sie Ihren Termin verschieben oder stornieren müssen.`,
    noInfoDescriptionAppointment: `Keine weiteren Informationen verfügbar. Bitte wenden Sie sich direkt an das Krankenhaus, wenn Sie Fragen zu Ihrem Termin haben.`,
    noInfoDescriptionAndDateAppointment: `In Kürze erhalten Sie ein Update mit weiteren Informationen zu Ihrem Termin. Bitte wenden Sie sich direkt an das Krankenhaus, wenn Sie Fragen zu Ihrem Termin haben.`,
    participants: `Teilnehmer`,
    noMdtAssigned: `Dem Patienten ist kein multidisziplinäres Team zugeordnet. Bitte ordnen Sie dem Patienten zuerst ein Team zu.`,
    scheduled: `Geplant`,
    updated: `Aktualisiert`,
    proposed: `Vorgeschlagen`,
    he: `Hebräisch`,
    restrictProcessingPersonal: `Einschränkung der Verarbeitung meiner persönlichen Daten`,
    restrictProcessingArticle: `Welche der folgenden Aussagen trifft bezüglich Artikel 18 der DSGVO auf Ihre Situation zu?`,
    dataAccuracy: `Datengenauigkeit`,
    unlawfulProcessing: `Unrechtmäßige Verarbeitung`,
    legalClaim: `Rechtsanspruch`,
    provideExplanation: `Bitte geben Sie eine Erläuterung an:`,
    provideExplanationDescription: `Bitte geben Sie einen erläuternden Text an, um das Problem zu beschreiben und die Bewertung Ihrer Anfrage zu unterstützen`,
    restrictProcessing: `Einschränkung der Verarbeitung`,
    sureProcessing: `Möchten Sie die Verarbeitung Ihrer persönlichen Daten wirklich einschränken?`,
    processingPasswordConfirmation: `Wenn Sie diese Anfrage einleiten, werden Ihre Daten vorübergehend deaktiviert. Wenn wir Sie nicht anderweitig informieren, werden wir die Daten nur speichern und sie nur dann weiter verarbeiten, wenn wir Ihre Zustimmung erhalten. Für weitere Fragen oder zur Aufhebung der Einschränkung wenden Sie sich bitte an support@care4todaypatient.com. Bitte geben Sie Ihr Kennwort ein, um diese Aktion zu bestätigen:`,
    processingSent: `Die Anfrage zur Einschränkung der Verarbeitung Ihrer personenbezogenen Daten wurde an die Support-E-Mail von Care4Today gesendet`,
    versionNumber: (params: string[]) => `Version ${params[0]}`,
    pleaseSelect: `Bitte wählen Sie:`,
    restrictedLogout: `Sie wurden abgemeldet, weil Ihre Anfrage zur Einschränkung der Verarbeitung personenbezogener Daten bearbeitet wurde und Ihr Care4Today-Konto eingeschränkt wurde. Bei Fragen wenden Sie sich bitte an support@care4todaypatient.com`,
    restrictProcessingAlreadyRequested: `Ihre Anfrage auf Entfernung persönlicher Daten ist bereits in Bearbeitung. Das Support Team wird Sie informieren, sobald der Prozess abgeschlossen ist.`,
    rightToRestrictQuestion: `Welche der folgenden Aussagen trifft bezüglich Artikel 18 der DSGVO auf Ihre Situation zu?`,
    rightToRestrictExplanation: `Bitte geben Sie eine Erläuterung an:`,
    rightToRestrictTitle: `Einschränkung der Verarbeitung meiner persönlichen Daten`,
    rightToRestrictExplanationPlaceholder: `Bitte geben Sie einen erläuternden Text an, um das Problem zu beschreiben und die Bewertung Ihrer Anfrage zu unterstützen.`,
    rightToRestrictConfirmationTitle: `Möchten Sie die Verarbeitung Ihrer persönlichen Daten wirklich einschränken?`,
    rightToRestrictConfirmationDescription: `Ihre Anfrage wird an das Support-Team gesendet. Ihr Konto und Ihre Daten werden vorübergehend deaktiviert. Wenn wir Sie nicht anderweitig informieren, werden wir die Daten nur speichern und sie nur dann weiter verarbeiten, wenn wir Ihre Zustimmung erhalten. Bitte beachten Sie, dass einige eingeschränkte persönliche Informationen, wie Ihr Name, die vom Krankenhausinformationssystem gesendet werden, möglicherweise weiterhin in den Terminen angezeigt werden.  Für weitere Fragen oder zur Aufhebung der Einschränkung wenden Sie sich bitte an support@care4todaypatient.com.  Bitte geben Sie Ihr Kennwort ein, um diese Aktion zu bestätigen:`,
    assignedRole: (params: string[]) => `Zugewiesene ${params[0]} (inaktiv)`,
    requestRestrictionSubmitted: `Die Anfrage zur Einschränkung der Verarbeitung Ihrer personenbezogenen Daten wurde an die Support-E-Mail von Care4Today gesendet`,
    temporarelyUnavailableHCPAlertMessage: `Das Medizinische Fachkraft ist auf der Plattform vorübergehend nicht verfügbar. Bei weiteren Fragen wenden Sie sich bitte an das Support-Team.`,
    temporarelyUnavailableHCPSubtitle: `Die Medizinische Fachkraft ist vorübergehend nicht verfügbar`,
    assignedHCP: (params: string[]) => `Zugewiesene ${params[0]}`,
    inactive: `Inaktiv`,
    appointmentInvite: `Sie haben einen Termin`,
    disabledAppointmentActionMessage: `Bitte nutzen Sie das Krankenhaus-Terminbuchungssystem direkt, um einen Termin zu planen, zu aktualisieren oder abzusagen.`,
    noFurtherInformation: `Keine weiteren Informationen verfügbar`,
    cancelled: `Abgesagt`,
    cancelledNotificationPrefix: `Abgesagt:`,
    updatedNotificationPrefix: `Aktualisiert:`,
    allDay: `Den ganzen Tag`,
    editCareModule: `Pflegemodul bearbeiten`,
    nextSurgeryProcedureInformation: `Weiter: Details zur Operation/zum Eingriff`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} ist nicht mehr Teil Ihres\nmultidisziplinären Teams`,
    editCareModuleWarning: `Bitte beachten Sie, dass bei einem Wechsel des Pflegemoduls der gesamte Verlauf der Ziele und Lernmaterialien aus dem vorherigen Verfahren für den Patienten nicht mehr verfügbar ist.`,
    editSurgeryWarning: `Bitte passen Sie ggf. die OP-Informationen an.`,
    nextUpdateMDT: `Weiter: Ärzteteam aktualisieren`,
    updateCareModule: `Pflegemodul aktualisieren`,
    editMdtTeamWarning: `Bitte überprüfen Sie das multidisziplinäre Team, um zu sehen, ob Aktualisierungen erforderlich sind.`,
    participantNotInMDT: `Sie sind für diesen Patienten nicht mehr Teil des MDT-Teams`,
    createMedicalTeam: `Ärzteteam erstellen`,
    editMedicalTeam: `Ärzteteam bearbeiten`,
    mdtName: `Name des MDT`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `Möchten Sie wirklich das Behandlungsmodul dieses Patienten von „${
            params[0]
        }“ auf „${params[1]}“ ändern?`,
    changePathwayConfirmationSubTitle: `Bitte beachten Sie, dass bei einem Wechsel des Pflegemoduls der gesamte Verlauf der Ziele und Lernmaterialien aus dem vorherigen Verfahren für den Patienten nicht mehr verfügbar ist`,
    changePathwaySuccessMessage: (params: string[]) =>
        `Sie haben das Patienten-${params[2]}-Pflegemodul erfolgreich von „${
            params[0]
        }“ auf „${params[1]}“ geändert.`,
    mdtChanged: `Ihr Ärzteteam hat sich geändert`,
    tapForDetails: `Tippen Sie hier, um weitere Informationen zu erhalten.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `Zugewiesene ${
            params[0]
        } ist nicht mehr Teil Ihres multidisziplinären Teams`,
    addPatientReceivedConsent: `Durch die Angabe der folgenden Informationen erkläre ich, dass ich die Einwilligung des Patienten zur Verarbeitung der Patientendaten erhalten habe.`,
    attended: `Teilgenommen`,
    entityCreationError: (params: string[]) =>
        `Beim Erstellen von ${params[0]} ist ein Fehler aufgetreten`,
    updateAppointmentError: `Beim Aktualisieren des Termins ist ein Fehler aufgetreten`,
    updateConsultationNoteError: `Beim Aktualisieren der Konsultationsnotiz ist ein Fehler aufgetreten`,
    createConsultationNoteError: `Beim Erstellen der Konsultationsnotiz ist ein Fehler aufgetreten`,
    missed: `Versäumt`,
    contentDescCloseNotification: `Benachrichtigung schließen`,
    pathwayChanged: `Ihr Pflegemodul hat sich`,
    pathwayChangedDetails: (params: string[]) =>
        `von „${params[0]}“ zu „${
            params[1]
        }“ geändert. Bitte kontaktieren Sie Ihren Versorgungskoordinatoren / Ihre medizinische Fachkraft für weitere Informationen.`,
    de: `Deutsch`,
    doYouWantToDeletePatient: (params: string[]) =>
        `Möchten Sie den Patienten ${params[0]} wirklich löschen?`,
    personWillBeRemovedFromRecords: `Diese Person ist nicht imstande, sich bei der C4T-App anzumelden und wird aus den digitalen Aufzeichnungen gelöscht.`,
    provideDeletionReason: `Bitte geben Sie einen Grund für die Löschung an:`,
    deletionSuccess: (params: string[]) =>
        `Sie haben ${params[0]} erfolgreich von der Plattform gelöscht`,
    consentNotProvided: `Zustimmung wurde nicht erteilt`,
    entryError: `Eingabefehler`,
    duplicatePatient: `Doppelt vorhandener Patient`,
    addExtraSecurity: `Machen Sie Ihr Konto mit einer zweistufigen Verifizierung besonders sicher`,
    mfaDescription: `Jedes Mal, wenn Sie sich bei Ihrem Konto anmelden, werden Sie aufgefordert, einen Sicherheitscode einzugeben. Diesen Sicherheitscode erhalten Sie per E-Mail oder Telefon.`,
    activateMfa: `Zweistufige Verifizierung aktivieren`,
    userAccountNotActive: `Ihr Benutzerkonto ist nicht aktiv`,
    useHCPPortal: `Nutzen Sie bitte das Online-HCP-Portal, falls Sie Ihr Passwort vergessen haben`,
    noPatientsAssigned: `Ihnen ist kein Patient zugeordnet.`,
    currentAppointments: `Aktuelle Termine`,
    noCurrentAppointments: `Es sind keine zukünftigen Termine verfügbar`,
    phase: `Phase`,
    noPhaseInformation: `Keine Phasen-Angaben`,
    noSubphaseInformation: `Keine Unterphasen-Angaben`,
    you: (params: string[]) => `${params[0]} (Sie)`,
    hcpsMedicalStaff: `HCPs`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `in ${params[0]} (${params[1]})`,
    newMessage: `Neue Nachricht`,
    addParticipant: `Teilnehmer hinzufügen`,
    editParticipant: `Teilnehmer bearbeiten`,
    messagesFor: (params: string[]) => `Nachrichten ${params[0]}`,
    noParticipants: `Keine Teilnehmer vorhanden`,
    whichMfaMethod: `Wie möchten Sie den Sicherheitscode erhalten?`,
    mfaMethodExplanation: `Dieser Sicherheitscode ist erforderlich, um auf Ihr Konto zugreifen zu können. Sie können den Anmeldecode über Ihr Mobiltelefon oder Ihre E-Mail-Adresse abrufen. Wählen Sie die für Sie am besten geeignete Methode.`,
    textMe: `Senden Sie mir einen Anmeldecode per SMS`,
    emailMe: `Senden Sie mir einen Anmeldecode per E-Mail`,
    textMeSubtitle: `Wir werden Sie nach Ihrer Telefonnummer fragen`,
    emailMeSubtitle: `Bitte bestätigen Sie die E-Mail-Adresse`,
    backToMethod: `Zurück zur Auswahl der Methode`,
    addPhone: `Fügen Sie eine Telefonnummer hinzu`,
    whichPhone: `Über welche Telefonnummer möchten Sie den Sicherheitscode erhalten?`,
    phoneDisclaimer: `Diese Telefonnummer wird nur für die Kontosicherheit verwendet. Es können Kosten für SMS und Datennutzung anfallen.`,
    sendCode: `Sicherheitscode senden`,
    confirmEmail: `Bestätigen Sie Ihre E-Mail`,
    whichEmail: `Über welche E-Mail-Adresse möchten Sie den Sicherheitscode erhalten?`,
    emailDisclaimer: `Diese E-Mail-Adresse wird nur zur Kontosicherheit verwendet.`,
    insertCode: `Bitte geben Sie Ihren Sicherheitscode ein`,
    mayTakeTwoMinutes: `Es kann bis zu zwei Minuten dauern, bis Sie Ihren Code erhalten.`,
    sentCodeByText: (params: string[]) =>
        `Wir haben gerade den Sicherheitscode per SMS an ${params[0]} gesendet`,
    sentCodeByEmail: (params: string[]) =>
        `Wir haben gerade den Sicherheitscode per E-Mail an ${
            params[0]
        } gesendet`,
    didntGetCode: `Haben Sie keinen Code erhalten?`,
    resendCode: `Sicherheitscode erneut senden`,
    authenticate: `Authentifizieren`,
    verifyingCode: `Sicherheitscode überprüfen`,
    mfaSuccess: `Es hat geklappt! Die zweistufige Authentifizierung ist aktiviert!`,
    mfaCodeRequired: `Für den Zugriff auf Ihr Konto ist ein Anmeldecode erforderlich.`,
    mfaMethodExplanationLogin: `Dieser Sicherheitscode ist erforderlich, um auf Ihr Konto zugreifen zu können. Sie können den Anmeldecode über Ihr Mobiltelefon oder Ihre E-Mail-Adresse abrufen.`,
    contentDescMfaIcon: `Symbol Zweistufige-Authentifizierung`,
    mfaSendCodeTo: (params: string[]) =>
        `Wir werden den Code an ${params[0]} senden`,
    continueLabel: `Weiter`,
    authenticating: `Authentifizierung`,
    mfaInvalidCode: `Der eingegebene Code ist ungültig. Bitte versuchen Sie es erneut.`,
    mfaUnableToVerifyPhoneNumber: `Wir können diese Telefonnummer nicht bestätigen. Bitte versuchen Sie es mit einem anderen.`,
    mfaUnableToVerifyEmail: `Wir können diese E-Mail-Adresse nicht bestätigen. Bitte versuchen Sie es mit einem anderen.`,
    sessionExpired: `Ihre Sitzung ist abgelaufen. Bitte melden Sie sich wieder an.`,
    passwordExpired: `Ihr Kennwort ist abgelaufen. Bitte ändern Sie Ihr Kennwort.`,
    rightToBeForgottenInfoNonIntegrated: `Durch Einleitung dieser Anfrage werden Ihre persönlichen Daten gelöscht und Sie können nicht mehr auf die Anwendung zugreifen. Für weitere Fragen wenden Sie sich bitte an support@care4todaypatient.com. Bitte geben Sie Ihr Kennwort ein, um diese Aktion zu bestätigen:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `Ihre Anfrage wird an das Support-Team gesendet. Ihr Konto und Ihre Daten werden vorübergehend deaktiviert. Wenn wir Sie nicht anderweitig informieren, werden wir die Daten nur speichern und sie nur dann weiter verarbeiten, wenn wir Ihre Zustimmung erhalten. Für weitere Fragen oder zur Aufhebung der Einschränkung wenden Sie sich bitte an support@care4todaypatient.com`,
    password_expired_message: `Das Passwort ist abgelaufen und muss geändert werden, um auf C4T zuzugreifen`,
    firstdayOftheWeek: `Erster Tag der Woche`,
    dateformat: `Datumsformat`,
    selectDateFormat: `Datumsformat auswählen`,
    selectDay: `Tag auswählen`,
    monday: `Montag`,
    tuesday: `Dienstag`,
    wednesday: `Mittwoch`,
    thursday: `Donnerstag`,
    friday: `Freitag`,
    saturday: `Samstag`,
    sunday: `Sonntag`,
    manageTheAppointmentTemplates: `Verwalten der Terminvorlage`,
    prefillTemplatesFor: `Vorausgefüllte Vorlage für`,
    appointmentTemplates: `Terminvorlagen`,
    backToTemplateTypes: `Zurück zu Vorlagentypen`,
    addNewAppointmentTemplate: `Neue Terminvorlage hinzufügen`,
    caremoduleName: `Name des Behandlungsmoduls`,
    selectPathway: `Wählen Sie einen Behandlungspfad`,
    notShowInDropdownAfterDelete: `Wenn Sie diese Vorlage löschen, wird sie nicht mehr in der Dropdown-Liste angezeigt`,
    messagesTemplates: `Vorlagen für Nachrichten`,
    addNewMessageTemplate: `Neue Nachrichtenvorlage hinzufügen`,
    pathway: `Behandlungspfad`,
    template: `Vorlagen`,
    typesTwo: `2 Typen`,
    scheduledAppointmentInDropdown: `Durch das Löschen dieser Vorlage wird sie bei der Planung eines Termins nicht mehr in den Dropdown-Feldern angezeigt.`,
    manageTemplate: `Vorlage verwalten`,
    manageTheMessageTemplates: `Verwalten der Nachrichtenvorlage`,
    addMdt: `+ Hinzufügen eines neuen MDT zur Plattform`,
    mdts: `MDTs`,
    NameAsc: `Name Asc`,
    NameDesc: `Name Desc`,
    Teams: `Teams`,
    MdtsName: `MDTs Name`,
    managemdts: `MDTs verwalten`,
    members: `Mtiglieder`,
    editTeam: `Team bearbeiten`,
    addANewMDTToThePlatform: `Hinzufügen eines neuen MDT zur Plattform`,
    week: `Woche`,
    month: `Monat`,
    year: `Jahr`,
    total: `Gesamt`,
    dailyaverage: `Täglicher Durchschnitt`,
    nochartdata: `Keine Diagrammdaten verfügbar`,
    youCanOnlyAssignOneMDTAtATime: `Sie können jeweils nur eine MDT zuweisen und lokalisieren`,
    noMoreOptionsAvailable: `Keine weiteren Optionen verfügbar`,
    mdt: `MDT`,
    relatingPatient: `Zuordnung eines Patienten`,
    nonrelatingPatient: `Keine Zuordnung eines Patienten`,
    sendMsgPatient: `Neue Nachricht an Patienten senden`,
    expectedResponseTime: `Erwartete Reaktionszeit zwischen 3 bis 4 Stunden`,
    walkedText: `ging`,
    walk: `laufen`,
    mymedicalteam: `Mein Ärzteteam`,
    yesterday: `Gestern`,
    close: `Schließen`,
    passwordUsedBefore: `Das neue Passwort wurde bereits verwendet und kann nicht wiederverwendet werden. Bitte geben Sie ein anderes Passwort ein.`,
    sendMessageTo: `Nachricht senden an`,
    message: `Nachricht`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} hat ${params[1]} zur Unterhaltung hinzugefügt`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} hat ${params[1]} aus der Unterhaltung entfernt`,
    removedParticipant: `Entfernter Teilnehmer`,
    noMessagesSelected: `Sie haben keine Nachricht ausgewählt`,
    noMessagesSelectedDesc: `Wählen Sie auf der linken Seite des Bildschirms eine Nachricht aus oder beginnen Sie eine neue Unterhaltung`,
    mfaMethodExplanationRegistration: `Dieser Sicherheitscode ist erforderlich, damit Sie auf Ihr Konto zugreifen können. Sie können den Code zur Anmeldung über Ihr Mobiltelefon oder Ihre E-Mail erhalten. Bitte wählen Sie die für Sie am besten geeignete Methode.\n\nBitte beachten Sie, dass Sie zu diesem Zeitpunkt nur eine Methode zur Verifizierung wählen können. Sobald Sie Ihre Wahl getroffen haben, wird Ihre Präferenz gespeichert und kann nicht geändert werden, ohne den Help Desk zu kontaktieren.`,
    signinCodeRequired: `Sicherheitscode anfordern`,
    securityCodeRequired: `Dieser Sicherheitscode ist erforderlich, damit Sie auf Ihr Konto zugreifen können. Sie können den Code zur Anmeldung erhalten, indem Sie die Methode anwenden, die sie bei Ihrer ersten Registrierung gewählt haben.`,
    newMfaUserDesc1: `Dieser Sicherheitscode ist erforderlich, damit Sie auf Ihr Konto zugreifen können. Sie können den Code zur Anmeldung über Ihr Mobiltelefon oder Ihre E-Mail erhalten. Bitte wählen Sie die für Sie am besten geeignete Methode.`,
    newMfaUserDesc2: `Bitte beachten Sie, dass Sie zu diesem Zeitpunkt nur eine Methode zur Verifizierung wählen können. Sobald Sie Ihre Wahl getroffen haben, wird Ihre Präferenz gespeichert und kann nicht geändert werden, ohne den Help Desk zu kontaktieren.`,
    feelFreeToMessageTeam: `Beginnen Sie eine Unterhaltung mit jemandem aus Ihrem Team.`,
    noFutureMessages: `Sie haben noch keine Nachrichten`,
    chatSelfRemove: `Sie haben sich erfolgreich aus der Unterhaltung entfernt`,
    noResultFound: `Kein Ergebnis gefunden`,
    chatUpdated: `Chat wurde erfolgreich aktualisiert`,
    chatNotUpdated: `Chat wurde nicht aktualisiert`,
    searchPlaceholder: `Nach einer Vorlage suchen …`,
    editPrefillTemplate: `Vorausgefüllte Vorlage bearbeiten`,
    forAppointments: `Für Termine`,
    addTemplateToList: `Vorlage zur Liste hinzufügen`,
    addNewPrefillTemplate: `Neue vorausgefüllte Vorlage hinzufügen`,
    forMessages: `Für Nachrichten`,
    editNewPrefillTemplate: `Neue vorausgefüllte Vorlage bearbeiten`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
