export const LANG_IT_TRANS = {
    accept: `Accetto`,
    accepted: `Accettato`,
    acceptedInvitation: `Hai accettato questo invito.`,
    actions: `Azioni`,
    addHcp: `Aggiungi operatore sanitario alla piattaforma`,
    addHCPTag: `+ Operatore sanitario`,
    addHcpToPlatform: `Aggiungi un operatore sanitario alla piattaforma`,
    addNewHCP: `+ Aggiungi un nuovo operatore sanitario alla piattaforma`,
    addNewPatient: `+ Aggiungi un nuovo paziente alla piattaforma`,
    addPatient: `Aggiungi paziente`,
    addPatientConsent: `Confermo di aver ricevuto il consenso da parte del paziente per l’inserimento dei suoi dati.`,
    addPatientToPlatform: `Aggiungi paziente alla piattaforma`,
    administration: `Amministrazione`,
    agreed: `Concordato`,
    allHcps: `Tutti gli operatori sanitari`,
    allowNotifications: `Ottimo, ha abilitato le notifiche.`,
    allPatients: `Tutti i pazienti`,
    almostHalfway: `Sei quasi a metà.`,
    almostThere: `Ci siamo quasi.`,
    am: `Mattina`,
    andMore: (params: string[]) => `e altri ${params[0]}`,
    apiErrorGetConsentDocument: `Impossibile caricare il documento di consenso. Toccare per riprovare.`,
    appointment: `Visita`,
    appointmentAcceptedByPatient: `Accettato dal paziente`,
    appointmentAwaitingPatientResponse: `In attesa di risposta del paziente`,
    appointmentDeclinedByPatient: `Rifiutato dal paziente`,
    appointmentName: `Nome visita`,
    appointmentNotification: `Notifica visita`,
    appointments: `Visite`,
    appointmentsForPatient: (params: string[]) => `Visite per ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `È possibile programmare una visita tra ${params[0]} e ${params[1]}`,
    appUnavailable: `Spiacenti, l’app non è disponibile al momento.Riprovare più tardi o controllare gli aggiornamenti.`,
    april: `Aprile`,
    ar: `Arabo`,
    areYouSureDeclineMessage: `Il team medico ha bisogno della tua collaborazione per la preparazione e il monitoraggio dei tuoi progressi.\n\nContatta il tuo medico di riferimento se non desideri iscriversi alla piattaforma`,
    areYouSureDeclineTitle: `Iscriversi alla piattaforma care4today?`,
    areYouSureDeleteNote: `Eliminare questa nota?`,
    article: `Articolo`,
    assignToMDT: `Assegna a MDT`,
    audio: `Audio`,
    august: `Agosto`,
    back: `Indietro`,
    backToAppointments: `Torna alle visite`,
    backToDetails: (params: string[]) => `Torna ai dettagli di ${params[0]}`,
    backToLogin: `Torna all’accesso`,
    backToPatientProfile: `Torna al profilo del paziente`,
    badPassword: `Hai inserito una password non valida.`,
    bariatrics: `Bariatrica`,
    blockedUser: `L’utente è stato bloccato.Riprovare tra mezz’ora.`,
    bmi: `IMC`,
    bookedSuccess: `La tua visita è stata prenotata correttamente`,
    cancel: `Annulla`,
    cancelAlert: `Annulla`,
    cantParseError: `Impossibile analizzare la risposta.`,
    cantSaveImage: `Impossibile salvare l’immagine.`,
    care4Today: `care4today`,
    careModules: `Moduli di assistenza`,
    changePassword: `Modifica password`,
    changePasswordSubtitle: `Scegliere la propria password personale.`,
    changePasswordTitle: `Personalizzare la password`,
    choosePicture: `Scegli immagine`,
    chooseProfilePicture: `Modifica immagine`,
    cm: `cm`,
    completed: `Operazione completata`,
    conditionalGoal: `Obiettivo condizionale`,
    confirmAppointmentDelete: `Eliminare questa visita?`,
    confirmed: `Confermato`,
    confirmNewPasswordPlaceholder: `Conferma nuova password`,
    consent: `Consenso`,
    consentDontAgree: `Non accetto e non desidero utilizzare la piattaforma care4today`,
    consentedOn: (params: string[]) => `Hai dato il consenso per ${params[0]}`,
    contact: `Contatto`,
    contactDetails: `Dati di contatto`,
    contactInfo: `INFORMAZIONI DI CONTATTO`,
    contentDescApptIcon: `Icona della visita`,
    contentDescAttachImage: `Allega immagine`,
    contentDescAttachment: `Allegato`,
    contentDescAttachmentImg: `Immagine a schermo intero`,
    contentDescBackground: `Sfondo`,
    contentDescChangePwdIcon: `Icona di modifica password`,
    contentDescClose: `Chiudi schermo intero`,
    contentDescDeleteAttachment: `Elimina allegato immagine`,
    contentDescDevicesIcon: `Icona dei dispositivi connessi`,
    contentDescEduContentExpandBtn: `Apri allegato contenuto formativo`,
    contentDescEduContentThumb: `Allegato contenuto formativo`,
    contentDescEduItemCompleted: `L’elemento formativo è completato`,
    contentDescEduItemIncomplete: `L’elemento formativo non è completato`,
    contentDescGoalIcon: `Icona dell’obiettivo personale`,
    contentDescHelpIcon: `Icona di aiuto`,
    contentDescKillswitchIcon: `Icona dell’interruttore di emergenza`,
    contentDescLegalIcon: `Icona dei documenti legali`,
    contentDescLogo: `Logo applicazione`,
    contentDescLogoutIcon: `Icona di uscita`,
    contentDescMdtPic: `Immagine dell’operatore sanitario`,
    contentDescMessageIcon: `Icona del messaggio`,
    contentDescNoGoalIcon: `Icona nessun obiettivo`,
    contentDescPathwayCurrent: `Icona della fase attuale`,
    contentDescPathwayIcon: `Icona del percorso`,
    contentDescPathwayOtherPhase: `Icona di un’altra fase`,
    contentDescProfilePic: `Immagine del profilo`,
    contentDescSend: `Invia`,
    create: `Crea`,
    createAMedicalTeam: `Crea un team medico`,
    createAppointment: `Crea visita`,
    createAppointmentButton: `Crea visita e invia invito`,
    createAppointmentSuccess: `Visita creata correttamente`,
    createAppt: `Crea visita`,
    createMDT: `Crea MDT`,
    currentBmi: `IMC attuale`,
    currentPhase: `Fase attuale`,
    currentWeight: `Peso attuale`,
    dashboard: `Pannello di controllo`,
    date: `Data`,
    dateOfBirth: `Data di nascita`,
    dateOfConsent: `Data del consenso`,
    dateOfConsentAsc: `Data di consenso in ordine ascendente`,
    dateOfConsentDesc: `Data di consenso in ordine discendente`,
    dateOfSurgery: `Data dell’intervento *`,
    december: `Dicembre`,
    decline: `Rifiuta`,
    declined: `Rifiutato`,
    declinedInvitation: `Hai rifiutato questo invito.`,
    declinedNotifications: `Non hai consentito le notifiche. Continuare?Puoi modificare questa opzione nel menu delle impostazioni.`,
    declinedSuccess: `Hai rifiutato la visita`,
    defaultError: `Si è verificato un errore`,
    delete: `Elimina`,
    deleteAppointmentSuccess: `Visita eliminata correttamente`,
    deleteNote: `Elimina nota`,
    deleting: `Eliminazione in corso…`,
    description: `Descrizione`,
    details: `Dettagli`,
    devices: `Dispositivi connessi`,
    disagreeConsentError: `Si è verificato un errore durante il rifiuto del consenso.Riprovare`,
    discardChanges: `Annullare le modifiche?`,
    document: `Documento`,
    done: `Fatto`,
    draftWontBeSaved: `La bozza non verrà salvata.Annullare comunque?`,
    duplicateMDT: `Operatore sanitario già selezionato`,
    edit: `Modifica`,
    editHcpsProfile: `Modifica profilo operatore sanitario`,
    editMessageDetails: `Modifica dettagli conversazione`,
    editMTDTeam: (params: string[]) => `Modifica team per ${params[0]}`,
    editPassword: `Modifica password`,
    editPatient: `Modifica paziente`,
    editPatientError: `Si è verificato un errore durante l’aggiornamento dei dettagli del paziente`,
    editPatientSuccess: `Dettagli paziente aggiornati correttamente.`,
    editProfile: `Modifica profilo`,
    editProfilePicture: `Modifica immagine profilo`,
    editSubject: `Modifica oggetto`,
    editTeamMembers: `Modifica membri del team`,
    editYourPersonalGoal: `Modifica il tuo obiettivo personale`,
    eduContentHint: `Toccare il pulsante Espandi per aprire il contenuto allegato.`,
    email: `E-mail`,
    emailAddress: `Indirizzo e-mail`,
    emailConfirmation: (params: string[]) =>
        `Abbiamo inviato un’e-mail a ${
            params[0]
        } con un link per reimpostare la password.`,
    emailExists: (params: string[]) =>
        `Un utente con l’e-mail ${params[0]} esiste già.`,
    emailSent: `E-mail inviata`,
    en: `Inglese`,
    enableNotifications: `Abilita notifiche`,
    enterANewHCP: `Inserisci un nuovo operatore sanitario`,
    enterSubjectHint: `Inserisci oggetto`,
    enterTheSubject: `Inserire l’oggetto di questa conversazione.`,
    errorEditingHcp: `Si è verificato un errore durante la modifica dell’operatore sanitario`,
    errorFindingConsentDocument: `Errore durante il recupero del documento di consenso.`,
    errorLoading: (params: string[]) =>
        `Errore durante il caricamento di ${params[0]}`,
    errorSavingSettings: `Errore durante il salvataggio delle impostazioni`,
    errorUpdatingPassword: `Impossibile aggiornare la password`,
    excessWeightLost: `Peso in eccesso perso`,
    failEditHcp: `Si è verificato un errore durante la modifica del profilo`,
    february: `Febbraio`,
    female: `Femmina`,
    filter: `Filtro`,
    firstName: `Nome`,
    forgotPasswordInstruction: `Fornire l’indirizzo e-mail con cui ci si è registrati all’ospedale.Verrà inviata un’e-mail con un link per reimpostare la password.`,
    forgotPasswordViewTitle: `Password dimenticata`,
    forgotYourPassword: `Password dimenticata?`,
    formTimeRangeInPast: `L’intervallo di tempo non può essere nel passato`,
    formTimeRangeStartGreaterThanEnd: `L’intervallo di tempo non è valido`,
    forPatient: `Per`,
    from: `Da`,
    ft: `ft`,
    fullName: `Nome completo`,
    function: `Reparto`,
    gained: `preso`,
    gender: `Sesso`,
    goal: `Obiettivo`,
    goalSavedError: `Impossibile salvare l’obiettivo.`,
    goalSavedSuccess: `Obiettivo salvato correttamente.`,
    goBack: `Indietro`,
    hcps: `Operatori sanitari`,
    healthCareProfessionals: (params: string[]) =>
        `Operatori sanitari ${params[0]}`,
    height: `Altezza`,
    help: `Aiuto`,
    heyChooseYourPicture: (params: string[]) =>
        `Salve ${params[0]}, scegli la tua immagine del profilo`,
    iAgree: `Accetto`,
    iAgreeFormat: (params: string[]) => `Accetto (${params[0]}/${params[1]})`,
    iAmSure: `Sono sicuro`,
    idealBodyWeight: `Peso ideale`,
    iDoNotAgree: `Non accetto`,
    iDontAgree: `Non accetto e non desidero utilizzare la piattaforma care4today`,
    imperial: `Imperiale`,
    in: `in`,
    includeLinkToLocation: `Includi link alla posizione`,
    initialWeight: `Peso iniziale`,
    installUpdate: `Installa aggiornamento`,
    invalidEmailError: `Indirizzo e-mail non valido`,
    invalidNumber: `Immettere un numero valido`,
    invalidTokenError: `Impossibile autenticare. Provare ad accedere di nuovo.`,
    it: `Italiano`,
    iWantToFitAgain: `Esempio:“Voglio entrare di nuovo in una L”`,
    january: `Gennaio`,
    july: `Luglio`,
    june: `Giugno`,
    keepGoing: `Continua così!`,
    keepMomentum: `Mantieni questo ritmo!`,
    kg: `kg`,
    kilogrammes: `chilogrammi`,
    language: `Lingua`,
    languageRequired: `Lingua *`,
    lastName: `Cognome`,
    lb: `lb`,
    learningMaterials: `Materiali didattici`,
    legalDocuments: `Documenti legali`,
    loading: `Caricamento in corso`,
    loadingPatients: `Caricamento dei pazienti in corso. Attendere…`,
    location: `Posizione`,
    locationUrl: `URL posizione`,
    lockScreenHint: `È necessario configurare una schermata di blocco del dispositivo per abilitare l’uso sicuro dell’app.`,
    login: `Accedi`,
    loginIncorrect: `La password o l’indirizzo e-mail inserito è errato`,
    logout: `Esci`,
    logoutAreYouSure: `Uscire?`,
    loseBefore: (params: string[]) => `Perdi ${params[0]}`,
    loseFormat: (params: string[]) => `Perdi ${params[0]} ${params[1]}`,
    lost: `perso`,
    male: `Maschio`,
    manageHCPs: `Gestisci operatori sanitari`,
    managePatients: `Gestisci pazienti`,
    march: `Marzo`,
    may: `Maggio`,
    mdtTeam: `Team MDT`,
    mdtTeamNotAddedYet: `MDT non ancora assegnato.`,
    mdtTeamUC: `TEAM MDT`,
    medicalTeam: `Team medico`,
    meetingInvite: `Hai un incontro`,
    meetingInviteWith: (params: string[]) => `Incontro con ${params[0]}`,
    messageCreated: `Hai iniziato correttamente una conversazione.`,
    messageNotCreated: `Non sei riuscito a iniziare una conversazione.`,
    messageNotification: `Notifica messaggio`,
    messageNotSent: `Messaggio non inviato`,
    messages: `Messaggi`,
    metric: `Metrico`,
    movePhaseConfirmation: (params: string[]) =>
        `Spostare ${params[0]} alla fase ${params[1]}?`,
    moveToNextPhase: `Passa alla fase successiva`,
    multiDisTeam: `Team multidisciplinare`,
    myMessages: `I miei messaggi`,
    myMotivation: `La mia motivazione:`,
    myPersonalGoal: `Il mio obiettivo personale`,
    myProfile: `Il mio profilo`,
    myTeam: `Il mio team`,
    name: `Nome`,
    nameOfMDT: `Nome dell’MDT *`,
    needsConsent: `Il paziente deve prima accettare il consenso.`,
    networkError: `Si è verificato un errore di rete`,
    newAppointment: `Nuova visita`,
    newChat: `Nuova chat`,
    newInvitation: `Nuovo invito`,
    newMessageNotificationMore: (params: string[]) =>
        `Sono presenti ${
            params[0]
        } nuovi messaggi.Aprire l’app per vedere le novità.`,
    newMessageNotificationOne: `È presente un nuovo messaggio.Aprire l’app per vedere le novità.`,
    newNote: `Nuova nota`,
    newPasswordPlaceholder: `Nuova password`,
    newPatientSuccess: (params: string[]) =>
        `${params[0]} è stato aggiunto correttamente alla piattaforma.`,
    newTeamFail: `Team MDT non assegnato`,
    newTeamSuccess: `Team MDT assegnato`,
    newVersionApp: `Aggiornare questa app con l’ultima versione disponibile nell’app store.`,
    nextAppointment: `Prossima visita`,
    nextSelectCareModule: `Avanti:Selezione moduli di assistenza`,
    nextSurgeryInformation: `Avanti:Informazioni sull’intervento`,
    niceToSeeYouAgain: `Piacere di rivederti!`,
    nickname: `Soprannome`,
    nicknameError: `Soprannome non valido.I caratteri speciali non sono consentiti.`,
    nl: `Olandese`,
    no: `No`,
    noAppointments: `Non sono disponibili visite`,
    noCurrentGoalForPatient: `Non esiste un obiettivo attuale associato a questo paziente`,
    noDate: `nessuna data impostata`,
    noFutureAppointments: `Nessuna visita imminente`,
    noGoalSet: `Nessun obiettivo impostato dall’operatore sanitario`,
    noMatchingConsentDocumentsFound: `Nessun documento di consenso corrispondente trovato`,
    noMessages: `Non sono disponibili messaggi`,
    noNetworkConnection: `Nessuna connettività di rete disponibile.Controllare…`,
    noNotesMessage: `Non sono disponibili note.\n Toccare “Crea” per aggiungere nuove note`,
    noPersonalGoalSet: `Nessun obiettivo personale impostato.`,
    noPersonalGoalSetDashboard: `Nessun obiettivo personale impostato.Accedere alla pagina delle impostazioni per aggiornarlo.`,
    noPlannedAppointments: `Nessuna visita pianificata`,
    noPreview: `Nessuna anteprima disponibile`,
    noProgressRecorded: `Nessun progresso registrato`,
    noResponseError: `Nessuna risposta ricevuta.`,
    notAgreed: `Non concordato`,
    noteDeletedError: `Impossibile eliminare la nota.`,
    noteDeletedSuccessfully: `Nota eliminata correttamente.`,
    notes: `Note`,
    noteSaved: `Nota salvata`,
    noteSavedError: `Impossibile salvare la nota.`,
    noteSavedSuccess: `Nota salvata correttamente.`,
    noteSaveError: `Errore. Impossibile salvare la nota.Riprovare?`,
    notifications: `Notifiche`,
    notNow: `Non ora`,
    notSet: `Non impostato`,
    notYetSubmitted: `Non ancora inviato`,
    noUnreadMessages: `Nessun messaggio non letto`,
    noUserFound: `Errore durante la ricerca dell’utente con le credenziali fornite.`,
    november: `Novembre`,
    noWeightDifference: `Nessuna differenza di peso`,
    october: `Ottobre`,
    ok: `OK`,
    onboardingNotificationsTitle: `Vogliamo tenerti sempre aggiornato`,
    onboardingNotifictionsInfo: `Riceverai notifiche su:\n\n• Le tue visite\n• Nuovi messaggi del team medico`,
    onVar: (params: string[]) => `in ${params[0]}`,
    openCare: `Aprire care4today e controllare se sono presenti nuove notifiche.`,
    optOutSubtitle: `Contattare il medico specialista se non si desidera iscriversi alla piattaforma.`,
    optOutTitle: `Iscriversi alla piattaforma care4today?`,
    organisation: `Organizzazione`,
    orthopedics: `Ortopedia`,
    other: `Altro`,
    outdatedVersion: `La versione dell’app attualmente in uso è obsoleta.`,
    overview: `Panoramica`,
    participant: `Partecipante`,
    password: `Password`,
    passwordComplexityError: `La password deve contenere almeno 8 caratteri e almeno 2 dei seguenti tipi di caratteri:maiuscole, minuscole, numeri o simboli.`,
    passwordMismatchError: `Password non corrispondenti`,
    passwordUpdated: `Password aggiornata`,
    pastAppointments: `Visite passate`,
    pathwayScheduleFail: `Si è verificato un errore.Impossibile aggiornare la programmazione del percorso`,
    patient: `Paziente`,
    patientAge: (params: string[]) => `${params[0]} anni`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} anni`,
    patientConsent: `Consenso paziente`,
    patientNameAsc: `Nome paziente in ordine ascendente`,
    patientNameDesc: `Nome paziente in ordine discendente`,
    patientRegistration: `Registrazione paziente`,
    patients: `Pazienti`,
    patientsCount: (params: string[]) => `${params[0]} pazienti`,
    patientsOverview: `Panoramica pazienti`,
    pending: `In attesa`,
    percent: `%`,
    personalGoal: `Obiettivo personale`,
    personalGoalEdit: `Obiettivo personale`,
    personalPassword: `Password personale`,
    personalPasswordHelper: `Scegliere la propria password personale.È sempre possibile cambiarla nel menu delle impostazioni.`,
    phoneError: `Numero di telefono non valido.Utilizzare solo numeri (senza parentesi, trattini, +)`,
    phoneNumber: `Numero di telefono`,
    picture: `Immagine`,
    pictureInstructions: `Scegliere l’immagine del profilo personale.Questa immagine verrà utilizzata per l’account.`,
    pleaseConnect: `Connettersi a Internet per assicurarsi di utilizzare l’ultima versione dell’app.`,
    pleaseContactYourHospital: `In caso di emergenza, contattare direttamente l’ospedale.`,
    pleaseProvidePassword: `Fornire la password per confermare questa azione:`,
    pm: `Pomeriggio`,
    pounds: `libbre`,
    preparation: `Preparazione`,
    preSurgeryPrep: `Preparazione pre-intervento`,
    previous: `Indietro`,
    privacyPolicy: `Informativa sulla privacy`,
    profileLabel: `Utilizzeremo queste informazioni per le comunicazioni tramite e-mail, messaggi di testo e questa app.Le condivideremo anche con il team medico.`,
    profilePicture: `Immagine del profilo`,
    profileTitle: `Utilizzeremo queste informazioni per le comunicazioni tramite e-mail, messaggi di testo e questa app.Le condivideremo anche con il team medico.`,
    progress: `Progressi`,
    progressMsgForgotPwd: `Convalida in corso…`,
    progressMsgLoading: `Caricamento in corso...`,
    progressMsgLoadingContent: `Caricamento del contenuto in corso...`,
    progressMsgLogin: `Caricamento del percorso in corso…\nQuesta operazione potrebbe richiede fino a 1 minuto.`,
    progressMsgMdtLoading: `Caricamento MDT in corso…`,
    progressMsgNotesLoading: `Caricamento delle note in corso…`,
    progressMsgProfileEdit: `Salvataggio del profilo in corso…`,
    progressMsgProfilePhoto: `Salvataggio della foto in corso…`,
    progressMsgResetPwd: `Salvataggio della password in corso…`,
    provideTheEmail: `Fornire l’indirizzo e-mail con cui ci si è registrati all’ospedale.`,
    pwdValidationDoesNotMatch: `Le password non corrispondono`,
    pwdValidationIllegal: `Contiene caratteri non consentiti`,
    pwdValidationNotComplex: `La complessità della password non soddisfa i requisiti`,
    pwdValidationTooShort: `La password è troppo corta`,
    quickFilter: `Filtro rapido`,
    remindmeLater: `Ricordamelo più tardi`,
    requiredFields: `Campi obbligatori`,
    requiredHCPs: `Operatori sanitari *`,
    resetPassword: `Reimposta password`,
    respond: `Rispondi`,
    retry: `Riprova`,
    save: `Salva`,
    saveAndContinue: `Salva e continua`,
    saveChanges: `Salva modifiche`,
    scheduleNewAppointment: `Programma nuova visita`,
    searchInConversation: `Cerca nelle conversazioni…`,
    secureRealmError: `Impossibile avviare: è necessario abilitare la schermata di blocco`,
    selectDifferentImage: `Seleziona un’altra immagine`,
    selectFile: `Seleziona file`,
    selectFunction: `Seleziona funzione`,
    selectLanguage: `Seleziona lingua`,
    selectOneOrMoreHCPs: `Seleziona uno o più operatori sanitari`,
    selectPictureSource: `Seleziona immagine da`,
    selectProfilePicture: `Seleziona immagine del profilo`,
    selectSurgeon: `Seleziona chirurgo`,
    send: `Invia`,
    sendMessage: `Invia messaggio`,
    sendNewMessage: `Invia nuovo messaggio`,
    september: `Settembre`,
    setPassword: `Imposta password`,
    setPasswordReminder: `È sempre possibile cambiarla nel menu delle impostazioni.`,
    settings: `Impostazioni`,
    setup: `CONFIGURAZIONE`,
    setYourPersonalGoal: `Imposta il tuo obiettivo personale`,
    someonesPathway: (params: string[]) => `percorso di ${params[0]}`,
    sortBy: `Ordina per`,
    splashSubtitle: `Chirurgia per la perdita di peso`,
    start: `Avvia`,
    startANewConversation: `Avvia una nuova conversazione`,
    startConversation: `Avvia conversazione`,
    startingPoint: `Punto di inizio`,
    startNewConversation: `+ Avvia nuova conversazione`,
    startPreparation: `Inizia con la preparazione`,
    status: `Stato`,
    subject: `Oggetto`,
    subjectChangedSuccess: `Oggetto della conversazione modificato correttamente`,
    subjectChangeFail: `Oggetto della conversazione non modificato`,
    submit: `Invia`,
    subPhase: `Sottofase`,
    successEditHcp: `Profilo modificato correttamente`,
    surgeon: `Chirurgo`,
    surgeryInformation: `Informazioni sull’intervento`,
    tasks: `attività`,
    tasksCompleted: `Attività completate`,
    team: `Team`,
    thisMonth: `Questo mese`,
    time: `Ora`,
    timeAndLocation: `Ora e posizione`,
    timeOfSurgery: `Ora dell’intervento *`,
    to: `A`,
    today: `Oggi`,
    toDo: `Da fare`,
    undo: `Annulla`,
    unitRequired: `Unità *`,
    units: `Unità`,
    unknown: `Preferisco non dirlo`,
    unknownError: `Si è verificato un errore durante l’elaborazione.Riprovare…`,
    unknownGender: `Preferisco non rispondere`,
    unknownUser: `Non noto`,
    unreadMessage: `Messaggio non letto`,
    unreadMessages: `Messaggi non letti`,
    untitled: `Senza titolo…`,
    update: `Aggiorna`,
    updateAppointment: `Modifica visita`,
    updateAppointmentButton: `Salva modifiche e invia aggiornamenti`,
    updateAppointmentSuccess: `Visita aggiornata correttamente`,
    updateMessage: `Per continuare a utilizzare questa app, è necessario aggiornarla alla versione più recente dall’app store`,
    updateProfilePicture: `Aggiorna immagine del profilo`,
    updateProgress: `Aggiorna progressi`,
    useCamera: `Usa fotocamera`,
    username: `Nome utente`,
    video: `Video`,
    viewAllMessages: `Visualizza tutti i messaggi`,
    viewAndEditPathway: `Visualizza e aggiorna date percorso`,
    viewDocument: `Visualizza documento`,
    weight: `Peso`,
    weightLoss: `Perdita di peso`,
    weightUpdatedSuccess: `Il peso attuale è aggiornato correttamente`,
    welcomeHeader: `Benvenuto`,
    welcomeMessage: (params: string[]) => `Salve ${params[0]}!`,
    wellDoneNextStep: `Complimenti!Sei pronto per passare alla fase successiva!`,
    withdrawConfirm: `OK, esci dall’app`,
    withdrawConsent: `Ritira consenso`,
    withdrawConsentBody: `Ritirando il consenso al trattamento delle informazioni personali, i dati locali come note e obiettivi personali verranno eliminati, e dopo un periodo di attesa di 30 giorni, non sarà più possibile accedere all’applicazione.`,
    withdrawConsentTitle: `Annullare l’iscrizione alla piattaforma care4today?`,
    writeAMessage: `Scrivi un messaggio…`,
    writeSomething: `Scrivi qualcosa…`,
    wrongUserName: `Il nome utente inserito è errato`,
    xUnread: (params: string[]) => `${params[0]} non letti`,
    yes: `Sì`,
    yesDelete: `Sì, elimina`,
    yesDiscard: `Sì, annulla`,
    youAreOffline: `Sei offline`,
    youCanSetASentence: `Puoi impostare una frase di motivazione per raggiungere il tuo obiettivo personale.`,
    youGained: (params: string[]) => `Hai preso ${params[0]}`,
    youGainedFormat: (params: string[]) =>
        `Hai preso ${params[0]} ${params[1]}`,
    youHaveANewMessageFrom: (params: string[]) =>
        `Hai un nuovo messaggio da ${params[0]}.`,
    youHaveNewAppointment: `Hai una nuova visita.Aprire l’app per vedere le novità.`,
    youHaveNewAppointments: (params: string[]) =>
        `Hai ${params[0]} nuove visite.Aprire l’app per vedere le novità.`,
    youHaveNewMessage: `È presente un nuovo messaggio.Aprire l’app per vedere le novità.`,
    youHaveNewMessages: (params: string[]) =>
        `Sono presenti ${
            params[0]
        } nuovi messaggi.Aprire l’app per vedere le novità.`,
    youHaveUndone: `Hai annullato l’opzione scelta precedente`,
    youLost: (params: string[]) => `Hai perso ${params[0]}`,
    youLostFormat: (params: string[]) => `Hai perso ${params[0]} ${params[1]}`,
    yourAppointments: `Le tue visite`,
    yourGoals: `I tuoi obiettivi`,
    yourNote: `La tua nota`,
    yourPassword: `La tua password`,
    yourPasswordHasBeenReset: `La tua password è stata reimpostata`,
    yourProfile: `Il tuo profilo`,
    export: `Esporta`,
    exportData: `Esporta dati personali`,
    exportDataFail: `Si è verificato un errore.Impossibile esportare i dati`,
    exportMyData: `Esporta i miei dati personali`,
    goalStepCount: `Obiettivo (passi/giorno)`,
    loadingPathway: `Caricamento del percorso in corso… Questa operazione potrebbe richiedere fino a 1 minuto.`,
    loadingPatient: `Caricamento del paziente in corso. Attendere…`,
    pleaseEnterTotalSteps: `Inserire il numero totale di passi alla fine di ogni giornata`,
    stepCount: `Numero passi`,
    stepsPerDay: `passi/giorno`,
    walkStepsPerDay: (params: string[]) => `Cammina ${params[0]} passi/giorno`,
    steps: `Passi`,
    avgWeeklySteps: `Media dei passi questa settimana`,
    rightToBeForgotten: `Elimina i miei dati personali`,
    totalStepsDuringDay: `Totale dei passi percorsi in un giorno`,
    youAlreadyWalked: (params: string[]) =>
        `Oggi hai camminato ${params[0]} passi`,
    rightToBeForgottenTitle: `Avviare l’eliminazione dei dati personali?`,
    rightToBeForgottenInfo: `Avviando questa richiesta, le informazioni personali verranno eliminate e non sarà più possibile accedere all’applicazione. Tieni presente che alcuni dati personali limitati, come il nome inviato dal Sistema informativo dell’ospedale, possono continuare a comparire negli appuntamenti.    Per eventuali ulteriori domande, contattare support@care4todaypatient.com.    Inserisci la password per confermare questa azione:`,
    passwordHint: `La tua password`,
    rightToBeForgottenSuccess: `La richiesta di eliminazione dei dati personali è stata inviata alla casella di posta dell’assistenza care4today`,
    incorrectPassword: `Password errata inserita`,
    errorInitiatingRightToBeForgotten: `Errore durante l’invio della richiesta. Contattare direttamente l’assistenza`,
    updateStepCount: `Aggiorna numero di passi`,
    mon: `Lun`,
    tue: `Mar`,
    wed: `Mer`,
    thu: `Gio`,
    fri: `Ven`,
    sat: `Sab`,
    sun: `Dom`,
    stepsAmount: (params: string[]) => `${params[0]} passi`,
    stepsGoalUpdateSuccess: `Valore passi aggiunto correttamente`,
    search: `Cerca...`,
    successEditMDT: `MDT aggiornato correttamente`,
    failEditMDT: `Si è verificato un errore durante l’aggiornamento dell’MDT`,
    userCreationError: `Si è verificato un errore durante la creazione dell’utente`,
    userUpdateSuccess: `Utente aggiornato correttamente`,
    legal: `Legale`,
    termsOfUse: `Condizioni d’uso`,
    disclaimer: `Esclusione di responsabilità`,
    exportDataSuccessV1: `La richiesta di esportazione dei dati personali è stata inviata al team di assistenza care4today`,
    exportDataSuccess: `Esportazione dei dati personali avviata`,
    dataFormatV1: `I dati personali verranno esportati nel formato di file CSV.Il file verrà inviato all’indirizzo e-mail registrato.`,
    dataFormat: `I dati personali verranno esportati nel formato di file JSON.Il file verrà inviato all’indirizzo e-mail registrato.`,
    viewAllMaterials: `Visualizza tutti i materiali`,
    viewAllAppointments: `Visualizza tutte le visite`,
    enjoyYourDay: `Buona giornata libera!`,
    motivateAlmost: `Ci siamo quasi.`,
    startConversationHcp: `Avvia una conversazione con un operatore sanitario`,
    andYou: `, te`,
    viewAllNotifications: `Visualizza tutte le notifiche`,
    noInvitations: `Nessun invito`,
    yourTimeline: `La tua sequenza temporale`,
    currentSubphase: `Sottofase attuale`,
    updateWeight: `Aggiorna peso attuale`,
    teamLoading: `Caricamento del team in corso`,
    noMdt: `Nessun MDT assegnato.`,
    teamDetails: `Visualizza dettagli team`,
    showResolved: `Mostra risolti`,
    readDoc: `Leggi documento`,
    consultationNotes: `Note consultazione`,
    viewAllConsultationNotes: `Visualizza tutte le note della consultazione`,
    createNewNote: `+ Crea nuova nota`,
    dismiss: `Ignora`,
    pictureError: `Errore durante il caricamento dell’immagine`,
    wrongFormat: `Formato immagine errato`,
    backToDashboard: `Torna al pannello di controllo`,
    noMessage: `Nessun messaggio`,
    noSpecialCharacters: `I caratteri speciali non sono consentiti.`,
    noNotesAvailable: `Nessuna nota disponibile`,
    hcpPortal: `Portale per gli operatori sanitari`,
    patientPortal: `Portale per i pazienti`,
    consultationNote: `Nota consultazione`,
    noteTitle: `Titolo nota`,
    noteContents: `Contenuti nota`,
    writeConsultationNotes: `Scrivi qui le note della consultazione`,
    createHcpNote: `Crea nota`,
    consultationNoteCreatedBy: (params: string[]) =>
        `Creato: ${params[0]} da ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `Ultima modifica: ${params[0]}`,
    loadingConsultaionNotes: `Caricamento note consultazione in corso`,
    consultationNotesFor: (params: string[]) =>
        `Note consultazione per ${params[0]}`,
    editHcpNote: `Modifica nota`,
    reason: `Motivo`,
    writeReasonForEditing: `Scrivi il motivo della modifica…`,
    confirmCancelCreateNote: `Uscire senza aver creato la nota?`,
    confirmCancelEditNote: `Uscire senza aver modificato la nota?`,
    rotateYourDevice: `Ruota il dispositivo`,
    patientId: `ID paziente`,
    oldPassword: `Vecchia password`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `Documenti`,
    hcpId: `ID operatore sanitario`,
    userInactivity: `È stata eseguita la disconnessione a causa dell’inattività.`,
    duplicateMrn: `Questo ID operatore sanitario esiste già in care4today`,
    confirm: `Conferma`,
    viewDetails: `Visualizza dettagli`,
    upperCaseLetters: `Lettere maiuscole`,
    lowerCaseLetters: `Lettere minuscole`,
    numbers: `Numeri`,
    specialCharacters: `Caratteri speciali (segni di punteggiatura, simboli)`,
    passwordRequirements: `La password deve essere contenere almeno 8 caratteri e soddisfare due criteri di complessità:`,
    incorrectOldPassword: `La vecchia password è errata.L’account verrà bloccato dopo 5 tentativi falliti`,
    newPasswordsNotSame: `Le nuove password inserite non sono uguali`,
    passwordSuccesfullyChanged: `Password modificata correttamente`,
    accountBlockedFifteenMinutes: `L’account è stato bloccato.Riprovare tra 15 minuti`,
    loadingLegalDocuments: `Caricamento dei documenti legali in corso…`,
    fr: `Francese`,
    errorFetchingLegalDocuments: `Errore durante il caricamento dei documenti legali`,
    nameAndMrnNotFound: `Impossibile trovare la combinazione di ID paziente e cognome`,
    duplicateNameAndMrn: `L’ID paziente esiste già in care4today`,
    NSCameraUsageDescription: `Questa app richiede l’accesso alla fotocamera per aggiungere/aggiornare l’immagine del profilo e aggiungere allegati alle note`,
    NSPhotoLibraryUsageDescription: `Questa app richiede l’accesso alla libreria di foto per aggiungere allegati alle note`,
    initiate: `Inizia`,
    lastNameAsc: `Cognome in ordine ascendente`,
    lastNameDesc: `Cognome in ordine discendente`,
    firstNameAsc: `Nome in ordine ascendente`,
    firstNameDesc: `Nome in ordine discendente`,
    messageParticipantIsInactive: `non più attivo`,
    participantNoLonger: `Il partecipante non è più un utente della piattaforma`,
    requestDeletionInProgress: `La tua richiesta di eliminazione dei dati personali è già in corso.Il team di assistenza ti aggiornerà alla conclusione del processo`,
    contactNotAvailableOnDeactivated: `Dati di contatto di un operatore sanitario disattivato non disponibili`,
    deactivated: `Disattivato`,
    noPermissionToSendMessage: `Non hai l’autorizzazione per inviare messaggi a questa persona`,
    refrainSendingMedData: `Evitare di inviare messaggi contenenti informazioni/dati medici del paziente`,
    refrainEnteringMedData: `Evitare di inserire informazioni/dati medici del paziente nel campo riportato sopra`,
    contactHospitalAppointment: `Se è necessario modificare o annullare la visita, contattare direttamente l’ospedale.`,
    noInfoDescriptionAppointment: `Nessun’altra informazione disponibile.Per eventuali domande sulla visita, contattare direttamente l’ospedale.`,
    noInfoDescriptionAndDateAppointment: `A breve, verrà inviato un aggiornamento con maggiori informazioni sulla visita.Per eventuali domande sulla visita, contattare direttamente l’ospedale.`,
    participants: `Partecipanti`,
    noMdtAssigned: `Nessun team multidisciplinare assegnato al paziente.Per prima cosa, assegnare un team al paziente.`,
    scheduled: `Programmato`,
    updated: `Aggiornato`,
    proposed: `Proposto`,
    he: `Ebraico`,
    restrictProcessingPersonal: `Limita il trattamento dei miei dati personali`,
    restrictProcessingArticle: `In base all’articolo 18 del Regolamento generale sulla protezione dei dati (GDPR), quale di questi elementi si applica alla tua situazione?`,
    dataAccuracy: `Accuratezza dei dati`,
    unlawfulProcessing: `Trattamento illegittimo`,
    legalClaim: `Procedimento legale`,
    provideExplanation: `Fornire una spiegazione:`,
    provideExplanationDescription: `Fornire un testo esplicativo per descrivere il problema e aiutare a valutare la richiesta`,
    restrictProcessing: `Limita il trattamento`,
    sureProcessing: `Limitare il trattamento dei dati personali?`,
    processingPasswordConfirmation: `Avviando questa richiesta, i dati verranno temporaneamente disabilitati e, salvo comunicazioni contrarie, archivieremo i dati e li sottoporremo a ulteriore trattamento solo se otteniamo il consenso.Per eventuali ulteriori domande o per annullare la limitazione, contattare support@care4todaypatient.com.Fornire la password per confermare questa azione:`,
    processingSent: `La richiesta di limitare il trattamento dei dati personali è stata inviata alla casella di posta dell’assistenza care4today`,
    versionNumber: (params: string[]) => `Versione ${params[0]}`,
    pleaseSelect: `Selezionare:`,
    restrictedLogout: `È stata eseguita la disconnessione perché la richiesta di limitare il trattamento dei dati personali è stata gestita e la limitazione applicata all’account care4today.In caso di eventuali domande, contattare support@care4todaypatient.com.`,
    restrictProcessingAlreadyRequested: `La richiesta di limitazione del trattamento dei dati personali è già in corso.Il team di assistenza ti aggiornerà alla conclusione del processo.`,
    rightToRestrictQuestion: `In base all’articolo 18 del Regolamento generale sulla protezione dei dati (GDPR), quale di questi elementi si applica alla tua situazione?`,
    rightToRestrictExplanation: `Fornire una spiegazione:`,
    rightToRestrictTitle: `Limita il trattamento dei miei dati personali`,
    rightToRestrictExplanationPlaceholder: `Fornire un testo esplicativo per descrivere il problema e aiutare a valutare la richiesta.`,
    rightToRestrictConfirmationTitle: `Limitare il trattamento dei dati personali?`,
    rightToRestrictConfirmationDescription: `La richiesta verrà inviata al team di assistenza. L’account e i dati verranno temporaneamente disabilitati e, salvo comunicazioni contrarie, archivieremo i dati e li sottoporremo a ulteriore trattamento solo se otteniamo il consenso. Tieni presente che alcuni dati personali limitati, come il nome inviato dal Sistema informativo dell’ospedale, possono continuare a comparire negli appuntamenti.    Per eventuali ulteriori domande o per annullare la limitazione, contattare support@care4todaypatient.com.    Inserisci la password per confermare questa azione:`,
    assignedRole: (params: string[]) => `${params[0]} assegnato (inattivo)`,
    requestRestrictionSubmitted: `La richiesta di limitare il trattamento dei dati personali è stata inviata alla casella di posta dell’assistenza care4today`,
    temporarelyUnavailableHCPAlertMessage: `L’operatore sanitario è temporaneamente non disponibile nella piattaforma.In caso di eventuali domande, contattare il team di assistenza.`,
    temporarelyUnavailableHCPSubtitle: `L’operatore sanitario è temporaneamente non disponibile`,
    assignedHCP: (params: string[]) => `${params[0]} assegnato`,
    inactive: `Inattivo`,
    appointmentInvite: `Hai una visita`,
    disabledAppointmentActionMessage: `Utilizzare direttamente il sistema di prenotazione delle visite dell’ospedale per programmare, aggiornare o annullare una visita.`,
    noFurtherInformation: `Nessun’altra informazione disponibile`,
    cancelled: `Annullato`,
    cancelledNotificationPrefix: `Annullato:`,
    updatedNotificationPrefix: `Aggiornato:`,
    allDay: `Tutto il giorno`,
    editCareModule: `Modifica modulo di assistenza`,
    nextSurgeryProcedureInformation: `Avanti:Dettagli su intervento/procedura`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} non fa più parte del\nteam multidisciplinare`,
    editCareModuleWarning: `Tenere presente che modificando il modulo di assistenza, tutta la cronologia di obiettivi e materiali didattici della procedura precedente non sarà più disponibile per il paziente.`,
    editSurgeryWarning: `Modificare le informazioni sull’intervento, se necessario.`,
    nextUpdateMDT: `Avanti:Aggiorna team medico`,
    updateCareModule: `Aggiorna modulo di assistenza`,
    editMdtTeamWarning: `Controllare il team multidisciplinare per verificare se sono necessari eventuali aggiornamenti.`,
    participantNotInMDT: `Non fai più parte del team MDT di questo paziente`,
    createMedicalTeam: `Crea team medico`,
    editMedicalTeam: `Modifica team medico`,
    mdtName: `Nome dell’MDT`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `Cambiare il modulo di assistenza di questo paziente da ${
            params[0]
        } a ${params[1]}?`,
    changePathwayConfirmationSubTitle: `Tenere presente che modificando il modulo di assistenza, tutta la cronologia di obiettivi e materiali didattici della procedura precedente non sarà più disponibile per il paziente.`,
    changePathwaySuccessMessage: (params: string[]) =>
        `Il modulo di assistenza del paziente ${
            params[2]
        } è stato modificato correttamente da ${params[0]} a ${params[1]}`,
    mdtChanged: `Il team medico è cambiato`,
    tapForDetails: `Toccare qui per trovare maggiori informazioni.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} assegnato non fa più parte del\nteam multidisciplinare`,
    addPatientReceivedConsent: `Fornendo le informazioni di seguito, dichiaro di aver ricevuto il consenso dal paziente per trattare i suoi dati.`,
    attended: `Seguito`,
    entityCreationError: (params: string[]) =>
        `Si è verificato un errore nella creazione di ${params[0]}`,
    updateAppointmentError: `Si è verificato un errore nell’aggiornamento della visita`,
    updateConsultationNoteError: `Si è verificato un errore nell’aggiornamento della nota della consultazione`,
    createConsultationNoteError: `Si è verificato un errore nella creazione della nota della consultazione`,
    missed: `Mancato`,
    contentDescCloseNotification: `Chiudere notifica`,
    pathwayChanged: `Il suo modulo di cura è stato modificato`,
    pathwayChangedDetails: (params: string[]) =>
        `da ${params[0]} a ${
            params[1]
        }.Per maggiori informazioni, La invitiamo a contattare il coordinatore dell’assistenza/operatore sanitario.`,
    de: `Tedesco`,
    doYouWantToDeletePatient: (params: string[]) =>
        `Eliminare il paziente ${params[0]}?`,
    personWillBeRemovedFromRecords: `Questa persona non sarà più in grado di accedere all’app C4T e verrà eliminata dalla documentazione digitale.`,
    provideDeletionReason: `Fornire un motivo per la cancellazione:`,
    deletionSuccess: (params: string[]) =>
        `${params[0]} è stato cancellato correttamente dalla piattaforma`,
    consentNotProvided: `Non è stato fornito alcun consenso`,
    entryError: `Errore di inserimento`,
    duplicatePatient: `Duplica paziente`,
    addExtraSecurity: `Rendi il tuo account più sicuro con la verifica in due passaggi`,
    mfaDescription: `Ogni volta che effettui l’accesso al tuo account da un nuovo dispositivo, ti verrà chiesto di digitare un codice di sicurezza.Il codice di sicurezza verrà inviato al tuo indirizzo e-mail o al tuo cellulare.`,
    activateMfa: `Attiva la verifica in due passaggi`,
    userAccountNotActive: `L’account utente non è attivo`,
    useHCPPortal: `Se hai dimenticato la password, utilizza il portale online per gli operatori sanitari`,
    noPatientsAssigned: `Non ti è stato assegnato alcun paziente.`,
    currentAppointments: `Visite correnti`,
    noCurrentAppointments: `Non sono disponibili visite future`,
    phase: `Fase`,
    noPhaseInformation: `Nessuna informazione sulla fase`,
    noSubphaseInformation: `Nessuna informazione sula fase secondaria`,
    you: (params: string[]) => `${params[0]} (tu)`,
    hcpsMedicalStaff: `Operatori sanitari`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `in ${params[0]} (${params[1]})`,
    newMessage: `Nuovo messaggio`,
    addParticipant: `Aggiungi partecipante`,
    editParticipant: `Modifica partecipante`,
    messagesFor: (params: string[]) => `Messaggi ${params[0]}`,
    noParticipants: `Nessun partecipante disponibile`,
    whichMfaMethod: `Come si desidera ricevere il codice di sicurezza?`,
    mfaMethodExplanation: `Questo codice di sicurezza è necessario per accedere al proprio account. È possibile ottenere il codice di accesso utilizzando il proprio telefono cellulare o e-mail. Scegliere il metodo che si adatta meglio alle proprie esigenze.`,
    textMe: `Inviami un codice di accesso tramite messaggio`,
    emailMe: `Inviami un codice di accesso tramite e-mail`,
    textMeSubtitle: `Chiederemo il numero di telefono`,
    emailMeSubtitle: `Confermare il proprio indirizzo e-mail`,
    backToMethod: `Torna alla scelta del metodo`,
    addPhone: `Aggiungere un numero di telefono`,
    whichPhone: `A che numero di telefono si desidera ricevere il codice di sicurezza?`,
    phoneDisclaimer: `Questo numero di telefono sarà usato solo per la sicurezza dell’account. I costi per i messaggi di testo e l’utilizzo dei dati potrebbero essere addebitati.`,
    sendCode: `Invia codice di sicurezza`,
    confirmEmail: `Confermare la propria e-mail`,
    whichEmail: `A che indirizzo e-mail si desidera ricevere il codice di sicurezza?`,
    emailDisclaimer: `Questo indirizzo e-mail sarà usato solo per la sicurezza dell’account.`,
    insertCode: `Inserire il codice di sicurezza`,
    mayTakeTwoMinutes: `Potrebbero essere necessari fino a 2 minuti per ricevere il codice.`,
    sentCodeByText: (params: string[]) =>
        `Abbiamo appena inviato il codice di sicurezza tramite messaggio di testo a ${
            params[0]
        }`,
    sentCodeByEmail: (params: string[]) =>
        `Abbiamo appena inviato il codice di sicurezza tramite e-mail a ${
            params[0]
        }`,
    didntGetCode: `Non ha ricevuto un codice?`,
    resendCode: `Invia di nuovo codice di sicurezza`,
    authenticate: `Autenticare`,
    verifyingCode: `Verifica del codice di sicurezza in corso`,
    mfaSuccess: `Autenticazione in 2 fasi abilitata correttamente.`,
    mfaCodeRequired: `È necessario un codice di accesso per accedere al proprio account.`,
    mfaMethodExplanationLogin: `Questo codice di sicurezza è necessario per accedere al proprio account. È possibile ottenere il codice di accesso utilizzando il proprio telefono cellulare o e-mail.`,
    contentDescMfaIcon: `Icona autenticazione in 2 fasi`,
    mfaSendCodeTo: (params: string[]) =>
        `Il codice sarà inviato a ${params[0]}`,
    continueLabel: `Continua`,
    authenticating: `Autenticazione in corso`,
    mfaInvalidCode: `Il codice immesso non è valido. Provare di nuovo.`,
    mfaUnableToVerifyPhoneNumber: `Impossibile verificare questo numero di telefono. Provare con un altro numero.`,
    mfaUnableToVerifyEmail: `Impossibile verificare questo indirizzo e-mail. Provare con un altro indirizzo.`,
    sessionExpired: `La tua sessione è scaduta. Collegarsi di nuovo.`,
    passwordExpired: `La password è scaduta. Modificare la password.`,
    rightToBeForgottenInfoNonIntegrated: `Avviando questa richiesta, le informazioni personali verranno eliminate e non sarà più possibile accedere all’applicazione.Per eventuali ulteriori domande, contattare support@care4todaypatient.com.Fornire la password per confermare questa azione:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `La richiesta verrà inviata al team di assistenza.L’account e i dati verranno temporaneamente disabilitati e, salvo comunicazioni contrarie, archivieremo i dati e li sottoporremo a ulteriore trattamento solo se otteniamo il consenso.Per eventuali ulteriori domande o per annullare la limitazione, contattare support@care4todaypatient.com.`,
    password_expired_message: `La password è scaduta e deve essere modificata per accedere a C4T`,
    firstdayOftheWeek: `Primo giorno della settimana`,
    dateformat: `Formato data`,
    selectDateFormat: `Seleziona il formato della data`,
    selectDay: `Seleziona il giorno`,
    monday: `Lunedì`,
    tuesday: `Martedì`,
    wednesday: `Mercoledì`,
    thursday: `Giovedì`,
    friday: `Venerdì`,
    saturday: `Sabato`,
    sunday: `Domenica`,
    manageTheAppointmentTemplates: `Gestisci il modello di appuntamento`,
    prefillTemplatesFor: `Modelli di pre-riempimento per`,
    appointmentTemplates: `Modelli di appuntamento`,
    backToTemplateTypes: `Torna ai tipi di modello`,
    addNewAppointmentTemplate: `Aggiungi nuovo modello appuntamento`,
    caremoduleName: `Nome modulo assistenza`,
    selectPathway: `Seleziona un percorso`,
    notShowInDropdownAfterDelete: `Eliminando questo modello non verrà più visualizzato nel menu a discesa`,
    messagesTemplates: `Modelli di messaggi`,
    addNewMessageTemplate: `Aggiungi nuovo modello di messaggio`,
    pathway: `Percorso`,
    template: `Modelli`,
    typesTwo: `2 tipi`,
    scheduledAppointmentInDropdown: `Eliminando questo modello non sarà più visualizzato nei campi a discesa quando si programma una visita.`,
    manageTemplate: `Gestisci il modello`,
    manageTheMessageTemplates: `Gestisci il modello di messaggio`,
    addMdt: `+ Aggiungi un nuovo MDT alla piattaforma`,
    mdts: `MDT`,
    NameAsc: `Nome in ordine ascendente`,
    NameDesc: `Nome in ordine discendente`,
    Teams: `Team`,
    MdtsName: `Nome MDT`,
    managemdts: `Gestisci MDT`,
    members: `Componenti`,
    editTeam: `Modifica il team`,
    addANewMDTToThePlatform: `Aggiungi un nuovo MDT alla piattaforma`,
    week: `Settimana`,
    month: `Mese`,
    year: `Anno`,
    total: `Totale`,
    dailyaverage: `Media giornaliera`,
    nochartdata: `Nessun dato grafico disponibile`,
    youCanOnlyAssignOneMDTAtATime: `È possibile assegnare solo un MDT alla volta localizza`,
    noMoreOptionsAvailable: `Non sono disponibili altre opzioni`,
    mdt: `MDT`,
    relatingPatient: `Relativo a un paziente`,
    nonrelatingPatient: `Non relativo a un paziente`,
    sendMsgPatient: `Invia nuovo messaggio al paziente`,
    expectedResponseTime: `Tempo di risposta previsto dalle 3 alle 4 ore`,
    walkedText: `camminato`,
    walk: `camminare`,
    mymedicalteam: `Il mio team medico`,
    yesterday: `Ieri`,
    close: `Chiudi`,
    passwordUsedBefore: `La nuova password è stata utilizzata in precedenza e non può essere riutilizzata. Inserisci un’altra password.`,
    sendMessageTo: `Invia messaggio a`,
    message: `Messaggio`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} ha aggiunto ${params[1]} alla conversazione`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} ha rimosso ${params[1]} dalla conversazione`,
    removedParticipant: `Partecipante rimosso`,
    noMessagesSelected: `Non hai messaggi selezionati`,
    noMessagesSelectedDesc: `Seleziona un messaggio sul lato sinistro dello schermo o inizia una nuova conversazione`,
    mfaMethodExplanationRegistration: `Questo codice di sicurezza è necessario per accedere al tuo account. Puoi ottenere il codice di accesso utilizzando il tuo cellulare o l’e-mail. Scegli il metodo più adatto a te.\n\nTieni presente che in questo momento puoi scegliere solo un metodo di verifica. Una volta effettuata la scelta, la preferenza verrà salvata e non potrà essere modificata senza contattare l’helpdesk.`,
    signinCodeRequired: `Richiedi codice di sicurezza`,
    securityCodeRequired: `Questo codice di sicurezza è necessario per accedere al tuo account. Puoi ottenere il codice di accesso utilizzando il metodo scelto durante la prima registrazione.`,
    newMfaUserDesc1: `Questo codice di sicurezza è necessario per accedere al tuo account. Puoi ottenere il codice di accesso utilizzando il tuo cellulare o l’e-mail. Scegli il metodo più adatto a te.`,
    newMfaUserDesc2: `Tieni presente che in questo momento puoi scegliere solo un metodo di verifica. Una volta effettuata la scelta, la preferenza verrà salvata e non potrà essere modificata senza contattare l’helpdesk.`,
    feelFreeToMessageTeam: `Inizia quando vuoi una conversazione con qualcuno del tuo team.`,
    noFutureMessages: `Non hai ancora messaggi`,
    chatSelfRemove: `Ti sei rimosso correttamente dalla conversazione`,
    noResultFound: `Nessun risultato trovato`,
    chatUpdated: `Chat aggiornata correttamente`,
    chatNotUpdated: `Chat non aggiornata`,
    searchPlaceholder: `Cerca un modello...`,
    editPrefillTemplate: `Modifica modello precompilato`,
    forAppointments: `Per appuntamenti`,
    addTemplateToList: `Aggiungi modello all'elenco`,
    addNewPrefillTemplate: `Aggiungi nuovo modello precompilato`,
    forMessages: `Per messaggi`,
    editNewPrefillTemplate: `Aggiungi nuovo modello precompilato`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
