export const LANG_NL_TRANS = {
    accept: `Accepteren`,
    accepted: `Geaccepteerd`,
    acceptedInvitation: `Je hebt deze uitnodiging geaccepteerd.`,
    actions: `Acties`,
    addHcp: `Voeg zorgverlener toe aan platform`,
    addHCPTag: `+ zorgverlener`,
    addHcpToPlatform: `Voeg een zorgverlener toe aan het platform`,
    addNewHCP: `+ Voeg nieuwe zorgverlener toe aan het platform`,
    addNewPatient: `+ Voeg een nieuwe patiënt toe aan het platform`,
    addPatient: `Voeg patiënt toe`,
    addPatientConsent: `Hierbij bevestig ik dat ik toestemming van de patiënt heb gekregen om zijn patiëntgegevens in te voeren.`,
    addPatientToPlatform: `Patiënt aan platform toevoegen`,
    administration: `Beheer`,
    agreed: `Akkoord`,
    allHcps: `Alle zorgverleners`,
    allowNotifications: `Je hebt meldingen ingeschakeld, super!`,
    allPatients: `Alle patiënten`,
    almostHalfway: `Je bent bijna op de helft!`,
    almostThere: `Je bent er bijna!`,
    am: `AM`,
    andMore: (params: string[]) => `en ${params[0]} meer`,
    apiErrorGetConsentDocument: `Het toestemmingsformulier is niet geladen. Klik hier om het opnieuw te proberen.`,
    appointment: `Afspraak`,
    appointmentAcceptedByPatient: `Geaccepteerd door patiënt`,
    appointmentAwaitingPatientResponse: `In afwachting van reactie patiënt`,
    appointmentDeclinedByPatient: `Afgewezen door patiënt`,
    appointmentName: `Afspraakomschrijving`,
    appointmentNotification: `Afspraakmelding`,
    appointments: `Afspraken`,
    appointmentsForPatient: (params: string[]) => `Afspraken voor ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `Een afspraak kan worden gepland tussen ${params[0]} en ${params[1]}`,
    appUnavailable: `Het spijt ons, de app is momenteel niet beschikbaar. Probeer het later opnieuw of controleer op updates.`,
    april: `April`,
    ar: `Arabisch`,
    areYouSureDeclineMessage: `Om je te helpen bij het voorbereiden en bewaken van je voortgang is het voor het zorgteam belangrijk dat je aangemeld bent op het platform. Neem contact op met de arts die je doorverwezen heeft als je geen gebruik wilt maken van het platform.`,
    areYouSureDeclineTitle: `Weet je zeker dat je geen gebruik wilt maken van het Care4Today-platform?`,
    areYouSureDeleteNote: `Weet je zeker dat je deze notitie wilt verwijderen?`,
    article: `Artikel`,
    assignToMDT: `Toewijzen aan multidisciplinair team`,
    audio: `Audio`,
    august: `Augustus`,
    back: `Terug`,
    backToAppointments: `Terug naar je afspraken`,
    backToDetails: (params: string[]) =>
        `Terug naar de gegevens van ${params[0]}`,
    backToLogin: `Terug naar Inloggen`,
    backToPatientProfile: `Terug naar patiëntprofiel`,
    badPassword: `Je hebt een ongeldig wachtwoord ingevuld.`,
    bariatrics: `Bariatrie`,
    blockedUser: `Je gebruiker is geblokkeerd. Probeer het over een half uur opnieuw.`,
    bmi: `BMI`,
    bookedSuccess: `Je afspraak is ingepland`,
    cancel: `Annuleren`,
    cancelAlert: `Annuleren`,
    cantParseError: `Kan geen reactie uitlezen.`,
    cantSaveImage: `Kan afbeelding niet opslaan.`,
    care4Today: `Care4Today`,
    careModules: `Zorgmodules`,
    changePassword: `Verander wachtwoord`,
    changePasswordSubtitle: `Kies je eigen wachtwoord.`,
    changePasswordTitle: `Kies je eigen wachtwoord`,
    choosePicture: `Kies foto`,
    chooseProfilePicture: `Verander foto`,
    cm: `cm`,
    completed: `Voltooid`,
    conditionalGoal: `Beoogd doel`,
    confirmAppointmentDelete: `Weet je zeker dat je deze afspraak wilt verwijderen?`,
    confirmed: `Bevestigd`,
    confirmNewPasswordPlaceholder: `Bevestig nieuw wachtwoord`,
    consent: `Toestemming`,
    consentDontAgree: `Ik ga niet akkoord en zal het Care4Today-platform niet gebruiken`,
    consentedOn: (params: string[]) =>
        `Je hebt toestemming gegeven op ${params[0]}`,
    contact: `Contact`,
    contactDetails: `Contactgegevens`,
    contactInfo: `CONTACTINFORMATIE`,
    contentDescApptIcon: `Afspraak icoon`,
    contentDescAttachImage: `Voeg afbeelding toe`,
    contentDescAttachment: `Bijlage`,
    contentDescAttachmentImg: `Volledig scherm`,
    contentDescBackground: `Achtergrond`,
    contentDescChangePwdIcon: `Wachtwoord wijzigen icoon`,
    contentDescClose: `Sluit het volledige scherm`,
    contentDescDeleteAttachment: `Verwijder bijlage met afbeelding`,
    contentDescDevicesIcon: `Gekoppelde apparaten icoon`,
    contentDescEduContentExpandBtn: `Open bijlage met educatiemateriaal`,
    contentDescEduContentThumb: `Bijlage met educatiemateriaal`,
    contentDescEduItemCompleted: `Educatie onderdeel is voltooid`,
    contentDescEduItemIncomplete: `Educatie onderdeel is niet voltooid`,
    contentDescGoalIcon: `Persoonlijk doel icoon`,
    contentDescHelpIcon: `Hulp icoon`,
    contentDescKillswitchIcon: `Killswitch icoon`,
    contentDescLegalIcon: `Juridische documenten icoon`,
    contentDescLogo: `Applicatielogo`,
    contentDescLogoutIcon: `Uitloggen icoon`,
    contentDescMdtPic: `Foto zorgprofessional`,
    contentDescMessageIcon: `Berichten icoon`,
    contentDescNoGoalIcon: `Geen doel icoon`,
    contentDescPathwayCurrent: `Huidige fase icoon`,
    contentDescPathwayIcon: `Zorgpad icoon`,
    contentDescPathwayOtherPhase: `Andere fase icoon`,
    contentDescProfilePic: `Profielfoto`,
    contentDescSend: `Versturen`,
    create: `Aanmaken`,
    createAMedicalTeam: `Medisch team aanmaken`,
    createAppointment: `Maak afspraak aan`,
    createAppointmentButton: `Maak afspraak aan en verstuur uitnodiging`,
    createAppointmentSuccess: `Afspraak succesvol aangemaakt`,
    createAppt: `Maak afspraak aan`,
    createMDT: `Maak MDT aan`,
    currentBmi: `Huidige BMI`,
    currentPhase: `Huidige fase`,
    currentWeight: `Huidig gewicht`,
    dashboard: `Dashboard`,
    date: `Datum`,
    dateOfBirth: `Geboortedatum`,
    dateOfConsent: `Datum van toestemming`,
    dateOfConsentAsc: `Datum van toestemming oplopend`,
    dateOfConsentDesc: `Datum van toestemming aflopend`,
    dateOfSurgery: `Operatiedatum *`,
    december: `December`,
    decline: `Afwijzen`,
    declined: `Afgeslagen`,
    declinedInvitation: `Je hebt deze uitnodiging afgeslagen.`,
    declinedNotifications: `Weet je zeker dat je geen meldingen wilt ontvangen? Je kunt dit wijzigen in het instellingenmenu.`,
    declinedSuccess: `Je hebt de afspraak afgeslagen`,
    defaultError: `Er is iets verkeerd gegaan`,
    delete: `Verwijderen`,
    deleteAppointmentSuccess: `Afspraak succesvol verwijderd`,
    deleteNote: `Notitie verwijderen`,
    deleting: `Verwijderen…`,
    description: `Omschrijving`,
    details: `Gegevens`,
    devices: `Gekoppelde apparaten`,
    disagreeConsentError: `Er is een fout opgetreden tijdens het niet akkoord gaan met de toestemming. Probeer het opnieuw`,
    discardChanges: `Veranderingen ongedaan maken?`,
    document: `Document`,
    done: `Gereed`,
    draftWontBeSaved: `Je concept zal niet worden opgeslagen. Wil je toch annuleren?`,
    duplicateMDT: `Zorgverlener al geselecteerd`,
    edit: `Bewerken`,
    editHcpsProfile: `Bewerken zorgverlenersprofiel`,
    editMessageDetails: `Bewerken gespreksgegevens`,
    editMTDTeam: (params: string[]) => `Bewerk team voor ${params[0]}`,
    editPassword: `Pas wachtwoord aan`,
    editPatient: `Bewerk patiënt`,
    editPatientError: `Er is een probleem opgetreden tijdens het bijwerken van de patiëntgegevens`,
    editPatientSuccess: `Patiëntgegevens succesvol bijgewerkt.`,
    editProfile: `Bewerken profiel`,
    editProfilePicture: `Bewerken profielfoto`,
    editSubject: `Bewerken onderwerp`,
    editTeamMembers: `Bewerken teamleden`,
    editYourPersonalGoal: `Je persoonlijke doel aanpassen`,
    eduContentHint: `Klik op de knop voor extra informatie.`,
    email: `E-mail`,
    emailAddress: `E-mailadres`,
    emailConfirmation: (params: string[]) =>
        `We hebben een e-mail naar ${
            params[0]
        } verstuurd met een link om het wachtwoord opnieuw in te stellen.`,
    emailExists: (params: string[]) =>
        `Er bestaat al een gebruiker met dit e-mailadres.`,
    emailSent: `E-mail verstuurd`,
    en: `Engels`,
    enableNotifications: `Activeer meldingen`,
    enterANewHCP: `Vul een nieuwe zorgverlener in`,
    enterSubjectHint: `Vul onderwerp in`,
    enterTheSubject: `Vul het onderwerp in voor dit gesprek.`,
    errorEditingHcp: `Er is een fout opgetreden tijdens het bewerken van de zorgverlener`,
    errorFindingConsentDocument: `Fout tijdens zoeken naar toestemmingsdocument.`,
    errorLoading: (params: string[]) => `Fout tijdens laden van ${params[0]}`,
    errorSavingSettings: `Fout tijdens opslaan van instellingen`,
    errorUpdatingPassword: `Kon wachtwoord niet bijwerken`,
    excessWeightLost: `Overmatig gewichtsverlies`,
    failEditHcp: `Er is een fout opgetreden tijdens het bewerken van je profiel`,
    february: `Februari`,
    female: `Vrouw`,
    filter: `Filteren`,
    firstName: `Voornaam`,
    forgotPasswordInstruction: `Vermeld het e-mailadres waarmee je bent geregistreerd in jouw ziekenhuis. We sturen je een e-mail met een link om jouw wachtwoord opnieuw in te stellen.`,
    forgotPasswordViewTitle: `Wachtwoord vergeten`,
    forgotYourPassword: `Je wachtwoord vergeten?`,
    formTimeRangeInPast: `De tijdsperiode kan niet in het verleden liggen`,
    formTimeRangeStartGreaterThanEnd: `De tijdsperiode is ongeldig`,
    forPatient: `Voor`,
    from: `Van`,
    ft: `ft`,
    fullName: `Volledige naam`,
    function: `Functie`,
    gained: `aangekomen`,
    gender: `Geslacht`,
    goal: `Doel`,
    goalSavedError: `Het doel kon niet worden opgeslagen!`,
    goalSavedSuccess: `Doel is succesvol opgeslagen!`,
    goBack: `Ga terug`,
    hcps: `Zorgverleners`,
    healthCareProfessionals: (params: string[]) => `${params[0]} zorgverleners`,
    height: `Lengte`,
    help: `Help`,
    heyChooseYourPicture: (params: string[]) =>
        `Hallo ${params[0]}, kies je profielfoto`,
    iAgree: `Ik ga akkoord`,
    iAgreeFormat: (params: string[]) =>
        `Ik ga akkoord (${params[0]}/${params[1]})`,
    iAmSure: `Ik ben er zeker van`,
    idealBodyWeight: `Ideaal lichaamsgewicht`,
    iDoNotAgree: `Ik ga niet akkoord`,
    iDontAgree: `Ik ga niet akkoord en zal het Care4Today-platform niet gebruiken`,
    imperial: `Imperial`,
    in: `in`,
    includeLinkToLocation: `Voeg een link naar de locatie toe`,
    initialWeight: `Startgewicht`,
    installUpdate: `Installeer update`,
    invalidEmailError: `Geen geldig e-mailadres`,
    invalidNumber: `Vul een geldig nummer in`,
    invalidTokenError: `De verificatie is mislukt. Probeer opnieuw in te loggen.`,
    it: `Italiaans`,
    iWantToFitAgain: `Voorbeeld: “Ik wil maat L weer aan kunnen”`,
    january: `Januari`,
    july: `Juli`,
    june: `Juni`,
    keepGoing: `Ga zo door!`,
    keepMomentum: `Houd dit vast!`,
    kg: `kg`,
    kilogrammes: `kilogram`,
    language: `Taal`,
    languageRequired: `Taal *`,
    lastName: `Achternaam`,
    lb: `pond`,
    learningMaterials: `Lesmateriaal`,
    legalDocuments: `Juridische documenten`,
    loading: `Bezig met laden…`,
    loadingPatients: `Patiëntengegevens worden geladen, een ogenblik geduld`,
    location: `Locatie`,
    locationUrl: `Locatie-URL`,
    lockScreenHint: `Je moet een vergrendelscherm voor het apparaat instellen om veilig gebruik van de app te kunnen maken.`,
    login: `Inloggen`,
    loginIncorrect: `Het E-mailadres of wachtwoord dat je hebt ingevuld, is onjuist`,
    logout: `Uitloggen`,
    logoutAreYouSure: `Weet je zeker dat je wilt uitloggen?`,
    loseBefore: (params: string[]) => `${params[0]} afvallen`,
    loseFormat: (params: string[]) => `${params[0]} ${params[1]} afvallen`,
    lost: `afgevallen`,
    male: `Man`,
    manageHCPs: `Beheer zorgverleners`,
    managePatients: `Beheer patiënten`,
    march: `Maart`,
    may: `Mei`,
    mdtTeam: `MDT-team`,
    mdtTeamNotAddedYet: `MDT nog niet toegewezen.`,
    mdtTeamUC: `MDT-TEAM`,
    medicalTeam: `Medisch team`,
    meetingInvite: `Je hebt een afspraak`,
    meetingInviteWith: (params: string[]) => `Afspraak met ${params[0]}`,
    messageCreated: `Gesprek succesvol gestart.`,
    messageNotCreated: `Het is niet gelukt om een gesprek te starten.`,
    messageNotification: `Melding bericht`,
    messageNotSent: `Bericht niet verstuurd`,
    messages: `Berichten`,
    metric: `Metrisch`,
    movePhaseConfirmation: (params: string[]) =>
        `Weet je zeker dat je ${params[0]} naar fase ${
            params[1]
        } wilt overzetten?`,
    moveToNextPhase: `Ga naar volgende fase`,
    multiDisTeam: `Multidisciplinair team`,
    myMessages: `Mijn berichten`,
    myMotivation: `Mijn motivatie:`,
    myPersonalGoal: `Mijn persoonlijk doel`,
    myProfile: `Mijn profiel`,
    myTeam: `Mijn team`,
    name: `Naam`,
    nameOfMDT: `Naam van MDT *`,
    needsConsent: `De patiënt moet eerst toestemming verlenen.`,
    networkError: `Er is een netwerkfout opgetreden`,
    newAppointment: `Nieuwe afspraak`,
    newChat: `Nieuw gesprek`,
    newInvitation: `Nieuwe uitnodiging`,
    newMessageNotificationMore: (params: string[]) =>
        `Je hebt ${
            params[0]
        } nieuwe berichten. Open de app om te zien wat er nieuw is.`,
    newMessageNotificationOne: `Je hebt een nieuw bericht. Open de app om te zien wat er nieuw is.`,
    newNote: `Nieuwe notitie`,
    newPasswordPlaceholder: `Nieuw wachtwoord`,
    newPatientSuccess: (params: string[]) =>
        `Je hebt ${params[0]} succesvol toegevoegd aan het platform.`,
    newTeamFail: `MDT-team niet toegewezen`,
    newTeamSuccess: `MDT-team toegewezen`,
    newVersionApp: `Update deze app naar de nieuwste beschikbare versie in de app store.`,
    nextAppointment: `Volgende afspraak`,
    nextSelectCareModule: `Volgende: Selecteer zorgmodules`,
    nextSurgeryInformation: `Volgende: Informatie over operatie`,
    niceToSeeYouAgain: `Fijn je weer te zien!`,
    nickname: `Bijnaam`,
    nicknameError: `Ongeldige bijnaam. Speciale tekens zijn niet toegestaan.`,
    nl: `Nederlandse`,
    no: `Nee`,
    noAppointments: `Er zijn geen afspraken beschikbaar`,
    noCurrentGoalForPatient: `Er is voor deze patiënt momenteel geen doel vastgesteld`,
    noDate: `geen datum ingesteld`,
    noFutureAppointments: `Geen aankomende afspraken`,
    noGoalSet: `Geen doel gesteld door jouw zorgverlener`,
    noMatchingConsentDocumentsFound: `Geen bijbehorende toestemmingsdocumenten gevonden`,
    noMessages: `Er zijn geen berichten beschikbaar`,
    noNetworkConnection: `Geen netwerkverbinding. Controleer…`,
    noNotesMessage: `Er zijn geen notities beschikbaar. Klik op 'Aanmaken' om nieuwe notities toe te voegen`,
    noPersonalGoalSet: `Geen persoonlijk doel ingesteld.`,
    noPersonalGoalSetDashboard: `Geen persoonlijk doel ingesteld. Ga naar de instellingenpagina om deze bij te werken.`,
    noPlannedAppointments: `Geen geplande afspraken`,
    noPreview: `Geen voorbeeld beschikbaar`,
    noProgressRecorded: `Geen voortgang vastgelegd`,
    noResponseError: `Geen antwoord ontvangen.`,
    notAgreed: `Niet akkoord`,
    noteDeletedError: `De opmerking kon niet worden verwijderd!`,
    noteDeletedSuccessfully: `Opmerking succesvol verwijderd!`,
    notes: `Opmerkingen`,
    noteSaved: `Opmerking opgeslagen`,
    noteSavedError: `De opmerking kon niet worden opgeslagen!`,
    noteSavedSuccess: `Opmerking opgeslagen!`,
    noteSaveError: `Fout, kan opmerking niet opslaan. Opnieuw proberen?`,
    notifications: `Meldingen`,
    notNow: `Niet nu`,
    notSet: `Niet ingesteld`,
    notYetSubmitted: `Nog niet verstuurd`,
    noUnreadMessages: `Geen ongelezen berichten`,
    noUserFound: `Gebruiker niet gevonden met verstrekte gegevens.`,
    november: `November`,
    noWeightDifference: `Geen gewichtsverschil`,
    october: `Oktober`,
    ok: `OK`,
    onboardingNotificationsTitle: `We willen je blijvend op de hoogte houden`,
    onboardingNotifictionsInfo: `Je ontvangt een melding over: Je afspraken. Nieuwe berichten van je medische team`,
    onVar: (params: string[]) => `op ${params[0]}`,
    openCare: `Open Care4today en controleer of je nieuwe meldingen hebt!`,
    optOutSubtitle: `Neem contact op met de zorgverlener die jou heeft doorverwezen als je niet wilt deelnemen aan het platform.`,
    optOutTitle: `Weet je zeker dat je niet wilt deelnemen aan het Care4Today-platform?`,
    organisation: `Organisatie`,
    orthopedics: `Orthopedie`,
    other: `Anders`,
    outdatedVersion: `Je gebruikt momenteel een verouderde versie van de app.`,
    overview: `Overzicht`,
    participant: `Deelnemer`,
    password: `Wachtwoord`,
    passwordComplexityError: `Het wachtwoord moet minimaal 8 tekens lang zijn en minimaal 2 van de volgende soorten tekens bevatten: Hoofdletters, kleine letters, cijfers of symbolen.`,
    passwordMismatchError: `Wachtwoorden komen niet overeen`,
    passwordUpdated: `Wachtwoord bijgewerkt`,
    pastAppointments: `Vorige afspraken`,
    pathwayScheduleFail: `Er is een fout opgetreden. Het zorgpadschema kan niet worden bijgewerkt`,
    patient: `Patiënt`,
    patientAge: (params: string[]) => `${params[0]} jaar`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} jaar`,
    patientConsent: `Toestemming patiënt`,
    patientNameAsc: `Patiëntnaam oplopend`,
    patientNameDesc: `Patiëntnaam aflopend`,
    patientRegistration: `Patiëntregistratie`,
    patients: `Patiënten`,
    patientsCount: (params: string[]) => `${params[0]} patiënten`,
    patientsOverview: `Patiëntenoverzicht`,
    pending: `Lopend`,
    percent: `%`,
    personalGoal: `Persoonlijk doel`,
    personalGoalEdit: `Persoonlijk doel`,
    personalPassword: `Persoonlijk wachtwoord`,
    personalPasswordHelper: `Kies je eigen wachtwoord. Je kunt je wachtwoord altijd opnieuw instellen in het instellingenmenu.`,
    phoneError: `Ongeldig telefoonnummer. Gebruik alleen cijfers (geen haakjes, koppeltekens of plustekens)`,
    phoneNumber: `Telefoonnummer`,
    picture: `Foto`,
    pictureInstructions: `Kies je eigen profielfoto. Deze foto wordt gebruikt voor je eigen account.`,
    pleaseConnect: `Maak verbinding met internet om ervoor te zorgen dat je de nieuwste versie van de app gebruikt.`,
    pleaseContactYourHospital: `Neem in geval van nood rechtstreeks contact op met je ziekenhuis.`,
    pleaseProvidePassword: `Vul je wachtwoord in ter bevestiging:`,
    pm: `PM`,
    pounds: `pond`,
    preparation: `Voorbereiding`,
    preSurgeryPrep: `Voorbereiding op operatie`,
    previous: `Vorige`,
    privacyPolicy: `Privacybeleid`,
    profileLabel: `We zullen deze informatie als adressering gebruiken in e-mails, sms-berichten en in deze app. We zullen deze informatie ook doorgeven aan jouw medisch team.`,
    profilePicture: `Profielfoto`,
    profileTitle: `We zullen deze informatie als adressering gebruiken in e-mails, sms-berichten en in deze app. We zullen deze informatie ook doorgeven aan jouw medisch team.`,
    progress: `Voortgang`,
    progressMsgForgotPwd: `Valideren…`,
    progressMsgLoading: `Bezig met laden…`,
    progressMsgLoadingContent: `Inhoud laden…`,
    progressMsgLogin: `Zorgpad wordt geladen, Dit kan tot 1 minuut duren…`,
    progressMsgMdtLoading: `MDT laden…`,
    progressMsgNotesLoading: `Notities laden…`,
    progressMsgProfileEdit: `Profiel opslaan…`,
    progressMsgProfilePhoto: `Foto opslaan…`,
    progressMsgResetPwd: `Wachtwoord opslaan…`,
    provideTheEmail: `Vermeld het e-mailadres waarmee je bent geregistreerd in het ziekenhuis.`,
    pwdValidationDoesNotMatch: `De wachtwoorden komen niet overeen`,
    pwdValidationIllegal: `Bevat ongeldige tekens`,
    pwdValidationNotComplex: `Wachtwoord is niet sterk genoeg`,
    pwdValidationTooShort: `Je wachtwoord is te kort`,
    quickFilter: `Snel filteren`,
    remindmeLater: `Help me herinneren`,
    requiredFields: `Verplichte velden`,
    requiredHCPs: `Zorgverleners *`,
    resetPassword: `Wachtwoord opnieuw instellen`,
    respond: `Reageren`,
    retry: `Opnieuw proberen`,
    save: `Opslaan`,
    saveAndContinue: `Opslaan en doorgaan`,
    saveChanges: `Wijzigingen opslaan`,
    scheduleNewAppointment: `Plan een nieuwe afspraak`,
    searchInConversation: `Zoeken in gesprekken…`,
    secureRealmError: `Starten niet gelukt - vergrendelscherm moet ingeschakeld zijn`,
    selectDifferentImage: `Selecteer een andere foto`,
    selectFile: `Selecteer bestand`,
    selectFunction: `Selecteer functie`,
    selectLanguage: `Selecteer taal`,
    selectOneOrMoreHCPs: `Selecteer een of meer zorgverleners`,
    selectPictureSource: `Selecteer foto uit`,
    selectProfilePicture: `Selecteer een profielfoto`,
    selectSurgeon: `Selecteer chirurg`,
    send: `Versturen`,
    sendMessage: `Verstuur bericht`,
    sendNewMessage: `Verstuur een nieuw bericht`,
    september: `September`,
    setPassword: `Stel een wachtwoord in`,
    setPasswordReminder: `Je kunt je wachtwoord altijd opnieuw instellen in het instellingenmenu.`,
    settings: `Instellingen`,
    setup: `INSTELLINGEN`,
    setYourPersonalGoal: `Stel je persoonlijke doel in`,
    someonesPathway: (params: string[]) => `${params[0]}'s zorgpad`,
    sortBy: `Sorteer op`,
    splashSubtitle: `Gewichtsverliesoperatie`,
    start: `Beginnen`,
    startANewConversation: `Begin een nieuw gesprek`,
    startConversation: `Begin een gesprek`,
    startingPoint: `Startpunt`,
    startNewConversation: `+ Begin een nieuw gesprek`,
    startPreparation: `Begin met jouw voorbereiding`,
    status: `Status`,
    subject: `Onderwerp`,
    subjectChangedSuccess: `Gespreksonderwerp succesvol aangepast`,
    subjectChangeFail: `Gespreksonderwerp niet gewijzigd`,
    submit: `Versturen`,
    subPhase: `Subfase`,
    successEditHcp: `Je hebt je profiel aangepast`,
    surgeon: `Chirurg`,
    surgeryInformation: `Informatie over operatie`,
    tasks: `taken`,
    tasksCompleted: `Taken voltooid`,
    team: `Team`,
    thisMonth: `Deze maand`,
    time: `Tijd`,
    timeAndLocation: `Tijd en Locatie`,
    timeOfSurgery: `Operatietijd *`,
    to: `Aan`,
    today: `Vandaag`,
    toDo: `Te doen`,
    undo: `Ongedaan maken`,
    unitRequired: `Eenheid *`,
    units: `Eenheden`,
    unknown: `Zeg ik liever niet`,
    unknownError: `Er is een fout opgetreden tijdens het verwerken. Probeer het opnieuw…`,
    unknownGender: `Ik geef liever geen antwoord`,
    unknownUser: `Onbekend`,
    unreadMessage: `Ongelezen bericht`,
    unreadMessages: `Ongelezen berichten`,
    untitled: `Naamloos…`,
    update: `Bijwerken`,
    updateAppointment: `Bewerken afspraak`,
    updateAppointmentButton: `Sla wijzigingen op en verstuur updates`,
    updateAppointmentSuccess: `Afspraak succesvol bijgewerkt`,
    updateMessage: `Je moet deze app vanuit de app store updaten naar de meest recente versie om de app te kunnen blijven gebruiken`,
    updateProfilePicture: `Update profielfoto`,
    updateProgress: `Update voortgang`,
    useCamera: `Gebruik camera`,
    username: `Gebruikersnaam`,
    video: `Video`,
    viewAllMessages: `Bekijk alle berichten`,
    viewAndEditPathway: `Bekijk en wijzig de data van het zorgpad`,
    viewDocument: `Bekijk document`,
    weight: `Gewicht`,
    weightLoss: `Gewichtsverlies`,
    weightUpdatedSuccess: `Huidige gewicht is succesvol bijgewerkt`,
    welcomeHeader: `Welkom`,
    welcomeMessage: (params: string[]) => `Hallo ${params[0]}!`,
    wellDoneNextStep: `Goed gedaan! Je bent klaar om naar de volgende fase te gaan!`,
    withdrawConfirm: `Oké, verlaat app`,
    withdrawConsent: `Trek toestemming in`,
    withdrawConsentBody: `Door jouw toestemming voor het verwerken van jouw persoonsgegevens in te trekken, worden jouw lokale gegevens, zoals opmerkingen en persoonlijke doelen, verwijderd. Na een wachtperiode van 30 dagen heb je geen toegang meer tot de applicatie.`,
    withdrawConsentTitle: `Weet je zeker dat je je wilt afmelden voor het Care4Today-platform?`,
    writeAMessage: `Schrijf een bericht…`,
    writeSomething: `Schrijf iets…`,
    wrongUserName: `De gebruikersnaam die je hebt ingevuld, is onjuist`,
    xUnread: (params: string[]) => `${params[0]} ongelezen`,
    yes: `Ja`,
    yesDelete: `Ja, verwijderen`,
    yesDiscard: `Ja, negeren`,
    youAreOffline: `Je bent offline`,
    youCanSetASentence: `Je kunt hier een zin instellen om jezelf te motiveren om je persoonlijke doel te bereiken.`,
    youGained: (params: string[]) => `Je bent ${params[0]} aangekomen`,
    youGainedFormat: (params: string[]) =>
        `Je bent ${params[0]} ${params[1]} aangekomen`,
    youHaveANewMessageFrom: (params: string[]) =>
        `Je hebt een nieuw bericht van ${params[0]}.`,
    youHaveNewAppointment: `Je hebt een nieuwe afspraak. Open de app om te zien wat er nieuw is.`,
    youHaveNewAppointments: (params: string[]) =>
        `Je hebt ${
            params[0]
        } nieuwe afspraken. Open de app om te zien wat er nieuw is.`,
    youHaveNewMessage: `Je hebt een nieuw bericht. Open de app om te zien wat er nieuw is.`,
    youHaveNewMessages: (params: string[]) =>
        `Je hebt ${
            params[0]
        } nieuwe berichten. Open de app om te zien wat er nieuw is.`,
    youHaveUndone: `Je hebt een eerder gekozen optie ongedaan gemaakt`,
    youLost: (params: string[]) => `Je bent ${params[0]} afgevallen`,
    youLostFormat: (params: string[]) =>
        `Je bent ${params[0]} ${params[1]} afgevallen`,
    yourAppointments: `Jouw afspraken`,
    yourGoals: `Jouw doelen`,
    yourNote: `Jouw opmerking`,
    yourPassword: `Jouw wachtwoord`,
    yourPasswordHasBeenReset: `Jouw wachtwoord is opnieuw ingesteld`,
    yourProfile: `Jouw profiel`,
    export: `Exporteren`,
    exportData: `Exporteer persoonlijke gegevens`,
    exportDataFail: `Er is een fout opgetreden. Gegevens kunnen niet worden geëxporteerd`,
    exportMyData: `Exporteer mijn persoonlijke gegevens`,
    goalStepCount: `Doel (stappen/dag)`,
    loadingPathway: `Zorgpad wordt geladen, dit kan tot 1 minuut duren`,
    loadingPatient: `Patiëntgegevens worden geladen, een ogenblik geduld`,
    pleaseEnterTotalSteps: `Vul aan het einde van elke dag het totale aantal stappen in`,
    stepCount: `Aantal stappen`,
    stepsPerDay: `stappen/dag`,
    walkStepsPerDay: (params: string[]) => `Loop ${params[0]} stappen/dag`,
    steps: `Stappen`,
    avgWeeklySteps: `Gemiddeld aantal stappen deze week`,
    rightToBeForgotten: `Verwijder mijn persoonlijke gegevens`,
    totalStepsDuringDay: `Totaal aantal stappen gelopen gedurende een dag`,
    youAlreadyWalked: (params: string[]) =>
        `Je hebt vandaag ${params[0]} stappen gelopen`,
    rightToBeForgottenTitle: `Weet je zeker dat je jouw persoonsgegevens wilt verwijderen?`,
    rightToBeForgottenInfo: `Door dit verzoek in te dienen, worden jouw persoonsgegevens verwijderd en heb je geen toegang meer tot de applicatie. Let erop dat sommige persoonsgegevens, zoals je naam verstuurd uit het ziekenhuisinformatiesysteem, nog steeds getoond kunnen worden in de afspraken. Neem voor verdere vragen contact op met support@care4todaypatient.com. Vul jouw wachtwoord in ter bevestiging:`,
    passwordHint: `Jouw wachtwoord`,
    rightToBeForgottenSuccess: `Het verzoek voor het verwijderen van persoonsgegevens is verstuurd naar de mailbox van de supportafdeling van Care4Today`,
    incorrectPassword: `Onjuist wachtwoord ingevuld`,
    errorInitiatingRightToBeForgotten: `Fout bij indienen aanvraag, neem rechtstreeks contact op met ondersteuning`,
    updateStepCount: `Update het aantal stappen`,
    mon: `Ma`,
    tue: `Di`,
    wed: `Wo`,
    thu: `Do`,
    fri: `Vr`,
    sat: `Za`,
    sun: `Zo`,
    stepsAmount: (params: string[]) => `${params[0]} stappen`,
    stepsGoalUpdateSuccess: `Aantal stappen succesvol toegevoegd`,
    search: `Zoeken…`,
    successEditMDT: `MDT succesvol bijgewerkt`,
    failEditMDT: `Er is een fout opgetreden tijdens het bijwerken van het MDT`,
    userCreationError: `Er is een fout opgetreden tijdens het aanmaken van de gebruiker`,
    userUpdateSuccess: `Gebruiker is succesvol bijgewerkt`,
    legal: `Juridisch`,
    termsOfUse: `Gebruiksvoorwaarden`,
    disclaimer: `Niet-aansprakelijkheidsverklaring`,
    exportDataSuccessV1: `Verzoek om persoonsgegevens te exporteren is verstuurd aan support afdeling van Care4Today`,
    exportDataSuccess: `Persoonsgegevens exporteren gestart`,
    dataFormatV1: `Jouw persoonsgegevens worden geëxporteerd naar CSV-formaat. Het bestand zal naar jouw e-mailadres worden verstuurd.`,
    dataFormat: `Jouw persoonsgegevens worden geëxporteerd naar JSON-formaat. Het bestand zal naar jouw e-mailadres worden verstuurd.`,
    viewAllMaterials: `Bekijk alle materialen`,
    viewAllAppointments: `Bekijk alle afspraken`,
    enjoyYourDay: `Geniet van je vrije dag!`,
    motivateAlmost: `Je bent er bijna!`,
    startConversationHcp: `Begin een gesprek met een zorgverlener`,
    andYou: `, je`,
    viewAllNotifications: `Bekijk alle meldingen`,
    noInvitations: `Geen uitnodigingen`,
    yourTimeline: `Jouw tijdlijn`,
    currentSubphase: `Huidige subfase`,
    updateWeight: `Huidig gewicht bijwerken`,
    teamLoading: `Teamgegevens worden geladen`,
    noMdt: `Geen multidisciplinair team toegewezen.`,
    teamDetails: `Bekijk teamgegevens`,
    showResolved: `Tonen dat het opgelost is`,
    readDoc: `Lees document`,
    consultationNotes: `Gespreksnotities`,
    viewAllConsultationNotes: `Kijkend naar artikel 18 van de AVG, wat geldt voor jouw situatie?`,
    createNewNote: `+ Maak een nieuwe notitie`,
    dismiss: `Opzeggen`,
    pictureError: `Fout bij laden afbeelding`,
    wrongFormat: `Verkeerd beeldformaat`,
    backToDashboard: `Terug naar dashboard`,
    noMessage: `Geen berichten`,
    noSpecialCharacters: `Speciale tekens zijn niet toegestaan.`,
    noNotesAvailable: `Geen notities beschikbaar`,
    hcpPortal: `Zorgverlenersportaal`,
    patientPortal: `Patiëntenportaal`,
    consultationNote: `Gespreksverslag`,
    noteTitle: `Titel notitie`,
    noteContents: `Inhoud notitie`,
    writeConsultationNotes: `Leg hier gespreksnotities vast`,
    createHcpNote: `Aanmaken notitie`,
    consultationNoteCreatedBy: (params: string[]) =>
        `Aangemaakt: ${params[0]} door ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `Laatst bewerkt: ${params[0]}`,
    loadingConsultaionNotes: `Laden van gespreksnotities`,
    consultationNotesFor: (params: string[]) =>
        `Gespreksnotities voor ${params[0]}`,
    editHcpNote: `Notitie bewerken`,
    reason: `Reden`,
    writeReasonForEditing: `Leg reden voor bewerking vast …`,
    confirmCancelCreateNote: `Weet je zeker dat je wilt afsluiten zonder de notitie te maken?`,
    confirmCancelEditNote: `Weet je zeker dat je wilt afsluiten zonder de notitie te bewerken?`,
    rotateYourDevice: `Draai je apparaat`,
    patientId: `Patiënt-ID`,
    oldPassword: `Oud wachtwoord`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `Documenten`,
    hcpId: `Zorgverlener-ID`,
    userInactivity: `Je bent uitgelogd vanwege inactiviteit.`,
    duplicateMrn: `Deze zorgverlener-ID bestaat al in Care4Today`,
    confirm: `Bevestigen`,
    viewDetails: `Bekijk details`,
    upperCaseLetters: `Hoofdletters`,
    lowerCaseLetters: `Kleine letters`,
    numbers: `Cijfers`,
    specialCharacters: `Speciale tekens (interpunctie, symbolen)`,
    passwordRequirements: `Het wachtwoord moet uit minimaal 8 tekens bestaan en aan de twee volgende criteria voldoen:`,
    incorrectOldPassword: `Oud wachtwoord is onjuist. Jouw account zal na 5 mislukte pogingen worden geblokkeerd`,
    newPasswordsNotSame: `De nieuwe wachtwoorden die je hebt ingevuld, zijn niet gelijk aan elkaar`,
    passwordSuccesfullyChanged: `Wachtwoord is succesvol gewijzigd`,
    accountBlockedFifteenMinutes: `Jouw account is geblokkeerd. Probeer het na 15 minuten opnieuw`,
    loadingLegalDocuments: `Juridische documenten laden…`,
    fr: `Frans`,
    errorFetchingLegalDocuments: `Fout tijdens het laden van juridische documenten`,
    nameAndMrnNotFound: `De combinatie van patiënt-ID en achternaam is niet gevonden`,
    duplicateNameAndMrn: `De patiënt-ID bestaat al in Care4Today`,
    NSCameraUsageDescription: `Deze app vereist toegang tot de camera om de profielfoto toe te voegen/bij te werken en bijlagen aan de notities toe te voegen`,
    NSPhotoLibraryUsageDescription: `Deze app vereist toegang tot de fotobibliotheek om bijlagen aan notities toe te voegen`,
    initiate: `Starten`,
    lastNameAsc: `Achternaam oplopend`,
    lastNameDesc: `Achternaam aflopend`,
    firstNameAsc: `Voornaam oplopend`,
    firstNameDesc: `Voornaam aflopend`,
    messageParticipantIsInactive: `is niet meer actief`,
    participantNoLonger: `De deelnemer is niet langer een gebruiker van het platform`,
    requestDeletionInProgress: `Jouw verzoek tot verwijdering van je persoonsgegevens is al in behandeling. Het support team zal je informeren zodra je verzoek is afgehandeld.`,
    contactNotAvailableOnDeactivated: `Contactgegevens niet beschikbaar voor gedeactiveerde zorgverlener`,
    deactivated: `Gedeactiveerd`,
    noPermissionToSendMessage: `Je bent niet bevoegd om deze persoon een bericht te sturen`,
    refrainSendingMedData: `Verzend geen berichten met medische gegevens/informatie van de patiënt`,
    refrainEnteringMedData: `Vul in bovenstaand veld geen medische gegevens/informatie van de patiënt in`,
    contactHospitalAppointment: `Neem rechtstreeks contact op met het ziekenhuis als je jouw afspraak moet verzetten of annuleren.`,
    noInfoDescriptionAppointment: `Geen verdere informatie beschikbaar. Neem rechtstreeks contact op met het ziekenhuis als je vragen hebt over jouw afspraak.`,
    noInfoDescriptionAndDateAppointment: `Een update met meer informatie over jouw afspraak volgt binnenkort. Neem rechtstreeks contact op met het ziekenhuis als je vragen hebt over jouw afspraak.`,
    participants: `Deelnemers`,
    noMdtAssigned: `Geen multidisciplinair team toegewezen aan de patiënt. Wijs eerst een team toe aan de patiënt.`,
    scheduled: `Gepland`,
    updated: `Bijgewerkt`,
    proposed: `Voorgesteld`,
    he: `Hebreeuws`,
    restrictProcessingPersonal: `Beperk de verwerking van mijn persoonsgegevens`,
    restrictProcessingArticle: `Kijkend naar artikel 18 van de AVG, wat geldt voor jouw situatie?`,
    dataAccuracy: `Nauwkeurigheid van de gegevens`,
    unlawfulProcessing: `Onwettige verwerking`,
    legalClaim: `Rechtsvordering`,
    provideExplanation: `Geef een toelichting:`,
    provideExplanationDescription: `Geef een toelichting op het probleem zodat de beoordeling van je verzoek verbetert`,
    restrictProcessing: `Beperk de verwerking`,
    sureProcessing: `Weet je zeker dat je de verwerking van jouw persoonsgegevens wilt beperken?`,
    processingPasswordConfirmation: `Door dit verzoek in te dienen, worden jouw gegevens tijdelijk geblokt en, tenzij we je anders laten weten, alleen opgeslagen en verder verwerkt als we jouw toestemming hebben verkregen. Neem voor verdere vragen of om de beperking op te heffen contact op met support@care4todaypatient.com. Vul jouw wachtwoord in ter bevestiging:`,
    processingSent: `Jouw verzoek om de verwerking van je persoonsgegevens te beperken, is verstuurd naar de mailbox van de support afdeling van Care4Today`,
    versionNumber: (params: string[]) => `Versie ${params[0]}`,
    pleaseSelect: `Selecteer:`,
    restrictedLogout: `Je bent uitgelogd omdat jouw verzoek om de verwerking van persoonsgegevens te beperken, is afgehandeld en de beperking is toegepast op jouw Care4Today-account. Als je vragen hebt, kun je contact opnemen met support@care4todaypatient.com`,
    restrictProcessingAlreadyRequested: `Jouw verzoek om de verwerking van persoonsgegevens te beperken, is in behandeling. De support afdeling zal jou informeren zodra jouw verzoek is afgehandeld.`,
    rightToRestrictQuestion: `Kijkend naar artikel 18 van de AVG, wat geldt voor jouw situatie?`,
    rightToRestrictExplanation: `Geef een toelichting:`,
    rightToRestrictTitle: `Beperk de verwerking van mijn persoonsgegevens`,
    rightToRestrictExplanationPlaceholder: `Geef een toelichting op het probleem zodat de beoordeling van jouw verzoek verbetert.`,
    rightToRestrictConfirmationTitle: `Weet je zeker dat je de verwerking van jouw persoonsgegevens wilt beperken?`,
    rightToRestrictConfirmationDescription: `Jouw aanvraag wordt verstuurd naar de support afdeling. Jouw account en gegevens worden tijdelijk geblokkeerd en, tenzij we jou anders laten weten, alleen opgeslagen en verwerkt als we jouw toestemming hebben verkregen. Neem voor verdere vragen of om de beperking op te heffen contact op met support@care4todaypatient.com`,
    assignedRole: (params: string[]) => `Toegekende ${params[0]} (inactief)`,
    requestRestrictionSubmitted: `Jouw verzoek om de verwerking van jouw persoonsgegevens te beperken, is verstuurd naar de mailbox van de support afdeling van Care4Today`,
    temporarelyUnavailableHCPAlertMessage: `De zorgverlener is tijdelijk niet beschikbaar op het platform. Neem in geval van vragen contact op met de support afdeling.`,
    temporarelyUnavailableHCPSubtitle: `De zorgverlener is tijdelijk niet beschikbaar`,
    assignedHCP: (params: string[]) => `Toegekende ${params[0]}`,
    inactive: `Inactief`,
    appointmentInvite: `Je hebt een afspraak`,
    disabledAppointmentActionMessage: `Gebruik rechtstreeks het reserveringssysteem van het ziekenhuis om een afspraak in te plannen, bij te werken of te annuleren.`,
    noFurtherInformation: `Geen verdere informatie beschikbaar`,
    cancelled: `Geannuleerd`,
    cancelledNotificationPrefix: `Geannuleerd:`,
    updatedNotificationPrefix: `Bijgewerkt:`,
    allDay: `De hele dag`,
    editCareModule: `Wijzig zorgmodule`,
    nextSurgeryProcedureInformation: `Volgende: Operatie/proceduregegevens`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${
            params[0]
        } maakt geen deel meer uit van\njouw multidisciplinaire team`,
    editCareModuleWarning: `Houd er rekening mee dat bij het wijzigen van de zorgmodule de geschiedenis van doelen en het lesmateriaal uit de vorige procedure niet meer beschikbaar zal zijn voor de patiënt.`,
    editSurgeryWarning: `Pas de operatie-informatie indien nodig aan.`,
    nextUpdateMDT: `Volgende: Werk medisch team bij`,
    updateCareModule: `Werk zorgmodule bij`,
    editMdtTeamWarning: `Controleer het multidisciplinaire team om te zien of er updates nodig zijn.`,
    participantNotInMDT: `Je maakt geen deel meer uit van het MDT-team voor deze patiënt`,
    createMedicalTeam: `Maak medisch team aan`,
    editMedicalTeam: `Bewerk medisch team`,
    mdtName: `Naam van MDT`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `Weet je zeker dat je de zorgmodule van deze patiënt wilt wijzigen van '${
            params[0]
        }' in '${params[1]}'?`,
    changePathwayConfirmationSubTitle: `Houd er rekening mee dat bij het wijzigen van de zorgmodule de geschiedenis van doelen en het lesmateriaal uit de vorige procedure niet meer beschikbaar zijn voor de patiënt`,
    changePathwaySuccessMessage: (params: string[]) =>
        `Je hebt de Patient ${params[2]} zorgmodule gewijzigd van '${
            params[0]
        }' in '${params[1]}'`,
    mdtChanged: `Jouw medisch team is gewijzigd`,
    tapForDetails: `Tik hier voor meer informatie.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `Toegewezen ${
            params[0]
        } maakt geen deel meer uit van jouw multidisciplinaire team`,
    addPatientReceivedConsent: `Door de onderstaande informatie te verstrekken, verklaar ik dat ik toestemming van de patiënt heb gekregen om zijn patiëntgegevens te verwerken.`,
    attended: `Bijgewoond`,
    entityCreationError: (params: string[]) =>
        `Er is een fout opgetreden tijdens het maken van de ${params[0]}`,
    updateAppointmentError: `Er is een fout opgetreden tijdens het bijwerken van de afspraak`,
    updateConsultationNoteError: `Er is een fout opgetreden tijdens het bijwerken van het gespreksverslag`,
    createConsultationNoteError: `Er is een fout opgetreden tijdens het maken van het gespreksverslag`,
    missed: `Gemist`,
    contentDescCloseNotification: `Melding sluiten`,
    pathwayChanged: `Uw zorgmodule is gewijzigd`,
    pathwayChangedDetails: (params: string[]) =>
        `van ${params[0]} tot ${
            params[1]
        }. Neem contact op met uw zorgcoördinator / zorgverlener voor meer informatie.`,
    de: `Duitse`,
    doYouWantToDeletePatient: (params: string[]) =>
        `Weet je zeker dat je patiënt ${params[0]} wilt verwijderen?`,
    personWillBeRemovedFromRecords: `Deze persoon zal niet meer in de C4T-app kunnen inloggen en zal uit de digitale administratie worden verwijderd.`,
    provideDeletionReason: `Geef een reden voor de verwijdering op:`,
    deletionSuccess: (params: string[]) =>
        `Je hebt patiënt ${params[0]} succesvol van het platform verwijderd`,
    consentNotProvided: `Er is geen toestemming gegeven`,
    entryError: `Invoerfout`,
    duplicatePatient: `Dubbele patiënt`,
    addExtraSecurity: `Voeg extra beveiliging aan je account toe met tweestapsverificatie`,
    mfaDescription: `Elke keer als je inlogt op een nieuw apparaat, zul je gevraagd worden jouw beveiligingscode in te voeren.De beveiligingscode wordt per e-mail of telefoon verzonden.`,
    activateMfa: `Tweestapsverificatie activeren`,
    userAccountNotActive: `Je gebruikersaccount is niet actief`,
    useHCPPortal: `Gebruik het online zorgverlenersportaal als je jouw wachtwoord bent vergeten`,
    noPatientsAssigned: `Er is geen patiënt aan je toegewezen.`,
    currentAppointments: `Huidige afspraken`,
    noCurrentAppointments: `Er zijn geen toekomstige afspraken beschikbaar`,
    phase: `Fase`,
    noPhaseInformation: `Geen fase-informatie`,
    noSubphaseInformation: `Geen subfase-informatie`,
    you: (params: string[]) => `${params[0]} (jij)`,
    hcpsMedicalStaff: `Zorgverleners`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `in ${params[0]} (${params[1]})`,
    newMessage: `Nieuw bericht`,
    addParticipant: `Deelnemer toevoegen`,
    editParticipant: `Deelnemer bewerken`,
    messagesFor: (params: string[]) => `Berichten ${params[0]}`,
    noParticipants: `Geen deelnemers beschikbaar`,
    whichMfaMethod: `Hoe wil je de beveiligingscode ontvangen?`,
    mfaMethodExplanation: `Deze beveiligingscode is vereist voor toegang tot je account. Je kunt de aanmeldcode krijgen via je mobiele telefoon of per e-mail. Kies jouw voorkeursmethode.`,
    textMe: `Stuur me de inlogcode met een tekstbericht`,
    emailMe: `E-mail me de inlogcode`,
    textMeSubtitle: `Wij vragen om je telefoonnummer`,
    emailMeSubtitle: `Bevestig je e-mailadres`,
    backToMethod: `Terug naar methodekeuze`,
    addPhone: `Voeg een telefoonnummer toe`,
    whichPhone: `Op welk telefoonnummer wil je de beveiligingscode ontvangen?`,
    phoneDisclaimer: `Dit telefoonnummer wordt alleen gebruikt voor accountbeveiliging. Er kunnen kosten van toepassing zijn voor berichtverzending en gegevensgebruik.`,
    sendCode: `Stuur beveiligingscode`,
    confirmEmail: `Bevestig jouw e-mailadres`,
    whichEmail: `Op welk e-mailadres wil je de beveiligingscode ontvangen?`,
    emailDisclaimer: `Dit e-mailadres wordt alleen gebruikt voor accountbeveiliging.`,
    insertCode: `Voer je beveiligingscode in`,
    mayTakeTwoMinutes: `Het kan tot twee minuten duren voordat je de code ontvangt.`,
    sentCodeByText: (params: string[]) =>
        `Wij hebben zojuist de beveiligingscode via een tekstbericht naar ${
            params[0]
        } gestuurd`,
    sentCodeByEmail: (params: string[]) =>
        `Wij hebben zojuist de beveiligingscode via een e-mailbericht naar ${
            params[0]
        } gestuurd`,
    didntGetCode: `Geen code ontvangen?`,
    resendCode: `Stuur beveiligingscode opnieuw`,
    authenticate: `Verifiëren`,
    verifyingCode: `Controleer beveiligingscode`,
    mfaSuccess: `Succes! 2-stapsverificatie is ingeschakeld!`,
    mfaCodeRequired: `Er is een aanmeldcode nodig voor toegang tot je account.`,
    mfaMethodExplanationLogin: `Deze beveiligingscode is vereist voor toegang tot je account. Je kunt de aanmeldcode krijgen via je mobiele telefoon of per e-mail.`,
    contentDescMfaIcon: `2-stapsverificatie-pictogram`,
    mfaSendCodeTo: (params: string[]) => `Wij sturen de code naar ${params[0]}`,
    continueLabel: `Doorgaan`,
    authenticating: `Bezig met verifiëren`,
    mfaInvalidCode: `De ingevoerde code is ongeldig. Probeer het opnieuw.`,
    mfaUnableToVerifyPhoneNumber: `Wij kunnen dit telefoonnummer niet verifiëren. Probeer een ander nummer.`,
    mfaUnableToVerifyEmail: `Wij kunnen je e-mailadres niet verifiëren. Probeer een ander e-mailadres.`,
    sessionExpired: `Jouw sessie is verlopen. Meld je opnieuw aan.`,
    passwordExpired: `Je wachtwoord is verlopen. Wijzig je wachtwoord.`,
    rightToBeForgottenInfoNonIntegrated: `Door dit verzoek in te dienen, worden jouw persoonsgegevens verwijderd en heb je geen toegang meer tot de applicatie. Neem voor verdere vragen contact op met support@care4todaypatient.com. Vul jouw wachtwoord in ter bevestiging:`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `Jouw aanvraag wordt verstuurd naar de support afdeling. Jouw account en gegevens worden tijdelijk geblokkeerd en, tenzij we jou anders laten weten, alleen opgeslagen en verwerkt als we jouw toestemming hebben verkregen. Neem voor verdere vragen of om de beperking op te heffen contact op met support@care4todaypatient.com`,
    password_expired_message: `Je wachtwoord is verlopen en moet worden gewijzigd om toegang te krijgen tot C4T`,
    firstdayOftheWeek: `Eerste dag van de week`,
    dateformat: `Datumformaat`,
    selectDateFormat: `Datumformaat kiezen`,
    selectDay: `Dag kiezen`,
    monday: `maandag`,
    tuesday: `dinsdag`,
    wednesday: `woensdag`,
    thursday: `donderdag`,
    friday: `vrijdag`,
    saturday: `zaterdag`,
    sunday: `zondag`,
    manageTheAppointmentTemplates: `De afspraaksjabloon beheren`,
    prefillTemplatesFor: `Sjablonen vooraf vullen voor`,
    appointmentTemplates: `Afspraaksjablonen`,
    backToTemplateTypes: `Terug naar sjabloontypen`,
    addNewAppointmentTemplate: `Nieuwe afspraaksjabloon toevoegen`,
    caremoduleName: `Naam van zorgmodule`,
    selectPathway: `Selecteer een zorgpad`,
    notShowInDropdownAfterDelete: `Door deze template te verwijderen, wordt het niet meer weergegeven in het vervolgkeuzemenu`,
    messagesTemplates: `Berichten templates`,
    addNewMessageTemplate: `Voeg nieuwe bericht template toe`,
    pathway: `Zorgtraject`,
    template: `Sjablonen`,
    typesTwo: `2 typen`,
    scheduledAppointmentInDropdown: `Door deze sjabloon te verwijderen, wordt het niet langer in de velden van het vervolgkeuzemenu getoond bij het plannen van een afspraak.`,
    manageTemplate: `Sjabloon beheren`,
    manageTheMessageTemplates: `De berichtsjabloon beheren`,
    addMdt: `+ Voeg een nieuw MDT (multidisciplinair team) toe aan platform`,
    mdts: `MDT's`,
    NameAsc: `Naam oplopend`,
    NameDesc: `Naam aflopend`,
    Teams: `Teams`,
    MdtsName: `Naam MDT`,
    managemdts: `MDT's beheren`,
    members: `Leden`,
    editTeam: `Team aanpassen`,
    addANewMDTToThePlatform: `+ Voeg een nieuw MDT toe aan het platform`,
    week: `Week`,
    month: `Maand`,
    year: `Jaar`,
    total: `Totaal`,
    dailyaverage: `Dagelijks gemiddelde`,
    nochartdata: `Geen grafiekgegevens beschikbaar`,
    youCanOnlyAssignOneMDTAtATime: `Je kunt slechts één MDT tegelijk toewijzen`,
    noMoreOptionsAvailable: `Geen opties meer beschikbaar`,
    mdt: `MDT`,
    relatingPatient: `Een patiënt betrekken`,
    nonrelatingPatient: `Geen patiënt betrekken`,
    sendMsgPatient: `Nieuw bericht naar patiënt verzenden`,
    expectedResponseTime: `Verwachte responstijd tussen 3 en 4 uur`,
    walkedText: `gelopen`,
    walk: `lopen`,
    mymedicalteam: `Mijn medisch team`,
    yesterday: `Gisteren`,
    close: `Sluiten`,
    passwordUsedBefore: `Nieuw wachtwoord is al eerder gebruikt en mag niet opnieuw gebruikt worden. Vul een ander wachtwoord in.`,
    sendMessageTo: `Bericht versturen naar`,
    message: `Bericht`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} heeft ${params[1]} aan het gesprek toegevoegd`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} heeft ${params[1]} uit het gesprek verwijderd`,
    removedParticipant: `Verwijderde deelnemer`,
    noMessagesSelected: `Je hebt geen bericht geselecteerd`,
    noMessagesSelectedDesc: `Selecteer een bericht aan de linkerkant van het scherm of begin een nieuw gesprek`,
    mfaMethodExplanationRegistration: `Deze beveiligingscode is vereist voor toegang tot je account. Je kunt de aanmeldcode krijgen via je mobiele telefoon of per e-mail. Kies de methode die voor jou het beste werkt.\n\nLet op: je kunt op dit moment slechts één verificatiemethode kiezen. Zodra je je keuze hebt gemaakt, wordt je voorkeur opgeslagen en kan deze niet gewijzigd worden zonder contact op te nemen met de helpdesk.`,
    signinCodeRequired: `Beveiligingscode aanvragen`,
    securityCodeRequired: `Deze beveiligingscode is vereist voor toegang tot je account. Je kunt de aanmeldcode krijgen via de methode die je hebt gekozen tijdens je eerste registratie.`,
    newMfaUserDesc1: `Deze beveiligingscode is vereist voor toegang tot je account. Je kunt de aanmeldcode krijgen via je mobiele telefoon of per e-mail. Kies de methode die voor jou het beste werkt.`,
    newMfaUserDesc2: `Let op: je kunt momenteel slechts één verificatiemethode kiezen. Zodra je je keuze hebt gemaakt, wordt je voorkeur opgeslagen en kan deze niet gewijzigd worden zonder contact op te nemen met de helpdesk.`,
    feelFreeToMessageTeam: `Begin gerust een gesprek met iemand uit je team.`,
    noFutureMessages: `Je hebt nog geen berichten`,
    chatSelfRemove: `Je hebt je uit het gesprek verwijderd`,
    noResultFound: `Geen resultaten gevonden`,
    chatUpdated: `Chat is bijgewerkt`,
    chatNotUpdated: `Chat is niet bijgewerkt`,
    searchPlaceholder: `Naar een sjabloon zoeken...`,
    editPrefillTemplate: `Vooraf gevulde sjabloon bewerken`,
    forAppointments: `Voor afspraken`,
    addTemplateToList: `Sjabloon toevoegen aan lijst`,
    addNewPrefillTemplate: `Nieuwe, vooraf gevulde sjabloon toevoegen`,
    forMessages: `Voor berichten`,
    editNewPrefillTemplate: `Nieuwe, vooraf gevulde sjabloon bewerken`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
