export const LANG_FR_TRANS = {
    accept: `Accepter`,
    accepted: `Accepté`,
    acceptedInvitation: `Vous avez accepté cette invitation.`,
    actions: `Actions`,
    addHcp: `Ajouter le PS sur la plateforme`,
    addHCPTag: `+ PS`,
    addHcpToPlatform: `Ajouter un PS sur la plateforme`,
    addNewHCP: `+ Ajouter un nouveau PS sur la plateforme`,
    addNewPatient: `+ Ajouter un nouveau patient sur la plateforme`,
    addPatient: `Ajouter le patient`,
    addPatientConsent: `Par la présente, je confirme avoir reçu le consentement du patient pour entrer ses données.`,
    addPatientToPlatform: `Ajouter le patient sur la plateforme`,
    administration: `Administration`,
    agreed: `Accepté`,
    allHcps: `Tous les PS`,
    allowNotifications: `Vous avez activé les notifications, bravo !`,
    allPatients: `Tous les patients`,
    almostHalfway: `Vous êtes presque à mi-chemin !`,
    almostThere: `Vous y êtes presque !`,
    am: `AM`,
    andMore: (params: string[]) => `et ${params[0]} supplémentaires`,
    apiErrorGetConsentDocument: `Échec de chargement du formulaire de consentement. Appuyez ici pour réessayer.`,
    appointment: `Rendez-vous`,
    appointmentAcceptedByPatient: `Accepté par le patient`,
    appointmentAwaitingPatientResponse: `En attente d’une réponse du patient`,
    appointmentDeclinedByPatient: `Refusé par le patient`,
    appointmentName: `Nom du rendez-vous`,
    appointmentNotification: `Notification de rendez-vous`,
    appointments: `Rendez-vous`,
    appointmentsForPatient: (params: string[]) =>
        `Rendez-vous pour ${params[0]}`,
    appointmentTimeRangeBetween: (params: string[]) =>
        `Un rendez-vous peut être programmé entre ${params[0]} et ${params[1]}`,
    appUnavailable: `Nous sommes désolés, l'application est actuellement indisponible. Veuillez réessayer ultérieuremsent ou vérifier les mises à jour.`,
    april: `Avril`,
    ar: `Arabe`,
    areYouSureDeclineMessage: `L'équipe soignante a besoin de vous pour vous aider dans la préparation et le suivi de vos progrès.\n\nVeuillez contacter votre médecin traitant si vous ne souhaitez pas vous inscrire sur la plateforme.`,
    areYouSureDeclineTitle: `Êtes-vous sûr(e) de ne pas vouloir vous inscrire à la plateforme Care4Today ?`,
    areYouSureDeleteNote: `Voulez-vous vraiment supprimer cette note ?`,
    article: `Article`,
    assignToMDT: `Attribuer à l’EPD`,
    audio: `Audio`,
    august: `Août`,
    back: `Retour`,
    backToAppointments: `Retour vers vos rendez-vous`,
    backToDetails: (params: string[]) =>
        `Retour vers les informations concernant ${params[0]}`,
    backToLogin: `Retour vers Connexion`,
    backToPatientProfile: `Retour vers le profil du patient`,
    badPassword: `Le mot de passe que vous avez saisi est invalide.`,
    bariatrics: `Étude et traitement de l'obésité`,
    blockedUser: `Votre utilisateur a été bloqué. Veuillez réessayer dans une demi-heure.`,
    bmi: `IMC`,
    bookedSuccess: `Votre rendez-vous a été pris avec succès`,
    cancel: `Annuler`,
    cancelAlert: `Annuler`,
    cantParseError: `Impossible d’analyser la réponse.`,
    cantSaveImage: `Impossible d’enregistrer l’image.`,
    care4Today: `Care4Today`,
    careModules: `Modules de soin`,
    changePassword: `Modifier le mot de passe`,
    changePasswordSubtitle: `Choisissez votre mot de passe.`,
    changePasswordTitle: `Veuillez personnaliser votre mot de passe`,
    choosePicture: `Sélectionner l’image`,
    chooseProfilePicture: `Modifier l’image`,
    cm: `cm`,
    completed: `Terminé`,
    conditionalGoal: `Objectif conditionnel`,
    confirmAppointmentDelete: `Voulez-vous vraiment supprimer ce rendez-vous ?`,
    confirmed: `Confirmé`,
    confirmNewPasswordPlaceholder: `Confirmer le nouveau mot de passe`,
    consent: `Consentement`,
    consentDontAgree: `Je refuse et n’utiliserai pas la plateforme Care4Today`,
    consentedOn: (params: string[]) => `Consentement donné le ${params[0]}`,
    contact: `Contact`,
    contactDetails: `Détails du contact`,
    contactInfo: `COORDONNÉES`,
    contentDescApptIcon: `Icône Rendez-vous`,
    contentDescAttachImage: `Joindre une image`,
    contentDescAttachment: `Pièce jointe`,
    contentDescAttachmentImg: `Image en mode plein écran`,
    contentDescBackground: `Antécédents`,
    contentDescChangePwdIcon: `Modifier l’icône Mot de passe`,
    contentDescClose: `Fermer le mode plein écran`,
    contentDescDeleteAttachment: `Supprimer l’image en pièce jointe`,
    contentDescDevicesIcon: `Icône Dispositifs connectés`,
    contentDescEduContentExpandBtn: `Ouvrir la pièce jointe au contenu éducatif`,
    contentDescEduContentThumb: `Pièce jointe au contenu éducatif`,
    contentDescEduItemCompleted: `La partie éducative est terminée`,
    contentDescEduItemIncomplete: `La partie éducative n’est pas terminée`,
    contentDescGoalIcon: `Icône Objectif personnel`,
    contentDescHelpIcon: `Icône Aide`,
    contentDescKillswitchIcon: `Icône Arrêt d’urgence`,
    contentDescLegalIcon: `Icône Documents juridiques`,
    contentDescLogo: `Logo de l’application`,
    contentDescLogoutIcon: `Icône Déconnexion`,
    contentDescMdtPic: `Photo du professionnel de santé`,
    contentDescMessageIcon: `Icône Message`,
    contentDescNoGoalIcon: `Icône Aucun objectif`,
    contentDescPathwayCurrent: `Icône Phase actuelle`,
    contentDescPathwayIcon: `Icône Parcours`,
    contentDescPathwayOtherPhase: `Icône Autre phase`,
    contentDescProfilePic: `Photo de profil`,
    contentDescSend: `Envoyer`,
    create: `Créer`,
    createAMedicalTeam: `Créer une équipe médicale`,
    createAppointment: `Créer un rendez-vous`,
    createAppointmentButton: `Créer un rendez-vous et envoyer une invitation`,
    createAppointmentSuccess: `Rendez-vous créé avec succès`,
    createAppt: `Créer le RDV`,
    createMDT: `Créer l'EPD`,
    currentBmi: `IMC actuel`,
    currentPhase: `Phase actuelle`,
    currentWeight: `Poids actuel`,
    dashboard: `Tableau de bord`,
    date: `Date`,
    dateOfBirth: `Date de naissance`,
    dateOfConsent: `Date du consentement`,
    dateOfConsentAsc: `Date de consentement croiss.`,
    dateOfConsentDesc: `Date de consentement décroiss.`,
    dateOfSurgery: `Date de l’intervention chirurgicale *`,
    december: `Décembre`,
    decline: `Décliner`,
    declined: `Décliné`,
    declinedInvitation: `Vous avez décliné cette invitation.`,
    declinedNotifications: `Vous n’avez pas autorisé les notifications. Êtes-vous sûr(e) de votre choix ? Vous pourrez modifier ce choix dans le menu Paramètres.`,
    declinedSuccess: `Vous avez décliné votre rendez-vous`,
    defaultError: `Un problème est survenu`,
    delete: `Supprimer`,
    deleteAppointmentSuccess: `Rendez-vous supprimé avec succès`,
    deleteNote: `Supprimer la note`,
    deleting: `Suppression…`,
    description: `Description`,
    details: `Détails`,
    devices: `Dispositifs connectés`,
    disagreeConsentError: `Une erreur s’est produite pendant votre refus de consentement. Veuillez réessayer.`,
    discardChanges: `Ignorer les modifications ?`,
    document: `Document`,
    done: `Terminé`,
    draftWontBeSaved: `Votre brouillon ne sera pas enregistré. Souhaitez-vous quand même annuler ?`,
    duplicateMDT: `PS déjà sélectionné`,
    edit: `Modifier`,
    editHcpsProfile: `Modifier le profil du PS`,
    editMessageDetails: `Modifier le sujet de la conversation`,
    editMTDTeam: (params: string[]) => `Modifier l’équipe pour ${params[0]}`,
    editPassword: `Modifier le mot de passe`,
    editPatient: `Modifier le patient`,
    editPatientError: `Un problème est survenu lors de la mise à jour des informations sur le patient`,
    editPatientSuccess: `Informations sur le patient mises à jour avec succès.`,
    editProfile: `Modifier le profil`,
    editProfilePicture: `Modifier la photo de profil`,
    editSubject: `Modifier le sujet`,
    editTeamMembers: `Modifier les membres de l’équipe`,
    editYourPersonalGoal: `Modifier votre objectif personnel`,
    eduContentHint: `Veuillez appuyer sur le bouton Développer pour ouvrir le contenu joint.`,
    email: `E-mail`,
    emailAddress: `Adresse e-mail`,
    emailConfirmation: (params: string[]) =>
        `Nous avons envoyé un e-mail à ${
            params[0]
        } contenant un lien pour réinitialiser votre mot de passe.`,
    emailExists: (params: string[]) =>
        `Un utilisateur avec l’adresse e-mail ${params[0]} existe déjà.`,
    emailSent: `E-mail envoyé`,
    en: `Anglais`,
    enableNotifications: `Activer les notifications`,
    enterANewHCP: `Saisir un nouveau PS`,
    enterSubjectHint: `Saisir un sujet`,
    enterTheSubject: `Saisissez le sujet de cette conversation.`,
    errorEditingHcp: `Une erreur s’est produite lors de la modification du PS`,
    errorFindingConsentDocument: `Erreur lors de la recherche du document de consentement.`,
    errorLoading: (params: string[]) =>
        `Erreur lors du chargement de ${params[0]}`,
    errorSavingSettings: `Erreur lors de l’enregistrement des paramètres`,
    errorUpdatingPassword: `Impossible de mettre à jour le mot de passe`,
    excessWeightLost: `Perte de poids excessif`,
    failEditHcp: `Une erreur s’est produite lors de la modification de votre profil`,
    february: `Février`,
    female: `Femme`,
    filter: `Filtre`,
    firstName: `Prénom`,
    forgotPasswordInstruction: `Indiquez l’adresse e-mail que vous avez fournie à votre hôpital. Nous vous enverrons un e-mail contenant un lien pour réinitialiser votre mot de passe.`,
    forgotPasswordViewTitle: `Mot de passe oublié?`,
    forgotYourPassword: `Avez-vous oublié votre mot de passe ?`,
    formTimeRangeInPast: `La plage horaire ne peut pas être dans le passé`,
    formTimeRangeStartGreaterThanEnd: `La plage horaire est invalide`,
    forPatient: `À l’attention de`,
    from: `De`,
    ft: `pied (’)`,
    fullName: `Nom complet`,
    function: `Fonction`,
    gained: `pris`,
    gender: `Sexe`,
    goal: `Objectif`,
    goalSavedError: `L'objectif n'a pas pu être enregistré !`,
    goalSavedSuccess: `Objectif enregistré avec succès !`,
    goBack: `Revenir en arrière`,
    hcps: `PS`,
    healthCareProfessionals: (params: string[]) =>
        `Professionnels de santé ${params[0]}`,
    height: `Taille`,
    help: `Aide`,
    heyChooseYourPicture: (params: string[]) =>
        `Bonjour ${params[0]}, choisissez votre photo de profil`,
    iAgree: `J’accepte`,
    iAgreeFormat: (params: string[]) => `J’accepte (${params[0]}/${params[1]})`,
    iAmSure: `Je suis sûr(e)`,
    idealBodyWeight: `Poids corporel idéal`,
    iDoNotAgree: `Je refuse`,
    iDontAgree: `Je refuse et je n’utiliserai pas la plateforme Care4Today`,
    imperial: `Impérial`,
    in: `pouce`,
    includeLinkToLocation: `Inclure le lien vers l’emplacement`,
    initialWeight: `Poids initial`,
    installUpdate: `Installer la mise à jour`,
    invalidEmailError: `E-mail invalide`,
    invalidNumber: `Veuillez saisir un numéro valide`,
    invalidTokenError: `Impossible de vous identifier. Veuillez essayer de vous connecter à nouveau.`,
    it: `Italien`,
    iWantToFitAgain: `Exemple : « Je veux pouvoir porter une taille L à nouveau »`,
    january: `Janvier`,
    july: `Juillet`,
    june: `Juin`,
    keepGoing: `Continuez !`,
    keepMomentum: `Continuez sur votre lancée !`,
    kg: `kg`,
    kilogrammes: `kilogrammes`,
    language: `Langues`,
    languageRequired: `Langues *`,
    lastName: `Nom`,
    lb: `lb`,
    learningMaterials: `Tâches à faire`,
    legalDocuments: `Documents juridiques`,
    loading: `Chargement`,
    loadingPatients: `Chargement des Patients. Veuillez patienter.`,
    location: `Lieu`,
    locationUrl: `URL de l’emplacement`,
    lockScreenHint: `Vous devez configurer un écran de verrouillage sur votre dispositif pour permettre une utilisation sécurisée de l’application.`,
    login: `Connexion`,
    loginIncorrect: `L’e-mail ou le mot de passe saisi n’est pas correct.`,
    logout: `Déconnexion`,
    logoutAreYouSure: `Voulez-vous vraiment vous déconnecter ?`,
    loseBefore: (params: string[]) => `Perdre ${params[0]}`,
    loseFormat: (params: string[]) => `Perdre ${params[0]} ${params[1]}`,
    lost: `perdus`,
    male: `Homme`,
    manageHCPs: `Gérer les PS`,
    managePatients: `Gérer les patients`,
    march: `Mars`,
    may: `Mai`,
    mdtTeam: `Équipe MD`,
    mdtTeamNotAddedYet: `EPD non attribuée pour l’instant.`,
    mdtTeamUC: `ÉQUIPE MD`,
    medicalTeam: `Équipe médicale`,
    meetingInvite: `Vous avez une réunion`,
    meetingInviteWith: (params: string[]) => `Réunion avec ${params[0]}`,
    messageCreated: `Conversation démarrée avec succès.`,
    messageNotCreated: `Échec du démarrage de la conversation.`,
    messageNotification: `Notification de message`,
    messageNotSent: `Message non envoyé`,
    messages: `Messages`,
    metric: `Métrique`,
    movePhaseConfirmation: (params: string[]) =>
        `Voulez-vous vraiment déplacer ${params[0]} vers la phase ${
            params[1]
        } ?`,
    moveToNextPhase: `Passer à la phase suivante`,
    multiDisTeam: `Équipe pluridisciplinaire`,
    myMessages: `Mes messages`,
    myMotivation: `Ma motivation :`,
    myPersonalGoal: `Mon objectif personnel`,
    myProfile: `Mon profil`,
    myTeam: `Mon équipe`,
    name: `Nom`,
    nameOfMDT: `Nom de l’EPD *`,
    needsConsent: `Le patient doit d’abord donner son consentement.`,
    networkError: `Une erreur de réseau s’est produite`,
    newAppointment: `Nouveau rendez-vous`,
    newChat: `Nouvelle discussion`,
    newInvitation: `Nouvelle invitation`,
    newMessageNotificationMore: (params: string[]) =>
        `Vous avez ${
            params[0]
        } nouveaux messages. Ouvrez l’application pour consulter les nouvelles.`,
    newMessageNotificationOne: `Vous avez un nouveau message. Ouvrez l’application pour consulter les nouvelles.`,
    newNote: `Nouvelle note`,
    newPasswordPlaceholder: `Nouveau mot de passe`,
    newPatientSuccess: (params: string[]) =>
        `Vous avez bien ajouté ${params[0]} sur la plateforme.`,
    newTeamFail: `Équipe pluridisciplinaire non attribuée`,
    newTeamSuccess: `Équipe pluridisciplinaire attribuée`,
    newVersionApp: `Veuillez mettre cette application à jour avec la version la plus récente disponible dans l’App. Store.`,
    nextAppointment: `Prochain rendez-vous`,
    nextSelectCareModule: `Suivant : Sélectionnez les modules de soin`,
    nextSurgeryInformation: `Suivant : Informations relatives à l’intervention chirurgicale`,
    niceToSeeYouAgain: `Ravi de vous revoir !`,
    nickname: `Surnom`,
    nicknameError: `Surnom non valide. Les caractères spéciaux ne sont pas autorisés.`,
    nl: `Néerlandais`,
    no: `Non`,
    noAppointments: `Il n'y a pas de rendez-vous disponible`,
    noCurrentGoalForPatient: `Il y a actuellement aucun objectif associé à ce patient`,
    noDate: `aucune date définie`,
    noFutureAppointments: `Aucun rendez-vous à venir`,
    noGoalSet: `Aucun objectif défini par votre PS`,
    noMatchingConsentDocumentsFound: `Aucun formulaire de consentement correspondant trouvé`,
    noMessages: `Aucun message disponible`,
    noNetworkConnection: `Aucune connexion au réseau disponible. Veuillez vérifier…`,
    noNotesMessage: `Aucune note disponible.\n Appuyez sur « Créer » pour ajouter de nouvelles notes.`,
    noPersonalGoalSet: `Aucun objectif personnel défini.`,
    noPersonalGoalSetDashboard: `Aucun objectif personnel défini. Allez à la page des paramètres pour mettre cette information à jour.`,
    noPlannedAppointments: `Aucun rendez-vous planifié`,
    noPreview: `Aucune prévisualisation disponible`,
    noProgressRecorded: `Aucun progrès enregistré`,
    noResponseError: `Aucune réponse reçue.`,
    notAgreed: `Refusé`,
    noteDeletedError: `Impossible de supprimer la note !`,
    noteDeletedSuccessfully: `Note supprimée avec succès !`,
    notes: `Notes`,
    noteSaved: `Note enregistrée`,
    noteSavedError: `Impossible d’enregistrer la note !`,
    noteSavedSuccess: `Note enregistrée avec succès !`,
    noteSaveError: `Erreur, impossible d’enregistrer la note. Réessayer ?`,
    notifications: `Notifications`,
    notNow: `Pas maintenant`,
    notSet: `Non défini`,
    notYetSubmitted: `Pas encore envoyé`,
    noUnreadMessages: `Pas de message non lu`,
    noUserFound: `Erreur lors de la recherche de l’utilisateur avec les identifiants fournis.`,
    november: `Novembre`,
    noWeightDifference: `Aucune différence de poids`,
    october: `Octobre`,
    ok: `OK`,
    onboardingNotificationsTitle: `Nous souhaitons vous tenir informé(e) à chaque fois`,
    onboardingNotifictionsInfo: `Vous recevrez des notifications concernant :\n\n• Vos rendez-vous\n• Les nouveaux messages de votre équipe médicale`,
    onVar: (params: string[]) => `le ${params[0]}`,
    openCare: `Veuillez ouvrir Care4Today et vérifier si vous avez des nouvelles notifications !`,
    optOutSubtitle: `Veuillez contacter votre médecin traitant si vous ne voulez pas vous inscrire sur la plateforme.`,
    optOutTitle: `Êtes-vous sûr(e) de ne pas vouloir vous inscrire à la plateforme Care4Today ?`,
    organisation: `Organisation`,
    orthopedics: `Orthopédie`,
    other: `Autre`,
    outdatedVersion: `Vous utilisez actuellement une version obsolète de l’application.`,
    overview: `Vue d’ensemble`,
    participant: `Destinataire`,
    password: `Mot de passe`,
    passwordComplexityError: `Le mot de passe doit être composé d’au moins 8 caractères et comporter au moins 2 des caractères suivants : lettres majuscules, lettres minuscules, chiffres ou symboles.`,
    passwordMismatchError: `Les mots de passe ne correspondent pas.`,
    passwordUpdated: `Mot de passe mis à jour`,
    pastAppointments: `Rendez-vous antérieurs`,
    pathwayScheduleFail: `Une erreur s’est produite. Le calendrier Pathway n’a pas pu être mis à jour.`,
    patient: `Patient`,
    patientAge: (params: string[]) => `${params[0]} ans`,
    patientAgeMoreTen: (params: string[]) => `${params[0]} ans`,
    patientConsent: `Consentement du patient`,
    patientNameAsc: `Nom du patient (ordre alph.)`,
    patientNameDesc: `Nom du patient (ordre alph. inversé)`,
    patientRegistration: `Inscription du patient`,
    patients: `Patients`,
    patientsCount: (params: string[]) => `${params[0]} patients`,
    patientsOverview: `Vue d’ensemble des patients`,
    pending: `En attente`,
    percent: `%`,
    personalGoal: `Objectif personnel`,
    personalGoalEdit: `Objectif personnel`,
    personalPassword: `Mot de passe personnel`,
    personalPasswordHelper: `Veuillez choisir votre mot de passe personnel. Vous aurez toujours la possibilité de modifier votre mot de passe dans le menu Paramètres.`,
    phoneError: `Numéro de téléphone non valide. Merci d’utiliser uniquement des chiffres (pas de parenthèses, pas de tirets, ni de signe +)`,
    phoneNumber: `Numéro de téléphone`,
    picture: `Photo`,
    pictureInstructions: `Veuillez choisir une photo de profil personnelle. Cette photo sera utilisée pour votre compte.`,
    pleaseConnect: `Veuillez vous connecter à Internet pour vérifier que vous utilisez bien la version la plus récente de l’application.`,
    pleaseContactYourHospital: `En cas d’urgence, veuillez contacter directement votre hôpital.`,
    pleaseProvidePassword: `Veuillez saisir votre mot de passe pour confirmer cette action :`,
    pm: `PM`,
    pounds: `livres`,
    preparation: `Préparation`,
    preSurgeryPrep: `Préparation avant intervention chirurgicale`,
    previous: `Précédent`,
    privacyPolicy: `Politique de confidentialité`,
    profileLabel: `Ceci nous permettra de vous adresser dans nos e-mails, messages SMS et cette application. Nous transmettrons également cette information à votre équipe médicale.`,
    profilePicture: `Photo de profil`,
    profileTitle: `Ceci nous permettra de vous adresser dans nos e-mails, messages SMS et cette application. Nous transmettrons également cette information à votre équipe médicale.`,
    progress: `Progrès`,
    progressMsgForgotPwd: `Validation…`,
    progressMsgLoading: `Chargement…`,
    progressMsgLoadingContent: `Chargement du contenu…`,
    progressMsgLogin: `Chargement du parcours, \nCela peut prendre jusqu'à 1 minute…`,
    progressMsgMdtLoading: `Chargement de l’EPD…`,
    progressMsgNotesLoading: `Chargement des notes…`,
    progressMsgProfileEdit: `Enregistrement du profil…`,
    progressMsgProfilePhoto: `Enregistrement de la photo…`,
    progressMsgResetPwd: `Enregistrement du mot de passe`,
    provideTheEmail: `Indiquez l’adresse e-mail que vous avez fournie à l’hôpital.`,
    pwdValidationDoesNotMatch: `Vos mots de passe ne correspondent pas`,
    pwdValidationIllegal: `Contient des caractères non autorisés`,
    pwdValidationNotComplex: `Le mot de passe n’est pas assez complexe`,
    pwdValidationTooShort: `Votre mot de passe est trop court`,
    quickFilter: `Filtre rapide`,
    remindmeLater: `Me rappeler plus tard`,
    requiredFields: `Champs obligatoires`,
    requiredHCPs: `PS *`,
    resetPassword: `Réinitialiser le mot de passe`,
    respond: `Répondre`,
    retry: `Réessayer`,
    save: `Enregistrer`,
    saveAndContinue: `Enregistrer et continuer`,
    saveChanges: `Enregistrer les modifications`,
    scheduleNewAppointment: `Prendre un nouveau rendez-vous`,
    searchInConversation: `Rechercher dans les conversations…`,
    secureRealmError: `Échec de lancement - Le verrouillage de l’écran doit être activé`,
    selectDifferentImage: `Sélectionner une image différente`,
    selectFile: `Sélectionner un fichier`,
    selectFunction: `Sélectionner une fonction`,
    selectLanguage: `Sélectionner la langue`,
    selectOneOrMoreHCPs: `Sélectionner un ou plusieurs PS`,
    selectPictureSource: `Sélectionner une image dans`,
    selectProfilePicture: `Sélectionner une photo de profil`,
    selectSurgeon: `Sélectionner un chirurgien`,
    send: `Envoyer`,
    sendMessage: `Envoyer le message`,
    sendNewMessage: `Envoyer un nouveau message`,
    september: `Septembre`,
    setPassword: `Définir le mot de passe`,
    setPasswordReminder: `Vous aurez toujours la possibilité de modifier votre mot de passe dans le menu Paramètres.`,
    settings: `Paramètres`,
    setup: `CONFIGURATION`,
    setYourPersonalGoal: `Définissez votre objectif personnel`,
    someonesPathway: (params: string[]) => `Parcours de ${params[0]}`,
    sortBy: `Trier par`,
    splashSubtitle: `Chirurgie de l’obésité`,
    start: `Démarrer`,
    startANewConversation: `Démarrer une nouvelle conversation`,
    startConversation: `Démarrer la conversation`,
    startingPoint: `Point de départ`,
    startNewConversation: `+ Démarrer une nouvelle conversation`,
    startPreparation: `Démarrer votre préparation`,
    status: `Statut`,
    subject: `Sujet`,
    subjectChangedSuccess: `Sujet de la conversation modifié avec succès`,
    subjectChangeFail: `Sujet de la conversation non modifié`,
    submit: `Envoyer`,
    subPhase: `Sous-phase`,
    successEditHcp: `Vous avez modifié votre profil avec succès`,
    surgeon: `Chirurgien`,
    surgeryInformation: `Informations relatives à l’intervention chirurgicale`,
    tasks: `tâches`,
    tasksCompleted: `Tâches terminées`,
    team: `Équipe`,
    thisMonth: `Ce mois`,
    time: `Heure`,
    timeAndLocation: `Heure et lieu`,
    timeOfSurgery: `Heure de l’intervention chirurgicale *`,
    to: `À`,
    today: `Aujourd’hui`,
    toDo: `À faire`,
    undo: `Annuler`,
    unitRequired: `Unité *`,
    units: `Unités de mesure`,
    unknown: `Préfère ne rien dire`,
    unknownError: `Une erreur s’est produite pendant le traitement. Veuillez réessayer…`,
    unknownGender: `Je préfère ne pas répondre`,
    unknownUser: `Inconnu`,
    unreadMessage: `Message non lu`,
    unreadMessages: `Messages non lus`,
    untitled: `Sans titre…`,
    update: `Mettre à jour`,
    updateAppointment: `Modifier le rendez-vous`,
    updateAppointmentButton: `Enregistrer les modifications et envoyer les mises à jour`,
    updateAppointmentSuccess: `Rendez-vous mis à jour avec succès`,
    updateMessage: `Pour continuer à utiliser l’application, vous devez la mettre à jour avec la version la plus récente disponible dans l’App. Store.`,
    updateProfilePicture: `Mettre à jour la photo de profil`,
    updateProgress: `Mettre à jour les progrès`,
    useCamera: `Utiliser la caméra`,
    username: `Nom d’utilisateur`,
    video: `Vidéo`,
    viewAllMessages: `Afficher tous les messages`,
    viewAndEditPathway: `Afficher et modifier les dates de parcours`,
    viewDocument: `Afficher le document`,
    weight: `Poids`,
    weightLoss: `Perte de poids`,
    weightUpdatedSuccess: `Le poids actuel a été mis à jour avec succès`,
    welcomeHeader: `Bienvenue`,
    welcomeMessage: (params: string[]) => `Bonjour ${params[0]} !`,
    wellDoneNextStep: `Bravo ! Vous êtes prêt(e) à passer à l’étape suivante !`,
    withdrawConfirm: `OK, quitter l’application.`,
    withdrawConsent: `Annuler le consentement`,
    withdrawConsentBody: `En annulant votre consentement au traitement de vos données personnelles, vos données locales telles que les notes et les objectifs personnels seront supprimées. Vous ne pourrez plus accéder à l’application après un délai de 30 jours.`,
    withdrawConsentTitle: `Voulez-vous vraiment vous désinscrire de la plateforme Care4Today ?`,
    writeAMessage: `Écrire un message...`,
    writeSomething: `Écrire quelque chose...`,
    wrongUserName: `Le nom d’utilisateur que vous avez saisi est incorrect`,
    xUnread: (params: string[]) => `${params[0]} non lu`,
    yes: `Oui`,
    yesDelete: `Oui, supprimer`,
    yesDiscard: `Oui, ignorer`,
    youAreOffline: `Vous êtes hors ligne`,
    youCanSetASentence: `Vous pouvez définir une phrase pour vous motiver à atteindre votre objectif personnel.`,
    youGained: (params: string[]) => `Vous avez pris ${params[0]}`,
    youGainedFormat: (params: string[]) =>
        `Vous avez pris ${params[0]} ${params[1]}`,
    youHaveANewMessageFrom: (params: string[]) =>
        `Vous avez un nouveau message de ${params[0]}.`,
    youHaveNewAppointment: `Vous avez un nouveau rendez-vous. Ouvrez l’application pour consulter les nouvelles.`,
    youHaveNewAppointments: (params: string[]) =>
        `Vous avez ${
            params[0]
        } nouveaux rendez-vous. Ouvrez l’application pour consulter les nouvelles.`,
    youHaveNewMessage: `Vous avez un nouveau message. Ouvrez l’application pour consulter les nouvelles.`,
    youHaveNewMessages: (params: string[]) =>
        `Vous avez ${
            params[0]
        } nouveaux messages. Ouvrez l’application pour consulter les nouvelles.`,
    youHaveUndone: `Vous avez annulé l’option choisie précédemment`,
    youLost: (params: string[]) => `Vous avez perdu ${params[0]}`,
    youLostFormat: (params: string[]) =>
        `Vous avez perdu ${params[0]} ${params[1]}`,
    yourAppointments: `Vos rendez-vous`,
    yourGoals: `Vos objectifs`,
    yourNote: `Votre note`,
    yourPassword: `Votre mot de passe`,
    yourPasswordHasBeenReset: `Votre mot de passe a été réinitialisé`,
    yourProfile: `Votre profil`,
    export: `Exporter`,
    exportData: `Exporter les données personnelles`,
    exportDataFail: `Une erreur s’est produite. Impossible d’exporter les données`,
    exportMyData: `Exporter mes données personnelles`,
    goalStepCount: `Objectif (pas/jour)`,
    loadingPathway: `Chargement du parcours. Cela peut prendre jusqu'à 1 minute…`,
    loadingPatient: `Chargement du patient. Veuillez patienter.`,
    pleaseEnterTotalSteps: `Veuillez saisir le nombre de pas effectués à la fin de chaque journée`,
    stepCount: `Nombre de pas`,
    stepsPerDay: `pas/jour`,
    walkStepsPerDay: (params: string[]) => `Marcher ${params[0]} pas/jour`,
    steps: `Pas`,
    avgWeeklySteps: `Nombre moyen de pas cette semaine`,
    rightToBeForgotten: `Supprimer mes données personnelles`,
    totalStepsDuringDay: `Nombre total de pas effectués dans une journée`,
    youAlreadyWalked: (params: string[]) =>
        `Vous avez fait ${params[0]} pas aujourd’hui`,
    rightToBeForgottenTitle: `Voulez-vous vraiment lancer la suppression de vos données personnelles ?`,
    rightToBeForgottenInfo: `En initiant cette demande, vos données personnelles seront supprimées et vous ne pourrez plus accéder à l’application. Veuillez noter que certaines données personnelle, restreintes, telles que votre nom, envoyé par le système d’information de l’hôpital, peuvent continuer à apparaître dans les rendez-vous.    Si vous avez d’autres questions, veuillez nous contacter à l’adresse : support@care4todaypatient.com.    Veuillez saisir votre mot de passe pour confirmer cette action :`,
    passwordHint: `Votre mot de passe`,
    rightToBeForgottenSuccess: `La demande de suppression des données personnelles a été envoyée à l'adresse email du service d'assistance de Care4Today.`,
    incorrectPassword: `Saisie de mot de passe incorrect`,
    errorInitiatingRightToBeForgotten: `Erreur lors de l’envoi de la demande, veuillez contacter l’assistance directement`,
    updateStepCount: `Mettre à jour le nombre de pas`,
    mon: `Lun`,
    tue: `Mar`,
    wed: `Mer`,
    thu: `Jeu`,
    fri: `Ven`,
    sat: `Sam`,
    sun: `Dim`,
    stepsAmount: (params: string[]) => `${params[0]} pas`,
    stepsGoalUpdateSuccess: `Le nombre de pas a été mis à jour avec succès`,
    search: `Rechercher...`,
    successEditMDT: `EPD mise à jour avec succès`,
    failEditMDT: `Une erreur s’est produite lors de la mise à jour de l’EPD`,
    userCreationError: `Une erreur s’est produite lors de la création de l’utilisateur`,
    userUpdateSuccess: `L'utilisateur a été mis à jour avec succès`,
    legal: `Juridique`,
    termsOfUse: `Conditions d’utilisation`,
    disclaimer: `Clause de non-responsabilité`,
    exportDataSuccessV1: `N/A`,
    exportDataSuccess: `La demande d’exportation de données personnelles a été envoyée au service d’assistance de Care4Today.`,
    dataFormatV1: `N/A`,
    dataFormat: `Vos données personnelles seront exportées dans un format CSV. Le fichier sera envoyé à l’adresse e-mail que vous avez enregistrée.`,
    viewAllMaterials: `Afficher tous les documents`,
    viewAllAppointments: `Afficher tous les rendez-vous`,
    enjoyYourDay: `Profitez de votre journée libre !`,
    motivateAlmost: `Vous avez bientôt terminé !`,
    startConversationHcp: `Démarrer une conversation avec un PS`,
    andYou: `, vous`,
    viewAllNotifications: `Afficher toutes les notifications`,
    noInvitations: `Aucune invitation`,
    yourTimeline: `Votre chronologie`,
    currentSubphase: `Sous-phase actuelle`,
    updateWeight: `Mettre à jour le poids actuel`,
    teamLoading: `Chargement de l’équipe`,
    noMdt: `Aucune EPD ne m’est attribuée.`,
    teamDetails: `Afficher les détails de l’équipe`,
    showResolved: `Afficher résolus`,
    readDoc: `Lire le document`,
    consultationNotes: `Notes de consultation`,
    viewAllConsultationNotes: `Afficher toutes les notes de consultation`,
    createNewNote: `+ Créer une nouvelle note`,
    dismiss: `Ignorer`,
    pictureError: `Erreur lors du chargement de la photo`,
    wrongFormat: `Mauvais format d’image`,
    backToDashboard: `Retour au tableau de bord`,
    noMessage: `Aucun message`,
    noSpecialCharacters: `Les caractères spéciaux ne sont pas autorisés.`,
    noNotesAvailable: `Aucune note disponible`,
    hcpPortal: `Portail PS`,
    patientPortal: `Portail Patient`,
    consultationNote: `note de consultation`,
    noteTitle: `Titre de la note`,
    noteContents: `Contenu de la note`,
    writeConsultationNotes: `Rédiger les notes de consultation ici`,
    createHcpNote: `Créer une note`,
    consultationNoteCreatedBy: (params: string[]) =>
        `Créé : ${params[0]} par ${params[1]}`,
    consultationNoteLastEdited: (params: string[]) =>
        `Dernière modification : ${params[0]}`,
    loadingConsultaionNotes: `Chargement des notes de consultation`,
    consultationNotesFor: (params: string[]) =>
        `Notes de consultation pour ${params[0]}`,
    editHcpNote: `Modifier la note`,
    reason: `Raison`,
    writeReasonForEditing: `Indiquer la raison de la modification...`,
    confirmCancelCreateNote: `Voulez-vous vraiment quitter sans créer de note ?`,
    confirmCancelEditNote: `Voulez-vous vraiment quitter sans modifier la note ?`,
    rotateYourDevice: `Faites pivoter votre dispositif`,
    patientId: `Identifiant du patient`,
    oldPassword: `Ancien mot de passe`,
    completedTotal: (params: string[]) => `${params[0]}/${params[1]}`,
    documents: `Documents`,
    hcpId: `Identifiant du PS`,
    userInactivity: `Vous avez été déconnecté pour cause d’inactivité.`,
    duplicateMrn: `Cet identifiant de PS existe déjà dans Care4Today`,
    confirm: `Confirmer`,
    viewDetails: `Afficher les détails`,
    upperCaseLetters: `Lettres majuscules`,
    lowerCaseLetters: `Lettres minuscules`,
    numbers: `Chiffres`,
    specialCharacters: `Caractères spéciaux (ponctuation, symboles)`,
    passwordRequirements: `Le mot de passe doit être composé d’au moins 8 caractères et répondre à deux critères de complexité :`,
    incorrectOldPassword: `L’ancien mot de passe est incorrect`,
    newPasswordsNotSame: `Les nouveaux mots de passe saisis ne sont pas identiques.`,
    passwordSuccesfullyChanged: `Mot de passe modifié avec succès.`,
    accountBlockedFifteenMinutes: `Votre compte est bloqué. Veuillez réessayer dans 15 minutes.`,
    loadingLegalDocuments: `Chargement des documents juridiques…`,
    fr: `Français`,
    errorFetchingLegalDocuments: `Erreur lors du chargement des documents juridiques.`,
    nameAndMrnNotFound: `La combinaison de l’ID du patient avec son nom est introuvable.`,
    duplicateNameAndMrn: `L’ID de ce patient existe déjà dans Care4Today.`,
    NSCameraUsageDescription: `Cette application nécessite un accès à l’appareil photo pour ajouter / mettre à jour la photo du profil et ajouter des pièces jointes aux notes`,
    NSPhotoLibraryUsageDescription: `Cette application nécessite un accès à la blibliothèque de photos pour ajouter des pièces jointes aux notes`,
    initiate: `Commencer`,
    lastNameAsc: `Nom Asc`,
    lastNameDesc: `Nom Desc`,
    firstNameAsc: `Prénom Asc`,
    firstNameDesc: `Prénom Desc`,
    messageParticipantIsInactive: `n’est plus actif.`,
    participantNoLonger: `Le participant n’est plus utilisateur de la plateforme.`,
    requestDeletionInProgress: `Votre requête de suppression de données personnelles est déjà en cours de traitement. L’équipe de support vous informera dès que le processus est terminé.`,
    contactNotAvailableOnDeactivated: `Les données de contact ne sont pas disponibles pour le PS (Professionnel de santé) désactivé.`,
    deactivated: `Désactivé`,
    noPermissionToSendMessage: `Vous n’êtes pas autorisé à envoyer un message à cette personne.`,
    refrainSendingMedData: `Veuillez éviter d’envoyer des messages contenant des données/informations médicales du patient.`,
    refrainEnteringMedData: `Veuillez éviter de saisir des données/informations médicales du patient dans le champ ci-dessus.`,
    contactHospitalAppointment: `Veuillez contacter l’hôpital si vous souhaitez changer ou annuler le rendez-vous !`,
    noInfoDescriptionAppointment: `Aucune autre information disponible. Veuillez contacter l’hôpital en cas de doute ou pour toutes questions concernant ce rendez-vous.`,
    noInfoDescriptionAndDateAppointment: `Vous recevrez une mise à jour sous peu. Elle vous apportera davantage d’information sur votre rendez-vous. Veuillez contacter l’hôpital en cas de doute ou pour toutes questions concernant ce rendez-vous.`,
    participants: `Participants`,
    noMdtAssigned: `Aucune équipe pluridisciplinaire attribuée au patient. Veuillez commencer par attribuer une équipe au patient.`,
    scheduled: `Planifié`,
    updated: `Mis à jour`,
    proposed: `Proposé`,
    he: `Hébreu`,
    restrictProcessingPersonal: `Restreindre le traitement de mes données personnelles`,
    restrictProcessingArticle: `Sur la base de l’article 18 du RGPD, lequel des énoncés suivants s’applique à votre situation ?`,
    dataAccuracy: `Exactitude des données`,
    unlawfulProcessing: `Traitement illégal`,
    legalClaim: `Réclamation juridique`,
    provideExplanation: `Veuillez fournir une explication :`,
    provideExplanationDescription: `Veuillez fournir un texte explicatif décrivant le problème pour aider à l’évaluation de votre demande`,
    restrictProcessing: `Limiter le traitement`,
    sureProcessing: `Êtes-vous sûr de vouloir limiter le traitement de vos données personnelles ?`,
    processingPasswordConfirmation: `En faisant cette demande, vos données seront temporairement désactivées et, sauf si nous vous informions du contraire, nous procéderons seulement au stockage de vos données et ne les traiterons à l’avenir qu’avec votre autorisation. Si vous avez d’autres questions ou si vous souhaitez lever cette restriction, veuillez nous contacter à : support@care4todaypatient.com. Veuillez saisir votre mot de passe pour confirmer cette action :`,
    processingSent: `Une demande de limitation du traitement de vos données personnelles a été envoyée à la boîte aux lettres de support de Care4Today`,
    versionNumber: (params: string[]) => `Version ${params[0]}`,
    pleaseSelect: `Veuillez sélectionner :`,
    restrictedLogout: `Vous avez été déconnecté car votre demande de limitation du traitement de vos données personnelles a été traitée et une restriction a été appliquée à votre compte Care4Today. Si vous avez des questions, veuillez nous contacter à : support@care4todaypatient.com`,
    restrictProcessingAlreadyRequested: `Votre demande de restriction du traitement de vos données personnelles est déjà en cours de traitement. L’équipe de support vous informera dès que le processus est terminé.`,
    rightToRestrictQuestion: `Sur la base de l’article 18 du RGPD, lequel des énoncés suivants s’applique à votre situation ?`,
    rightToRestrictExplanation: `Veuillez fournir une explication :`,
    rightToRestrictTitle: `Restreindre le traitement de mes données personnelles`,
    rightToRestrictExplanationPlaceholder: `Veuillez fournir un texte explicatif décrivant le problème pour aider à l’évaluation de votre demande.`,
    rightToRestrictConfirmationTitle: `Êtes-vous sûr de vouloir limiter le traitement de vos données personnelles ?`,
    rightToRestrictConfirmationDescription: `Votre demande sera envoyée à l’équipe de support. Votre compte et vos données seront temporairement désactivés et, sauf si nous vous informions du contraire, nous procéderons uniquement au stockage de vos données et ne les traiterons à l’avenir qu’avec votre autorisation. Veuillez noter que certaines données personnelles, restreintes, telles que votre nom, envoyé par le système d’information de l’hôpital, peuvent continuer à apparaître dans les rendez-vous.    Si vous avez d’autres questions ou si vous souhaitez lever cette restriction, veuillez nous contacter à l’adresse : support@care4todaypatient.com.    Veuillez saisir votre mot de passe pour confirmer cette action :`,
    assignedRole: (params: string[]) => `Affecté ${params[0]} (inactif)`,
    requestRestrictionSubmitted: `Une demande de limitation du traitement de vos données personnelles a été envoyée à la boîte aux lettres de support de Care4Today`,
    temporarelyUnavailableHCPAlertMessage: `Le professionnel de santé est temporairement indisponible sur la plateforme. Si vous avez des questions, veuillez contacter l’équipe de support.`,
    temporarelyUnavailableHCPSubtitle: `Le professionnel de santé est temporairement indisponible`,
    assignedHCP: (params: string[]) => `Affecté ${params[0]}`,
    inactive: `Inactif`,
    appointmentInvite: `Vous avez un rendez-vous`,
    disabledAppointmentActionMessage: `Veuillez utiliser directement le système de réservation de rendez-vous de l’hôpital pour programmer, mettre à jour ou annuler un rendez-vous.`,
    noFurtherInformation: `Aucune autre information disponible`,
    cancelled: `Annulé`,
    cancelledNotificationPrefix: `Annulé :`,
    updatedNotificationPrefix: `Mis à jour :`,
    allDay: `Toute la journée`,
    editCareModule: `Modifier le module de soin`,
    nextSurgeryProcedureInformation: `Suivant : Détail de l’intervention / la procédure`,
    hcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} ne fait plus partie de votre équipe pluridisciplinaire`,
    editCareModuleWarning: `Veuillez noter qu’en changeant le module de soin, tout l’historique associés aux objectifs et au matériel d’apprentissage de la procédure précédente ne sera plus disponible pour le patient.`,
    editSurgeryWarning: `Veuillez ajuster les informations de l’intervention si nécessaire.`,
    nextUpdateMDT: `Suivant : Mettre à jour l’équipe médicale`,
    updateCareModule: `Mettre à jour le module de soin`,
    editMdtTeamWarning: `Veuillez vérifier l’équipe pluridisciplinaire pour voir si des modifications sont nécessaires.`,
    participantNotInMDT: `Vous ne faites plus partie de l’équipe pluridisciplinaire pour ce patient`,
    createMedicalTeam: `Créer une équipe médicale`,
    editMedicalTeam: `Modifier une équipe médicale`,
    mdtName: `Nom de l’équipe pluridisciplinaire`,
    changePathwayConfirmationTitle: (params: string[]) =>
        `Êtes-vous certain de vouloir changer le module de soin de ce patient de « ${
            params[0]
        } » à « ${params[1]} » ?`,
    changePathwayConfirmationSubTitle: `Veuillez noter qu’en changeant le module de soin, tout l’historique associés aux objectifs et au matériel d’apprentissage de la procédure précédente ne sera plus disponible pour le patient.`,
    changePathwaySuccessMessage: (params: string[]) =>
        `Vous avez changé avec succès le module de soin du patient ${
            params[2]
        } de « ${params[0]} » à « ${params[1]} »`,
    mdtChanged: `Votre équipe médicale a changé`,
    tapForDetails: `Appuyez ici pour en savoir plus.`,
    restrictedHcpRemovedFromMdtMessage: (params: string[]) =>
        `${params[0]} ne fait plus partie de votre équipe pluridisciplinaire`,
    addPatientReceivedConsent: `En fournissant les informations ci-dessous, je déclare avoir reçu le consentement du patient pour le traitement des données du patient.`,
    attended: `Honoré`,
    entityCreationError: (params: string[]) =>
        `Une erreur s’est produite lors de la création de ${params[0]}`,
    updateAppointmentError: `Une erreur s’est produite lors de la mise à jour du rendez-vous`,
    updateConsultationNoteError: `Une erreur s’est produite lors de la mise à jour de la note de consultation`,
    createConsultationNoteError: `Une erreur s’est produite lors de la création de la note de consultation`,
    missed: `Manqué`,
    contentDescCloseNotification: `Fermer la notification`,
    pathwayChanged: `Votre module de soin a été changé`,
    pathwayChangedDetails: (params: string[]) =>
        `de ${params[0]} à ${
            params[1]
        }. Veuillez contacter votre coordinateur de soins / professionnel de santé pour en savoir plus.`,
    de: `Allemande`,
    doYouWantToDeletePatient: (params: string[]) =>
        `Êtes-vous certain de vouloir supprimer le patient ${params[0]} ?`,
    personWillBeRemovedFromRecords: `Cette personne ne sera plus en mesure de se connecter à l’application C4T et sera effacée numériquement.`,
    provideDeletionReason: `Veuillez indiquer le motif de cette suppression :`,
    deletionSuccess: (params: string[]) =>
        `Vous avez bien supprimé ${params[0]} de la plate-forme`,
    consentNotProvided: `Le consentement n’a pas été donné`,
    entryError: `Erreur de saisie`,
    duplicatePatient: `Dupliquer le patient`,
    addExtraSecurity: `Renforcer la sécurité de votre compte grâce à la vérification en deux étapes`,
    mfaDescription: `À chaque fois que vous vous connecterez à votre compte depuis un nouvel appareil, nous vous demanderons d’entrer un code de sécurité.Ce code de sécurité vous sera envoyé par e-mail ou par téléphone.`,
    activateMfa: `Activer la vérification en 2 étapes`,
    userAccountNotActive: `Votre compte utilisateur n’est pas actif`,
    useHCPPortal: `Veuillez utiliser le portail PS en ligne si vous avez oublié votre mot de passe`,
    noPatientsAssigned: `Aucun patient ne vous a été attribué.`,
    currentAppointments: `Rendez-vous actuels`,
    noCurrentAppointments: `Aucun rendez-vous à venir`,
    phase: `Phase`,
    noPhaseInformation: `Aucune information concernant la phase`,
    noSubphaseInformation: `Aucune information concernant la sous-phase`,
    you: (params: string[]) => `${params[0]} (vous)`,
    hcpsMedicalStaff: `PS`,
    patientSubphasePhasePrefix: (params: string[]) =>
        `dans ${params[0]} (${params[1]})`,
    newMessage: `Nouveau message`,
    addParticipant: `Ajouter un participant`,
    editParticipant: `Modifier le participant`,
    messagesFor: (params: string[]) => `Messages ${params[0]}`,
    noParticipants: `Aucun participant disponible`,
    whichMfaMethod: `De quelle manière souhaitez-vous recevoir votre code de sécurité ?`,
    mfaMethodExplanation: `Ce code de sécurité est obligatoire pour accéder à votre compte. Vous pouvez obtenir ce code d’accès sur votre téléphone portable ou par e-mail. Choisissez la méthode qui vous convient le mieux.`,
    textMe: `Envoyez-moi un code d’accès par SMS`,
    emailMe: `Envoyez-moi un code d’accès par e-mail`,
    textMeSubtitle: `Nous vous demanderons votre numéro de téléphone`,
    emailMeSubtitle: `Veuillez confirmer votre adresse e-mail`,
    backToMethod: `Retour au choix de la méthode`,
    addPhone: `Ajouter un numéro de téléphone`,
    whichPhone: `Sur quel numéro de téléphone souhaitez-vous recevoir le code de sécurité ?`,
    phoneDisclaimer: `Ce numéro de téléphone sera uniquement utilisé pour la sécurité de votre compte. Des frais relatifs aux SMS et à l’utilisation de données pourront s’appliquer.`,
    sendCode: `Envoyer le code de sécurité`,
    confirmEmail: `Confirmer votre e-mail`,
    whichEmail: `Sur quelle adresse e-mail souhaitez-vous recevoir le code de sécurité ?`,
    emailDisclaimer: `Cette adresse e-mail sera uniquement utilisée pour la sécurité de votre compte.`,
    insertCode: `Veuillez insérer votre code de sécurité`,
    mayTakeTwoMinutes: `Il vous faudra peut-être attendre jusqu’à deux minutes pour recevoir votre code.`,
    sentCodeByText: (params: string[]) =>
        `Le code de sécurité vient d’être envoyé par SMS à ${params[0]}`,
    sentCodeByEmail: (params: string[]) =>
        `Le code de sécurité vient d’être envoyé par e-mail à ${params[0]}`,
    didntGetCode: `Vous n’avez pas reçu de code ?`,
    resendCode: `Renvoyer un code de sécurité`,
    authenticate: `Authentifier`,
    verifyingCode: `Code de sécurité en cours de vérification`,
    mfaSuccess: `Opération réussie ! L’authentification à 2 étapes est activée !`,
    mfaCodeRequired: `Un code d’accès est exigé pour accéder à votre compte.`,
    mfaMethodExplanationLogin: `Ce code de sécurité est obligatoire pour accéder à votre compte. Vous pouvez obtenir ce code d’accès sur votre téléphone portable ou par e-mail.`,
    contentDescMfaIcon: `Icône de l’athentification en 2 étapes`,
    mfaSendCodeTo: (params: string[]) => `Le code sera envoyé à ${params[0]}`,
    continueLabel: `Continuer`,
    authenticating: `Authentification en cours`,
    mfaInvalidCode: `Le code que vous avez saisi n’est pas valide. Veuillez réessayer.`,
    mfaUnableToVerifyPhoneNumber: `Nous ne pouvons pas vérifier ce numéro de téléphone. Veuillez en saisir un autre.`,
    mfaUnableToVerifyEmail: `Nous ne pouvons pas vérifier cette adresse e-mail. Veuillez en saisir une autre.`,
    sessionExpired: `Votre session a expiré. Veuillez vous reconnecter.`,
    passwordExpired: `Votre mot de passe a expiré. Veuillez changer votre mot de passe.`,
    rightToBeForgottenInfoNonIntegrated: `En lançant cette demande, vos informations personnelles seront supprimées et vous ne pourrez plus accéder à l’application. En cas de question, veuillez contacter support@care4todaypatient.com. Veuillez saisir votre mot de passe pour confirmer cette action :`,
    rightToRestrictConfirmationDescriptionNonIntegrated: `Votre demande sera envoyée à l’équipe de support. Votre compte et vos données seront temporairement désactivés et, sauf si nous vous informions du contraire, nous procéderons seulement au stockage de vos données et ne les traiterons à l’avenir qu’avec votre autorisation. Si vous avez d’autres questions ou si vous souhaitez lever cette restriction, veuillez nous contacter à : support@care4todaypatient.com`,
    password_expired_message: `Le mot de passe a expiré et doit être modifié pour accéder à C4T`,
    firstdayOftheWeek: `Premier jour de la semaine`,
    dateformat: `Format de date`,
    selectDateFormat: `Sélectionner le format de date`,
    selectDay: `Sélectionner le jour`,
    monday: `Lundi`,
    tuesday: `Mardi`,
    wednesday: `Mercredi`,
    thursday: `Jeudi`,
    friday: `Vendredi`,
    saturday: `Samedi`,
    sunday: `Dimanche`,
    manageTheAppointmentTemplates: `Gérer le modèle de rendez-vous`,
    prefillTemplatesFor: `Modèles de préremplissage pour`,
    appointmentTemplates: `Modèles de rendez-vous`,
    backToTemplateTypes: `Retour aux types de modèles`,
    addNewAppointmentTemplate: `Ajouter un nouveau modèle de rendez-vous`,
    caremoduleName: `Nom du module de soins`,
    selectPathway: `Sélectionner un chemin`,
    notShowInDropdownAfterDelete: `En supprimant ce modèle, il ne sera plus affiché dans la liste déroulante`,
    messagesTemplates: `Modèles de messages`,
    addNewMessageTemplate: `Ajouter un nouveau modèle de message`,
    pathway: `Chemin`,
    template: `Modèles`,
    typesTwo: `2 types`,
    scheduledAppointmentInDropdown: `En supprimant ce modèle, il ne sera plus affiché dans les champs déroulants lors de la planification d’un rendez-vous.`,
    manageTemplate: `Gérer le modèle`,
    manageTheMessageTemplates: `Gérer le modèle de message`,
    addMdt: `+ Ajouter une nouvelle EMD à la plateforme`,
    mdts: `EMD`,
    NameAsc: `Nom Asc`,
    NameDesc: `Nom Desc`,
    Teams: `Équipes`,
    MdtsName: `Nom des EMD`,
    managemdts: `Gérer les EMD`,
    members: `Membres`,
    editTeam: `Modifier l’équipe`,
    addANewMDTToThePlatform: `Ajouter une nouvelle EMD à la plateforme`,
    week: `Semaine`,
    month: `Mois`,
    year: `Année`,
    total: `Total`,
    dailyaverage: `Moyenne quotidienne`,
    nochartdata: `Aucun tableau de données disponible`,
    youCanOnlyAssignOneMDTAtATime: `Vous ne pouvez attribuer qu’une seule EMD par heure locale`,
    noMoreOptionsAvailable: `Aucune autre option n’est disponible`,
    mdt: `EMD`,
    relatingPatient: `Associer un patient`,
    nonrelatingPatient: `Ne pas associer un patient`,
    sendMsgPatient: `Envoyer un nouveau message au patient`,
    expectedResponseTime: `Temps de réponse attendu entre 3 et 4 heures`,
    walkedText: `marché`,
    walk: `marche`,
    mymedicalteam: `Mon équipe médicale`,
    yesterday: `Hier`,
    close: `Fermer`,
    passwordUsedBefore: `Le nouveau mot de passe a déjà été utilisé et ne peut être réutilisé. Veuillez saisir un nouveau mot de passe.`,
    sendMessageTo: `Envoyer le message à`,
    message: `Message`,
    addChatParticipant: (params: string[]) =>
        `${params[0]} a ajouté ${params[1]} à la conversation`,
    removeChatParticipant: (params: string[]) =>
        `${params[0]} a retiré ${params[1]} de la conversation`,
    removedParticipant: `Participant retiré`,
    noMessagesSelected: `Vous n’avez pas de message sélectionné`,
    noMessagesSelectedDesc: `Sélectionnez un message sur le côté gauche de l’écran ou lancez une nouvelle conversation`,
    mfaMethodExplanationRegistration: `Ce code de sécurité est nécessaire pour accéder à votre compte. Vous pouvez obtenir le code d’identification à l’aide de votre téléphone portable ou de votre e-mail. Veuillez choisir la méthode qui vous convient le mieux.\n\nVeuillez noter que vous ne pouvez choisir qu’une seule méthode de vérification pour le moment. Une fois que vous aurez fait votre choix, votre préférence sera enregistrée et ne pourra pas être modifiée sans contacter le service d’assistance.`,
    signinCodeRequired: `Demander un code de sécurité`,
    securityCodeRequired: `Ce code de sécurité est nécessaire pour accéder à votre compte. Vous pouvez obtenir le code de connexion en utilisant la méthode que vous avez choisie lors de votre première inscription.`,
    newMfaUserDesc1: `Ce code de sécurité est nécessaire pour accéder à votre compte. Vous pouvez obtenir le code d’identification à l’aide de votre téléphone portable ou de votre e-mail. Veuillez choisir la méthode qui vous convient le mieux.`,
    newMfaUserDesc2: `Veuillez noter que vous ne pouvez choisir qu’une seule méthode de vérification pour le moment. Une fois que vous aurez fait votre choix, votre préférence sera enregistrée et ne pourra pas être modifiée sans contacter le service d’assistance.`,
    feelFreeToMessageTeam: `N’hésitez pas à entamer une conversation avec une personne de votre équipe.`,
    noFutureMessages: `Vous n’avez pas encore de messages`,
    chatSelfRemove: `Vous vous êtes retiré de la conversation`,
    noResultFound: `Aucun résultat trouvé`,
    chatUpdated: `La discussion a été mise à jour avec succès`,
    chatNotUpdated: `La discussion n’a pas été mise à jour`,
    searchPlaceholder: `Rechercher un modèle...`,
    editPrefillTemplate: `Modifier le modèle de pré-remplissage`,
    forAppointments: `Pour les rendez-vous`,
    addTemplateToList: `Ajouter un modèle à la liste`,
    addNewPrefillTemplate: `Ajouter un nouveau modèle de pré-remplissage`,
    forMessages: `Pour les messages`,
    editNewPrefillTemplate: `Modifier un nouveau modèle de pré-remplissage`,
    generateNewCode: `unverified translation`,
    manageRegistration: `unverified translation`,
    generateOnboardingCode: `unverified translation`,
    generateCode: `unverified translation`,
    onboardingRequests: `unverified translation`,
    approveSelected: `unverified translation`,
    requestDate: `unverified translation`,
    phone: `unverified translation`,
    searchPatient: `unverified translation`,
    pathwayCode: `unverified translation`,
    timedCode: `unverified translation`,
    areYouSureDeleteTemplate: `unverified translation`,
    validUntil: `unverified translation`,
    selectPathwayText: `unverified translation`,
};
